### ISSUE TITLE
state by state gini coefficients

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1003]
Daniel Kim (daniel.him@post.harvard.edu) asked:

> I am wondering if it would be possible to add the state Gini
> coefficient (specified for each state) as a measure that could be
> added as a result retrieved from TaxBrain.

I replied

> Currently we don’t have a dataset that is representative at the state level, but we will be getting one this fall. The new dataset will be based on the current population survey, and we can also distribute it publicly. 
> 
> Once we have the new dataset, the first step would be for one of Tax-Calculator’s open source contributors to add a feature for calculating pre- and post- tax gini coefficients by state. Tax-Calculator is the open source model that runs behind TaxBrain. This would be a fairly small project for an existing or new Tax-Calculator contributor. 
> 
> Once the feature is in Tax-Calculator, anyone would be able to download the source code and the publicly-available database and calculate gini coefficients for themselves with a small amount of programming experience.  
> 
> The next step would be for TaxBrain contributors to decide whether the feature should also be added to TaxBrain for the benefit of users with no programming experience. 
> 
> Another issue to note is that currently Tax-Calculator, and therefore TaxBrain, only deal with individual income and payroll tax liabilities at the Federal level. When users are looking at the effect of taxes on state by state gini coefficients, they would very likely want to include the effect of state and local taxes. We do know state and local tax amounts for taxpayers who itemize their deductions, and one of our contributors is in the middle of imputing these values for non-itemizers, but that project isn’t finished yet. I expect it to be finished this fall or winter. 

This issue is to request that state by state gini coefficients to be added as a Tax-Calculator utility function. While we won't be able to take advantage of them until the CPS file is available, they could be added to TC before then. 

Once this issue is resolved, Daniel Kim should be notified.

**Comment by salimfurth** [comment]
Be careful about using CPS for state-by-state information. It's not balanced at the state level, so small groups - like high earners - won't be accurately counted for small states.

**Comment by martinholmer** [comment]
@MattHJensen, regarding issue #1003 (state gini coefficients) @salimfurth said this:
> Be careful about using CPS for state-by-state information. It's not balanced at the state level, so small groups - like high earners - won't be accurately counted for small states.

This seem like sensible advice.  Shall we just close issue #1003?

**Comment by martinholmer** [comment]
This issue has been bought to the attention of the developer in the [PUF-State-Distribution repository](https://github.com/open-source-economics/PUF-State-Distribution).
