### ISSUE TITLE
CG, EITC, CTC enhancement requests

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1025]
A Senator’s office is interested in assessing a plan that includes the provisions below, among others. These are the provisions that I think might require some TC enhancement. The parameter values should be seen as placeholders. For perspective, the plan might also include repealing the corporate income tax. 
	
1)   Capital Gains.

Tax all (not just long-term) capital gains and qualified dividends at ordinary income tax rates, but provide a 50% exclusion for capital gains that are reinvested within the same tax year that the gains are realized as well as a small investor exclusion of the first $10,000 in capital gains. Current rules excluding capital gains from the sale of a primary residence would be maintained. 

[MJ: I’m not sure yet how to deal with the 50% exclusion for same-year reinvestments. Everything else looks relatively straightforward. ]

2) EITC replacement

Replace the EITC with a subsidy for workers who earn less than $35,000 in wage income. The maximum subsidy would be $1000 and would be phased in at a rate of 10% starting with the first dollar in wage income and hitting the maximum subsidy at $10,000 in earned income. Other tax provisions aside, this feature would create a 10% negative income tax bracket up to the $10,000 earnings level.

The subsidy would phase out at a 10% rate beginning at $25,000 with the credit fully phased out by the time a worker earns $35,000 in wages.

The subsidy would be calculated on a per-worker income basis rather than on a household income basis like the current EITC.

Under the proposal, if a family has more than one wage earner, each would be eligible for the wage subsidy up to $35,000 in wages. This could result in a married couple earning a total of $50,000 ($25,000 each) with $2,000 wage subsidy.

[MJ: I expect this will need to be a new function]

 3)   CTC and ACTC replacement

Fully replace the current CTC and ACTC with a tax credit that would be refundable up to payroll tax liability.

This tax credit would phase in at the rate of payroll taxes paid (12.4%) with a maximum credit of $3000 per child. The credit would phase out at a rate of 10% for incomes above $175,000 for individual filers and $350,000 for joint filers. The credit would also be refundable up to the value of payroll taxes paid.

[MJ: We can probably expand the “additional additional child tax credit” to accomodate this, since the refundability rules look the same.]

**Comment by martinholmer** [comment]
In issue #1025 @MattHJensen identified some Tax-Calculator enhancements that would broaden the range of reforms Tax-Calculator can simulate.

The kinds of capital gains and qualified dividends reforms described in #1025 will be possible to simulate after pull request #1027 is merged into the master branch.

The kinds of EITC reforms described in #1025 will be possible to simulate after pull request #1028 is merged into the master branch.

The kinds of CTC reforms described in #1025 will be possible to simulate after pull request #1029 is merged into the master branch.

All three of these pull requests need to be reviewed closely.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

**Comment by MattHJensen** [comment]
Thanks a lot @martinholmer. I will review these PRs closely. If anyone else wants to do the same, it would certainly be appreciated. 

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

**Comment by martinholmer** [comment]
The enhancements requested in issue #1025 have been implemented in three merged pull requests: #1027, #1028 and #1029.
