### ISSUE TITLE
Questions about MTR graphs after bug-fix in PR#1020

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1026]
@MattHJensen asked in #1020:
> I expect that #1021 means there is no longer a change in MTR for IIT when you pop the cap as is shown in the second graph [in #1020].  Do you have any ideas at this point about what is causing the blips for payroll tax MTR for the 15-20 percentiles of [wages] in the first chart [in #1020]?

These are two good questions.

(1) After merging #1021, the second graph looks like this:

![image](https://cloud.githubusercontent.com/assets/12170745/19928535/2f09c378-a0d5-11e6-9517-401454673a6d.png)

So, yes, it would seem from a visual inspection that the marginal income tax rate does not change when all earnings are subject to payroll taxes.  But a closer examination of the output produced by the `mtr_graph_data` utility function shows that a few filing units experience a decline in their marginal income tax rate.  This is to be expected because AGI is down for filing units who had SchC or SchF income above the pre-reform social security cap, and for some the reduced AGI puts them in a lower income tax bracket.  The reason AGI drops is that half of the self-employment tax (on SchC plus SchF income) is subtracted from AGI (see 2015 Form 1040 line 27).  See below for the tabulation details on this point.

(2) After merging #1021, the first graph looks like this:

![image](https://cloud.githubusercontent.com/assets/12170745/19929189/7b8dfcac-a0d8-11e6-90de-b8ca07a83d35.png)

The question is why is the pre-reform (blue) marginal payroll tax rate below 15.3 percent for some wage and salary income percentiles below the 20th percentile?  Again, this is to be expected because filing units with little or no wage and salary income can have SchC plus SchF income above the pre-reform social security cap, and therefore, a small increase in wage income causes no increase in their total payroll tax liability.  When the social security cap is "popped", the same small increase in wage income causes an increase in total payroll taxes.  Another way to look at this is to notice that when putting AGI or Expanded Income on the x axis eliminates the low-percentile blue "blips" (see the script used to generate 18 versions of these graphs in #1020).

So, now after the fix in pull request #1021, the graphs I've generated for a "pop-the-cap" reform make sense to me.  The fact that the second graph in #1020 did **not** look right to me is what led to the investigation that revealed the bug fixed in #1021.  So, the new visualization capabilities can also serve as debugging tools.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen 

**Details on Interaction of Income and Payroll Taxes**

Here is what was done to develop the answer in (1) above:
```
$ cat mtr-graphx.py
from taxcalc import *
ref = {2013: {'_SS_Earnings_c': [9e99]}}
calc1 = Calculator(policy=Policy(), records=Records())
calc2 = Calculator(policy=Policy(), records=Records())
calc2.policy.implement_reform(ref)
gdata = mtr_graph_data(calc1, calc2,
                       mars='ALL',
                       mtr_variable='e00200p',
                       mtr_measure='itax',
                       mtr_wrt_full_compen=False,
                       income_measure='wages',
                       dollar_weighting=True)
print(gdata['lines'])

$ cp ../tax-calculator-data/puf.csv .

$ python mtr-graphx.py > mtr-out

$ awk 'BEGIN{e=1e-4}{d=$3-$2}d>e||d<-e{print $0,d}' mtr-out
71   0.280924  0.280806 -0.000118
72   0.284720  0.284556 -0.000164
74   0.289833  0.289696 -0.000137
75   0.283749  0.283546 -0.000203
77   0.289583  0.289423 -0.00016
79   0.303569  0.303261 -0.000308
81   0.314623  0.314880 0.000257
91   0.346713  0.346593 -0.00012
95   0.390230  0.390101 -0.000129
```

**Comment by martinholmer** [comment]
The answers in issue #1026 to two questions posed by @MattHJensen about marginal tax rate graphs has been open for nine days.  I'm going to close it now as it seems this was enough time for anybody who was interested to read it.

**Comment by jdebacker** [comment]
@martinholmer This was a great example of how to use the plotting function.  Do you have an example the will plot MTRs from the baseline and a reform together using the updated TC methods?

**Comment by martinholmer** [comment]
@jdebacker asked:
> This was a great example of how to use the plotting function. Do you have an example the will plot MTRs from the baseline and a reform together using the updated TC methods?

Doesn't the graph produced by the Calculator class `mtr_graph` method contain what you want?
If not, what exactly do you want to graph that is different from the `mtr_graph` output, an example of which is given in [example (8) in the user documentation section on analsysis](http://open-source-economics.github.io/Tax-Calculator/#cli-init-analysis).

**Comment by jdebacker** [comment]
@martinholmer Thanks for pointing out this documentation.  I had been looking at some other docs and didn't see this with examples of the graphing function.  Very nice documentation!

**Comment by martinholmer** [comment]
@jdebacker said:
> Thanks for pointing out [example (8) in] [this documentation](http://open-source-economics.github.io/Tax-Calculator/#cli-init-analysis). I had been looking at some other docs and didn't see this with examples of the graphing function. Very nice documentation!

Sure; no problem.  If you didn't find it that easily, maybe I should add some more links to it.
Can you suggest where some extra links could be added?  Where did you look first?

**Comment by jdebacker** [comment]
@martinholmer I think you are good with respect to your links. You have the link to the "Using Tax Calculator" first in the readme for the TC repo and I guess I should have clicked on that.  Instead, I was drawn to the "Cookbook" because I thought I needed the most flexible options.  Again, nice job with all this.  I hope to one day have something similar for the projects I've been contributing to!
