### ISSUE TITLE
Integrating CPS based file into TaxCalc

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/Tax-Calculator#1030]
This issue continues the work being done to make TaxCalc more accessible by allowing for the use of non-puf data sources as seen in PR #376 and issue #851. This specifically addresses creating a CPS based file to be used as an alternative to the PUF and modifying TaxCalc to use it, as brought up in issue #319.

> Create a file based off of the CPS that could be used as an alternative to the PUF or PUF-CPS match file.
An advantage of this file is that it could form the base for an extrapolated, nationally representative, file for revenue estimation.
John O'Hare is helping us with this as part of the PUF-CPS match project.

I recently received access to the file John has been working on and here are the first steps I'll be taking on the project. I'd appreciate any feedback on them or pointing out any issues I may miss.

1. Renaming necessary variables to match the E-codes used in SOI documentation (e.g. taxable interest income is `INSTST` in the CPS file but `e00300` in PUF. It will be renamed to `e00300`).
   1. This will only be done for variables that are explicitly equivalent. There are some that are found in the PUF but not explicitly in the CPS file. I'm currently looking into ways to address this.
2. Create a new `VALID_READ_VARS` set to be referenced when using the CPS file or modify the existing one.
   1. It is my understanding that, in addition to having a publicly available dataset, part of the appeal of using CPS based data is the presence of demographic information missing from `puf.csv`. Therefore, TaxCalc will need to allow for a different set of variables which include these data when using the CPS file rather than the PUF.
    2. This would require either adding the new variables to the current `VALID_READ_VARS` set or creating a new one that's referenced instead when using the CPS file. 
3. Figure out how to differentiate between the PUF and CPS files in order to allow for additional variables and weights.
    1. As mentioned above, there will be different acceptable variables in each file and different `WEIGHTS.csv` files will be needed. Additionally, the extrapolation process can be broken down to use state level blow up factors rather than national with the CPS file (more on that below).
    2. The easiest way to implement I can think of right now would be to have the user specify which type of file is being used, but that creates new potential user errors so I'm not entirely comfortable with this option. I would really appreciate any alternative ideas for this y'all may have for this in particular.
4. Implement state-level blow up factors (longer term goal).
    1. The CPS data includes which state the filer is in and I've been told state level data will be used during the process of creating the corresponding `WEIGHTS.csv` file. This state level work can be continued by using the state equivalent to the [IRS data](https://www.irs.gov/uac/soi-tax-stats-historic-table-2) currently  used to create the blow up factors in TaxCalc. Right now my idea is to have a new method in `records.py` like `_blowup` that will utilize a different set of blow up factors for each state. The factors can be held in a dictionary where the keys are the state codes and the values are DataFrames holding each state's factors by year.
    2. The goal is to be as precise as possible with our blow up factors. I anticipate this being particularly resource consuming so I believe it can wait until the other aspects of this project have been addressed.

Again, all of this is a first pass at planning out what needs to be done. I'd love further feedback on how this process could be streamlined.

**Comment by feenberg** [comment]
On Thu, 3 Nov 2016, andersonfrailey wrote:

> 
> This issue continues the work being done to make TaxCalc more accessible by allowing for the use of
> non-puf data sources as seen in PR #376 and issue #851. This specifically addresses creating a CPS
> based file to be used as an alternative to the PUF and modifying TaxCalc to use it, as brought up in
> issue #319.
>
>       Create a file based off of the CPS that could be used as an alternative to the PUF or
>       PUF-CPS match file.
>       An advantage of this file is that it could form the base for an extrapolated, nationally
>       representative, file for revenue estimation.
>       John O'Hare is helping us with this as part of the PUF-CPS match project.
> 
> I recently received access to the file John has been working on and here are the first steps I'll be
> taking on the project. I'd appreciate any feedback on them or pointing out any issues I may miss.
>
>  1. Renaming necessary variables to match the E-codes used in SOI documentation (e.g. taxable
>     interest income is INSTST in the CPS file but e00300 in PUF. It will be renamed to e00300).
>      1. This will only be done for variables that are explicitly equivalent. There are some that are
>         found in the PUF but not explicitly in the CPS file. I'm currently looking into ways to
>         address this.

If a variable is missing from the CPS, then it should be treated as zero, 
and the code should allow this. In the long run we will have several data 
sources, and users will have there own. It isn't difficult to treat 
missing data as zero - it is what the IRS does on your tax form.

>  2. Create a new VALID_READ_VARS set to be referenced when using the CPS file or modify the existing
>     one.

Variables present in the CPS but not in the PUF should be allowed and not
cause an error. I am mystified by the use of "VALID_READ_VARIABLES" 
because it seems counter-productive to signal an error merely because 
there are extra variables.

>      1. It is my understanding that, in addition to having a publicly available dataset, part of the
>         appeal of using CPS based data is the presence of demographic information missing from
>         puf.csv. Therefore, TaxCalc will need to allow for a different set of variables which
>         include these data when using the CPS file rather than the PUF.
>      2. This would require either adding the new variables to the current VALID_READ_VARS set or
>         creating a new one that's referenced instead when using the CPS file.
>  3. Figure out how to differentiate between the PUF and CPS files in order to allow for additional
>     variables and weights.
>      1. As mentioned above, there will be different acceptable variables in each file and different
>         WEIGHTS.csv files will be needed. Additionally, the extrapolation process can be broken down
>         to use state level blow up factors rather than national with the CPS file (more on that
>         below).

Does the weights file need to be a separate file? Can it be part of the 
income data file?

What is the function of the state level blow up factors? Can not each
record be given weights that reflect state totals?

>      2. The easiest way to implement I can think of right now would be to have the user specify
>         which type of file is being used, but that creates new potential user errors so I'm not
>         entirely comfortable with this option. I would really appreciate any alternative ideas for
>         this y'all may have for this in particular.

We already have a box to specify 100% or 2%. A  box with the data 
source selected from a radio button list is the way to go.

>  4. Implement state-level blow up factors (longer term goal).
>      1. The CPS data includes which state the filer is in and I've been told state level data will
>         be used during the process of creating the corresponding WEIGHTS.csv file. This state level

OK, is this saying that the weights will be modified to match known state 
level totals?

>         work can be continued by using the state equivalent to the IRS data currently used to create
>         the blow up factors in TaxCalc. Right now my idea is to have a new method in records.py like

Are the "blow up factors" a different name for the weights that John 
provides to match CBO aggregates?

>         _blowup that will utilize a different set of blow up factors for each state. The factors can
>         be held in a dictionary where the keys are the state codes and the values are DataFrames
>         holding each state's factors by year.

So John will provide a new set of weights that meet CBO aggregates and 
some other state totals? Where will the state totals come from?

>      2. The goal is to be as precise as possible with our blow up factors. I anticipate this being
>         particularly resource consuming so I believe it can wait until the other aspects of this
>         project have been addressed.
>

Unless we are providing tables tabbed by state, it isn't crucial to have 
accurate state weights. We could provide such tables for per capita 
variables even without accurate state weights.

The most difficult aspect of using the CPS is what to do about the missing 
very high income taxpayers. What is the plan for that?

dan feenberg

**Comment by martinholmer** [comment]
@andersonfrailey said:
> I recently received access to the file John [O'Hare] has been working on and here are the first steps I'll be taking on the project. I'd appreciate any feedback on them or pointing out any issues I may miss.

It is good to have a long-run plan, but also very important to go about this complex task step by step, beginning with simple issues and progressing to more complex issues.  It would appear that the overall outlines of your plan are consistent with that approach.

I want to ask questions about just your first step:

> 1.  Renaming necessary variables to match the E-codes used in SOI documentation (e.g. taxable interest income is INSTST in the CPS file but e00300 in PUF. It will be renamed to e00300).  This will only be done for variables that are explicitly equivalent. There are some that are found in the PUF but not explicitly in the CPS file. I'm currently looking into ways to address this.

You don't say, but I'm assuming that the new "CPS file" is in CSV-format and is named `cps.csv`, right?  

How many variables are in `cps.csv` but not in `puf.csv`?  What are their names?

How many variables are in `puf.csv` but not in `cps.csv`?  What are their names?

Can you make a copy of the `cps.csv` file available?  I'd like to take a look.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by andersonfrailey** [comment]
@feenberg 

> Does the weights file need to be a separate file? Can it be part of the
income data file?

The initial weights can be part of the initial data file, but if we want to be able to extrapolate them out and have weights for ten years they need to be in a separate file to work with how the program is currently designed.

> What is the function of the state level blow up factors? Can not each
record be given weights that reflect state totals?

> OK, is this saying that the weights will be modified to match known state
level totals?

@Amy-Xu will address these questions.

> Are the "blow up factors" a different name for the weights that John
provides to match CBO aggregates?

No. The blow up factors are applied to variables like `e00200` when the calculator is used in future years to extrapolate those variables out.

> So John will provide a new set of weights that meet CBO aggregates and
some other state totals? Where will the state totals come from?

Yes he will. The state totals will come from IRS data found [here](https://www.irs.gov/uac/soi-tax-stats-historic-table-2).

> The most difficult aspect of using the CPS is what to do about the missing
very high income taxpayers. What is the plan for that?

The current plan is to adjust the weights of the high income payers we do have to try and account for this during stage II of the extrapolation process in TaxData. It will likely be a solution similar to what we tried in TaxData PR [#40](https://github.com/open-source-economics/taxdata/pull/40) where we added additional wages and salaries targets to try and improve the wage distribution in our current PUF.

**Comment by andersonfrailey** [comment]
@martinholmer 

> You don't say, but I'm assuming that the new "CPS file" is in CSV-format and is named cps.csv, right?

The file is in CSV-format, but not called `cps.csv` yet. The file I've been given currently has a little over 500 variables that have been pulled from the CPS and PUF files used to create the matched file and some added during the statistical matching process. I'll be dropping the unnecessary variables and doing some other basic cleaning up to create the `cps.csv` that can be used by TaxCalc. 

> How many variables are in cps.csv but not in puf.csv? What are their names?

As mentioned above, there are over 500 variables in the file that will be trimmed down to be `cps.csv`. Many of them are variables added during the matching process that need to be dropped. I will report back with a list when I get rid of these variables that are unrelated to each tax unit.

> How many variables are in puf.csv but not in cps.csv? What are their names?

I have an initial list of the variables that are not explicitly in `cps.csv`, but I'm working through some technical documentation that includes information on the imputation of some other variables. When I finish reading that I will send you a list of any that are in `puf.csv` and cannot be imputed from or found in `cps.csv` as well.

> Can you make a copy of the cps.csv file available? I'd like to take a look.

After I do my initial cleaning of the file I have and produce a more workable `cps.csv` file I will send it over to you.

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for your answers to my questions.  Your plan of action makes sense.  I'll wait until you have generated a `cps.csv` file before getting involved again with these issues.

**Comment by jdebacker** [comment]
@andersonfrailey, thanks for your work on this.  Great extension of the Tax-Calculator capabilities.

@feenberg said:

> Variables present in the CPS but not in the PUF should be allowed and not
cause an error. I am mystified by the use of "VALID_READ_VARIABLES"
because it seems counter-productive to signal an error merely because
there are extra variables.

+1 from me on this.

@andersonfrailey said:

> The file I've been given currently has a little over 500 variables that have been pulled from the CPS and PUF files used to create the matched file and some added during the statistical matching process. I'll be dropping the unnecessary variables and doing some other basic cleaning up to create the cps.csv that can be used by TaxCalc.

Related to some of @feenberg's comments regarding the use of other data sources in Tax-Calculator, I think you want to consider how you can make it as easy as possible to include other data sources as you build in the ability to use the CPS.  For example, you might consider starting with CPS data formatted exactly as one might download from the [NBER's CPS data archive](http://www.nber.org/data/current-population-survey-data.html).  In this way, you'd be creating scripts to get the files from a format that others would start with into something that is able to be read into Tax-Calculator.

**Comment by Amy-Xu** [comment]
Thank you Dan and Martin. Your questions really make me to think more in depth about this process. I try to address some questions here, but I'll need to further confirm with John.

Dan asked: 
>What is the function of the state level blow up factors? Can not each
>record be given weights that reflect state totals?

Let me clarify a bit our jargons here. In the whole extrapolation process, we're doing a two-stage adjustments. In stage I, we multiply the year zero dollar amounts of each record by factors that deem appropriate for that type of income, to make sure the database aggregates match SOI/CBO estimates of year t. But this essentially is assuming everyone gets the same growth rate, which is not realistic, and in particular would mess up EITC. So in Stage II, we use a linear programming algorithm to adjust the weights in order to make the wage by AGI distribution looks like 2014 SOI estimates. 

Back to your question, as CBO doesn't have separate projection for each state, we probably don't need a separate functions for blow-up factors. But we do need state level targets for stage II, and our targets would be based on the lastest SOI estimates available, and CBO national level growth rates. For the second part of your question, I think the answer is similar to why we need a stage II adjustment. The weights reflect year zero totals need adjustment to get later year distribution right.

**Comment by feenberg** [comment]
On Fri, 4 Nov 2016, Jason DeBacker wrote:

> 
> Related to some of @feenberg's comments regarding the use of other data sources in
> Tax-Calculator, I think you want to consider how you can make it as easy as possible
> to include other data sources as you build in the ability to use the CPS. For example,
> you might consider starting with CPS data formatted exactly as one might download from
> the NBER's CPS data archive. In this way, you'd be creating scripts to get the files
> from a format that others would start with into something that is able to be read into
> Tax-Calculator.

I was thinking more of the

   CEX, because it is the best US source of expenditure data
   SCF, because it is the best US source of wealth data and the
   PSID because it provides a long panel with good income data.

All of these would address important questions that the PUF is hard 
pressed to address without dubious imputations.

dan feenberg

**Comment by jdebacker** [comment]
To clarify, I agree with @feenberg re other data sources.  But, since you are starting with the CPS, I thought it might be enlightening start with a more "raw" version, which will get you thinking about how to write more general functions (and make more generalizable assumptions) to get alternative data sources into the format needed for Tax-Calc (which will eventually include other sources besides the CPS and PUF).

**Comment by MattHJensen** [comment]
I just opened a new issue, #1033, to discuss how to handle surplus variables in Tax-Calculator. I believe a solution to that issue would also preempt needing to deal with the second part of this issue:

> 
>- Create a new `VALID_READ_VARS` set to be referenced when using the CPS file or modify the existing one.
>    - It is my understanding that, in addition to having a publicly available dataset, part of the appeal of using CPS based data is the presence of demographic information missing from `puf.csv`. Therefore, TaxCalc will need to allow for a different set of variables which include these data when using the CPS file rather than the PUF.
>     - This would require either adding the new variables to the current `VALID_READ_VARS` set or creating a new one that's referenced instead when using the CPS file. 
>

**Comment by MattHJensen** [comment]
This issue (#1030) is about integrating a prepared CPS file with TC and not about the preparation of the CPS file itself, but @feenberg suggested that it would still be useful, as background reading, to include documentation describing how the CPS file was prepared. Here is such documentation for John's original project for preparing the CPS file. There have been some modifications between the original project and ours, but much is the same: 

[Technical DocumentationV4-2.pdf](https://github.com/open-source-economics/Tax-Calculator/files/587502/Technical.DocumentationV4-2.pdf)

Suggested enhancements to the preparation of the file itself, in particular suggestions on how to improve how the various imputations and augmentations were conducted, should be [new issues in the TaxData repo. ](https://github.com/open-source-economics/taxdata/issues/new)

**Comment by andersonfrailey** [comment]
Update on the progress of this issue:

I’m almost ready to say `cps.csv ` is complete. I’m going through and double checking that everything was done correctly. I’ll open a TaxData PR to upload the code used to create the file when I am finished.

For clarity, `cps.csv` refers to this new file, `puf.csv` refers to the PUF currently in use, and the production file refers to the larger file I used to create `cps.csv`.

There are 41 variables in `cps.csv` , slightly less than half of the number in `puf.csv`.  I’ve attached a spreadsheet with the list of the variables that are included, those that are not included, and variables found in the production file that may be useful to someone, but are not included in `cps.csv`. You can also compare aggregate totals between `cps.csv` and `puf.csv`. With that, I would like to address some of the larger differences in totals between the two files:

**e02100(p,s)  (Farm net profit/loss) , e00800 (alimony received), e01400 (taxable IRA distribution), e32800 (child/dependent care expenses), and e03240 (domestic production activity deduction)** were all read directly from the production file. The value of these variables in the production file just differ greatly from the PUF.

**e00300 and e00400 (taxable and tax-exempt interest income):**  In the production file, interest income is not split between taxable and tax-exempt, and in total was about 9% higher than the PUF file. I split it using the ratio found in table 1.4 of the [IRS data](https://www.irs.gov/uac/soi-tax-stats-individual-statistical-tables-by-size-of-adjusted-gross-income): 60% taxable, 40% tax-exempt. However, in the PUF the split is roughly 70% and 30%, which explains the large difference in tax-exempt interest income. Were I to use the PUF ratio, both variables would differ from the PUF by about 9% like the sum of interest income does.

**nu13 (number of dependents under 13):**  The production file contains the exact ages for up to five dependents. Because of this, I was able to count exactly how many were under 13. When I created this variable for the PUF, I only had the age range for three dependents and randomly assigned a fourth.  Because I was working with age ranges, I did not include the 13-17 rage to avoid significantly over shooting the actual number, which would have left out 13 year olds. There are over 5 million 13 year olds represented in this dataset, 38% of the total difference. Additionally, not having to randomly assign the fourth 13 year old gives a more accurate count. 

It should be noted that I only counted up to four under 13 dependents even though there are five dependent age variables. This was to stay consistent with the maximum possible for `nu13` in `puf.csv`. I can add the fifth if there is a desire for it. This will require a small adjustment to the function in TaxCalc used to simulate Trump’s child tax credit plan because it caps at four children.

**nu05 (number of dependents under 5:** As previously mentioned, the PUF only had variables for up to three dependents. Because the CPS has data on five I was able to count up to five under five per tax unit, significantly increasing the total number.

**elderly_dependent (presence of an elderly dependent):** Like the fourth dependent under 13, this was randomly assigned. When I created it for the PUF, I only assigned up to one per tax unit because there were so few instances of elderly dependents in the data I looked at. It seems that I was very wrong about this and will need to reevaluate this for the next PUF release. Having access to the age of each dependent allowed me to get a true count of the number of dependents above 65 which is reflected in `cps.csv`.

Other notes:

In the production file, charitable contributions are given as a lump sum, not split into cash and non-cash. I split this total to match the ratio seen in `puf.csv`  (I was not able to find IRS data on the split). It is my understanding that qualified dividends are just a subset of ordinary dividends so I used the same logic to get qualified dividends from ordinary dividends, only using the IRS ratio. Please let me know if this is incorrect. 

Unlike the PUF file, the CPS only has three categories for MARS. 1 = single, 2 = married filing jointly, and 3 = head of household. I changed head of household to 4 in order to match the PUF, but did not want to attempt to create a married filing separately category.

I spoke to John earlier this week and he said he should have the 10 year weights file ready soon. When I get that I will open up a PR to make the necessary changes to integrate everything into TaxCalc.

If anyone would like to take a look at the file as is, let me know and I will email it to you.

[CPS-PUF Comp.xlsx](https://github.com/open-source-economics/Tax-Calculator/files/598862/CPS-PUF.Comp.xlsx)


@martinholmer @MattHJensen @Amy-Xu @feenberg @jdebacker

**Comment by Amy-Xu** [comment]
Thanks to @andersonfrailey for all the work in PR https://github.com/open-source-economics/taxdata/pull/46. 

Anderson mentioned that

>There are 41 variables in cps.csv , slightly less than half of the number in puf.csv.

I think it might be more precise to say less than half of the variables required by TC. Out of all missing variables, I agree with Dan @feenberg that we probably should treat them as zero, but personally I feel concerned with [the capital gain section](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/functions.py#L572). 

Because CPS is not a tax dataset, it only provide total dividends and interest but not any line items in schedule D. So for the capital gain function I linked above, we only have an imputed qualified div (e00650), but not any other e-variables. Among those missing e-variables, 25% or 28% gain doesn't seem to be crucial, but how about long term and short term gain minus loss (e22250 & e23250)? I believe those two are also involved in our [AGI calculation](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/functions.py#L201) as well. More importantly, the corresponding section in AMT probably reply on the same set of variables as well.

Simply zeroing out those variables without touching any tax logic could potentially throw off our total cap gain liabilities, AMT, or even AGI at the beginning. I'm not really how to deal with this, but think it's definitely something worth our attention. 

@martinholmer @MattHJensen

**Comment by andersonfrailey** [comment]
@Amy-Xu in the [technical documentation](https://github.com/open-source-economics/Tax-Calculator/files/625677/Technical.DocumentationV4-2.pdf) Quantria states they use a "two-stage regression-based approach" to imputing short and long term capital gains and losses. From page 12:

> We use a two-stage, regression-based approach where the probability of realizing a capital gain or loss is estimated in the first stage and the (conditional) amount of the gain or loss is estimated in the second stage.
Once total capital gains are imputed, we rely on tabulations from the 2004 PUF to allocate gains between short- and long-term gains by income class. Regression results are shown in Table B-1A and Table B-1B.

Perhaps we could try something like that?

**Comment by Amy-Xu** [comment]
@andersonfrailey that sounds like a reasonable approach to me. At the same time, it is going to be a major imputation that affects many sections of calculation. Do we want to force our users to use the imputation for cap gains or give them options to zero those numbers out just in case they're not happy with the imputations? That's probably another issue to think about.

**Comment by feenberg** [comment]
On Thu, 1 Dec 2016, Amy Xu wrote:

> 
> @andersonfrailey that sounds like a reasonable approach to me. At the same time, it is
> going to be a major imputation that affects many sections of calculation. Do we want
> to force our users to use the imputation for cap gains or give them options to zero
> those numbers out just in case they're not happy with the imputations? That's probably
> another issue to think about.

What variables are available to make the imputation? If it is only 
non-gain income I would rather see "hot decking" because regression 
imputations put a lot of structure on the result.

dan

**Comment by andersonfrailey** [comment]
> What variables are available to make the imputation? If it is only
non-gain income I would rather see "hot decking" because regression
imputations put a lot of structure on the result.

@feenberg, Quantria uses the natural log of interest income, natural log of dividend income, natural log of pension income, marginal tax rate, marital status, family size, and number of aged/blind exemptions. 

We have the values of interest, dividend, and pension income, number of aged exemptions, and marital status. There are some variables that could be used to get family size (number of dependent exemptions, number of children at/away from home exemptions, and the presence of a spouse can be implied from one of the numerous variables on spouses in the data set). The only one missing is marginal tax rate.

**Comment by feenberg** [comment]
On Fri, 2 Dec 2016, andersonfrailey wrote:

>
>       What variables are available to make the imputation? If it is only
>       non-gain income I would rather see "hot decking" because regression
>       imputations put a lot of structure on the result.
> 
> @feenberg, Quantria uses the natural log of interest income, natural log of dividend
> income, natural log of pension income, marginal tax rate, marital status, family size,
> and number of aged/blind exemptions.
> 
> We have the values of interest, dividend, and pension income, number of aged
> exemptions, and marital status. There are some variables that could be used to get
> family size (number of dependent exemptions, number of children at/away from home
> exemptions, and the presence of a spouse can be implied from one of the numerous
> variables on spouses in the data set). The only one missing is marginal tax rate.

Missing in which dataset? I thought we were comparing PUF and CPS. Can't 
we use our calculated marginal tax rate (before gains)?

dan

**Comment by andersonfrailey** [comment]
>Missing in which dataset? I thought we were comparing PUF and CPS. Can't
we use our calculated marginal tax rate (before gains)?

Sorry, I should've been more clear which dataset I was talking about. My above comment referred to the CPS dataset. MTR is not included in the CPS file. The PUF file has all the variables and we could use our calculated MTR. 

Quantria uses a PUF file to estimate the probability of realizing a capital gain/loss and then the conditional amount of that gain/loss and uses the results of this to impute a total for capital gains in the CPS. 

We could run the CPS file through TaxCalc to get an MTR without gains, but couldn't some of the other missing variables like supplemental income and various deductions have significant affects on the result?

**Comment by feenberg** [comment]
On Fri, 2 Dec 2016, andersonfrailey wrote:

>
>       Missing in which dataset? I thought we were comparing PUF and CPS. Can't
>       we use our calculated marginal tax rate (before gains)?
> 
> Sorry, I should've been more clear which dataset I was talking about. My above comment
> referred to the CPS dataset. MTR is not included in the CPS file. The PUF file has all
> the variables and we could use our calculated MTR.
> 
> Quantria uses a PUF file to estimate the probability of realizing a capital gain/loss
> and then the conditional amount of that gain/loss and uses the results of this to
> impute a total for capital gains in the CPS.
> 
> We could run the CPS file through TaxCalc to get an MTR without gains, but couldn't
> some of the other missing variables like supplemental income and various deductions
> have significant affects on the result?
>

The result of the imputation won't be perfect.

dan

**Comment by martinholmer** [comment]
More recent discussion of this topic is at [taxdata issue 90](https://github.com/open-source-economics/taxdata/issues/90).
