### ISSUE TITLE
Handle "Surplus" Variables

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1033]
Over in #1030, 

@feenberg said:

> Variables present in the CPS but not in the PUF should be allowed and not
> cause an error. I am mystified by the use of "VALID_READ_VARS"
> because it seems counter-productive to signal an error merely because
> there are extra variables.

@jdebacker said: 

> +1 from me on this.

As far as I can tell there is one modest and one major downside to using `VALID_READ_VARS` to limit the datasets that Tax-Calculator can accomodate. 

The modest downside is that someone with a file containing both valid and invalid variables must preprocess their file to remove all invalid variables. I can see how this could be an inconvenience in its own right. 

A serious downside is that whenever we remove a variable from `VALID_READ_VARS`, it breaks backwards compatibility with earlier versions of our puf-csv file and with any external applications such as TaxBrain, OG-USA, or B-tax that are using earlier versions of the puf-csv file. This has caused serious difficulties in the past for all three of these projects. 

We would be able to eliminate both of these downsides by giving a warning when 'invalid' variables are included in a dataset rather than issuing an error. Since these variables aren't actually 'invalid', they are just 'unused', we might want to rename `VALID_READ_VARS` to `USED_VARS`, or even better, `USABLE_VARS` We could even tell the user which variables weren't used.  

I'd be interested to hear what others think about this approach, and in particular if there are any benefits of `VALID_READ_VARS` that we would be forgoing by adopting it. 

cc @talumbau, @zrisher, @rickecon, @martinholmer, @Amy-Xu, @andersonfrailey, @GoFroggyRun, @codykallen

**Comment by MattHJensen** [comment]
I just changed the name to Handle "Surplus" Variables, as that is what the intent really is. My question is, "How can we handle surplus variables in Tax-Calculator. I propose a solution above. 

Note that these issues were also discussed in October 2015 in #425.

**Comment by MattHJensen** [comment]
I believe the solution described above would also deal with

**Comment by martinholmer** [comment]
@MattHJensen said:
> As far as I can tell there is one modest and one major downside to using VALID_READ_VARS to limit the datasets that Tax-Calculator can accommodate.
>
> ... [snip] ...
>
> A serious downside is that whenever we remove a variable from VALID_READ_VARS, it breaks backwards compatibility with earlier versions of our puf-csv file and with any external applications such as TaxBrain, OG-USA, or B-tax that are using earlier versions of the puf-csv file. This has caused serious difficulties in the past for all three of these projects.

Whatever the merits of #1033, I think this problem has little to do with VALID_READ_VARS and more to do with a lack of coordination among team members.  There has always been a careful process of rolling out a new `puf.csv` file with plenty of notice to all team members.  Sometimes the new `puf.csv` is smaller and sometimes it is larger (as with the current revision described in [taxdata PR 43](https://github.com/open-source-economics/taxdata/pull/43)).

**Comment by MattHJensen** [comment]
> Whatever the merits of #1033, I think this problem has little to do with VALID_READ_VARS and more to do with a lack of coordination among team members. There has always been a careful process of rolling out a new puf.csv file with plenty of notice to all team members. Sometimes the new puf.csv is smaller and sometimes it is larger (as with the current revision described in taxdata PR 43).

I agree that lack of coordination is a problem, but coordination is hard, especially as the number of external users of Tax-Calculator grows, both people and applications. I think we should aim to make as few breaking changes as possible, given that each one causes trouble and costs time for many people, and the current usage of VALID_READ_VARS is causing a significant number of our breaking changes.

**Comment by martinholmer** [comment]
@MattHJensen said in #1033:
> Since these [surplus] variables aren't actually 'invalid', they are just 'unused', we might want to rename VALID_READ_VARS to USED_VARS, or even better, USABLE_VARS.

How about `USABLE_READ_VARS` to go along with the existing and essential `INTEGER_READ_VARS`?   If we make (1) that name change and (2) simply pass over input variables that are not in the `USABLE_READ_VARS` set without any warning or notice (which could get very messy and lengthy), are goals of #1033 achieved?

@MattHJensen @feenberg @jdebacker

**Comment by MattHJensen** [comment]
> How about USABLE_READ_VARS to go along with the existing and essential INTEGER_READ_VARS?

Yes, that sounds good to me. 

> simply pass over input variables that are not in the USABLE_READ_VARS set without any warning or notice (which could get very messy and lengthy), are goals of #1033 achieved?

I think that would be just fine for now. 

Perhaps we may eventually want to adopt something from @zrisher's work to warn users when their LUCA tax form variables aren't used, but we won't know until his work is finished and in the meantime I wouldn't want him to change his approach or make it any harder to accomodate this use case.

**Comment by feenberg** [comment]
On Fri, 4 Nov 2016, Matt Jensen wrote:

>
>       Whatever the merits of #1033, I think this problem has little to do with
>       VALID_READ_VARS and more to do with a lack of coordination among team
>       members. There has always been a careful process of rolling out a new
>       puf.csv file with plenty of notice to all team members. Sometimes the new
>       puf.csv is smaller and sometimes it is larger (as with the current
>       revision described in taxdata PR 43).
> 
> I agree that lack of coordination is a problem, but coordination is hard, especially
> as the number of external users of Tax-Calculator grows, both people and applications.
> I think we should aim to make as few breaking changes as possible, given that each one
> causes trouble and costs time for many people, and the current usage of
> VALID_READ_VARS is causing a significant number of our breaking changes.
>


I think it is possible to have a minimum list of required variables, and 
make everything else optional. Programmers would have to use some 
discipline to ensure that zero for a variable was a reasonable value. 
This is natural for most income and deduction items - missing is zero 
and that income is probably included in some other line. If the PSID 
doesn't have separate variables for farm and schedule C, but reports them 
both as "business income", then having zero for farm income isn't a real 
problem.

Sometimes it requires a little though. For example, in taxsim I have 
variables for "total dividends" and "qualified dividends" instead of 
"qualified dividends" and "unqualified dividends". That means that older 
code could still use  total dividends and get a good result from a recent 
dataset, while newer datasets (when used with newer code) correctly 
handled the special treatment of dividends.

Backwards compatibility is generally possible and very desirable. I don't 
see the need for even a warning about unused variables.

dan

**Comment by martinholmer** [comment]
I believe Tax-Calculator pull request #1035 resolves the issues raised in #1033.

**Comment by MattHJensen** [comment]
> I believe Tax-Calculator pull request #1035 resolves the issues raised in #1033.

Thank you @martinholmer for such a fast resolution to this. Closing.
