### ISSUE TITLE
expand CTC_new to include an under5_bonus

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1054]
Samuel Hammond and Robert Orr have a recent Niskanen Center paper, "[Toward a Universal Child Benefit](https://niskanencenter.org/wp-content/uploads/2016/10/UniversalChildBenefit_final.pdf)", that analyzes two CTC proposals. 

> Our first estimate is our preferred structure: a fully refundable $2000 child tax credit for any child under 18. Our second estimate is also fully refundable, but matches the rates of Clinton’s proposal: $2000 children ages 0 to 4, and $1000 for children ages 5 to 17.

To analyze the first proposal, I'll use the CTC_new capabilities that @martinholmer contributed recently. In order to accomodate the full refundability, I plan to set CTC_new_refund_limit_rt, which is the percentage of payroll taxes the credit can be refunded against, to infinity. 

To analyze the second proposal, I also plan to use the CTC_new capabilities, but I will need to add an under5_bonus to the credit amount.

**Comment by martinholmer** [comment]
@MattHJensen said about analyzing the Hammond-Orr CTC reform proposals:
> To analyze the first proposal, I'll use the CTC_new capabilities that @martinholmer contributed recently. In order to accommodate the full refundability, I plan to set CTC_new_refund_limit_rt, which is the percentage of payroll taxes the credit can be refunded against, to infinity.

That will work fine as long as their CTC proposal rules out refundable CTC for those with no earnings.

**Comment by MattHJensen** [comment]
> That will work fine as long as their CTC proposal rules out refundable CTC for those with no earnings. In other words, this approach will work only if in their reform proposal has a credit phase-in. Is that what they are proposing?

No, that is not what they are proposing. Thanks a lot for pointing this out to me. I will update #1055 shortly.
