### ISSUE TITLE
CG behavioral elasticity example -- should it rely on CG MTR from TC/TD? 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1065]
The CG behavioral elasticity example in the [`Behavior.response()` docstring](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/behavior.py#L109-L124) uses the capital-gains-weighted average (pre-reform) marginal tax rate from TPC to . I am wondering if we should switch to using the MTR from TC/TD. 

> Note: the nature of the capital-gains elasticity used here is similar
>           to that used in Joint Committee on Taxation, "New Evidence on the
>           Tax Elasticity of Capital Gains: A Joint Working Paper of the Staff
>           of the Joint Committee on Taxation and the Congressional Budget
>           Office", (JCX-56-12), June 2012.  In particular, the elasticity
>           use here is equivalent to the term inside the square brackets on
>           the right-hand side of equation (4) on page 11 --- not the epsilon
>           variable on the left-hand side of equation (4), which is equal to
>           the elasticity used here times the weighted average marginal tax
>           rate on long-term capital gains.  So, the JCT-CBO estimate of
>           -0.792 for the epsilon elasticity (see JCT-CBO, Table 5) translates
>           into a much larger absolute value for the _BE_cg elasticity used by
>           Tax-Calculator.  So, for example, if the capital-gains-weighted
>           average (pre-reform) marginal tax rate was, say, 0.216 (as reported
>           by Tax Policy Center), then the _BE_cg elasticity to use here (that
>           corresponds to the -0.792) would be about -3.67.

@martinholmer, do you remember the history of thought on using TPC's to begin with? 

@codykallen, do you remember which sources you used to derive the -3.49 elasticity that you have been using?

**Comment by codykallen** [comment]
Yes, I used the TPC marginal rates but the OSPC's income shares. And I still have the workbook I used to produce the -3.49 semi-elasticity.

**Comment by codykallen** [comment]
I just ran the numbers for 2016, using weights (taxable gain, as in the CBO-JCT paper) and marginal tax rates on p23250 from TC. I come up with a semi-elasticity of -3.45. This also corresponds to a net-of-tax-rate elasticity of 2.66.

**Comment by MattHJensen** [comment]
@codykallen, would you be interested in updating the `behavior.response()` docstring w your new finding?

**Comment by codykallen** [comment]
@MattHJensen I just updated it in PR #1076

**Comment by MattHJensen** [comment]
Thanks @codykallen! Closing by #1076.
