### ISSUE TITLE
Implementing Ryan-Brady plan

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1068]
To implement the Ryan-Brady plan in the Tax-Calculator, we need to make two modifications: excluding part of only certain types of investment income (qdiv, ltcg and interest income), and a 500 credit for all dependents that functions with the child tax credit. 

The tax [blueprint](http://abetterway.speaker.gov/_assets/pdf/ABetterWay-Tax-PolicyPaper.pdf) calls for excluding half of investment income, and taxing the remainder as ordinary income, but the Blueprint is not clear on exactly what types of income this applies to. If we assume that this applies to all investment income, then the current setup of ALD_Investment_ec_rt is sufficient. Alex Brill decided to apply this only to ltcg, qdiv and interest, which requires a different structure of the CapGains function than what we currently have. We could implement this by modifying the application of ALD_Investment_ec_rt or by created a new exclusion parameter to apply only to ltcg, qdiv and interest. The latter approach should arguably include an assert statement to ensure that one does not apply ALD_Investment_ec_rt and the more limited exclusion in the same reform. 

The $500 credit for dependents is nonrefundable and is structured with the child tax credit. The plan technically calls for an increase in the CTC by $500 (the extra $500 is nonrefundable) and for a $500 nonrefundable credit for non-child dependents. We assumed that this should have the same phase-out structure as the CTC, but with the beginning of the phase-out set to begin when the phase-out of the CTC ends. I implemented it by hijacking the personal_credit, but a permanent solution should have its own credit (dependent_credit). We could implement it in two possible ways: implementing it as its own credit with the phase-out described above (I already have the code for it), or by adding it to the ChildTaxCredit function (prectc += dependent_credit) and then subtracting it from the refundable portion in the AdditionalCTC function (more complicated). 

Does anyone have any thoughts on the investment income exclusion portion? I already have the code to implement these changes, but I'd like feedback on the investment income exclusion portion. 

@martinholmer @MattHJensen @andersonfrailey @Amy-Xu @feenberg @GoFroggyRun

**Comment by feenberg** [comment]
There is much "investment income" in partnerships and schedule c, but also 
much earned income. How do we distinguish those?

dan

**Comment by codykallen** [comment]
Income from partnerships and Sch C gets taxed separately, with a maximum rate of 25%.

**Comment by codykallen** [comment]
The $500 nonrefundable credit for dependents is implemented in PR #1069.

**Comment by martinholmer** [comment]
@codykallen said in issue #1068:
> The tax blueprint calls for excluding half of investment income, and taxing the remainder as ordinary income, but the Blueprint is not clear on exactly what types of income this applies to.  If we assume that this applies to all investment income, then the current setup of ALD_Investment_ec_rt is sufficient.  Alex Brill decided to apply this only to ltcg, qdiv and interest, which requires a different structure of the CapGains function than what we currently have. 

Frankly, I'm reluctant to add features to Tax-Calculator that are not actually part of a tax reform proposal.  Why don't you have Alex Brill check with authors of the Blueprint to see exactly what their proposal is?  Meanwhile, you can assume that the exclusion applies to all investment income and use the existing `_ALD_Investment_ec_rt` policy parameter to characterize this Blueprint reform provision.

**Comment by MattHJensen** [comment]
> Frankly, I'm reluctant to add features to Tax-Calculator that are not actually part of a tax reform proposal. Why don't you have Alex Brill check with authors of the Blueprint to see exactly what their proposal is? 

@martinholmer, I'm hesitant to subscribe to this approach for a few reasons: 

- Alex and Cody are active users and contributors, and the reform is interesting to them. Plus it could be interesting to others. 
- We can't expect that every contributor who would like to analyze a proposed reform to have access to the reform authors. 
- Sometimes when a contributor does have access to the reform authors, s/he still might choose not to talk to the authors so as to avoid any pressures that could stem from that for some other reason. 

This isn't to say that I'm not concerned about how messy `functions.py` is going to get as we parameterize more and more reform proposals. I'm continuing to stew on ideas like that which @feenberg expressed in #429 for TaxBrain and which I tried to extend to TC's `function.py` in [this comment](https://github.com/open-source-economics/Tax-Calculator/issues/429#issuecomment-236417930). I hope others are continuing to think about these ideas as well.

**Comment by martinholmer** [comment]
@codykallen said at the beginning of the conversation about issue #1068:
> The tax blueprint calls for excluding half of investment income, and taxing the remainder as ordinary income, but the Blueprint is not clear on exactly what types of income this applies to. If we assume that this applies to all investment income, then the current setup of ALD_Investment_ec_rt is sufficient. **Alex Brill decided to apply this only to ltcg, qdiv and interest, which requires a different structure of the CapGains function than what we currently have.** We could implement this by modifying the application of ALD_Investment_ec_rt or by created a new exclusion parameter to apply only to ltcg, qdiv and interest. The latter approach should arguably include an assert statement to ensure that one does not apply ALD_Investment_ec_rt and the more limited exclusion in the same reform.
>
> ...
>
> Does anyone have any thoughts on the investment income exclusion portion? I already have the code to implement these changes, but I'd like feedback on the investment income exclusion portion

Then @MattHJensen said about @martinholmer's comment:
>> Frankly, I'm reluctant to add features to Tax-Calculator that are not actually part of a tax reform proposal. Why don't you have Alex Brill check with authors of the Blueprint to see exactly what their proposal is?
>
> I'm hesitant to subscribe to this approach for a few reasons ...
>
> ...
>
> This isn't to say that I'm not concerned about how messy `functions.py` is going to get as we parameterize more and more reform proposals. I'm continuing to stew on ideas like that which @feenberg expressed in issue #429 for TaxBrain and which I tried to extend to TC's `function.py` in [a] comment [in #429].

OK.  Let me try to use this enhancement request as an opportunity to try to develop the code-snippet approach to structural reforms in Tax-Calculator as described in #429.  @codykallen, can you send me (via private email) the preliminary code changes you've developed for Alex's idea about what the Blueprint means?

**Comment by MattHJensen** [comment]
@codykallen, has this issue been fully resolved by #1069 and #1071?
