### ISSUE TITLE
TaxBrain minimum value for additional standard deduction

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1078]
The TaxBrain entry for the additional standard deduction for the aged and blind requires that the input value be greater than or equal to the default value. Is there a reason for this? 

@MattHJensen @martinholmer

**Comment by martinholmer** [comment]
@codykallen asked:
> The TaxBrain entry for the additional standard deduction for the aged and blind requires that the input value be greater than or equal to the default value. Is there a reason for this?

I don't know the answer to your question.  I think @Amy-Xu and @MattHJensen were involved in the addition of validation logic during September 2015.  Back then the `current_law_policy.json` file was called `params.json`.  If we look at the history of the `params.json` file, we see that the validation field for the `_STD_Aged` parameter was added in commit ecbc149 on 18-Sep-2015 and then modified in commit 37664c5 on 19-Sep-2015.  I know that was a long time, but can you remember the rationale for this particular validation, @Amy-Xu or @MattHJensen?

@feenberg

**Comment by martinholmer** [comment]
I see that the two commits mentioned above in issue #1078 were merged into Tax-Calculator master branch in pull request #355.  The #355 conversation contains some discussion about the technicalities of the validation fields being added to the parameter information, but does not seem to provide any rationale.  However, issue #331 does provide the rationale for the addition of the validation info.

@MattHJensen @Amy-Xu @feenberg @codykallen

**Comment by codykallen** [comment]
@MattHJensen, that makes sense. Thanks for clearing that up.
