### ISSUE TITLE
Implementation of CG_nodiff

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1087]
The current implementation of CG_nodiff in the CapGains function has a problematic statement on line 218.

qdcg_pos = max(0., e00650 + c01000)
qdcg_exclusion = (max(CG_ec, qdcg_pos) + CG_reinvest_ec_rt * max(0., qdcg_pos - CG_ec))
ymod1 = max(0., ymod1 - qdcg_exclusion)

If a reform sets CG_nodiff to True and does not change the default value of qdcg_pos, then the effect should be to tax capital gains and qualified dividends as ordinary income, but the current implementation instead removes all taxation of qdiv and capital gains. This causes tax revenue to fall $178 billion in 2017 instead of rising. This also causes average MTRs on ltcg and stcg to fall to approximately zero.

@MattHJensen @martinholmer @feenberg @andersonfrailey @Amy-Xu @GoFroggyRun

**Comment by codykallen** [comment]
If memory serves, I believe this was originally implemented on behalf of Senator Mike Lee. I am hesitant to change the implementation without hearing from those more familiar with his proposal.

**Comment by martinholmer** [comment]
@codykallen,  Thanks for the #1087 bug report.  I hope to look at this in a few minutes.

**Comment by codykallen** [comment]
Thanks for fixing this, @martinholmer

**Comment by martinholmer** [comment]
@codykallen said:
> If a reform sets CG_nodiff to True and **does not change the default value of qdcg_pos**, then the effect should be to tax capital gains and qualified dividends as ordinary income, but the current implementation instead removes all taxation of qdiv and capital gains.

You are correct in that there is a bug (see #1088 for the fix), but users cannot "change the default value of qdcp_pos" because `qdcp_pos` is a calculated variable (not a policy parameter).  The bug was that the first term in the expression for `qdcg_exclusion` should use a `min()` not a `max()` function.

Thanks for the bug report.
