### ISSUE TITLE
stats_summary.py errors

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/Tax-Calculator#1089]
I just tried running `stats_summary.py` and `stats_summary.py --output correlation` and I ran into the following errors:

First:
```
Traceback (most recent call last):
  File "stats_summary.py", line 142, in <module>
    sys.exit(main())
  File "stats_summary.py", line 38, in main
    table = creat_table_base()
  File "stats_summary.py", line 92, in creat_table_base
    description = puf_ecodes_info.Definition_2014[fval].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
This traces back to the for loop in the `creat_table_base` function. The root cause appears to be due to certain variables that are in `Records.USABLE_READ_VARS`, but not in `e_variable_info.csv` (`elderly_dependent`, `nu13`, `nu05`, and `cmbtp`).

Once I add those variables to `codes_imp_set` so that they are not included in the list of variables read from `e_variable_info.csv` the error was resolved.

Second:
```
Traceback (most recent call last):
  File "stats_summary.py", line 143, in <module>
    sys.exit(main())
  File "stats_summary.py", line 40, in main
    gen_sum_stats(table, calc=calc1)
  File "stats_summary.py", line 110, in gen_sum_stats
    weighted = getattr(calc.records, variable) * calc.records.s006
AttributeError: 'Records' object has no attribute 'c62100_everyone'
```
Removing `c62100_everyone`  and `_prexmp`, both of which were added to the table DataFrame in the `creat_table_base` function eliminates this error and the program is able to finish running, but they are both included in the current version of `variable_stats_summary.csv`, which leads me to believe their presence hasn't caused an error in the past.

The same error also occurs when generating the correlation matrix and dropping the above mentioned variables also solves this error. However, as was the case with the statistics summary, both variables are included in the current version of `correlation.csv` so this problem seems to have been avoided in the past.

I am running the latest version of TaxCalc, the only difference is I am using the new weights file.

Can anybody else reproduce either of these errors?

@MattHJensen @martinholmer @Amy-Xu @feenberg

**Comment by martinholmer** [comment]
Any use of the current, very out-of-date version of the `e_variable_info.csv` file is bound to cause problems.   See the recent discussion of this matter in issue #633.

@andersonfrailey @MattHJensen @zrisher
