### ISSUE TITLE
Conda dependency constraints overwritten by Pip requirements

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#1093]
In Conda's env config file `environment.yml` we specify the versions of `numpy` and `pandas` that Conda should install:

```
- numpy =1.10.4
- pandas =0.18.0
```

These versions were specified in #669 to fix issues encountered with older versions of those packages.

However, in Pip's env config file `requirements.txt` we say it may install the current default version of `pandas` and any `numpy` >= 1.7:

```
pandas
numpy >= 1.7
```

Pip determines what versions to fetch without knowing the versions specified in the Conda config.
When #669 was submitted, this had no effect because we were specifying the newest versions in `environment.yml`. However, there are now newer versions of each package, and these lines in `requirements.txt` render ineffective our controls in `environment.yml`. 

Some tests fail with the newest version of `pandas`, so this makes the initial environment unusable for a new contributor.

**Comment by talumbau** [comment]
@zrisher thanks for digging in here and rooting out the issues. One piece of info as we look at what is the best way to proceed: the `requirements.txt` was last touched in February of 2015 (by me) and I can't recall why it was ever included. Might be something that was needed for uploading to PyPI. Not totally sure. Anyway, my desire would be to move forward without it, if possible.

**Comment by talumbau** [comment]
Taking a closer look, I don't think the requirements.txt is the culprit for the recent failures reported by following the Contributor Guide. Rather, I think this requirements.txt is some left over cruft that should be removed. The only possible need would be for uploading releases to PyPI, but we'll solve that another way. So, just to make sure I understand, do you know of a workflow where someone is explicitly using this requirements.txt right now?

**Comment by zrisher** [comment]
> So, just to make sure I understand, do you know of a workflow where someone is explicitly using this requirements.txt right now?

It was part of my workflow, because I assumed it was meant to be used in the same fashion that both Conda and Pip are used (and documented to be used) in `webapp-public`. There have definitely been times in the past where Conda didn't offer a package and listing it under the `pip` line in Conda's requirements didn't work either. The only option was to include it via the standard pip process. It seems that as time goes by, Conda is supporting more packages both directly and via its pip extensions (yay!). So yes, it seems this workflow isn't needed here, and hopefully could be deprecated there as well.
