### ISSUE TITLE
Is there a way to run code coverage test on local computer?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1101]
Travis-CI conducts a code-coverage test when a pull request is submitted to GitHub.
Is there a way to run that same code-coverage test on my local (Mac) computer?

**Comment by talumbau** [comment]
Yes, you can generate the code coverage data on your local machine by running the same line as Travis CI does:

```
coverage run -m py.test -v -m "not requires_pufcsv" --pep8
```

This produces an XML report that is not very readable by humans. So, the next step is to create an HTML report of that data by running the HTML report generator:

```
coverage html
```

This will create a directory called `htmlcov` (or overwrite the contents if that directory already exists) with a collection of HTML pages giving code coverage results of the previous run similar to what is available on codecov.io. On Mac, you can start navigating these pages by typing:

```
open htmlcov/index.html
```

This will open a browser tab with the top level view of the results.

**Comment by martinholmer** [comment]
@talumbau,  Thanks for the clear explanation of how to generate code-coverage statistics on a local computer (instead of waiting to see what happens when a pull request is submitted to GitHub).  Your instructions worked perfectly on my Mac.  Thanks.
