### ISSUE TITLE
Is the `consump` object used properly in test_consumption_response?

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#1106]
In `test_consumption_response`, a default Consumption object is created in the first line of the test. Then, the `response` method is called a few lines later:

```
consump.response(recs, 1.0)
```

At that point, the `consump` object is no longer referred to. In the section with the comment

```
# compute earnings mtr with consumption response
```

I thought `consump` would be used, but instead the `calc1` object is created with `consumption=None` passed to the Calculator constructor. Then, the consumption response is added with this line:

```
    calc1.consumption.update_consumption(consumption_response)
```

Is this the preferred style? In other words, is it preferable to do this style (create Calculator with consumption=None, then call calc.consumption.update_consumption), rather than create a Consumption object and pass it to the Calculator constructor?

The context for me is that I am implementing https://github.com/OpenSourcePolicyCenter/webapp-public/issues/431, which will allow users to put Consumption parameters in to dropq, so we have to add code to `taxcalc.dropq` to handle this case, so I am wondering the best way to take Consumption parameters and create properly initialized Calculator objects for dropq code.

cc @martinholmer @MattHJensen

**Comment by martinholmer** [comment]
@talumbau asked in issue #1106:
> Is this the preferred style [for using a Consumption object]?  In other words, is it preferable to do this style (create Calculator with consumption=None, then calc.consumption.update_consumption), rather than create a Consumption object and pass it to the Calculator constructor?

Either is fine.  I have a subjective preference for this style:
```
con = Consumption()
con.update_consumption(...)
calc = Calculator(policy=..., records=..., ..., consumption=con) 
```
The alternative style was used in the `test_consumption_response` you refer to in order to get the most number of assert tests with the least amount of code.  If that is not the goal, my subjective preference is for the idiom above.  But others might have a different view.  The main thing is that the two different approaches produce the same results.

**Comment by talumbau** [comment]
got it. Thanks!
