### ISSUE TITLE
AppVeyor not working

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1139]
@talumbau,  Is the AppVeyor site down or is there something wrong with Tax-Calculator's use of it?

**Comment by talumbau** [comment]
I don't know what exactly occurred with the AppVeyor build for https://github.com/open-source-economics/Tax-Calculator/pull/1135, but it appears that it works as follows:

 - AppVeyor starts a 60 minute clock when it detects the PR
 - the build job has 60 minutes to acquire resources, run your setup and tests, and then report pass or fail
 - if nothing happens within those 60 minutes (no resources acquired), the job is declared a fail

It appears that no resources were supplied to the AppVeyor job for PR #1135 before the 60 minute clock was up, so it was noted as a failed job. I restarted the job, it was able to acquire resources, and then it passed the tests.

**Comment by martinholmer** [comment]
@talumbau said:
>  I restarted the job, it was able to acquire resources, and then it passed the tests.

How did you "restart the job"?

**Comment by talumbau** [comment]
You can't see the button to restart unless you are part of the AppVeyor project. I just did two things to make you a part of the AppVeyor project: I sent you an email invite to join, but I also make the Github team associated with this project a member of the AppVeyor project. The second one is probably what we want. Disregard the email for now. See if you can log in to AppVeyor using your Github account. You should see the project I created and the next time a build starts, you should see additional buttons to restart the build if desired.

**Comment by martinholmer** [comment]
@talumbau, Thanks for the help on AppVeyor.  I'll see how it goes.
