### ISSUE TITLE
Add `section` attribute for all parameters in current_law_policy.json that can be used w puf.csv

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1141]
Among other uses, the `section` attribute on a `current_law_policy.json` parameter indicate to the TaxBrain team that the parameter should be available on TaxBrain and which section it should be included in. 

In #1109, I added `section` attributes to almost every parameter in current_law_policy.json. Given that it means more parameters will be included on TaxBrain, I also endeavored to improve their documentation so that they will make sense for TaxBrain users. 

The only parameters in Tax-Calculator that do not have `section` attributes now and therefore will not appear on TaxBrain are:

- [ ] _ALD_Investment_ec_base_code_active (and param_code)
- [ ] _AMT_Child_em
- [ ] _AMT_KT_c_Age
- [ ] _AMT_thd_MarriedS
- [ ] _AMT_em_pe
- [ ] _LLC_Expense_c
- [ ] _ETC_pe_Single
- [ ] _ETC_pe_Married

There are four reasons why a parameter might appear on this list: 

1. The parameter activates param_code, and the param_code parameter itself (`ALD_Investment_ec_base_code ) is stored somewhere other than `current_law_policy.json`.

    - If we store `ALD_Investment_ec_base_code` in `current_law_policy.json` and include documentation, then we could add `ALD_Investment_ec_base_code` and `_ALD_Investment_ec_base_code_active` to the TaxBrain GUI input page.

2. The parameter requires taxpayer data that isn't available in puf.csv

    - We could add a `puf.csv_compatible` attribute to `current_law_policy.json` and A) don't display incompatible parameters on TaxBrain and B) disallow reform files that contain incompatible parameters on TaxBrain. 

3. The parameter is redundant, buggy, or otherwise doesn't make sense. 

    - We should delete it. 

4. When I was working on #1109, I thought there was a possibility that the parameter fell into category (2) or (3), and I didn't take the time to investigate whether it was appropriate to add a section label.

**Comment by martinholmer** [comment]
@MattHJensen said  in issue #1141 on January 12, 2016:
> The only parameters in Tax-Calculator that do not have section attributes now and therefore will not appear on TaxBrain are:
>
> _ALD_Investment_ec_base_code_active (and param_code)
> _AMT_Child_em
> _AMT_KT_c_Age
> _AMT_thd_MarriedS
> _AMT_em_pe
> _LLC_Expense_c
> _ETC_pe_Single
> _ETC_pe_Married

This is an April 14, 2016, update on the eight parameters listed above.

Parameters no longer in Tax-Calculator:
* _ALD_Investment_ec_base_code_active (and param_code)
* _AMT_thd_MarriedS

Parameters documented in `current_law_policy.json` and used in `AMT` function:
* _AMT_Child_em
* _AMT_KT_c_Age
* _AMT_em_pe

Parameters documented in `current_law_policy.json` and used in `EducationTaxCredit` function:
* _LLC_Expense_c
* _ETC_pe_Single
* _ETC_pe_Married

Are there reasons for not including the those three AMT policy parameters and those three EducationTaxCredit parameters in the TaxBrain GUI to Tax-Calculator?

**Comment by MattHJensen** [comment]
> Are there reasons for not including the those three AMT policy parameters and those three EducationTaxCredit parameters in the TaxBrain GUI to Tax-Calculator?

@martinholmer, I excluded them because I couldn't remember anyone using them in the past and thought we should test a few reforms using the parameters to ensure that the results make sense. I still haven't had an opportunity to do this but continue to think it would be useful before making them available on TaxBrain.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I excluded them because I couldn't remember anyone using them in the past and thought we should test a few reforms using the parameters to ensure that the results make sense. I still haven't had an opportunity to do this but continue to think it would be useful before making them available on TaxBrain.

OK.  That makes sense.

**Comment by martinholmer** [comment]
@MattHJensen, Tax-Calculator issue #1141 seems to have been resolved.
Let me know if that is not the case, otherwise I'll close #1141 on Monday.

**Comment by martinholmer** [comment]
@martinholmer said:
> @MattHJensen, Tax-Calculator issue #1141 seems to have been resolved.
> Let me know if that is not the case, otherwise I'll close #1141 on Monday.
