### ISSUE TITLE
Some Items in current_law_policy.json Lack Section Fields

### ISSUE THREAD

**Issue by brittainhard** [open-source-economics/Tax-Calculator#1142]
The fields without section names are:

- `_AMT_thd_MarriedS`
- `_ALD_Investment_ec_base_code_active`
- `_AMT_Child_em`
- `_LLC_Expense_c`
- `_ETC_pe_Married`
- `_AMT_em_pe`
- `_AMT_KT_c_Age`
- `_ETC_pe_Single`

@talumbau @MattHJensen I'm relying on thee section names to organize the UI, so this fields will have to be left out if they do not have section names.

**Comment by brittainhard** [comment]
I've also noticed that some of the names for sections are not consistent, i.e. `Payroll Taxes` and `Payroll taxes`. I can work around this problem for now.

**Comment by MattHJensen** [comment]
@brittainhard, leaving out params w o section labels is the right step for now. See #1141 for more info.

**Comment by MattHJensen** [comment]
@brittainhard, I resolved the payroll taxes inconsistency w #1154. Since everything else is the same as #1141, I am closing this in favor of #1141.
