### ISSUE TITLE
Where is the private repository for the taxpuf package?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1143]
In Tax-Calculator issue #1119, @MattHJensen said 11 days ago:
> +1 for the private GH repo and email notifications. The repo should go in the opensourcepolicycenter GH organization rather than open-source-economics.
> @PeterDSteinberg

And then 7 days ago in the same issue, @zrisher said:
> @martinholmer @talumbau @PeterDSteinberg @MattHJensen It could be useful to document the aforementioned setup and update steps for the `taxpuf dependency within this repo or the `taxpuf` repo.

@PeterDSteinberg, where do you stand on this work?  It seems important to create a repo for your new capability and document it, right?

**Comment by PeterDSteinberg** [comment]
@MattHJensen : Can you make a private repository in `OpenSourcePolicyCenter` called `taxpuf` for me and others to have read/write but not admin access?  I don't have rights to do this, I don't think.

@martinholmer : I can transfer the `taxpuf` package assets (`taxpuf.zip` from my email chain) to the repository and provide docs ~ 1 day after the private repo is created.  I'll update this issue when I update the new repo with those files.  I'll also make a couple of minor improvements at that time to `build_puf_package.py`, the helper script in `taxpuf` for building `taxpuf` itself and uploading to correct channel on anaconda.org.

**Comment by MattHJensen** [comment]
@PeterDSteinberg, all set.

**Comment by PeterDSteinberg** [comment]
@MattHJensen @martinholmer I'll ping you [when I think this PR for `taxpuf`](https://github.com/OpenSourcePolicyCenter/taxpuf/pull/1) is ready to merge, hopefully tomorrow morning.  I don't expected major changes between now and then.

**Comment by MattHJensen** [comment]
Thanks @PeterDSteinberg!
