### ISSUE TITLE
growth factor consistency

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1144]
Over at #1105, @codykallen said:

> I wonder how much of the difference is due to different GDP growth rates. Considering the our growth rates in growth.json are substantially lower than the CBO's August 2016 projections, could you rerun with new growth rates to see how much of the difference in payroll taxes is due to the different GDP growth rates?

The `growth.json` growth factors should not influence the baseline extrapolation. These only affect the extrapolation when the Growth class uses _differences_ between `growth.REAL_GDP_GROWTH` and `growth.factor_target` to adjust the baseline. You can see the history of thought: https://github.com/open-source-economics/Tax-Calculator/pull/424

That said, these parameters would make much more sense if `growth.REAL_GDP_GROWTH` and `growth.factor_target` were actually consistent with real GDP estimates from the particular CBO report that our baseline extrapolation depends on. It seems like this step is easily forgotten in the extrapolation update procedures, though. One simple solution would be to augment [this test](https://github.com/open-source-economics/Tax-Calculator/pull/424/files#diff-966d25cbcde08a0f1c9ea88bff601372R128) to check for consistency, but there could be better ideas. 

@andersonfrailey, given that updating `growth.REAL_GDP_GROWTH` and `growth.factor_target` needs to be a step in the extrapolation update procedures, could you handle this issue and update the appropriate taxdata docs? 

cc @Amy-Xu

**Comment by martinholmer** [comment]
Issue #1144 (about `Growth.REAL_GDP_GROWTH_RATES` values) has been resolved by pull request #1167.
