### ISSUE TITLE
Should we be using our Python skills in another way?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1149]
Thought members of the Tax-Calculator development team might be interested in this article:
[Algorithmic trading in less than 100 lines of Python code](https://www.oreilly.com/learning/algorithmic-trading-in-less-than-100-lines-of-python-code).
There is a nice endorsement of the Anaconda Python distribution.

@MattHJensen @talumbau @PeterDSteinberg @Amy-Xu @andersonfrailey @GoFroggyRun @zrisher @codykallen

**Comment by MattHJensen** [comment]
Where's the conda distribution though!?: 
![image](https://cloud.githubusercontent.com/assets/8301092/22182996/f4a85bd6-e080-11e6-8c8f-478cd56486fa.png)

**Comment by talumbau** [comment]
Hmm.. looks like they need to start releasing to PyPI or some conda package repository (conda-forge or anaconda.org):

https://github.com/oanda/oandapy

**Comment by martinholmer** [comment]
OK, we've enjoyed making fun of the finance types using Python.  Closing "issue" #1149.
