### ISSUE TITLE
Streamline conda package release for Tax-Calc / OG-USA and others

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/Tax-Calculator#1158]
This is a reminder to either 1) fix the `distribution` folder in Tax-Calculator, OG-USA to be more general, or 2) get conda forge builds working.  Currently the conda package build and upload scripts  have a couple hardcoded sections that need to change, and it would be easy to build the packages for all Python versions, rather than just 2.7.  Also, make corresponding changes in the Wiki for each repo.

**Comment by PeterDSteinberg** [comment]
This issue is somewhat related to #1118

**Comment by PeterDSteinberg** [comment]
TODO ( @MattHJensen - this list captures our conclusions from #1180 ):

 * [ ] Make a new repo in Github `open-source-economics` Github org that is public.  @MattHJensen - I think you will need to create the repo.  A name might be `taxbrain-builder` or similar since it will build `taxcalc`, `ogusa`, `btax`, and the future package we will create to abstract some of the model logic out of `webapp-public`.
 * [ ] Move logic that is currently in the `distribution` directories of Tax-Calculator, OG-USA to the new builder repo in `open-source-economics`
 * [ ] Modify conda recipe in Tax-Calculator to be based on programmatically reading `environment.yml` and inserting dependencies in `meta.yaml` (See also #1180 discussion)
 * [ ] Close PRs / issues related to `conda-forge`
 * [ ] Document package build process

**Comment by MattHJensen** [comment]
@PeterDSteinberg, this looks right to me. Here's the [policybrain-bulder repo](https://github.com/open-source-economics/policybrain-builder). Could you wait on this project until after webapp milestones b3, though? Getting through b2 and b3 ought to be high priorities right now.

**Comment by PeterDSteinberg** [comment]
Delaying until after b3 sounds good to me @MattHJensen

**Comment by martinholmer** [comment]
@PeterDSteinberg listed this to-do item in the discussion of Tax-Calculator issue #1158:
> Modify conda recipe in Tax-Calculator to be based on programmatically reading environment.yml and inserting dependencies in meta.yaml (See also #1180 discussion)

I'm not sure this is a good idea.  The `environment.yml` file specifies the development and testing environment, while `conda.recipe/meta.yaml` specifies the execution environment (with no testing) of the taxcalc package.  These two environments need not be the same, which is what this to-do item would impose.

I'd suggest you take it off your list of things to do and also check a number of other boxes that seem to have been implements in the new policybrain-builder repository.

@MattHJensen

**Comment by PeterDSteinberg** [comment]
@martinholmer - Most of the items of the checklist above had been completed, but I had not circled back to this issue.  Regarding your comment above, I agree at this point it would be easier to keep the `meta.yaml` and `environment.yml` logic separate.  In that case, this comment is a reminder for everyone when you change a package dependency or its version in the `environment.yml` or `conda.recipe`, you must make that change in both the `conda.recipe` and the `envrionment.yml`, otherwise some of us may be running with different requirements' versions.

cc @MattHJensen @jdebacker @brittainhard

**Comment by martinholmer** [comment]
@PeterDSteinberg said in the conversation around issue #1158:
>  I agree at this point it would be easier to keep the `meta.yaml` and `environment.yml` logic separate.  In that case, this comment is a reminder for everyone when you change a package dependency or its version in the `environment.yml` or `conda.recipe/meta.yaml`, you must make that change in both the `conda.recipe/meta.yaml` and the `envrionment.yml` files, otherwise some of us may be running with different requirements' versions.

Agreed!  Thanks for spelling out the details of this to make it crystal clear.

Now that you have circled back to issue #1158, what is its status? 
Can it be closed with a pointer to the work being done in the policybrain-builder repo?

@MattHJensen @PeterDSteinberg @brittainhard @jdebacker @rickecon @GoFroggyRun

**Comment by PeterDSteinberg** [comment]
Closing this issue.  If you have questions about `environment.yml`, `conda.recipe/meta.yaml` for any of the packages, see the [policybrain-builder repo](https://github.com/open-source-economics/policybrain-builder) and the corresponding Jenkins job.  If you need access to the Jenkins worker or help with [policybrain-builder](https://github.com/open-source-economics/policybrain-builder), let me know.  When running [policybrain-builder](https://github.com/open-source-economics/policybrain-builder), feel free to message me to check the pushed packages, and remember to look into whether you are pushing to the `dev` or `main` label of `ospc`.

**Comment by martinholmer** [comment]
@PeterDSteinberg,  Thanks!
