### ISSUE TITLE
Update current_law_policy.json with 2017 parameters

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1165]
The latest parameter values hardcoded into Tax-Calculator are for 2016. IRS has released info for 2017, so these need to be updated. 

Last year's update was discussed in #538 and implemented in #554. Useful sources are described at both of those links.

**Comment by martinholmer** [comment]
Issue #1165 was resolved by @andersonfrailey pull request #1169 that added 2017 values to the `current_law_policy.json` file.
