### ISSUE TITLE
CodeCoverage not working on GitHub PR submit

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1168]
For the last two days, there is no code coverage report generated when submitting a pull request on GitHub.  Has something been changed?  Or is something broken?

@PeterDSteinberg @MattHJensen

**Comment by martinholmer** [comment]
See an example of what is happening now at #1167.

**Comment by PeterDSteinberg** [comment]
I am not aware of any specific changes. Is there a fee associated with our usage level of codecov.io, @MattHJensen, and if so, maybe we are over our limit?

**Comment by martinholmer** [comment]
CodeCoverage seems to have "upgraded" its report format and content.  So, eventually you do get a sensible report as can now be in pull request #1167.

@MattHJensen @PeterDSteinberg
