### ISSUE TITLE
Problem with Windows environment

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1173]
A new Windows user followed the getting started directions in [this document](http://taxcalc.readthedocs.io/en/latest/contributor_guide.html), but could not pass all the unit tests because the mock package had not been installed.  Here is the the error message:
```
================================== FAILURES ===================================
_____________________________ test_force_no_numba _____________________________

    def test_force_no_numba():
        """
        Force execution of code for non-existence of Numba
        """
        global Magic_calc6

        # Mock the numba module
>       from mock import Mock
E       ImportError: No module named mock

taxcalc\tests\test_decorators.py:296: ImportError
```
@PeterDSteinberg, Can you explain why this happened on Windows?  Would the same thing happen to a new Mac users or a new Linux user?  What files control the addition of packages needed by Tax-Calculator but not in the standard Anaconda Python distribution?

**Comment by MattHJensen** [comment]
On #1172 I asked:

> Salim, did anything happen when you did activate taxcalc-dev? I don't see taxcalc-dev prepended to your system command prompt, so I'm wondering if that step didn't work.

To which Salim replied:

 > No, I never get any response when I run 'activate taxcalc-dev' - I didn't know I was supposed to.

**Comment by martinholmer** [comment]
@MattHJensen said:
> On #1172 I asked:
>
> Salim, did anything happen when you did activate taxcalc-dev? I don't see taxcalc-dev prepended to your system command prompt, so I'm wondering if that step didn't work.
To which Salim replied:
>
>> No, I never get any response when I run `activate taxcalc-dev` -- I didn't know I was supposed to.

I don't know what is supposed to happen either.  What is supposed to happen?  If there should be some kind of message, then does the lack of a message mean that the environment is not being activated?

That seems unlikely because all the other packages needed by Tax-Calculator were installed on his computer.  It was **only** the mock package that was missing.

Where is the documentation about how all this Conda environment magic is supposed to work?

**Comment by PeterDSteinberg** [comment]
See PR #1180 for a fix.  In the meantime `conda install mock` should install the necessary package.
