### ISSUE TITLE
Questions about variables in StageIFactors.csv file

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1174]
I have questions about the source and use of a couple of variables in the `StageIFactors.csv` file.
Here is a listing of the variables in that file:
```
tax-calculator$ ../csvvars taxcalc/StageIFactors.csv 
1 YEAR
2 APOPN
3 APOPDEP
4 APOPSNR
5 AGDPN
6 ATXPY
7 ASCHF
8 ABOOK
9 ACPIU
10 ACPIM
11 ARETS
12 AWAGE
13 ASCHCI
14 ASCHCL
15 ASCHEI
16 ASCHEL
17 AINTS
18 ADIVS
19 ACGNS
20 ASOCSEC
21 AUCOMP
22 AIPD
```
Here are my questions:

(1) I couldn't find anything in the taxdata repository that describes how the `AIPD` variable is constructed.  It was not listed in the `taxdata/docs/info/CBO Baseline Updating Instructions` file that contains all the other other economic projection variables.  Did I miss the documentation for the source of this variable?

(2) The `taxdata/docs/info/CBO Baseline Updating Instructions` file does mention a CBO projection variable called `RENTS`, but I don't see a variable like that in the `taxcalc/StageIFactors.csv` file.  Have I missed it?  If not, is there a reason to discuss it along with the other CBO economic projection variables that are included in the `taxcalc/StageIFactors.csv` file?

(3) The `taxcalc/StageIFactors.csv` file contains a variable called `APOPDEP`, but I can't find where it is used by Tax-Calculator.  Have I missed where it is used?  If not, is there a reason for including it in the `taxcalc/StageIFactors.csv` file?

(4) The `taxcalc/StageIFactors.csv` file contains a variable called `ARETS`, but I can't find where it is used by Tax-Calculator.  Have I missed where it is used?  If not, is there a reason for including it in the `taxcalc/StageIFactors.csv` file?

Answers to these questions will be very helpful in my redesign of the Growth class.  Thanks in advance for the answers to my questions.

@MattHJensen @Amy-Xu @andersonfrailey @feenberg @GoFroggyRun @codykallen

**Comment by Amy-Xu** [comment]
Martin asked:
>(1) I couldn't find anything in the taxdata repository that describes how the AIPD variable is constructed. It was not listed in the taxdata/docs/info/CBO Baseline Updating Instructions file that contains all the other other economic projection variables. Did I miss the documentation for the source of this variable?

Good catch! AIPD is not a factor we have from beginning. I added this factor because e19200 was off by about $200 million. This factor was derived from SOI interest paid amounts and CBO personal income growth rates. PR https://github.com/open-source-economics/Tax-Calculator/pull/231 has more details.

**Comment by Amy-Xu** [comment]
>(3) The taxcalc/StageIFactors.csv file contains a variable called APOPDEP, but I can't find where it is used by Tax-Calculator. Have I missed where it is used? If not, is there a reason for including it in the taxcalc/StageIFactors.csv file?

Interesting! I never noticed that. In the extrapolation process, this factor was used to make sure total dependent exemption number is on the right track. Maybe we have different assumptions on dependents in taxcalc? I'm not entirely sure on this. 

@MattHJensen

**Comment by andersonfrailey** [comment]
@martinholmer @Amy-Xu, looking through TaxCalc, I don't see anywhere APOPDEP is used. As far as I can tell it's only used in the extrapolation process. I believe it is the same case for ARETS.

As for RENTS, I might be missing something, but I can't see where it is used even in Stage One. @Amy-Xu is this correct or have I just overlooked it?

**Comment by martinholmer** [comment]
@andersonfrailey said:
> looking through TaxCalc, I don't see anywhere APOPDEP is used. As far as I can tell it's only used in the extrapolation process. I believe it is the same case for ARETS.

By "only used in the extrapolation process", do you mean used only in calculations internal to the taxdata repository?

@Amy-Xu @MattHJensen

**Comment by andersonfrailey** [comment]
@martinholmer 
>By "only used in the extrapolation process", do you mean used only in calculations internal to the taxdata repository?

Correct.

**Comment by martinholmer** [comment]
Tax-Calculator issue #1174 has been resolved by [taxdata pull request 63](https://github.com/open-source-economics/taxdata/pull/63).
