### ISSUE TITLE
Values in Current Law Policy

### ISSUE THREAD

**Issue by brittainhard** [open-source-economics/Tax-Calculator#1191]
@MattHJensen @PeterDSteinberg 

I'm working on the problem that causes the output of the `_AGI_surtax_thd` paramater to look like this: 
<img width="767" alt="screen shot 2017-02-13 at 11 39 00 am" src="https://cloud.githubusercontent.com/assets/5440553/22895152/24d5acde-f1e1-11e6-88b7-acbbab062c10.png">

The surtax parameter only has values for one year, so the [`expand_2D`](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters.py#L406) function adds in the missing values up to 2017. The problem is that inflation rates get applied to the `9e99` values, and you end up with strange numbers in the UI. If you are using the app and set the year to 2013, then the default inputs look fine, but they get larger as you increase the year setting, which is why you get values like `9.71309658528e+99`.

Peter and I talked it out, and we both think that values ending in `e99` are arbitrary placeholders, so the main problem here is fixing how these values appear on the frontend. Is it the case that these are arbritrary placeholders?

If so, there are a couple of options for fixing this. First, we could prevent inflation rates from being applied to numbers like `1e99` or `9e99` by adding some logic in the function. Second, we could just update `current_law_policy.json` and give it values for the missing years for `_AGI_surtax_thd`.

Let me know what you think, or if you need more clarification.

**Comment by MattHJensen** [comment]
@brittainhard said:

> Second, we could just update current_law_policy.json and give it values for the missing years for _AGI_surtax_thd.

That makes the most sense to me. It is what we do to, e.g., `_ID_c`:

    "_ID_c": {
        "long_name": "Ceiling on the amount of itemized deductions allowed (dollars)",
        "description": "The amount of itemized deductions is limited to this dollar amount. ",
        "section_1": "Itemized deductions",
        "section_2": "Ceiling on the amount of itemized deductions allowed",
        "irs_ref": "",
        "notes": "",
        "start_year": 2013,
        "col_var": "MARS",
        "row_var": "FLPDYR",
        "row_label": ["2013",
                      "2014",
                      "2015",
                      "2016",
                      "2017"],
        "cpi_inflated": true,
        "col_label": ["single", "joint", "separate", "head of household", "widow", "separate"],
        "value": [[1e99, 1e99, 1e99, 1e99, 1e99, 1e99],
                  [1e99, 1e99, 1e99, 1e99, 1e99, 1e99],
                  [1e99, 1e99, 1e99, 1e99, 1e99, 1e99],
                  [1e99, 1e99, 1e99, 1e99, 1e99, 1e99],
                  [1e99, 1e99, 1e99, 1e99, 1e99, 1e99]]
    },

I will fix this now.
