### ISSUE TITLE
Move macro elasticity from dropq to taxcalc

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1210]
As an act of expediency a long time ago, we put the implementation of the macro elasticity calculations in dropq. We should find a home for it in taxcalc.

**Comment by martinholmer** [comment]
@MattHJensen said:
> As an act of expediency a long time ago, we put the implementation of the macro elasticity calculations in dropq. We should find a home for it in taxcalc.

It is already in Tax-Calculator; look at the `taxcalc/macro_elasticity.py` file.

**Comment by MattHJensen** [comment]
Hmm, I guess I'm guiltier in my memory than real life. Closing.
