### ISSUE TITLE
Need for Tax-Calculator website

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1218]
After starting to read Karl Fogel's [Producing Open Source Software: How to Run a Successful Free Software Project](http://producingoss.com/en/producingoss.pdf), it seems clear that the Tax-Calculator project needs a website.  At first, it should target people who want to use Tax-Calculator on their local computer, and therefore, include simple instructions about how to get started and include static HTML documentation of policy parameters and input variables.  Eventually, it would be desirable to add a mailing list for users.  This user website would be accessible to those without any Python knowledge.

Although the projects are much bigger and more complex than Tax-Calculator, two examples of what seem to me to be successful user websites are those for [SQLite](http://www.sqlite.org/) and especially [Fossil](http://www.fossil-scm.org/index.html/doc/trunk/www/index.wiki).

This issue hopes to stimulate a discussion about how best to provide such a website.  All comments and suggestions are welcome.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @PeterDSteinberg

**Comment by rickecon** [comment]
@martinholmer I haven't started reading the book yet, but it seems sufficient to me to have an active GitHub repository with detailed README's  and issues, and then a link to a [Sphinx style](http://www.sphinx-doc.org/en/stable/) documentation set of pages (e.g., readthedocs).

**Comment by PeterDSteinberg** [comment]
@martinholmer - I have done readthedocs format a number of times.  Here's a good example of it for the dask project:

[http://dask.pydata.org](http://dask.pydata.org)

And here is the source and configuration files for making those docs:

[https://github.com/dask/dask/tree/master/docs](https://github.com/dask/dask/tree/master/docs)

It is possible also to push such docs to [readthedocs.io](http://readthedocs.io) automatically on merge to master, so that evry PR may update the relevant docs at the same time, if we would like.  Here's an example from a NASA project I am working on that is built automatically and pushed:  

[http://ensemble-learning-models.readthedocs.io](http://ensemble-learning-models.readthedocs.io)

**Comment by martinholmer** [comment]
@rickecon,  The objective is to present information for users (not developers) most of whom know nothing about version control, Python, etc.  They just want to be able to analysis tax reforms on their computer.  So, I'm not sure a GitHub repository, which shows all the files and their history, is the best approach.  When you go to a website, you never see a listing of all the .html and .css files that the browser is reading.

**Comment by martinholmer** [comment]
@PeterDSteinberg, Thanks for the suggestion of rst files and readthedocs, which is definitely an option for documentation.  But what about a mailing list and download of Tax-Calculator?  Can those things be handled on readthedocs?

**Comment by PeterDSteinberg** [comment]
Regarding the mailing list @martinholmer , we could add a `git push` hook event.  [This shows the basic idea](https://git-scm.com/docs/githooks#post-receive): it is about adding a post receive event, so after a tag is pushed by @MattHJensen , an email is sent out.  

(Here's a fancy post-receive event example from the docs linked above)[https://github.com/git/git/blob/master/contrib/hooks/post-receive-email]

**Comment by martinholmer** [comment]
@PeterDSteinberg, Thanks for the mailing list suggestion.  Can the capability you mention handle a mailmain mailing list like [this one](http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/fossil-users) and its archive like [this one](http://www.mail-archive.com/fossil-users@lists.fossil-scm.org/)?

**Comment by feenberg** [comment]
On Mon, 6 Mar 2017, Martin Holmer wrote:

> 
> @rickecon, The objective is to present information for users (not
> developers) most of whom know nothing about version control, Python, etc.
> They just want to be able to analysis tax reforms on their computer. So, I'm
> not sure a GitHub repository, which shows all the files and their history,
> is the best approach. When you go to a website, you never see a listing of
> all the .html and .css files that the browser is reading.

I think the typical economist would see a Github site as an invitation to 
go away. It meets the needs of a developer, but not of a user. The program 
can provide a useful service to many users without them modifying the 
Python code, but we need to have some documentation that guides the user 
to that end. Once they have experience as a user, they may be motivated to 
develope. Even better would be an installable .msi package for Windows 
that would bring everything in.

Do we have some way for users to convert a PUF into taxcalc format? Are we 
using SAS for that? The typical user won't have SAS. The CPS derived file 
is great, but not for all purposes. (Neither is the PUF, of course).

dan

**Comment by feenberg** [comment]
On Mon, 6 Mar 2017, Martin Holmer wrote:

> 
> @PeterDSteinberg, Thanks for the suggestion of rst files and readthedocs,
> which is definitely an option for documentation. But what about a mailing
> list and download of Tax-Calculator? Can those things be handled on
> readthedocs?

We do already have a mailing list, but it has no traffic to speak of. Matt 
has mentioned that all the congressional staff type users he is familiar 
with desire total anonymity and will not participate. But I would hope for 
student and faculty users also and they haven't shown up yet. I get more 
support questions for taxsim every week than I have seen on our mailing 
list in a year.

dan feenberg

**Comment by MattHJensen** [comment]
We have some experience with and infrastructure for readthedocs already because of [taxcalc.readthedocs.org](taxcalc.readthedocs.org) which is generated from the reStructuredText files [here](https://github.com/open-source-economics/Tax-Calculator/tree/master/docs/source).

**Comment by MattHJensen** [comment]
We have some experience and infrastructure for readthedocs already because of [taxcalc.readthedocs.org](taxcalc.readthedocs.org) which is generated from the reStructuredText (reST) files [here](https://github.com/open-source-economics/Tax-Calculator/tree/master/docs/source).

One option would be to continue using readthedocs while we develop the initial version of our user documentation.  Once the user documentation is complete, we could decide whether we want to move away from readthedocs to something with more flexible styling. 

It looks like a more flexible option that we could adopt now or later would be [GitHub pages with Jekyll. ](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/)

Jekyll can support reStructuredText [by itself](http://randomgeekery.org/post/2015/restructuredtext-in-jekyll/), but I'm not sure how readily GitHub pages and Jekyll interact when using reStructuredText instead of the default markdown.

**Comment by martinholmer** [comment]
@MattHJensen offered suggestions about how to develop and maintain static-web-page documentation for users of the Tax-Calculator CLI `tc`:
> It looks like a more flexible option that we could adopt now or later would be [GitHub pages with Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/).

After just a little reading about Jekyll it does seem promising.  One particular advantage is that it has an [addon](https://jekyllrb.com/docs/extras/) that allows LaTeX math expressions to be rendered as PNG graphs embedded in the text so that the resulting webpage looks similar to a PDF file generated from LaTeX.  We have already run into [problems in the taxdata repository](https://github.com/open-source-economics/taxdata/pull/82) because our current documentation methods don't allow for this.

Thanks for the suggestions.

**Comment by martinholmer** [comment]
@MattHJensen, After reading more about GitHub Pages, it seems like we would have a conflict because we are already using the `Tax-Calculator/docs` subdirctory for ReadTheDoc source files.  See this description of [GitHub Pages publishing sources](https://github.com/blog/2228-simpler-github-pages-publishing).  Using the `gh-pages` BRANCH as the source for GitHub pages seems infeasible since we are going to be using scripts to generate HTML files from JSON files that are on the `master` BRANCH.

**Comment by martinholmer** [comment]
@MattHJensen,  This [web page](http://docs.readthedocs.io/en/latest/faq.html) seems to say we can rename the `Tax-Calculator/docs/` directory as `Tax-Calculator/read-the-docs/` and everything will continue to work as it does now.

Is that the way you see it?

Here is the relevant info from that web page:
```
Where do I need to put my docs for RTD to find it?

Read the Docs will crawl your project looking for a conf.py.
Where it finds the conf.py, it will run sphinx-build in that directory.
So as long as you only have one set of sphinx documentation in your project,
it should Just Work.
```

If you concur, I'll try this rename when I return from Toronto on Tuesday, April 11th.
This rename will allow the `Tax-Calculator/docs/` directory to be used by GitHub Pages.

**Comment by MattHJensen** [comment]
@martinholmer, your googling was more effective than mine -- I looked for the same thing and didn't find it. That sounds great.

**Comment by martinholmer** [comment]
Thanks to all of you who contributed ideas about how to offer users (not developers) a website that provides basic information on how to use Tax-Calculator via the TaxBrain GUI and the tc CLI.

We're going to start by using GitHub pages to host this non-interactive website for users.

New issues will be raised as they come up in that development process.  Meanwhile, I'm closing issue #1218.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @PeterDSteinberg @brittainhard @rickecon
