### ISSUE TITLE
Tax-Calculator's interaction with webapp-public and deploy

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/Tax-Calculator#1224]
The handling of parameters between `webapp-public`, `deploy` and `taxcalc` is currently in an inconsistent state.  Basically, we have always received in the backend celery tasks, dicts like: 

`{u'2017': {u'_AMEDT_rt': [0.01], u'_ID_BenefitSurtax_Switch': [[True, True, True, True, True, True, True]]}}`

`webapp-public` currently continues to send `user_mods` to celery workers like that.

The problem is that `taxcalc` is now strictly [enforcing a new dictionary structure here](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/dropq/dropq.py#L51) and we get an exception there.  The exception is that we do not have the new `user_mods` structure with keys of: 

```
'policy', 'consumption', 'behavior','growdiff_baseline', 'growdiff_response','gdp_elasticity'
```

Questions:

 * It appears to me that the dict example above `{u'2017':...` should be the `policy` dict and we could assign every other field, such as `growdiff_baseline` to empty dicts,  not sure if that simple fix is accurate and it may mask calculation errors later.
 * Should all the parameters from `ospc.org/taxbrain` go into the `policy` dict?  It seems we may need to change [the usages of `package_up_vars` in webapp-public](https://github.com/OpenSourcePolicyCenter/webapp-public/search?utf8=%E2%9C%93&q=package_up_vars) to make sure we package the `user_mods` in the format.

**Comment by PeterDSteinberg** [comment]
^^ cc @martinholmer @MattHJensen @brittainhard

**Comment by MattHJensen** [comment]
@PeterDSteinberg,

My initial assessment is that: 

The parameters from the TaxBrain static input page should all go into the `policy` dict. 

The parameters from the TaxBrain macro-elasticity dynamic model should go into the `gdp_elasticity` dict. 

The parameters from the TaxBrain Partial Equilibrium dynamic model should go into the `behavior` dict.

**Comment by PeterDSteinberg** [comment]
That makes sense to me @MattHJensen. The unused fields will just be `{}` so we don't get this key missing exception.  Does that mean `growdiff_baseline`, `growdiff_response`, and `consumption` are currently not used by the apps - placeholders for future features?

**Comment by MattHJensen** [comment]
> Does that mean growdiff_baseline, growdiff_response, and consumption are currently not used by the apps - placeholders for future features?

Yes and no. They are not currently used by the TaxBrain GUI. But they will be available to taxbrain/file users after https://github.com/OpenSourcePolicyCenter/webapp-public/issues/500 is resolved.

**Comment by PeterDSteinberg** [comment]
Ok - I'll make changes to deploy based on what you described above, @MattHJensen .  Then I'll deploy to test-app in next hour or so and, if all goes well, ospc later today.

**Comment by brittainhard** [comment]
@PeterDSteinberg are there changes that need to be made in taxbrain? Can we tell, based on the request sent to the flask server, whether the data came from static input or one of the dynamic models?

**Comment by PeterDSteinberg** [comment]
@brittainhard - the backend will know which endpoint is passing the parameters and can make some adjustments.  But it seems like we need some way in `macro-elasticity` and `Partial Equilibrium` models to differentiate between `policy` parameters and parameters specific to the elasticity or equilibrium model.  Is that correct, @MattHJensen ?  It was my impression that since those models are built on `taxcalc`, that they have parameters that may be considered `policy` and some that may be either `behavior` or `gdp_elasticity` (depending on the endpoint receiving request).

**Comment by MattHJensen** [comment]
@PeterDSteinberg, that is correct. The policy parameters are coming along from the static input, and then the behavior or gdp_elasticity params are added to those depending on the dynamic modeling case.

**Comment by martinholmer** [comment]
Is there likely to be any further discussion of Tax-Calculator issue #1224, **Tax-Calculator's interaction with webapp-public and deploy**?

If not, should #1224 be closed?

@PeterDSteinberg @MattHJensen

**Comment by MattHJensen** [comment]
Thanks @martinholmer. I believe this is resolved and am closing. @PeterDSteinberg, please comment if this should be reopened.
