### ISSUE TITLE
Parameterizing specific policy reforms

### ISSUE THREAD

**Issue by jjbergdo** [open-source-economics/Tax-Calculator#1236]
Hi everyone. I am writing on behalf of the research team at the Indiana University Lilly Family School of Philanthropy with a  request. We are developing a white paper on the effects of certain proposed policy changes to both charitable giving and overall tax revenue.  Based on initial feedback, it appears that these can be implemented using the Tax Calculator. 

However, we have a tight timeline and no one on our team  has worked with the Tax Calculator before. The two big policy changes we would like to be able to test are:
 
- [ ] Make the charitable deduction available to non-itemizers
- [x] Expand the standard deduction to 95% of filers (from the ~2/3s who currently use it)
 
We talked to @matthjensen about gaining access to the puf.csv file for the purpose of imputing charitable deductions for non-filers based on our work with the Panel Study of Income Dynamics (PSID). I'll open a separate issue with more on that imputation — I understand that the first reform would require that data. 

There are other things we would like to test, but those are already available for modifying with the Tax Calculator (e.g., top marginal tax rates). We would greatly appreciate any help in regards to this.

**Comment by MattHJensen** [comment]
> - Expand the standard deduction to 95% of filers (from the ~2/3s who currently use it)

@jjbergdo, in the model currently, taxpayers choose between the itemized deduction and the standard deduction in order to minimize their total tax liabilities.  The simplest ways to move more filers onto the standard deduction is to either lower the value of itemized deductions or increase the value of the standard deduction. Is your goal to find the value of the standard deduction such that 95% of tax units choose to take it rather than itemize? Or do you have something else in mind?

**Comment by jjbergdo** [comment]
@MattHJensen My understanding is that we were planning on expanding the standard deduction, modeled (for now) after the Camp tax reform plan from a few years ago, with $11,000/individual $22,000/married for the standard deduction values. The 95% number came from some analysis of the plan at the time. Sorry for the lack of clarity there.

**Comment by MattHJensen** [comment]
> My understanding is that we were planning on expanding the standard deduction, modeled (for now) after the Camp tax reform plan from a few years ago, with $11,000/individual $22,000/married for the standard deduction values.

Thanks @jjbergdo for the clarification. That's something that taxcalc can already do, so I am going to check this off and focus on the other reform.
