### ISSUE TITLE
Webapp users should be able to change the number of tax brackets

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#132]
Many tax proposals increase or decrease the number the number of tax brackets. Decreasing the number of tax brackets is most common, and the webapp currently allows users to decrease the number of brackets by zeroing out thresholds. Some users will want to increase the number of brackets, and zeroing out thresholds to decrease the number of brackets is not particularly elegant. We should extend taxcalc and TaxBrain to accommodate this.

**Comment by MattHJensen** [comment]
This has not proven to be high-priority. @GoFroggyRun will need to add a tax bracket as part of his work on https://github.com/open-source-economics/plot_concepts/issues/3, but there is not a need right now for user-defined numbers of taxbrackets in Tax-Calculator and TaxBrain right now.

**Comment by feenberg** [comment]
On Thu, 4 Aug 2016, Matt Jensen wrote:

> 
> This has not proven to be high-priority. @GoFroggyRun will need to add a tax bracket
> as part of his work on open-source-economics/plot_concepts#3, but there is not a need
> right now for user-defined numbers of taxbrackets in Tax-Calculator and TaxBrain right
> now.

It is certainly easy enough to use fewer brackets - just repeat the last 
bracket info. But additional brackets are not possible. We could just add 
an extra bracket that repeats the currentl last bracket to the standard 
web page if we wanted to give the opportunity to add an additional bracket 
without spending a lot of time developing a mechanism for an arbitraty 
number of brackets.

One additional bracket is a characteristic of many proposed reforms in the 
past.

dan

**Comment by MattHJensen** [comment]
> We could just add an extra bracket that repeats the currentl last bracket to the standard web page if we wanted to give the opportunity to add an additional bracket without spending a lot of time developing a mechanism for an arbitrary number of brackets.

@gofroggyrun, could you keep this in mind when you are adding an extra bracket to tax-calculator fpr the plot work--that the default should be set to duplicate the existing top rate? Also, once the functionality is in tax-calculator, could you open an issue on webapp-public requesting that it be added to TaxBrain as well?

**Comment by GoFroggyRun** [comment]
@feenberg:
>
We could just add an extra bracket that repeats the currentl last bracket to the standard web page if we wanted to give the opportunity to add an additional bracket without spending a lot of time developing a mechanism for an arbitrary number of brackets.

Thanks for your thoughtful suggestion on dealing with extra tax brackets. I'll add such feature to tax-calculator.

@MattHJensen:
>
Also, once the functionality is in tax-calculator, could you open an issue on webapp-public requesting that it be added to TaxBrain as well?

Will do.
