### ISSUE TITLE
The taxcalc 0.8.2 package for Python 2.7 is missing in action

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1348]
Three weeks ago I was able to use `conda` to install the taxcalc 0.8.2 package on my computer which is running Python 2.7.  You can see that from these [file-upload-test results](https://github.com/open-source-economics/Tax-Calculator/tree/master/file-upload-tests) I committed three weeks ago.

But today I get these results:
```
$ python --version
Python 2.7.12 :: Anaconda 2.3.0 (x86_64)

$ conda --version
conda 4.3.17

$ conda install -c ospc taxcalc=0.8.2 --dry-run
Fetching package metadata ...........
Solving package specifications: .
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7*
  - taxcalc 0.8.2* -> python 3.4*
Use "conda info <package>" to see the dependencies for each package.

$ conda search -c ospc taxcalc | grep 0.8
                             0.8.0               np111py35_0  ospc            
                             0.8.0               np111py34_0  ospc            
                             0.8.0               np111py27_0  ospc            
                             0.8.1               np111py27_0  ospc            
                             0.8.1               np111py35_0  ospc            
                             0.8.1               np111py34_0  ospc            
                             0.8.2               np111py34_0  ospc            
                             0.8.2               np111py35_0  ospc            
```
What happened to the `np111py27_0` version of the taxcalc 0.8.2 package?

This it the most recent package (because we don't yet have a taxcalc package for the 0.8.3 code release) and the version of the package for Python 2.7 has gone missing.  What's happening?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @zrisher 
@PeterDSteinberg @brittainhard

**Comment by PeterDSteinberg** [comment]
0.8.2 was in the dev label on ospc.  It was not supposed to be that way.  I'm pretty sure I tested and confirmed it was not that way when I rebuilt 0.8.2 2 days ago and confirmed.  

For the next 2 months or so (and probably this is a good long term goal), whenever any of us is going to run policybrain-builder or the Jenkins job around it, we should send out an alert email to: @MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @zrisher@PeterDSteinberg @brittainhard 

And let that group know what is being built, when to expect the build in dev label, and when to expect it will move to main.

**Comment by PeterDSteinberg** [comment]
I moved 0.8.2 from dev to main and now this works:

```
$ conda install -c ospc taxcalc=0.8.2
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/psteinberg/miniconda3-4.1.11/envs/py27d:

The following packages will be SUPERSEDED by a higher-priority channel:

    taxcalc: 0.8.3-np111py27_0 ospc/label/dev --> 0.8.2-np111py27_0 ospc

taxcalc-0.8.2- 100% |################################| Time: 0:00:30 203.10 kB/
```

**Comment by martinholmer** [comment]
@PeterDSteinberg,  Thanks for making the 0.8.2 taxcalc package available again.
