### ISSUE TITLE
request for personal exemption to payroll tax

### ISSUE THREAD

**Issue by ecbrown5** [open-source-economics/Tax-Calculator#1369]
A congressional staff member made this request after receiving an email about TaxBrain:

> I love this!  I had one random idea for an addition:  Tim Carney proposed concept of a personal exemption to payroll tax.  I think that would be an interesting variable to add to this.  http://www.washingtonexaminer.com/the-case-for-a-payroll-tax-cut/article/2560211

**Comment by econ02** [comment]
I will be working on this, check back for an update on my progress.

**Comment by MattHJensen** [comment]
Given the lack of clarity from user who requested this change, I am closing the issue until we have a better defined proposal. Otherwise we are likely to model something that isn't valuable to our users.
