### ISSUE TITLE
request to add (Tax change)/(Pre-reform after-tax income) to distributional tables

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1371]
Ernie Tedeschi requested on Twitter: 

![image](https://cloud.githubusercontent.com/assets/8301092/26210279/1a688b88-3bbd-11e7-8574-f996c014f08b.png)

**Comment by andersonfrailey** [comment]
@MattHJensen, I can work on this

**Comment by andersonfrailey** [comment]
![tabel example](https://cloud.githubusercontent.com/assets/20684675/26222017/6f61bf5a-3be6-11e7-9a74-9f0f8746c1bc.PNG)

@MattHJensen, is something like the column `aftertax_perc` what you had in mind? If so I'll open the PR now (I tried to recreate the reform in the screen grab but I must be missing a parameter somewhere. Either way the idea stands).

**Comment by MattHJensen** [comment]
@andersonfrailey, could you try reposting the table? It isn't showing up for me:

![image](https://cloud.githubusercontent.com/assets/8301092/26224470/85650dac-3bf0-11e7-8485-360345b14f8c.png)

**Comment by andersonfrailey** [comment]
![tabel example](https://cloud.githubusercontent.com/assets/20684675/26248115/f8e2fa54-3c6e-11e7-925d-eb82ecede333.JPEG)

@MattHJensen how about now?

**Comment by andersonfrailey** [comment]
It appears the screenshot I posted does not appear when using Chrome or Firefox. [Here](http://nbviewer.jupyter.org/github/andersonfrailey/Notebook-Uploads/blob/master/Pct%20Column%20Test.ipynb) is a link to the notebook the screenshot it from.

**Comment by MattHJensen** [comment]
@andersonfrailey, could you make a notebook with a table for a top rate cut from 39.6 to 35 and a table w a doubling of the standard deduction?

**Comment by MattHJensen** [comment]
@andersonfrailey, could you also open a PR with the changes so we can review the code diffs?

**Comment by MattHJensen** [comment]
@andersonfrailey, could you also include a separate table in the notebook with avg expanded income by decile?

**Comment by andersonfrailey** [comment]
@MattHJensen, [here](http://nbviewer.jupyter.org/github/andersonfrailey/Notebook-Uploads/blob/master/pct%20table.ipynb) is the notebook, but I'm having trouble with the PR. 

In `test_utils.py` I get multiple attribution errors `'str' object has no attribbute 'closed'`. I get the same error when running the tests on my master branch when I run `py.test` despite both being up to date with the origin. Should I open the PR anyway so others can see what might be going wrong?

**Comment by martinholmer** [comment]
Probably your taxcalc-dev conda environment is not up-to-date

**Comment by andersonfrailey** [comment]
Thanks, @martinholmer. Got it working.

**Comment by MattHJensen** [comment]
This is resolved. Closing.
