### ISSUE TITLE
Dedicated ceiling for interest paid deduction

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1384]
The [Renacci reform file](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/Renacci.json) implements a ceiling on the dollar amount of mortgage interest through the `ID_c` parameter (`long_name: Ceiling on the amount of itemized deductions allowed (dollars)`)

This works because all other itemized deductions are eliminated with the Renacci reform, and so the broad `ID_c` parameter only applies to the sole remaining deduction for interest paid. 

But it is quite precarious. 

One of the purposes of these reform files is to give users a starting point for tinkering with the reforms. If any user starts with Renacci.json and reverses the repeal of another itemized deduction, then the `ID_c` parameter will suddenly stop serving as a ceiling on interest paid and begin serving as a ceiling on all allowable itemized deductions. 

One option for solving this potential confusion would be to add a new, dedicated parameter that places a ceiling on the interest paid deduction. There may be other options that I haven't thought of. 

@hdoupe, could you think about whether a dedicated ceiling parameter is the right solution and, if so, open a PR that implements the parameter and replaces the use of `ID_c` in renacci.json?

cc @andersonfrailey

**Comment by hdoupe** [comment]
@MattHJensen, I'll give this some thought.  What do you think about offering this type of ceiling for each of the itemized deductions instead of only doing one for the interest paid?

**Comment by MattHJensen** [comment]
> What do you think about offering this type of ceiling for each of the itemized deductions instead of only doing one for the interest paid?

I don't have a problem with that. Interest paid (or mortgage interest to be more specific) is where I've seen the policy proposal before, but I can see why users might be interested in applying ceilings to other deductions as well.

**Comment by martinholmer** [comment]
Merging pull request #1385 by @hdoupe has resolved issue #1384, which is now being closed.
