### ISSUE TITLE
nonrefundable personal credit for analyzing Josh McCabe's "Tax Plan for Working-Class Families"

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1420]
[Josh McCabe](https://joshmccabe.wordpress.com/) is interested in being able to score his [tax proposal](http://www.nationalreview.com/article/448388/tax-reform-restructure-benefits-help-working-class-families) with Tax-Calculator / TaxBrain. 

I _believe_ there is only one capability that needs to be added to make it possible, the "nonrefundable personal credit."

**Comment by MattHJensen** [comment]
@econ02, could you look into this? 

cc @andersonfrailey @hdoupe

**Comment by feenberg** [comment]
On Fri, 9 Jun 2017, Matt Jensen wrote:

> 
> Josh McCabe is very interested in being able to score his tax proposal with
> Tax-Calculator / TaxBrain.
> 
> I believe there is only one capability that needs to be added to make it
> possible, a "$600 nonrefundable personal credit."

Would that be very similar in effect to raising the lowest tax bracket 
threshold by $6,000?

dan

**Comment by econ02** [comment]
The above suggestion should work, correct @MattHJensen ?

cc @feenberg

**Comment by MattHJensen** [comment]
I think we should add the credit parameter rather than relying on the lowest tax bracket threshold for two reasons:

1. It would have a similar effect on revenue, but not the same, and my intuition definitely isn't good enough to tell Josh to trust me that "it's close."
2. We'd get the intermediate variables wrong. For instance, we report total nonrefundable credits.

**Comment by econ02** [comment]
@MattHJensen Sounds good. 

My plan will be to build it with three variables (like the refundable credit) and just make it not refundable. 

_II_ncredit = Non-refundable credit amount
_II_ncredit_ps = Non-refundable credit phaseout start
_II_ncredit_prt = Non-refundable credit phaseout rate

**Comment by MattHJensen** [comment]
@econ02, the structure makes sense to me. 

The parameter API names warrant further consideration. You probably noticed that we don't currently have a consistent scheme for differentiating refundable and nonrefundable credits via their parameter names. For most parameters, refundability is documented in their long_name and section attribute, but not in their API name. 

In this case, I can see why it makes sense to document refundability in the API name as well, as the credit is identical to _II_credit but nonrefundable. 

My initial suggestion is _II_credit_nr, but I'd be interested to hear from @Amy-Xu, @martinholmer, and others about this as well. Don't worry too much about the name for now, though, as it can easily be changed after you open your PR. 

Creating a consistent naming scheme is complicated by the fact that some parameters are "partially refundable," and the rules for partial refundability vary.

**Comment by econ02** [comment]
See pull request #1427

**Comment by martinholmer** [comment]
Merging pull request #1427 by @econ02 has resolved issue #1420, which can now be closed.
