### ISSUE TITLE
Problem with `e20500` puf.csv variable and functions.py logic

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1425]
One of the variables in the `puf.csv` file is defined this way:
```
    "e20500": {
      "type": "float",
      "desc": "Sch A: Net casualty or theft loss",
      "form": {"2013-2016": "1040 Sch A line 20"}
    },
```
In other words, 10% of AGI has **already** been subtracted.

But we have a tax policy parameter called `ID_Casualty_frt` which is defined as:
```
  "_ID_Casualty_frt": {
        "long_name": "Deduction for casualty loss; floor as a decimal fraction of AGI",
        "description": "Taxpayers are eligible to deduct the portion of their casualty loss exceeding this fraction of AGI.",
        "section_1": "Itemized Deductions",
        "section_2": "Casualty",
        "irs_ref": "Form 4684, line 17, in-line.",
        "notes": "This rate cannot be decreased to lower than 0.1 due to lack of data. ",
        "row_var": "FLPDYR",
        "row_label": ["2013"],
        "start_year": 2013,
        "cpi_inflated": false,
        "col_var": "",
        "col_label": "",
        "value": [0.1],
        "validations": {"min": "default"}
    },
```

In order to juggle the contradiction in the input variable and the policy variable, the code undoes the 10% AGI subtraction in order to give the `ID_Casualty_frt` policy variable a role to play:
```
    # Casualty
    if e20500 > 0.0:  # add back to e20500 the PUFCSV_YEAR disregard amount
        c37703 = e20500 + ID_Casualty_frt_in_pufcsv_year * posagi
    else:  # small pre-disregard e20500 values are assumed to be zero
        c37703 = 0.
    c20500 = (max(0., c37703 - ID_Casualty_frt * posagi) *
              (1. - ID_Casualty_hc))
    c20500 = min(c20500, ID_Casualty_c[MARS - 1])
```

This approach is approximately correct for the `puf.csv` file, but potentially incorrect for other data being processed by Tax-Calculator.  For example, will the new CPS-base input dataset know AGI in order to subtract 10% of AGI from gross casualty losses?

Should we leave things as they are?  Or should we attempt to be more general, perhaps by having the input variable be gross casualty losses before the subtraction of ten percent of AGI?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @hdoupe

**Comment by feenberg** [comment]
I suggest defining a new variable in the base file for the gross amount, 
and let it be treated by Ohara's constants like other variables, and then 
used in the tax calculator. Reconstructing the gross amount ex post is 
fraught with difficulties, and changes in AGI will have a disproportionate 
affect on estimate of the net amount, since 10% of AGI is likely to be 
large relative to the net.

dan

**Comment by martinholmer** [comment]
@feenberg said:
> I suggest defining a new variable in the base file for the gross amount, and let it be treated by Ohara's constants like other variables, and then used in the tax calculator. Reconstructing the gross amount ex post is fraught with difficulties, and changes in AGI will have a disproportionate affect on estimate of the net amount, since 10% of AGI is likely to be large relative to the net.

I agree completely with your analysis.  The current problem is even worse than I first thought because, as you point out, the current logic is wrong (even when using the `puf.csv` file) whenever a reform changes AGI.

The [taxdata pull request 94](https://github.com/open-source-economics/taxdata/pull/94) implements your suggestion to replace in the `puf.csv` file the net loss variable `e20500` with a gross loss variable `g20500`.  I'll prepare a Tax-Calculator pull request to handle the new `puf.csv` file.

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe

**Comment by MattHJensen** [comment]
This makes sense to me, too.

**Comment by martinholmer** [comment]
The bug identified in taxcalc #1425 has been resolved by [taxdata pull request 94](https://github.com/open-source-economics/taxdata/pull/94) and taxcalc pull request #1426.
