### ISSUE TITLE
Tax cut vs. tax increase dynamic visualization

### ISSUE THREAD

**Issue by rickecon** [open-source-economics/Tax-Calculator#1448]
@DoraSzazs will begin work on a dynamic visualization using `Bokeh` that would generate in the `TaxBrain` user's browser window based on three columns of the distributional output by income group of a TaxBrain run (Tax units with tax cut, Tax units with tax increase, Average tax change).

<img width="935" alt="screen shot 2017-06-30 at 9 47 35 am" src="https://user-images.githubusercontent.com/4317690/27740968-4f9e886a-5d79-11e7-9027-54ed61c38d8d.png">

We are envisioning a dynamic bar chart that looks like the following sketch.

![img_0922](https://user-images.githubusercontent.com/4317690/27740579-20b43cc6-5d78-11e7-8768-8b030f9e2c8d.JPG)

We want:
1. A bar chart with number of filers with a tax increase by income bin on top (above the line) and the number of tax units with a tax cut by income bin on the bottom (below the line).
2. A small plot above the bars that shows the average tax change by income group
3. A slider bar that allows the user to adjust the chart for a certain year in the budget window

@MattHJensen @PeterDSteinberg

**Comment by DoraSzasz** [comment]
@rickecon 

I am thinking to push this plot here: https://github.com/open-source-economics/plots/tree/master/contrib, into a new folder, "tax_change". Do you agree? In this case we may want to create this issue under: open-source-economics/plots.

**Comment by DoraSzasz** [comment]
The first draft looks like this:
![screen shot 2017-07-13 at 10 38 58 am](https://user-images.githubusercontent.com/5504833/28174635-a4404cee-67b7-11e7-9e53-e1f955cd9903.png)

I still have to add the slider for the year. What years should I include? Do we have data for these years? I will also have to work on the design (fonts, grids, colors, tools). Any suggestion is welcomed. @MattHJensen @brittainhard

**Comment by rickecon** [comment]
@DoraSzasz , that is a great first draft.

1. I think the label on the x-axis of the main plot, instead of "Intervals", should be "Income brackets ($ thousands)".
2. I think we should have data point markers (circles or diamonds) in the top plot for average tax change.
3. Change the vertical labels on the main plot to be "Tax units with tax increase" and "Tax units with tax cut". It would be nice if those two labels could also be split over two lines.
4. I am wondering if we should change the units on the vertical axis to be percent of total tax units rather than number of tax units. Making this change would incorporate the total tax units in the "Count" column of the tabular output.
5. The slider should include the current year and the following nine years (the 10-year budget window).

@MattHJensen

**Comment by martinholmer** [comment]
@rickecon, where do we stand on Tax-Calculator issue #1448?

**Comment by martinholmer** [comment]
There as been no issue #1448 discussion for over four months and further conversation should be in `open-source-economics/plots` repo as suggested by @DoraSzasz earlier in the #1448 discussion.
