### ISSUE TITLE
pass through income shifting

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1461]
A TaxBrain user, John Olson, wrote to me via email: 
 
> We go through all this lovely trouble of separating out pass-through income rates in TaxBrain, and it would be great to model income-shifting, perhaps as an option in the partial-equilibrium simulation. The Tax Policy Center accomplishes this by redefining wage income as pass-through income when the marginal tax rate for income in a bracket is lower for a pass-through than ordinary income in that same bracket. UI-wise, I imagine it could be a checkbox to allow for this sort of income-shifting, or maybe we can define it in terms of an elasticity parameter.

(John kindly set up a GH account so that he can participate in any discussion of this issue: @olsonjs.)

**Comment by MattHJensen** [comment]
For reference, here is TPC's description of how they modeled the Trump campaign proposal, which they interpreted as specifying a top rate on pass through income of 15% [[source doc](http://www.taxpolicycenter.org/sites/default/files/alfresco/publication-pdfs/2000924-an-analysis-of-donald-trumps-revised-tax-plan.pdf)]:

> we assumed that starting in 2017, each year 5 percent of workers currently earning wages of $100,000 or more ($200,000 or more on a joint return) would begin to work through sole proprietorships or other pass-through businesses, until half had made that switch. Workers who switched and as a result had more than $500,000 of total pass-through income were taxed (under the special rates that apply to dividends) on actual distributions (which we assumed would be half of their new total pass-through income).

**Comment by martinholmer** [comment]
The [TPC 18-Oct-2016 analysis of the Trump tax plan](http://www.taxpolicycenter.org/sites/default/files/alfresco/publication-pdfs/2000924-an-analysis-of-donald-trumps-revised-tax-plan.pdf) includes this text at the top of page 2:
> The revised Trump plan would reduce the top individual income tax rate to 33 percent, reduce the corporate rate to 15 percent, and allow owners of pass-through businesses (such as sole proprietorships, partnerships, and S corporations) to elect to be taxed at a flat rate of 15 percent rather than under the regular individual income tax rates.  Capital gains and dividends would be taxed under the current preferential rate structure.  Distributions from “large” pass-through businesses received by owners who elected the 15 percent flat rate would be taxed as dividends. 

About that last sentence: is there a reason the `Trump2017.json` reform file does not include this feature?  Or does `Trump2017.json` include this reform provision, but I missed it in my quick read of that reform file?

@MattHJensen @codykallen

**Comment by codykallen** [comment]
@martinholmer asked 

> Is there a reason the Trump2017.json reform file does not include this feature? Or does Trump2017.json include this reform provision, but I missed it in my quick read of that reform file?

Trump2017.json does not include this feature because the Trump 2017 tax proposal lacks that degree of detail. As an example, the one-page proposal the administration released earlier this year simply states,

> 15% business tax rate

TPC's most recent discussion of the 2017 tax [proposal](http://www.taxpolicycenter.org/taxvox/trying-understand-details-president-trumps-tax-plan) states

> The Administration proposed a 15 percent rate on partnerships, sole proprietorships, and other pass-through businesses, but said little about how such a provision would work. TPC is assuming the 15 percent rate applies to all pass-through income and that it is a cap. Thus, someone in the 10 percent bracket would pay at 10 percent and someone in the 35 percent bracket would pay at 15 percent.

Trump2017.json uses the same assumption as TPC uses in its most recent analysis. 

I agree that it would be useful to allow individuals to reclassify wage income as pass-through income. We should build that feature, but we also need to consider potential regulations to prevent such income shifting.

**Comment by martinholmer** [comment]
@codykallen, Thanks for the background information on the `Trump2017.json` reform.

You also said:
> I agree that it would be useful to allow individuals to reclassify wage income as pass-through income. We should build that feature, but we also need to consider potential regulations to prevent such income shifting.

I'm still working on pull request #1464 to incorporate the idea that the new personal LLCs could, if no regulations prevented this, pay some compensation as wages (in order to get some income taxed in the lowest regular brackets below 15%) and the rest of compensation as pass-through income (that is taxed at 15%).  This idea came up in comments on the original version of PR #1464.

Do you have any thoughts on #1464?

**Comment by codykallen** [comment]
@martinholmer, it would be useful to also impose dollar or percent caps on the amount of pass-through income. In PR #1464, @olsonjs said 

> Are we sure the proposed law doesn't include some regulation defining what an employee is? There is currently a small tax benefit to non-wage income that the IRS polices with modest success. It would become a huge deal under this proposal, but I expect the problem is that the drafters of the law don't appreciate the difficulties of enforcement rather than that they expect to allow anyone to take advantage.

The Trump proposal (and the Ryan-Brady proposal) don't include specific definitions of what an employee is. However, Ways & Means at least appreciates the difficulties of enforcement. There are various potential rules under consideration to distinguish wage and pass-through income. Perhaps the most useful (and programmable) is the allocation of a fixed share of pass-through income to labor and a fixed share to capital, with the labor share taxed as ordinary wage income and the capital share taxed at the preferential rate.

**Comment by martinholmer** [comment]
@codykallen said:
> The Trump proposal (and the Ryan-Brady proposal) don't include specific definitions of what an employee is.  However, Ways & Means at least appreciates the difficulties of enforcement.  There are various potential rules under consideration to distinguish wage and pass-through income. 
 Perhaps the most useful (and programmable) is the allocation of a fixed share of pass-through income to labor and a fixed share to capital, with the labor share taxed as ordinary wage income and the capital share taxed at the preferential rate.

@codykallen,  Thanks for this information about the legislative thinking.
Do you know the range of values they're talking about for the fixed share to labor?

**Comment by codykallen** [comment]
From what I've heard, the most plausible labor-capital split would be 70/30. But if you want to build in that type of split, you could input any mandated labor share between 0 and 1.

**Comment by olsonjs** [comment]
This report from the BLS about estimating labor share may be useful, specifically the sections about proprietor's labor compensation: https://www.bls.gov/opub/mlr/2017/article/estimating-the-us-labor-share.htm

The Tax Foundation also talks a little about labor compensation here: https://taxfoundation.org/walkthrough-gross-domestic-income/

**Comment by martinholmer** [comment]
Thanks to both @codykallen and @olsonjs for the helpful information and discussion in issue #1461.

**Comment by martinholmer** [comment]
@codykallen said:
> From what I've heard, the most plausible labor-capital split would be 70/30. But if you want to build in that type of split, you could input any mandated labor share between 0 and 1.

Yes, I will build in the flexibility of the full [0,1] range for the labor share.

But what would the labor share be applied to in Tax-Calculator?
Would it be the share of `e02000` or 
the share of `e26270` or the share of 
the new `k1bx14_p` and `k1bx14_s` variables?

If you need to refresh your memory about how these variables are defined, search the [user documentation](http://open-source-economics.github.io/Tax-Calculator/) or the `records_variables.json` file.

**Comment by codykallen** [comment]
@martinholmer asked:

> But what would the labor share be applied to in Tax-Calculator?

That's hard to say. My best guess is that it would be applied to the sum of labor income (`e00200`) and all pass-through income, presumably `e00900 + e26270`. We may need to make some distinctions for primary and secondary filers, such as applying the split to `e00200p + e00900p + e26270` and `e00200s + e00900s` separately. I'm not sure how useful `k1bx14_p` and `k1bx14_s` will be for this, since they only cover partnership income but not S-corporation income.

**Comment by martinholmer** [comment]
@codykallen said:
>> But what would the labor share be applied to in Tax-Calculator?
>
> That's hard to say. My best guess is that it would be applied to the sum of labor income (e00200) and all pass-through income, presumably e00900 + e26270. We may need to make some distinctions for primary and secondary filers, such as applying the split to e00200p + e00900p + e26270 and e00200s + e00900s separately. I'm not sure how useful k1bx14_p and k1bx14_s will be for this, since they only cover partnership income but not S-corporation income.

Again, thanks for your thoughtful observations.  I guess this gets messy very quickly.

**Comment by martinholmer** [comment]
Now that pull request #1464 has been merged into the master branch, it seems sensible to close this issue #1461, which deals with earnings-shifting behavioral responses under the `Trump2017.json` reform.

I want to thank all of your for the helpful discussion of these matters in this issue.  The discussion here made the work in pull request #1464 much better than it would have been without this discussion.

@MattHJensen @feenberg @codykallen @olsonjs
