### ISSUE TITLE
ospc.org issues

### ISSUE THREAD

**Issue by ecbrown5** [open-source-economics/Tax-Calculator#1478]
The "About" page on ospc.org needs to include Cost of Capital Calculator with logo under "Our Products."

Also on the "About" page, all three of the social media links (Twitter, Facebook,LinkedIn) are inactive.

The "Apps" link on the bottom of the home page is also inactive. 

Thank you for your help!

**Comment by MattHJensen** [comment]
@ecbrown5, could you please move this issue to www.github.com/opensourcepolicycenter/webapp-public. Closing here.
