### ISSUE TITLE
Add pass through shifting method to the behavior module? 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1487]
I am wondering whether others think it would make sense and be valuable to parameterize the pass through shifting capabilities that @martinholmer developed in https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/earnings_shifting.py by incorporating those capabilities or similar in `behavior.py` and `behavior.json.` 

This would allow us to incorporate @olsonjs's suggestion for TaxBrain from #1461:

> UI-wise, I imagine it could be a checkbox to allow for this sort of income-shifting, or maybe we can define it in terms of an elasticity parameter. 

cc @feenberg, @hdoupe, @codykallen @andersonfrailey

**Comment by martinholmer** [comment]
@MattHJensen asked on July 20, 2017:
> I am wondering whether others think it would make sense and be valuable to parameterize the pass through shifting capabilities that @martinholmer developed in https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/earnings_shifting.py by incorporating those capabilities or similar in `behavior.py` and `behavior.json`.

This seems to be low benefit and very costly (maybe infeasible), so I think we should focus on higher priority issues.
