### ISSUE TITLE
Forthcoming release 0.10.0

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1492]
In major pull requests, please add a commit that edits the 0.10.0 section of the [release history](https://github.com/open-source-economics/Tax-Calculator/blob/master/RELEASES.md).

The last commit in 0.9.2 was 16dcccd, which was the merge of #1490 on July 26, 2017.

**Comment by martinholmer** [comment]
Are there any not-yet-merged enhancements that developers want included in version 0.9.3?

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe

**Comment by MattHJensen** [comment]
@martinholmer, there is nothing further that I hope to include in 0.10.0.  (I aim to include #1526 in 0.10.1 rather than 0.10.0.)

**Comment by martinholmer** [comment]
Tax-Calculator version 0.10.0 was released on August 28, 2017.
