### ISSUE TITLE
Consider using division operator from future module

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#1507]
Regarding the small differences between Python 2 and Python 3, the only thing that occurs to me is that there may be one or two operations occurring somewhere where the `/` operator is doing truncating integer division for Python 2 and float division for Python 3. It would be an interesting experiment to put `from __future__ import division` in all source files and see if the Py2 vs Py3 discrepancy is resolved. Making a note here to try myself, but whoever tries first should just report back results and if it resolves the findings in https://github.com/open-source-economics/Tax-Calculator/pull/1506

**Comment by martinholmer** [comment]
One experiment along the lines suggest in issue #1507 was conducted as part of the work involved in preparing merged pull request #1508.  Adding the `from __future__ import division` statement to several files did not change any `test_cpscsv.py` results under Python 2.7.

**Comment by martinholmer** [comment]
@talumbau found the source of the Python 2.7 versus Python 3.x differences described in #1506.
The results of his investigation are in issue #1522. 
So, the now obsolete issue #1507 is now being closed.
