### ISSUE TITLE
The WARNING for uses of iterate_jit with puf=True needs a better warning

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#152]
It should be clear that the puf argument in the function definition needs to be listed last, not the puf=True keyword argument in the invocation of the iterate_jit decorator.

**Comment by martinholmer** [comment]
@talumbau said on February 26, 2015:
> It should be clear that the `puf` argument in a function definition needs to be listed last, not the `puf=True` keyword argument in the invocation of the `iterate_jit` decorator.

The `puf` variable was removed from both Tax-Calculator function definitions and decorators in a series of pull requests merged in late June and July, 2016. These pull requests are in the range from #803 to #813.  So, the legitimate concern raised in this issue #152 is no longer relevant.
