### ISSUE TITLE
Decision to take standard deduction or itemized should be based on >= $0.01 difference

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#1522]
In looking at the Python 2 vs Python 3 differences raises in #1506, I wanted to understand why it is necessary to put a special additional epsilon for Python 3 in the `test_agg` test. If one takes this out, the expected results differ from the actual results (in Python 3) for two quantities: itemized deductions and taxable income.

Looking at itemized deductions, it turns out that this calculation in `utils.py` is different between Python 2 and 3:

```
   ided1 = recs.c04470 * recs.s006
   val = ided1[recs.c04470 > 0.].sum()
```

In Python 2, the size of `ided1[recs.c04470 > 0.]` is 258789 for the `test_agg` test, but it is of size 258788 in Python 3. Listing all of the indices in both Python 2 and Python 3, I find that the only index where there is a difference is index 63569. It turns out that in Python 2, `recs.c04470[63569] !=0`, but in Python 3, `recs.c04470[63569] == 0.`

This difference comes from when `c04470` is set in `calculate.py`:

```
       self.records.c04470[:] = np.where(item_taxes < std_taxes, item, 0.)
```

`item_taxes` is compared strictly against `std_taxes`. The troublesome value is at index 63569. The values between Python 2 and Python 3 when this line of code is executed in the test are as follows:

Python 3:

```
item_taxes[63659] = 7551.436044406477776647079736
std_taxes[63659] = 7551.436044406477776647079736
```

Python 2:

```
item_taxes[63659] = 7551.436044406477776647079736
std_taxes[63659] = 7551.436044406478686141781509
```

Here, I have forced the output of the floating point values to 24 digits after the decimal place. In truth, the numbers do not actually have this much precision, but this is enough to show that they are not the exact same floating point number in Python 2. In Python 3, the numbers are exactly the same, and so the comparison `item_taxes < std_taxes` fails for that index. In Python 2, std_taxes is bigger by ~1e-12, so we count this tax unit as an itemizer, instead of taking the standard deduction.

As to why this values comes at as `7551.436044406478686141781509` in Python 2 and `7551.436044406477776647079736` in Python 3, I didn't trace any further, but it is calculated in `functions.py`.

The point of this issue is to suggest that the Tax-Calculator should have a different method for determining whether a tax unit takes the standard deduction or itemizes deductions. My suggestion would be:

the tax unit takes the standard deduction, unless the tax owed through itemizing deductions is at least $0.01 less than the tax owed with the standard deduction.

I implemented this through something like these functions:

```
       self.records.standard[:] = np.where(less_than(item_taxes, std_taxes),
                                            0., std)
```

where `less_than` is:

```
def less_than(a, b, tol=0.01):
    """
    Return boolean array indicating if element in a < corresponding element
    in b, exceeding an absolute tolerance of tol
    """
    return (b - a) >= tol
```

When I ran the tests with these changes, many tests failed (a lot of rounding differences in some of the more involved tests), so this is a change that would have to be discussed.

To me (a complete novice in this area), the proposed rule is sane and reflects what an actual person would do. I don't think it's particularly realistic to count a record as itemizing or not based on a difference of 1e-12. This would also resolve any of these small differences between Python 2 and 3.

Perhaps there is another, better, rule that folks could come up with. I just think that a straight floating point comparison is not the best.

**Comment by martinholmer** [comment]
@talumbau, Thanks for your in-depth analysis in #1522 of differences between Python 2.7 and Python 3.x floating-point calculations and the resulting problem mentioned in #1506.  Your suggestion is not unreasonable; we'll give it serious consideration.  Thanks again for the excellent detective work.

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @codykallen

**Comment by martinholmer** [comment]
@talumbau, After thinking more about your suggestion in issue #1522, I'm not so sure your idea will solve our problem.  If the floating-point arithmetic is slightly different in Python 2.7 and Python 3.x, then won't we run the risk of getting the "boundary problem" you discovered no matter where we put the dividing line?  Put a different way, if we get one filing unit that is on either side of `itemized_savings > 0.0` boundary, who's to say we won't get a different filing unit that is on either side of `itemized_savings > 0.01` boundary?

Or maybe I'm missing something about your suggestion.

**Comment by talumbau** [comment]
Yes, I believe I understand your point. For a given tax unit, if itemized savings in Python 2 was 0.01 - epsilon and 0.01 in Python 3, the behavior should be the same for both versions (the tax unit should be counted as itemized). Therefore, the rule should probably be:

the tax unit takes the standard deduction, unless the tax owed through itemizing deductions *rounded to the nearest cent* is at least $0.01 less than the tax owed with the standard deduction when *rounded to the nearest cent*.

This adds a bit more discretization to the approach to handle these small deltas (which shouldn't exist anyway but I'll have to dig in to that another day).

**Comment by martinholmer** [comment]
@talumbau said:
> Therefore, the rule should probably be:
>
> the tax unit takes the standard deduction, unless the tax owed through itemizing deductions rounded to the nearest cent is at least $0.01 less than the tax owed with the standard deduction when rounded to the nearest cent.
>
> This adds a bit more discretization to the approach to handle these small deltas (which shouldn't exist anyway but I'll have to dig in to that another day).

But even this rule runs the risk of producing different results on Python 2.7 and Python 3.x.  The two different sets of floating-point calculations can produce different (rounded to the nearest cent) results.

I appreciate your intellectual curiosity and your detective work revealed the cause of the problem, which is slightly different floating-point results on Python 2.7 and Python 3.x.  I imagine if we had been doing the `requires_pufcsv` test on all versions of Python, we might have already run into this issue.  What to do?  Frankly, I'm happy to leave the core and test code just as it is.  Too many risks on changing the tax-calculating logic without an assured solution to this test problem.

**Comment by martinholmer** [comment]
There has been no discussion of issue #1522 for two weeks.
I'm going to close #1522 for the reasons discussed earlier in #1522.
We know there are floating-point differences between Python 2.7 and Python 3.x and the unit tests take that into account.  I don't think there is any way to avoid these differences via a "rounding" strategy.
