### ISSUE TITLE
Next release after 0.10.2

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1535]
In major pull requests, please add a commit that edits the 0.11.0 section of the release history in [RELEASES.md](https://github.com/open-source-economics/Tax-Calculator/blob/master/RELEASES.md#release-0110-on-2017--).

The last commit in 0.10.0 was 5993ab6, which was the merge of #1533 on August 28, 2017.
There was a bug fix that produced 0.10.1 on 2017-09-08.
There was a bug fix that produced 0.10.2 on 2017-09-13.
Both of these bug fixes have been incorporated into the 0.11.0 release.

**Comment by martinholmer** [comment]
@MattHJensen,  What do you think about doing release 0.11.0 now?
I'll be happy to handle this, but wanted to get your thoughts before proceeding.

@Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun

**Comment by MattHJensen** [comment]
> @MattHJensen, What do you think about doing release 0.11.0 now?

That sounds good to me. 

> I'll be happy to handle this, but wanted to get your thoughts before proceeding.

Thank you!

**Comment by martinholmer** [comment]
Release 0.11.0 was issued on 2017-09-21.
