### ISSUE TITLE
Which expanded_income to use in TaxBrain/dropq difference table bins?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1540]
In many reforms, `expanded_income` is unchanged from the current-law baseline.  But in situations where there is a difference, a question arises about how to classify filing units in `expanded_income` bins.  Should we use the baseline `expanded_income` or should we use the reform `expanded_income`?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @brittainhard @talumbau

**Comment by Amy-Xu** [comment]
It seems to me that we should use baseline expanded_income? That was the case with AGI when it's used as a bin classifier -- no matter how AGI is changed in the reform, always use the baseline AGI.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> It seems to me that we should use baseline expanded_income? That was the case with AGI when it's used as a bin classifier -- no matter how AGI is changed in the reform, always use the baseline AGI.

OK, but I'm unsure what you're referring to when you talks about AGI being "used as a bin classifier".
Where in Tax-Calculator do we use AGI as a bin classifier?

**Comment by feenberg** [comment]
Sorry, a thinko. I meant the baseline expanded income if that is what is 
used.

dan

**Comment by martinholmer** [comment]
Seems as if @Amy-Xu and @feenberg favor using baseline expanded income or baseline AGI (if that is the income measure) to classify filing units in bins in difference tables.  Anybody else want to state a view?

**Comment by MattHJensen** [comment]
I am in agreement w @Amy-Xu and @feenberg that we should use the baseline income measure for tabbing distribution tables. Otherwise a progressive reform that also moves people up the income-measure distribution might look regressive.

**Comment by martinholmer** [comment]
Thanks to everyone who responded to my question in issue #1540.
The answers were consistent and that answer has been incorporated into pull request #1537.
