### ISSUE TITLE
Add preset for Ro Khanna and Sen. Sherrod Brown

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1552]
A user asked for help modeling the Ro Khanna and Sherrod Brown EITC expansion. Adding a preset seems like an easy medium for providing that help. 

[Official description and link to legislative text](https://khanna.house.gov/media/press-releases/release-sen-sherrod-brown-and-rep-ro-khanna-introduce-landmark-legislation)

[TPC score](http://www.taxpolicycenter.org/taxvox/plan-radically-expand-earned-income-tax-credit)

**Comment by martinholmer** [comment]
@MattHJensen said in #1552:
> A user asked for help modeling the Ro Khanna and Sherrod Brown EITC expansion. Adding a preset seems like an easy medium for providing that help.

What exactly do you mean by a "preset"?
Does you mean a JSON reform file that represents this 2017 reform?
If so, I'll be happy to create one and add it to the taxcalc/reforms directory.

**Comment by MattHJensen** [comment]
> Does you mean a JSON reform file that represents this 2017 reform?
Yes, that's what I mean. 

> If so, I'll be happy to create one and add it to the taxcalc/reforms directory.
Thank you very much!

**Comment by martinholmer** [comment]
Issue #1552 has been resolved by merge of pull request #1555.
