### ISSUE TITLE
Human readable parameter diff

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1558]
Many of our users work with Tax-Calculator through their research assistants. 

Oftentimes the boss is quite knowledgeable about taxes, but the RA isn't. 

This leads to mistakes in translation from boss to RA to model to RA to boss. 

For example, the boss asks her RA to repeal the state and local tax deduction. The RA sets the state and local income and sales tax deduction haircut to one, not thinking or knowing that there is more to state taxation than income and sales. The boss never sees the parameter long names. and the only hope for correction is for the results to look wrong enough to raise an alarm. 

What should happen is that the RA should show a clear list of parameter changes and parameter documentation to his boss. But bosses don't think or know to ask for this, and it would be difficult for RAs to prepare such a file anyways as it would require significant manual labor.

This issue is to request a Tax-Calculator feature for automatically generating such a file. 

This file would of course be useful elsewhere, such as in the appendix of a paper so that readers could review the changes themselves and better replicate the paper. 

There have been several TaxBrain requests for such parameter-change documentation from @feenberg, but we haven't responded to those requests yet. If we add this feature to Tax-Calculator, it should make it much easier to make the same feature available on TaxBrain. 

I am not proposing a particular design right now as I haven't entirely thought out what the user needs or how something like this would be implemented.

**Comment by martinholmer** [comment]
@MattHJensen said in issue #1558:
> I am not proposing a particular design right now as I haven't entirely thought out what the user needs or how something like this would be implemented.

Don't spend any time now on "how something like this would be implemented" just clarify your thinking about "what the user needs".

Everybody on the development team should contribute their ideas about what information should be in this document and how the document should be organized.  Also, views about whether this document should be ASCII text or HTML would be appreciated.

@Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @codykallen @rickecon @jdebacker

**Comment by andersonfrailey** [comment]
At a minimum, I believe the document should have the parameter name, its description in the `current_law_policy.json` file, the default value, the new value, and the year that new value goes into effect.

As for the output file format, I'm in favor of a table with the above information sorted by parameter name or year of the reform.

I don't have a strong opinion on the output file type. My initial feeling is it might be a little easier to format as an HTML table than in a text file, but others may disagree.

**Comment by martinholmer** [comment]
Issue #1558 is mostly a TaxBrain issue because the `tc` CLI to Tax-Calculator already uses a commented text file with embedded JSON that specifies the reform's parameter changes.  And `tc` also accepts an assumption file that includes any behavior-response, consumption-response, growth-response, or growth-baseline changes that the user wants to make.  That file format also allows comments, so that the rationale for each change can be documented.  Both the reform and assumption file are text files that can be printed for or emailed to anybody interested in the exact nature of a Tax-Calculator simulation run.  Plus all the baseline information on all reform and assumption parameters is available in the [online documentation](http://open-source-economics.github.io/Tax-Calculator/) that can easily be searched in a browser.

This means, if the boss's RA were using Tax-Calculator, the documentation needs described in #1558 would already be largely met.  So, the question in #1558 is how best to provide TaxBrain users with this kind of documentation about each simulation run.

With version TaxBrain version 1.0.2, the TaxBrain GUI specification of a run is converted into a JSON reform file and sent to Tax-Calculator for execution.  As a first step in providing more TaxBrain run documentation that is easy to distribute, **why not make the TaxBrain-generated JSON reform file available on the TaxBrain Static Results page?**  If it could be downloaded and printed that would provide some easy-to-share documentation about the reform specified in the TaxBrain run.  (Plus it would provide a convenient way to check that the internal translation of the TaxBrain GUI input into JSON is being done correctly.  And it would provide a JSON reform file for use on a local computer with `tc`.)

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun

**Comment by MattHJensen** [comment]
@martinholmer said:

> Issue #1558 is mostly a TaxBrain issue because the tc CLI to Tax-Calculator already uses a commented text file with embedded JSON that specifies the reform's parameter changes. And tc also accepts an assumption file that includes any behavior-response, consumption-response, growth-response, or growth-baseline changes that the user wants to make. That file format also allows comments, so that the rationale for each change can be documented. Both the reform and assumption file are text files that can be printed for or emailed to anybody interested in the exact nature of a Tax-Calculator simulation run. Plus all the baseline information on all reform and assumption parameters is available in the online documentation that can easily be searched in a browser.

This is not my diagnosis of the issue at hand, which is that _Tax-Calculator_ users do not have an easy way to generate a human-readable file that describes their reforms. Yes, they could prepare such a file themselves by copying and pasting the parameter documentation from current_law_policy.json into a reform file, but that is a significant amount of work and they don't do it. Yes, they could just include the parameter names in the file and then their boss could cross-check against current_law_policy.json for the documentation, but that is also a significant amount of work and it doesn't happen to my knowledge.

**Comment by martinholmer** [comment]
@MattHJensen said:
> This is not my diagnosis of the issue at hand, which is that *Tax-Calculator* users do not have an easy way to generate a human-readable file that describes their reforms.

Oh, so you're talking about people who are working with Tax-Calculator by developing custom Python scripts that specify reforms as a dictionary (rather than specify reforms in a JSON reform file)?  Is that the target audience for this enhancement?

**Comment by MattHJensen** [comment]
> Oh, so you're talking about people who are working with Tax-Calculator by developing custom Python scripts that specify reforms as a dictionary (rather than specify reforms in a JSON reform file)? Is that the target audience for this enhancement?

The users who I have seen encounter this problem are developing custom Python scripts that specify reforms as dictionaries, but I imagine users of JSON reform files would face the same problem. So the target audience is "anyone using Tax-Calculator locally to analyze reforms." 

In some ways, TaxBrain users have it easier on this front because the edit parameters page includes, all in one place, old value, new value, and parameter documentation via the hover over. That said, @feenberg is right that there is not a good way to output that information from TaxBrain in a way that could be included in an appendix. I also certainly see the value of generating a reform file from TaxBrain input as you suggest above, but that solves a related but different problem. 

I wonder if a unified solution to all of these problems would involve making a Tax-Calculator utility for adding current law values and parameter documentation as comments (or additional attributes) to a json reform file. Then both Tax-Calculator and TaxBrain users could choose to output that file.

**Comment by martinholmer** [comment]
@MattHJensen said about issue #1558:
> I wonder if a unified solution to all of these problems would involve making a Tax-Calculator utility for adding current law values and parameter documentation as comments (or additional attributes) to a json reform file. Then both Tax-Calculator and TaxBrain users could choose to output that file.

OK, this approach sounds promising.  Let me think about this in more detail.

@feenberg @Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @codykallen

**Comment by hdoupe** [comment]
@martinholmer said
> As a first step in providing more TaxBrain run documentation that is easy to distribute, why not make the TaxBrain-generated JSON reform file available on the TaxBrain Static Results page? If it could be downloaded and printed that would provide some easy-to-share documentation about the reform specified in the TaxBrain run. (Plus it would provide a convenient way to check that the internal translation of the TaxBrain GUI input into JSON is being done correctly. And it would provide a JSON reform file for use on a local computer with tc.)

I second this.  Giving the users the ability to spot bugs in the input processing logic would be very helpful.

**Comment by feenberg** [comment]
On Fri, 22 Sep 2017, Martin Holmer wrote:

> 
> @MattHJensen said:
>
>       This is not my diagnosis of the issue at hand, which is that Tax-Calculator
>       users do not have an easy way to generate a human-readable file that
>       describes their reforms.
> 
> Oh, so you're talking about people who are working with Tax-Calculator by developing
> custom Python scripts that specify reforms as a dictionary (rather than specify reforms
> in a JSON reform file)? Is that the target audience for this enhancement?
>

Let me repeat my suggestion:

From time to time I get revenue scores in the form of two-page memoes, the 
first page describes the change in the law, the second has a distribution 
chart with a footnote also describing the change. The two descriptions are 
not always consistent and oftimes the description is quite vague so the 
distribution table is not useful. I feel we could do the profession a 
service by including with the distribution table an exact description of 
the changes used for the simulation. We can easily do this by printing the 
base and reform values of changed parameters as a header or footnote on 
the distribution table. If only a few parameters are changed, this is only 
a few lines. It should not be JSON, it is intended for human readability. 
The reader will not be a computer programmer.

dan

**Comment by martinholmer** [comment]
Issue #1558 has been resolved by pull requests #1564 and #1567.
