### ISSUE TITLE
taxcalc/comparison/stats_summary.py script does not work

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1562]
The `taxcalc/comparison/variable_stats_summary.csv` file was last generated on May 4, 2017.

The `taxcalc/comparison/correlation.csv` file was last generated on April 20, 2017.

According to the [taxpuf repo](https://github.com/OpenSourcePolicyCenter/taxpuf/releases), the `puf.csv` file has changed twice since then: once on June 16 and again on July 5.

But the `taxcalc/comparison/stats_summary.py` script no longer works.

@Amy-Xu, can you look into this?

**Comment by Amy-Xu** [comment]
@martinholmer I will look into this script shortly.

**Comment by martinholmer** [comment]
Issue #1562 has been resolved by pull request #1566.
