### ISSUE TITLE
Example notebook glitch

### ISSUE THREAD

**Issue by Amy-Xu** [open-source-economics/Tax-Calculator#1565]
https://github.com/open-source-economics/Tax-Calculator/tree/master/read-the-docs/notebooks

The two notebooks cannot be loaded on github.

**Comment by martinholmer** [comment]
@Amy-Xu said in #1565:
> The two notebooks cannot be loaded on GitHub.

Work just fine for me just now.  What happens on your computer?

**Comment by Amy-Xu** [comment]
@martinholmer Works well now. Sorry it was probably an internet issue.
