### ISSUE TITLE
Mortgage interest tax deduction option?

### ISSUE THREAD

**Issue by travelmail26** [open-source-economics/Tax-Calculator#1580]
is it possible to create an option to limit order and the mortgage interest rate deduction? I didnt see it in the list of options and its a very popular idea right now.

**Comment by martinholmer** [comment]
@travelmail26 asked:
> is it possible to create an option to limit order and the mortgage interest rate deduction? I didnt see it in the list of options and its a very popular idea right now.

You can use [TaxBrain](http://www.ospc.org/taxbrain/) to specify a maximum amount for itemized total interest paid (most of which is mortgage interest) using these Interest Paid Ceiling boxes:

![screen shot 2017-10-09 at 3 53 49 pm](https://user-images.githubusercontent.com/12170745/31356194-3218283c-ad0b-11e7-8e43-b44e63410e1f.png)

Does this capability meet your needs?
If not, please explain in detail exactly what kind of tax reform you want to simulate.

**Comment by martinholmer** [comment]
@travelmail26 asked about limiting the itemized mortgage-interest deduction in issue #1580.

Would you like to continue this conversion?  If not, I'll close this (#1580) issue.
