### ISSUE TITLE
Puzzling results for Brown-Khanna EITC expansion?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1581]
@travelmail26 said:
> Im having issues with average tax cut size per income on the expanded EITC. When i run what i think is a close appoximation to khanna's plan, the total cost seems right, but the average tax credit is less than 1500. it should be much higher.

> https://www.ospc.org/taxbrain/18094/

> or maybe im missing something about the averages? thanks

A couple of things to check:

1.  Make sure you've specified the GAIN Act correctly.  Look at [this document](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/BrownKhanna.json) to see our understanding of the details of the Brown-Khanna GAIN Act that expands the EITC.

2.  I'm not sure what you're looking at on TaxBrain to come to the conclusion that the "average tax credit is less than 1500".  The EITC is refundable, so when I use the Build Table options at the bottom of your results from run 18094 (see full URL above), I get this for current-law:

![screen shot 2017-10-09 at 6 21 53 pm](https://user-images.githubusercontent.com/12170745/31360957-e441ff34-ad1e-11e7-8264-e06f3fa4f168.png)
![screen shot 2017-10-09 at 6 24 00 pm](https://user-images.githubusercontent.com/12170745/31361027-31112416-ad1f-11e7-9635-1a08dc173798.png)

And this for the reform:

![screen shot 2017-10-09 at 6 30 00 pm](https://user-images.githubusercontent.com/12170745/31361170-fbe7e44a-ad1f-11e7-99ef-e7d3d64ddbf8.png)
![screen shot 2017-10-09 at 6 30 12 pm](https://user-images.githubusercontent.com/12170745/31361171-fdfe490e-ad1f-11e7-91e4-0735d17b84e4.png)

So, if we look at the third expanded income decile (labeled 20-30) we can calculate an average reform-induced increase in all refundable credits of about $1,834 per filing unit.  So, that's not too far away from your $1500.  Why exactly do you think the average increase in EITC should be "much higher" than these kinds of numbers?

**Comment by travelmail26** [comment]
I believe these are tpc's distribution table estimates

http://www.taxpolicycenter.org/model-estimates/earned-income-tax-credit-eitc-expansion-options-march-2017/t17-0201-increase-earned

at least some income brackets are averaging over $3k. maybe i did my simulation wrong. but that seems like it could be correct, given that some families will be getting 12k in tax credits

**Comment by martinholmer** [comment]
@travelmail26 said:
> I believe these are tpc's distribution table estimates
>
> http://www.taxpolicycenter.org/model-estimates/earned-income-tax-credit-eitc-expansion-options-march-2017/t17-0201-increase-earned
>
> at least some income brackets are averaging over $3k. maybe i did my simulation wrong. but that seems like it could be correct, given that some families will be getting 12k in tax credits

First, note that the TPC table is dated March 2017, so I have doubts whether this is exactly the GAIN Act, which was announced just a few weeks ago.

Second, when I click on the URL you provide I get Table T17-0201, which shows the "Average Federal Tax Change ($)" from the EITC reform they are simulating ranging from zero in the highest income groups to a maximum of $1,530 in their $20K-$30K income group.  I'm not seeing any groups have their income tax liability change more the $1,530.  Where do you see changes "over $3k"?

**Comment by martinholmer** [comment]
@travelmail26,  When looking at Table T17-0201 again, I see an "Avg Tax Cut for those with a Cut" column that does have an average as high as $3,460 per filing unit.  I guess that's what you're talking about.

There is no contradiction here.  This is simple arithmetic.  If, for an income group, the average tax change for those with a tax cut is, say $3,000 and the average tax change for everyone is, say, $1,500, then that means that half of the filing units in that income group have no change.  The TaxBrain results are conceptually equivalent to the TPC "Average Federal Tax Change" column.

**Comment by travelmail26** [comment]
ohhhh. ok. let me ask tpc what theres means. good to get the details right

**Comment by martinholmer** [comment]
Hopefully, issue #1581 has been resolved, in part, by improving the naming and ordering of difference table columns in merged pull request #1584.  @travelmail26, if you have any other questions regarding the Brown-Khanna GAIN Act or about interpreting the meaning of results in TaxBrain tables, feel free to open a new issue.
