### ISSUE TITLE
Comparing tax models

### ISSUE THREAD

**Issue by travelmail26** [open-source-economics/Tax-Calculator#1608]
The tax foundation just released a new study on tax cuts and wage growth

https://twitter.com/speakerryan/status/923555386413764613

What do you think is the best way to compare the tax foundation with other models? Can taxbrain currently do this?

**Comment by MattHJensen** [comment]
TaxBrain can not currently do this for business tax proposals, although it can to some extent for individual income and payroll tax proposals. OG-USA can do this, and you could open an issue for instructions over there. You could also use the stylized model linked to and described in [this blog post](http://www.aei.org/publication/analyzing-the-link-between-corporate-taxes-investment-and-gdp/).
