### ISSUE TITLE
add behavioral example to the 10 mins notebook 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1609]
#1604 deleted the behavioral example notebook. This issue is to add a behavioral example to the 10mins notebook.

See #1603 for background.

**Comment by martinholmer** [comment]
As described in #1610 there is now a [Tax-Calculator Cookbook](http://open-source-economics.github.io/Tax-Calculator/cookbook.html) with several recipes, one of which shows how to use the Behavior class.  As a result of this documentation, this issue is being closed.
