### ISSUE TITLE
Strengthen tests in 10mins notebook

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1610]
In #1603 I asked: 

> I do wonder why our notebook tests didn't catch this though.

@martinholmer replied:

> 
> Because the notebook tests are very weak. They only detect a fatal Python error.
> They have never done any validity checking on the answers the notebooks produce.
> 
> All I'm saying is that many of the results produced in the Behavioral_example.ipynb notebook are numerically incorrect after the merge of PR #1582. The notebook runs without a Python crash, but produces many incorrect results.

As @martinholmer further pointed out, this indicates a need for stronger tests in the 10min notebook.

**Comment by martinholmer** [comment]
This [comment](https://github.com/open-source-economics/Tax-Calculator/issues/1721#issuecomment-349613436) illustrates the weakness of the testing logic in the `test_notebooks.py` file.

**Comment by MaxGhenis** [comment]
I'm not familiar with the issue here, but would be happy to contribute example notebooks as a form of documentation if it can be resolved. I have a variety in https://github.com/MaxGhenis/taxcalc-notebooks of varying degrees of complexity, ranging from notebook versions of @martinholmer's recipes to larger analyses.

**Comment by martinholmer** [comment]
Over the past several months, this issue has been resolved indirectly by developing a [Tax-Calculator Cookbook](http://open-source-economics.github.io/Tax-Calculator/cookbook.html) of tested Python scripts that use the `taxcalc` package.  These scripts are tested before each release and can be easily uploaded into Jupyter Notebooks by users who like the interactive nature of notebooks.

**Comment by martinholmer** [comment]
Given the development of the Cookbook, this issue is being closed.
