### ISSUE TITLE
Updating data through 2027

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1611]
Currently, Tax-Calculator only extends through 2026. 

Given that we are near the end of 2017, and potential individual tax policy changes would likely tax effect beginning in 2018, Tax-Calculator will not be able to estimate the 10-year revenue impact of a policy change, for policy reforms beginning in 2018. 

I believe the necessary CBO data used to construct the growth factors has been out for months. Can we update growfactors.csv to reflect the new baseline CBO projections?

@MattHJensen @andersonfrailey @martinholmer @hdoupe @Amy-Xu

**Comment by andersonfrailey** [comment]
@codykallen we have everything we need to update. I believe this is a task our intern will be able to handle now that the instructions are relatively clear. I can have her start working on this.

**Comment by martinholmer** [comment]
@codykallen,  Thanks for the suggestion in issue #1606 1611.
Extending the extrapolation of data through 2027 with the new version of the `puf.csv` file is being handled as part of [taxdata pull request 114](https://github.com/open-source-economics/taxdata/pull/114).
