### ISSUE TITLE
Chained CPI capability

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1612]
Does Tax-Calculator have the capability to apply the chained CPI inflation to tax parameters? This could show up as part of tax reform, and we should have the capability to model it. 

I think the simplest approach would make a slight change to the `_ACPIU` growfactor, but does that inflation rate affect anything besides the parameter values linked to inflation?

Also, it is possible that tax proposals could link some parameters to the chained CPI but not others. If that is on the table, how would we model it?

@MattHJensen @andersonfrailey @hdoupe @martinholmer @Amy-Xu

**Comment by martinholmer** [comment]
@codykallen said in issue #1612:
> I think the simplest approach [to simulating chained CPI indexing reforms] would make a slight change to the `_ACPIU` growfactor, but does that inflation rate affect anything besides the parameter values linked to inflation?

I think the answer to your question is NO.  I think that because of the following results:
```
iMac2:taxcalc mrh$ grep ACPIU *py
growdiff.py:            growfactors.update('ACPIU', cyr, self._ACPIU[i])
growfactors.py:    VALID_NAMES = set(['ABOOK', 'ACGNS', 'ACPIM', 'ACPIU',
growfactors.py:        rates = [round((self.gfdf['ACPIU'][cyr] - 1.0), 4)
```
The `rates =` statement in `growfactors.py` is in the `price_inflation_rates` method.
So, when we look for where the `price_inflation_rates` method is used, we see this:
```
iMac2:taxcalc mrh$ grep price_inflation_rates *py
growfactors.py:    def price_inflation_rates(self, firstyear, lastyear):
policy.py:        self._inflation_rates = self._gfactors.price_inflation_rates(syr, lyr)
```
The Policy class does export the private `_inflation_rates` series via the `inflation_rate` method, but that method is called only to index parameters in child classes of the ParametersBase class (like the Policy class).

@codykallen also asked:
> Also, it is possible that tax proposals could link some parameters to the chained CPI but not others. 

NO, not when using your "simplest approach".

**Comment by codykallen** [comment]
@martinholmer's general reponse:

> NO, not when using your "simplest approach".

I figured as much. My questions was whether that would be approximately correct, not whether it was perfect. As far as I can tell, Tax-Calculator lacks the ability to apply alternative definitions of the inflation rate. And I'm unaware of a built-in capability to apply alternative inflation measures to some parameters but not others. 

The purpose of this issue was to ask whether Tax-Calculator can effectively model changes to inflation indexing. I thought the answer was no, and @martinholmer seems to confirm that. 

Given that changes to inflation indexing are at least on the table in tax reform discussions, this is a capability that Tax-Calculator should have.

**Comment by martinholmer** [comment]
@codykallen said:
> As far as I can tell, Tax-Calculator lacks the ability to apply alternative definitions of the inflation rate.

**That's not what I said.**  
What I did say was that you were correct when you suggested this approach:
> I think the simplest approach would make a slight change to the _ACPIU growfactor 

That approach will work just fine.  Just be sure you don't change the `growfactors.csv` file.
Instead use the `Growdiff` class along the lines in this test:
```
def test_update_and_apply_growdiff():
    syr = 2013
    nyrs = 5
    lyr = syr + nyrs - 1
    gdiff = Growdiff(start_year=syr, num_years=nyrs)
    # update Growdiff instance
    diffs = {2014: {'_AWAGE': [0.01]},
             2016: {'_AWAGE': [0.02]}}
    gdiff.update_growdiff(diffs)
    expected_wage_diffs = [0.00, 0.01, 0.01, 0.02, 0.02]
    assert_allclose(gdiff._AWAGE, expected_wage_diffs, atol=0.0, rtol=0.0)
    # apply growdiff to Growfactors instance
    gf = Growfactors()
    pir_pre = gf.price_inflation_rates(syr, lyr)
    wgr_pre = gf.wage_growth_rates(syr, lyr)
    gfactors = Growfactors()
    gdiff.apply_to(gfactors)
    pir_pst = gfactors.price_inflation_rates(syr, lyr)
    wgr_pst = gfactors.wage_growth_rates(syr, lyr)
    expected_wgr_pst = [wgr_pre[i] + expected_wage_diffs[i]
                        for i in range(0, nyrs)]
    assert_allclose(pir_pre, pir_pst, atol=0.0, rtol=0.0)
    assert_allclose(wgr_pst, expected_wgr_pst, atol=1.0e-9, rtol=0.0)
```

Do current chain CPI indexing reform proposals apply the chained CPI to only a subset of policy parameters?

**Comment by codykallen** [comment]
@martinholmer asked

> Do current chain CPI indexing reform proposals apply the chained CPI to only a subset of policy parameters?

It's not entirely clear. I know some parameters it could be applied to, but I haven't seen enough detail (in most plans) to know whether indexing to the chained CPI would apply only to specific parameters or in general. Given the uncertainty involved, it probably isn't worthwhile to build the capability for to apply chained CPI indexing differentially. 

Given the uncertainty involved, I'm closing the issue for now, but I'll reopen if a new plan comes up with such suggestions.

**Comment by martinholmer** [comment]
@codykallen said in #1612:
> Given the uncertainty involved [in whether reforms call for applying chained CPI to some indexed policy parameters while applying the unchained CPI to other indexed policy parameters], I'm closing the issue for now, but I'll reopen if a new plan comes up with such suggestions.

OK.  But what we've learned from this discussion is that we can apply a Growdiff value to the `_ACPIU` growfactor to simulate policy reforms that apply the chained CPI to **all** indexed policy parameters.
Users can do this without any change in Tax-Calculator logic.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @hdoupe
