### ISSUE TITLE
`pip install taxcalc` fails

### ISSUE THREAD

**Issue by craigcitro** [open-source-economics/Tax-Calculator#1613]
Just tried in a fresh virtualenv:

```
$ pip install taxcalc
Collecting taxcalc
  Downloading taxcalc-0.7.82.tar.gz (7.4MB)
    100% |████████████████████████████████| 7.4MB 192kB/s
    Complete output from command python setup.py egg_info:
    versioneer.py:713: SyntaxWarning: assertion is always true, perhaps remove parentheses?
      assert (versionfile_source is not None,
    versioneer.py:716: SyntaxWarning: assertion is always true, perhaps remove parentheses?
      assert (parentdir_prefix is not None,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-meBq3z/taxcalc/setup.py", line 13, in <module>
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-meBq3z/taxcalc/
$
```

I think the issue is that `README.md` needs to be listed in your `MANIFEST.in`.

**Comment by martinholmer** [comment]
@craigcitro said:
> Just tried in a fresh virtualenv:
> ```
> $ pip install taxcalc
> Collecting taxcalc
> Downloading taxcalc-0.7.82.tar.gz (7.4MB)
> ```

I'm not sure where it said to use `pip` to install the conda taxcalc package.
Can you point us to where you read this, so that we can eliminate that misinformation?

Your best bet is to follow the directions [here](http://open-source-economics.github.io/Tax-Calculator/#cli-install-test) and do this:
```
$ conda install -c ospc taxcalc
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/mrh/anaconda:

The following NEW packages will be INSTALLED:

    taxcalc: 0.12.0-py27_0 ospc

Proceed ([y]/n)? y

$ conda list taxcalc
# packages in environment at /Users/mrh/anaconda:
#
taxcalc                   0.12.0                   py27_0    ospc
```
If you have the Anaconda distribution for Python 3.6 (rather than 2.7) installed, then the `27` in the above example will appear as `36`.

Also, notice that this approach installs the newest version of the conda taxcalc package, which is 0.12.0.

Let us know if this works better for you.

**Comment by craigcitro** [comment]
I don't have `conda` installed -- but it looks like part of the issue is that the PyPI package is just really out of date:
  https://pypi.python.org/pypi/taxcalc
If you don't want people to use `pip`, any reason not to remove that package?

FWIW, `pip install https://github.com/open-source-economics/Tax-Calculator/archive/0.12.0.tar.gz` worked just fine.

**Comment by martinholmer** [comment]
@craigcitro asked:
> If you don't want people to use pip, any reason not to remove that package?

We are trying to remove that old package now.  
Thanks for pointing out this problem.
This pip package was put up before I started working on the project.

You're absolutely correct: it is very misleading to have this ancient version of taxcalc at this URL https://pypi.python.org/pypi/taxcalc

@MattHJensen @talumbau

**Comment by martinholmer** [comment]
@craigcitro said:
> I don't have conda installed ...
> FWIW, `pip install https://github.com/open-source-economics/Tax-Calculator/archive/0.12.0.tar.gz` worked just fine.

That interesting.  But if you don't have conda installed you probably don't have installed the Anaconda Python distribution, which is the environment that taxcalc operates in.

**Comment by hdoupe** [comment]
@craigcitro I'm glad that you're interested in Tax-Calculator.  Since we have had version problems with packages like NumPy and Pandas in the past, we primarily use conda for installation and setting up our development environment.

Let us know if you have anymore issues installing or running Tax-Calculator.

**Comment by MattHJensen** [comment]
> FWIW, pip install https://github.com/open-source-economics/Tax-Calculator/archive/0.12.0.tar.gz worked just fine.

This does not work for me. I'm leaving this issue open with a help wanted for someone to investigate whether it makes sense to get the package working with pip.

**Comment by martinholmer** [comment]
Matt said
> This does not work for me. I'm leaving this issue open with a help wanted for someone to investigate whether it makes sense to get the package working with pip.

I don’t see how pip install could ever work because it probably doesn’t understand the package dependencies in coma.recipe, which are critical for Tax-Calculator.

**Comment by martinholmer** [comment]
Thanks to @MattHJensen for removing the very old version of Tax-Calculator source code that had be put on PyPI during the spring of 2017.  This means that issue #1613 has been resolved.

And thanks again to @craigcitro for bring this problem to our attention.
