### ISSUE TITLE
Implementing Extrapolated Benefits into Tax-Calculator

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/Tax-Calculator#1617]
I've started working on modifying Tax-Calculator so that it will include benefit data for each tax unit. One of the bigger issues is determining the best way to include extrapolated benefit data. This issue is intended to serve as a discussion place to determine the best way to do that.

@hdoupe found that, compressed, a CSV with extrapolated benefit data for each tax unit is 3.2MB. However, when the file is opened it is closer to 200MB. Thus, we don't think that simply including that file in the taxcalc package would be the best option.

Other ideas that Hank and I have talked about are to use "growth factors" for the benefit data. The basic premise is that, instead of a file with the actual values for each year, we would have a file with a factors to multiply the values by so the result is the extrapolated value.

Alternatively, we could make a file that has the extrapolated benefits for just those who actually receive a benefit. We would then use the `RECID` variable to assign the benefits in Tax-Calculator. All tax units not included in the benefit CSV file would be shown to receive zero benefits.

We havne't checked what file size we would be facing with either of the options I specified, but I'd imagine both would be smaller than a full CSV file with values for everyone. This is obviously a work in progress so I would love to hear any other ideas the community has.

cc @martinholmer @MattHJensen @Amy-Xu

**Comment by Amy-Xu** [comment]
>@hdoupe found that, compressed, a CSV with extrapolated benefit data for each tax unit is 3.2MB. However, when the file is opened it is closer to 200MB. Thus, we don't think that simply including that file in the taxcalc package would be the best option.

I agree that this dataset shouldn't be included in taxcalc package, but if the dataset here refers to the one in taxdata [PR #108](https://github.com/open-source-economics/taxdata/pull/108), the size of that dataset can be reduce by at least 50%, because in the final output, we only need benefit per tax unit, not number of participants per tax unit.

> Other ideas that Hank and I have talked about are to use "growth factors" for the benefit data. The basic premise is that, instead of a file with the actual values for each year, we would have a file with a factors to multiply the values by so the result is the extrapolated value.

My concern for this method is about total participants. By controlling the total number of participants and benefits, we keep the average benefit in control. And the average benefit amount matters for UBI reform results. 

>Alternatively, we could make a file that has the extrapolated benefits for just those who actually receive a benefit. We would then use the RECID variable to assign the benefits in Tax-Calculator. All tax units not included in the benefit CSV file would be shown to receive zero benefits.

This seems more feasible.

**Comment by andersonfrailey** [comment]
Bringing this conversation back up, I modified the extrapolation scripts to include the `RECID` of each tax unit and only benefits for those who actually receive them, and drop the number of participants for each year. Compressed it is 3MB and uncompressed it's 65.3MB. This seems much more reasonable to include in the package.

**Comment by Amy-Xu** [comment]
@andersonfrailey Thanks Anderson! Sounds great. 👍

**Comment by martinholmer** [comment]
The merge of Tax-Calculator pull request #1719 resolves issue #1617.
