### ISSUE TITLE
Restructuring pass-through income

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1619]
The current version of the treatment of separate pass-through income allows it to be taxed at a different rate schedule. It determines pass-through income as the sum of `e00900` and `e26270`, which is technically true under current law. However, not all of this income is necessarily eligible for reduced pass-through tax rates. For example, the new Tax Cuts and Jobs Act would make 30% of business net income eligible for the reduced rates and 70% remain as ordinary income. 

To address this properly, I think we need a new function to determine what amount of income qualifies for the separate pass-through tax rates. A basic (and reasonable) approach would be to add indicators for whether `e00900` (sole proprietorship income), `e26270` (partnership and S corporation income) and `e02000 - e26270` (other Sch E income) would count toward business income, and a separate parameter for what share of "business income" is eligible for the reduced tax rates. 

I think I can build this reasonably easily (with some annoyance to design tests), but I'd like to hear some feedback before doing this. 

@MattHJensen @andersonfrailey @martinholmer @Amy-Xu @feenberg @GoFroggyRun @hdoupe

**Comment by MattHJensen** [comment]
This would allow for a dramatic simplification of the TaxBrain and Tax-Calculator user experiences if I understand it correctly. Users would only need to specify a separate pass thru rate schedule if they set this new percent-eligible parameter above 0. 

+1.

**Comment by GoFroggyRun** [comment]
@MattHJensen said: 
>Users would only need to specify a separate pass thru rate schedule if they set this new percent-eligible parameter above 0.

It seems that, as shown in PR #1620, what @codykallen suggests in #1619 is a more precise composition of PT amount. If there were reforms involving PT brackets, users still have to go through those PT fields on TaxBrain page. 

@codykallen said:
>To address this properly, I think we need a new function to determine what amount of income qualifies for the separate pass-through tax rates. A basic (and reasonable) approach would be to add indicators for whether e00900 (sole proprietorship income), e26270 (partnership and S corporation income) and e02000 - e26270 (other Sch E income) would count toward business income, and a separate parameter for what share of "business income" is eligible for the reduced tax rates.

I agree that this approach would yield a much more precise PT amount under related reforms. + 1

**Comment by codykallen** [comment]
This issue has been addressed by PR #1620. Closing.
