### ISSUE TITLE
ospc.org/hello is broken (linked from docs page)

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1640]
https://www.ospc.org/docs/ links to https://ospc.org/hello ("leave a note for the OSPC team"). This link doesn't work.

**Comment by MaxGhenis** [comment]
Ah, it needs www: https://www.ospc.org/hello works.

**Comment by MattHJensen** [comment]
Closing in favor of https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/737.
