### ISSUE TITLE
_ID_RealEstate_c is not documented

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1641]
`_ID_RealEstate_c` is in the TCJA reform file (https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Nov3.json) but not the parameters documentation  (http://open-source-economics.github.io/Tax-Calculator/index.html#pol).

**Comment by MattHJensen** [comment]
I will make sure this gets into the docs. 

In the meantime, you can read about it in the [current_law_policy.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/current_law_policy.json#L1158) parameter file from which the documentation is created.

**Comment by MattHJensen** [comment]
Looks like @martinholmer beat me to it!

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for your documentation bug report in Tax-Calculator issue #1641.

That bug has now been fixed, so the `_ID_RealEstate_*` policy parameters are now documented in the [itemized deductions policy parameters section of the user documentation](http://open-source-economics.github.io/Tax-Calculator/#pol-itemized-deductions).
