### ISSUE TITLE
Discrepancy between documentation and TCJA on _DependentCredit_Child_c

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1642]
The [parameters documentation](http://open-source-economics.github.io/Tax-Calculator/index.html#pol) says of `_DependentCredit_Child_c`:

> Notes: The Tax Cuts and Jobs Act sets this at $600

But the [TCJA reform](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Nov3.json#L101) sets it at 500 starting in 2018.

**Comment by codykallen** [comment]
@MaxGhenis, an intial reading would suggest that the TCJA sets the total child tax credit as $1600, but the refundable portion is based on the current $1000. This would be implemented by leaving `_CTC_c` as $1000 and setting `DependentCredit_Child_c` to $600. 

However, the TCJA also indexes the refundable portion to inflation, with the cost of living adjustment compared to the value in 2016 ($1000) rounded up to the nearest $100. Hence the refundable amount is rounded up to $1100 in 2018. To maintain the total amount of $1600 (which is not adjusted for inflation), the nonrefundable portion `DependentCredit_Child_c` is decreased accordingly ($500 in 2018). 

This is discussed further in PR #1631.

**Comment by MattHJensen** [comment]
@codykallen or @MaxGhenis, do you think it would be valuable to open a PR adding a note to the reform file with this information?

**Comment by martinholmer** [comment]
@codykallen,  Do you have an opinion about this question posed a week ago by @MattHJensen in issue #1642?

@MattHJensen asked:
> do you think it would be valuable to open a PR adding a note to the reform file with this information?

**Comment by codykallen** [comment]
> do you think it would be valuable to open a PR adding a note to the reform file with this information?

We're currently discussing potential alternative implementations of the interaction between `prectc` and `dependent_credit`. Once that is cleared up, we can reconsider whether it's worthwhile to add a note for that.

**Comment by martinholmer** [comment]
@codykallen said in issue #1642:
> We're currently discussing potential alternative implementations of the interaction between prectc and dependent_credit. Once that is cleared up, we can reconsider whether it's worthwhile to add a note for that [new approach].

OK.  So, it would seem issue #1642 is obsolete.  I'll close it now.
