### ISSUE TITLE
Strengthen caveats about cps.csv

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1647]
I have found in my own analysis and it has been reported to me from others that the cps.csv produces significantly different results than the puf.csv file for common reforms that our users want to analyze. For example, with the TCJA_Nov3.json reform file the revenue loss with the cps.csv file is under half of that with the puf.csv file. 

@evtedeschi3 reports that the error can be dramatically reduced with a different weights file, but we don't have that available for our users at this point. 

We need dramatically beef up the caveats that we provide for the cps.csv file that ships with taxcalc. The only current warning I could find in the tax-calculator documentation is:

> Second, recently we made freely available a public-use file containing only filing units derived from a recent March CPS survey. For several reasons, the results generated by this cps.csv file are not exactly the same as the results generated by the puf.csv file.

I am giving this a bug label given the significance of the discrepancy that I see between our current tax-calculator documentation and the utility of the file. 

@andersonfrailey has written stronger warnings in the taxdata repo, so that might be a place to start.

**Comment by martinholmer** [comment]
@MattHJensen said:
> @andersonfrailey has written stronger warnings in the taxdata repo
Where is that language?

**Comment by martinholmer** [comment]
Pull request #1648 expanded the discussion of CPS-vs-PUF differences in the user documentation.

All are welcome to suggest additional changes in that difference discussion or to add a difference discussion somewhere else in the Tax-Calculator and/or PolicyBrain repositories.

**Comment by MattHJensen** [comment]
> Where is that language?

Hmm, I can't find it now, although I'm sure @andersonfrailey wrote it. Perhaps he knows where it is.

**Comment by andersonfrailey** [comment]
I can't find it right now either. @martinholmer's additions in PR #1648 might be the best we have at the moment. It's possible I wrote something in one of the PR's that added the CPS file, but never added it to any official documentation.

**Comment by martinholmer** [comment]
Over the past six days, nobody has suggested any other language (in addition to or as an alternative to the #1648 changes) about the caveats associated with using the `cps.csv` (rather than the `puf.csv`) file as Tax-Calculator input.  So, issue #1647 is being closed.  Anybody is welcome to add and/or revise what we have now.
