### ISSUE TITLE
Pass-through income from service activities

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1650]
Both the House and Senate versions of the TCJA have rules determining what types of pass-through income are eligible for preferential tax treatment, with separate rules for personal services businesses. 

The House bill defines personal services businesses as 

> businesses involving the performance of services in the fields of law, accounting, consulting, engineering, financial services, or performing arts.

Under the rules in the House bill, the default capital percentage for these firms would be zero (instead of 30% for other types of pass-through businesses), but they would be eligible to apply an alternative capital percentage as the business's capital investments multiplied by the federal short-term rate plus 7 percent. 

As @jdebacker noted in PR #1620, 

> Perhaps just applying this formula [i.e. 30%] to all filers makes sense (especially since it's ripe for noncompliance anyway so knowing the breakdown of capital/labor income by filer under current law might not makes much sense going forward).

The Senate bill defines personal services businesses as 

>  any trade or business activity involving the performance of services in the fields of health, law, engineering, architecture, accounting, actuarial science, performing arts, consulting, athletics, financial services, brokerage services, or any trade or business where the principal asset of such trade or business is the reputation or skill of one or more of its employees. 

In the Senate bill, a taxpayer may deduct 17.4% of qualified business income from a sole proprietorship, partnership or S corporation. For personal services businesses, the benefit of this deduction is phased out for taxable income in excess of $75,000 ($150k for married joint), with a phase-out length of $25,000 ($50k for married joint). The chairman's mark does not clearly define the "benefit of this deduction"; without the actual bill text or more detail, I'm not certain we can model the phase-out. 

However, the inability to model the phase-out may be irrelevant, since we cannot distinguish personal services business income from other business income. And as @jdebacker noted, this is ripe for noncompliance anyway. 

Given this, I think it would be best to simply model this as an exclusion of 17.4 percent of qualified business income. 

@MattHJensen @martinholmer @jdebacker

**Comment by MattHJensen** [comment]
> Given this, I think it would be best to simply model this as an exclusion of 17.4 percent of qualified business income.

That makes sense to me as well.

**Comment by codykallen** [comment]
Modeling for this has been addressed in PR #1651. Closing.
