### ISSUE TITLE
quantile distribution tables  by # of people or # tax units?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#167]
We should consider whether to break our quantile distributional tables by number of people rather than by number of tax units.

**Comment by feenberg** [comment]
Don't you think tax units are far more commonly used?

dan

**Comment by MattHJensen** [comment]
I thought tax units were used generally as well, but I noticed that TPC is using number of people. I figure it’s not an urgent issue, but that we should think more about what is best.

http://www.taxpolicycenter.org/numbers/displayatab.cfm?DocID=4050&topic2ID=40&topic3ID=41&DocTypeID=

http://www.taxpolicycenter.org/numbers/displayatab.cfm?DocID=4177&topic2ID=40&topic3ID=41&DocTypeID=2

see footnote 3.



On Mar 7, 2015, at 6:15 PM, feenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't you think tax units are far more commonly used?

dan

**Comment by MattHJensen** [comment]
[This NTJ paper](http://www.ntanet.org/NTJ/65/4/ntj-v65n04p739-58-effects-adjusting-distribution-tables.pdf) by Julie-Anne Cronin, Portia DeFilippes, and Emily Lin argues for adjusting for family size.

**Comment by MattHJensen** [comment]
Our users are starting to have opinions about our distribution tables, so I am closing this until we have a user request for something different than what we are currently doing.
