### ISSUE TITLE
Consistent naming of reform files

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1679]
I propose we name reform files with `[bill shorthand]_[chamber]_[date introduced]`

So the `TCJA_House.json` file would become `TCJA_House_110317.json`. 

What do others think? 

@hdoupe @martinholmer @evtedeschi3 @GoFroggyRun @codykallen @andersonfrailey

**Comment by martinholmer** [comment]
@MattHJensen, Your naming convention sound like a good idea to me, but **the person who changes the JSON reform file names must also change the links in the taxcalc/reforms/REFORMS.md file**.

**Comment by MattHJensen** [comment]
>  Your naming convention sound like a good idea to me, but the person who changes the JSON reform file names must also change the links in the taxcalc/reforms/REFORMS.md file.

Thanks for the tip. I'll do this.

**Comment by MaxGhenis** [comment]
May I suggest the ISO 8601 standard of YYYY-MM-DD, or just YYYYMMDD, rather than DDMMYY? This will be less confusing to users outside US (whose analog of our mm/dd/yyyy is dd/mm/yyyy) and also enable correct sorting in case similar reforms are produced across a year boundary.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> May I suggest the ISO 8601 standard of YYYY-MM-DD, or just YYYYMMDD, rather than DDMMYY? This will be less confusing to users outside US (whose analog of our mm/dd/yyyy is dd/mm/yyyy) and also enable correct sorting in case similar reforms are produced across a year boundary.

This is a very good suggestion.  For these reasons, we have been using the ISO 8601 standard for dates in the `RELEASES.md` file.
