### ISSUE TITLE
How to replace weights with CPS file in Python?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1683]
I'm looking to use alternate weights for the CPS data in Python. On Nov 10, @MattHJensen recommended something like `calc.records.s006 = new_weights`, and that appeared to work, producing different downstream results.

However, after updating taxcalc yesterday, it now appears that `advance_to_year` resets the weights, so this no longer works. In [this notebook](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/Compare%20TCJA%20combined%20liability%20with%20normal%20vs.%20Tedeschi%20weights.ipynb) I printed out the total weight at various steps in the policy reform setup process. Regardless of the weights in the baseline calculator, they are set to the same value after this step, which also differs from the initial built-in weights.

Given this, it doesn't seem like resetting them after `advance_to_year` would be appropriate. What's the best way to use different weights?

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I'm looking to use alternate weights for the CPS data in Python.  On Nov 10, @MattHJensen recommended something like `calc.records.s006 = new_weights` ...
>
> However, after updating taxcalc yesterday, it now appears that `advance_to_year` resets the weights, so this no longer works in [this notebook](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/Compare%20TCJA%20combined%20liability%20with%20normal%20vs.%20Tedeschi%20weights.ipynb).

From your notebook, you are doing something like this:
```
tedeschi_weights = pd.read_csv('~/cps_weights_2026.csv')
recs = Records.cps_constructor()
calc = Calculator(records=recs, policy=Policy())
calc.records.s006 = tedeschi_weights.s006
```
The Records.cps_constructor() is a convenience function that assumes you want to use the standard CPS weights.  
But you want to do something else, so you can't use that convenience function.
What you need to do is pass the alternative weights file to the Records constructor like this:
```
data_path = os.path.join(Records.CUR_PATH, 'cps.csv.gz')
recs = Records(data=data_path,
               weights='~/cps_weights_2026.csv',
               adjust_ratios=None,
               start_year=Records.CPSCSV_YEAR)
```
I don't have the alternative weights file to test this suggestion, so this exact code might not work.
IMPORTANT NOTICE: the Records constructor expects a weights file with weights for every year, so I'm wary of the alternative weights file you're using.  It's filename suggests it has weights for only one year.  It needs to have weights for all years (look at the structure of the `cps_weights.csv` file).

**Comment by MaxGhenis** [comment]
Thanks. You're correct that the weights file only has one year's weight. I'll revise and replace `Records.cps_constructor()` with `Records()`.

For posterity, these are the columns of [cps_weights.csv](https://github.com/open-source-economics/taxdata/blob/master/cps_stage2/cps_weights.csv.gz):

       SEQUENCE WT2015 WT2016 WT2017 WT2018 WT2019 WT2020 WT2021 WT2022 WT2023
       WT2024 WT2025 WT2026 WT2027

**Comment by MaxGhenis** [comment]
After creating a weights file of the same format as cps_weights.csv, this worked ([notebook](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/Compare%20TCJA%20combined%20liability%20with%20normal%20vs.%20Tedeschi%20weights.ipynb)). 

The only adjustment to your suggestion was putting the weights csv in the `Records.CUR_PATH`, as the [code](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/records.py#L470) only looks in that folder. An alternative could be loading it as a `DataFrame` first and passing that.

**Comment by martinholmer** [comment]
@MaxGhenis, thanks for your feedback with respect to issue #1683.  
It's very useful to the Tax-Calculator developers to know whether or not our advice to users is helpful to them.
