### ISSUE TITLE
Add reform file tests

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1688]
I think it would be helpful to commit the results for the reform files to the repo in some manner similar to `reforms.json` and `test_reforms.py`

**Comment by martinholmer** [comment]
@MattHJensen said in issue #1688:
> I think it would be helpful to commit the results for the reform files to the repo in some manner similar to `reforms.json` and `test_reforms.py`.

What kind of results for which "reform files"?

**Comment by MattHJensen** [comment]
> What kind of results for which "reform files"?

- The .json reform files in `taxcalc/reforms`

- X (perhaps 10) years of revenue changes from current law would be helpful.

**Comment by martinholmer** [comment]
Issue #1688 has been resolve by the merge of pull request #1766.
