### ISSUE TITLE
Why do requires_pufcsv test results differ under Python 2.7 and 3.6

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1691]
In #1690, I said: 

> As far as I can tell, the only change in this PR was to update from python 2.7 to python 3.6, which I needed to do to handle some bugs in my WIP PR #1614. Yet that Python update appears to have influenced tax-calculator results. Has anyone else run the `requires_pufcsv` tests on master on a machine running Python 3.6?

A replication from someone else using 3.6 would be a good first step.

**Comment by martinholmer** [comment]
@MattHJensen ,   Can you update this PR?

**Comment by martinholmer** [comment]
See [this discussion](https://github.com/open-source-economics/Tax-Calculator/pull/1715#issuecomment-348394895) about why these 2.7-vs-3.6 differences are unlikely to be a bug in Tax-Calculator.

**Comment by martinholmer** [comment]
This issue is in the process of being resolved by pull request #1715.

**Comment by martinholmer** [comment]
The current discussion of 2.7 versus 3.6 test differences is in pull request #1715.
Closing issue #1691 because there has been no original comments in over two weeks (because the conversation is in #1715).
