### ISSUE TITLE
Ideas for distributing spending effects from ACA individual mandate repeal? 

### ISSUE THREAD

**Issue by evtedeschi3** [open-source-economics/Tax-Calculator#1706]
CBO has released an analysis that [distributes the changes in health spending](https://www.cbo.gov/system/files/115th-congress-2017-2018/reports/53333-wydenletter.pdf) resulting from the repeal of the ACA individual mandate. They aggregate their results by income level in a manner similar to JCT.

I'll think about this further, but perusing this quickly, my guess is there's not enough information here to map these results into tax-calculator space (I'm thinking in an off-model way post-simulation for people interested in an all-in distributional analysis). However perhaps someone has ideas. We'd presumably need to identify not only Medicaid recipients but also ACA marketplace participants, which would be tricky given that only 2/3 of the current cps.csv sample (those in 2014 & 2015) represent a period in which the ACA marketplaces were open at all, and even then they arguably weren't fully phased-in at those points. This would be a case where having the `fips`, `h_seq`, and `ffpos` variables could prove very useful.

**Comment by martinholmer** [comment]
@Amy-Xu,  Do you have any thoughts on the question posed by @evtedeschi3 in issue #1706?

**Comment by feenberg** [comment]
I don't have any thoughts, because I don't understand the memo. Why does 
removing the tax penalty for going uninsured reduce Medicaid spending?

We would need to discuss this with a health economist.

dan

**Comment by Amy-Xu** [comment]
@evtedeschi3  I have tried estimating ACA PTC using @martinholmer and Nikolai's [simulation model](http://chiselapp.com/user/mrh/repository/OSPC-ACA/doc/trunk/www/home.wiki) based on the three year CPS tax-unit dataset (all income variable adjusted to 2014). This model assigns full-year benefit to participants who're only eligible for part of the year. On top of that, I also have the same feeling that the market exchanges weren't fully phased in by that point. So our estimates for both participation and benefits are higher than the admin totals of 2014. 

Here's the [updated documentation](https://docs.google.com/document/d/1ng3TbwG5ywRA7vcN8d8Z76k6QGBDlORCZLyy8cX7z_o/edit?usp=sharing) for ACA PTC, which I will add to my C-TAM PR soon.

**Comment by evtedeschi3** [comment]
@feenberg asked:

> Why does removing the tax penalty for going uninsured reduce Medicaid spending?

Mainly because there's high turnover in Medicaid from year to year, so if you repeal the mandate (or effectively do so by making the penalty toothless), lower Medicaid participation quickly arises. The magnitude of the dynamics here that CBO assumes are far from universally-accepted, but health economists I've talked to have said the broad story CBO is telling with Medicaid is consistent with the empirical literature.

@Amy-Xu asked:

> I have tried estimating ACA PTC using @martinholmer and Nikolai's simulation model based on the three year CPS tax-unit dataset (all income variable adjusted to 2014). This model assigns full-year benefit to participants who're only eligible for part of the year. On top of that, I also have the same feeling that the market exchanges weren't fully phased in by that point. So our estimates for both participation and benefits are higher than the admin totals of 2014.

This is extremely helpful. I agree that market exchanges probably were not fully phased-in early on.

**Comment by martinholmer** [comment]
No conversation in issue #1706 for over six week, so issue seems to be stale.
