### ISSUE TITLE
Medical floor rate for medical deduction in itemized deduction

### ISSUE THREAD

**Issue by Amy-Xu** [open-source-economics/Tax-Calculator#171]
`
c17750 = .075*_posagi;             
c17000 =  max(0,e17500-c17750);
`

In the original snippet for medical deduction, the floor rate was hard coded as 7.5%. (Later on I parameterized it as ID_medical_frt.) However starting from the beginning of 2013, this rate increases to 10% for most taxpayers and remains as 7.5% for taxpayers or their spouses no younger than 65.  http://www.irs.gov/taxtopics/tc502.html

I changed this rate from 7.5% to 10% in this pull request #169 , but have not incorporated the exceptions for elderly taxpayers yet. 

Need to find a way to separate taxpayers by the age of 65.

**Comment by MattHJensen** [comment]
We can solve this with the CPS match

**Comment by martinholmer** [comment]
Issue #171 has been resolved by the merger into the master branch of pull request #839.
