### ISSUE TITLE
Speeding up the MTR function

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1727]
Does anyone have any good ideas for speeding up the running time of the `mtr` function?

At this point, the `mtr` function is the primary factor slowing down the running time for BRC. To applythe behavioral responses in BRC, I need to compute the effective marginal tax rate on income from corporate equity for each year 2017-2027 (which includes `e00650`, `p22250`, `p23250` and `e01700`) and on income from noncorporate equity for each year 2014-2027 (which includes `e00900`, `e26270`, `e02000` and `e01700`). In total, this requires calling the `mtr` function 200 times. If I hardcode the baseline values (which I'd prefer not to, in case results change), then I can reduce it to a mere 100 calls to the `mtr` function. 

Given that the `mtr` function is not very fast currently (a few second to run), it would be very helpful if the function could somehow run more quickly. Does anyone have ideas on how to go about this?

@MattHJensen @martinholmer @andersonfrailey @hdoupe

**Comment by martinholmer** [comment]
@codykallen said:
> Given that the [Calculator class] `mtr` [method] is not very fast currently (a few second to run), it would be very helpful if the function could somehow run more quickly. 

Can you give us some details on your `mtr` timing methods and results?

**Comment by codykallen** [comment]
@martinholmer suggested

> Can you give us some details on your `mtr` timing methods and results?

That's a good suggestion. Unfortunately, AEI's new security software is preventing any Python code from compiling in Anaconda applications for me (as of today), so I won't be able to provide that for at least another day or so.

**Comment by feenberg** [comment]
On Wed, 6 Dec 2017, codykallen wrote:

> 
> Does anyone have any good ideas for speeding up the running time of the mtr
> function?
> 
> At this point, the mtr function is the primary factor slowing down the
> running time for BRC. To applythe behavioral responses in BRC, I need to
> compute the effective marginal tax rate on income from corporate equity for
> each year 2017-2027 (which includes e00650, p22250, p23250 and e01700) and
> on income from noncorporate equity for each year 2014-2027 (which includes
> e00900, e26270, e02000 and e01700). In total, this requires calling the mtr
> function 200 times. If I hardcode the baseline values (which I'd prefer not
> to, in case results change), then I can reduce it to a mere 100 calls to the
> mtr function.
>

I am not looking at the source code, so these remarks may be way off base, 
but...

I take it that each call to mtr computes the t0 and t1 (where t0 is the 
baseline) and takes the difference as the tax rate? Why not calculate t0 
in each run, and pass it to mtr for use it for all 4 mtr computations?

Also, I am not sure why the tax rates on non-corporate equity would differ 
from one another.

dan

**Comment by codykallen** [comment]
@martinholmer suggested:

> Can you give us some details on your `mtr` timing methods and results?

On my work computer, it takes 2.43 second to call `mtr` once. However, since I need to call it several times for each year 2014-2027, the time it takes to call `calc.increment_year()`, `calc.calc_all()` and `calc.mtr()` is 3.78 seconds.

**Comment by codykallen** [comment]
@feenberg suggested

> Why not calculate t0 in each run, and pass it to mtr for use it for all 4 mtr computations?

That's a useful idea. If we don't end up speeding up the mtr function, then I will build my own version along those lines. 

@feenberg also said

> Also, I am not sure why the tax rates on non-corporate equity would differ from one another.

The different types of noncorporate equity follow slightly different distributions, and passive Sch E business income is subject to the NIIT.

**Comment by codykallen** [comment]
Calculating the effective marginal tax rate on noncorporate business income for 2014-2027 take 162.27 seconds. Calculating the EMTR on income from corporate equity for 2017-2027 takes 132.17 seconds. Each of those must be done twice.

**Comment by martinholmer** [comment]
@codykallen said:
> the time it takes to call `calc.increment_year()`, `calc.calc_all()` and `calc.mtr()` is 3.78 seconds.

Can you point us to the script in the BRC repo that is doing all these `mtr` calls?

**Comment by codykallen** [comment]
@martinholmer asked

> Can you point us to the script in the BRC repo that is doing all these `mtr` calls?

The functions in BRC that call the `taxcalc.Calculator.mtr` function are in `usercode_taxcalc.py`. They are `calc_tau_nc` and `calc_tau_e`, which are called for each year by `get_mtr_nc_list` and `get_mtr_e_list`. 

`get_mtr_nc_list` is called for the baseline in `gen_baseline.py` and for the reform in `reform_implementation.py`. `get_mtr_e_list` is called for the baseline and reform in the `legal_response` function in `responses.py`.

**Comment by martinholmer** [comment]
@codykallen, I've added an option to reduce the number of calc_all() calls when mass producing MTRs in pull request #1728.  I'm not sure how much using this option will speed up your BRC scripts.  If there isn't much of a speed-up, that suggests you don't know where your script is spending most of its time.  It is quite common for computer programs to spend well more than half their runtime just a few functions.  Finding those "hot spots" is a prerequisite for code optimization.  If you really want to speed up your script, use a [Python profiler](https://docs.python.org/2/library/profile.html) to find which functions take the most time in your script.

**Comment by martinholmer** [comment]
@codykallen,  See the timing results in the MTR speedup test described [here](https://github.com/open-source-economics/Tax-Calculator/pull/1728#issuecomment-350049441).
