### ISSUE TITLE
_sit+e18500 or c18300 in AMTI calc

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#173]
We currently use _sit + e18500 in the calculation of c62100. Should we be using c18300? 

c18300 = max(_sit, e18450) + e18500 + e18800 + e18900

**Comment by martinholmer** [comment]
@MattHJensen said on March 10, 2015:
> We currently use _sit + e18500 in the calculation of c62100. Should we be using c18300?

As of July 23, 2016, the calculation of `c62100` does use `c18300` and does not use either `_sit` or `e18500` as seen in the `AMTI()` code fragment below:
```
    if _standard == 0.0:
        if f6251 == 1:
            cmbtp = cmbtp_itemizer
        else:
            cmbtp = 0.
        c62100 = (c00100 - c04470 +
                  max(0., min(c17000, 0.025 * c00100)) +
                  c18300 -
                  c60260 + c20800 - c21040)
        c62100 += cmbtp
    if _standard > 0.0:
        if f6251 == 1:
            cmbtp = cmbtp_standard
        else:
            cmbtp = 0.
        c62100 = c00100 - c60260
        c62100 += cmbtp
```
So, it would seem that this issue #173 has been resolved.
