### ISSUE TITLE
More flexible CSV/SQL output file?

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#1732]
Currently, tax-calculator's command line interface, `tc`, offers two kinds of output, in terms of number of output variables, for CSV/SQL file. According to `tc`'s [documentation](http://open-source-economics.github.io/Tax-Calculator/index.html#cli), users could either choose to generate a minimal output file or a much more complete output file. 

While working with tax-calculator users, however, from time to time, @MattHJensen and I heard complaints that a minimal output file is not informative enough to work with, and the full version is yuge (200+ mb for a single year) that makes i/o operations inefficient. Would it be reasonable to have more variable output options for CSV/SQL output files?

In particular, we could:

1. Supply certain amount of output variables in between the minimal list and the full list. Those 41 variables generated by [Internet Taxsim](http://users.nber.org/~taxsim/taxsim9/) might be something we could consider.

2. Or, even better, let users customize the output variables at their discretionary. Some option like `--customize` or `--trim` could be added to `tc` that reads a file that contains possible outputs via `tc`. The file can be pre-defined in tax-calculator to avoid formate confusions. Users eventually would trim the output file, and thus having this done simultaneously while data are generated would simplify their workflows and definitely save much of the i/o time on large files. 

@MattHJensen @martinholmer what do you think?

**Comment by martinholmer** [comment]
@GoFroggyRun said among other things in issue #1732:
>  I heard complaints that [the] minimal output file is not informative enough to work with, and the [--dump] version is huge (200+ mb for a single year) that makes i/o operations inefficient. Would it be reasonable to have more variable output options for CSV/SQL output files?

There are two separate issues here.

First, what exactly is meant by the phrase "minimal output file is not informative enough to work with"?
What kind of work are people doing with the output file that forces them to do use the --dump option?
I need the answers to these questions in order to respond to this issue.

Second, the "i/o operations" are not "inefficient", it is just that the output file is very large when using the dump option (especially when working with `cps.csv` input).  Here, for the record, is what happens when specifying the --dump or --sqldb option as opposed to not specifying that option (and getting the minimal output).

Minimal output:
```
iMac2:tax-calculator mrh$ date ; tc cps.csv 2018 ; date
Fri Dec  8 12:03:08 EST 2017
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2018.
Fri Dec  8 12:03:53 EST 2017

iMac2:tax-calculator mrh$ ls -l cps-18*
-rw-r--r--  1 mrh  staff       205 Dec  8 12:03 cps-18-#-#-doc.text
-rw-r--r--  1 mrh  staff  17731481 Dec  8 12:03 cps-18-#-#.csv
```
Dump output:
```
iMac2:tax-calculator mrh$ date ; tc cps.csv 2018 --dump ; date
Fri Dec  8 12:04:19 EST 2017
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2018.
Fri Dec  8 12:07:03 EST 2017

iMac2:tax-calculator mrh$ ls -l cps-18*
-rw-r--r--  1 mrh  staff        205 Dec  8 12:07 cps-18-#-#-doc.text
-rw-r--r--  1 mrh  staff  448202197 Dec  8 12:07 cps-18-#-#.csv
iMac2:tax-calculator mrh$ 
```
SQLite output:
```
iMac2:tax-calculator mrh$ date ; tc cps.csv 2018 --sqldb ; date
Fri Dec  8 12:36:06 EST 2017
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2018.
Fri Dec  8 12:37:33 EST 2017

iMac2:tax-calculator mrh$ ls -l cps-18*
-rw-r--r--  1 mrh  staff        205 Dec  8 12:36 cps-18-#-#-doc.text
-rw-r--r--  1 mrh  staff   17731481 Dec  8 12:36 cps-18-#-#.csv
-rw-r--r--  1 mrh  staff  253157376 Dec  8 12:37 cps-18-#-#.db
```
Runtime summary:
```
SUMMARY:
no-options runtime:    45 seconds
with --sqldb runtime:  87 seconds
with --dump runtime:  164 seconds
```
So, are the complaints about waiting two minutes longer (164 seconds rather than 45 seconds) when getting the dump output?  

If so, why not speed things up and use the --sqldb option, which produces the same output in a smaller file (241 MB) much faster (less than a minute longer than when getting the minimal output).  The tabulation of that database file is lightening fast and using the SQL declarative language is a very simple, yet powerful, way to summarize micro-data results.

Or, are the complaints about the large size of the dump output file (which is about 427 MB when using `cps.csv` input)?  If the complaints are about the large size of the output file, how are people using the output file?  When, for example, I use a one-line AWK script to tabulate total weighted income tax liability from the dump file, I get the results in just six seconds (which I find an acceptable waiting time).

**Comment by martinholmer** [comment]
@GoFroggyRun,  Can you answer my questions about the issue #1732 you raised recently?

**Comment by GoFroggyRun** [comment]
@martinholmer regarding you first question, a user from CNN is trying to analyze the impact of Senate reform on after tax income, grouped by filing status, income bins and number of kids. In this case, the minimal file is not quite enough to work with, and he has to generate the full version. In fact, however, the only variables needed to perform the work are:

```
'c00100', 'aftertax_income', 'n24', 'FLPDYR', 'MARS', 'RECID'
```

That's not a lot of variables added to the output file, and not too different from the minimal file either. Users in cases like these have to go with the full version.

**Comment by martinholmer** [comment]
Thanks for your answer. 
So it seems as if #1735 will meet that person’s needs.

**Comment by GoFroggyRun** [comment]
@martinholmer for your second concern, I am not very much familiar with SQL database, and I have never seen users using this options up until now. 

Regardlessly, let's do some math base on the runtime summary you provided: say some user would like to investigate the senate bill, house bill and current law in a ten-year window. Let's further assume that the user needs the variables in my previous comment and thus has to go with the full version. In this case, we have 3*10 runs. 

For the minimal output option, the amount of time to generate the file is 3*10*45 seconds, which is 22.5 minutes. 

For the `--sqldb` option, the different amount of time compared to the minimal file is 3*10*(87-45) seconds, which is 21 minutes extra (about 93.3% more). 

For the `--dump` option, the different amount of time compared to the minimal file is 3*10*(164-45) seconds, which is 59.5 minutes extra (about 264% more). 

Imagine we are able to generate a file contains exactly (or even roughly) these variables:

```
'c00100', 'aftertax_income', 'n24', 'FLPDYR', 'MARS', 'RECID'
```

There are six variables here, so I'd assume the runtime to generate such file is not too different form the minimal file. The user would have saved at least about 21 min, in most cases 59.5 min, while using `tc` to generate the data required.

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> Regardlessly, let's do some math base on the runtime summary you provided: say some user would like to investigate the senate bill, house bill and current law in a ten-year window. Let's further assume that the user needs the variables in my previous comment and thus has to go with the full version. In this case, we have 3*10 runs.
>
> For the minimal output option, the amount of time to generate the file is 31045 seconds, which is 22.5 minutes.

But "31045 seconds" is not 22.5 minutes.  

Is this example, in which someone wants to generate 30 `tc` runs, contrived by you to make your point or are there users out there who are actually trying to do this?

Even with minimal output the 30 runs take 30*45 seconds, which is 1350 seconds or 22.5 minutes.
Why in your example didn't you assume the user doing this would use all the CPU cores on the local computer and run 7 or 8 runs in each of four command-prompt windows.  I haven't tried that but there is no reason why it wouldn't work (as far as I can tell).  If the resulting run time is too slow, the user can run 15 on one computer and the other 15 runs on another computer.  This kind of distributed processing (using all the cores on a computer and using multiple computers) is what TaxBrain does to get its fast turn-around speed.

**Comment by martinholmer** [comment]
Issue #1732 has been resolved by pull request #1735.

**Comment by GoFroggyRun** [comment]
>Is this example, in which someone wants to generate 30 tc runs, contrived by you to make your point or are there users out there who are actually trying to do this?

Yes. There are. Moreover, the percentage runtime differences are regardless of number of runs. 

>Even with minimal output the 30 runs take 30*45 seconds, which is 1350 seconds or 22.5 minutes.
Why in your example didn't you assume the user doing this would use all the CPU cores on the local computer and run 7 or 8 runs in each of four command-prompt windows. 

Good idea. If there are ways users could do to reduce runtime while running multiple reforms, we should have included these tips in the `tc` documentation. Knowledge of parallel computing is too much to assume.

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> Good idea. If there are ways users could reduce runtime while running multiple reforms [or multiple years], we should have included these tips in the tc documentation.  Knowledge of parallel computing is too much to assume.

OK, I'll add that to the user documentation.  But it seems to me that if a user is doing this kind of analysis (comparing three reforms in each of ten years using an editor and invoking run execution at the command-line prompt), then they are almost certain to know that their computer (typically) has four CPU cores, and that they can run more than one program at a time on their computer.
