### ISSUE TITLE
TaxBrain: Tax liabilities uniformly *increase* when adding a basic income

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1737]
I tried a basic reform in the TaxBrain GUI in which the only change is entering $2,000 in the "UBI benefit for those under 18" box: http://www.ospc.org/taxbrain/25246/

This produced a tax liability increase for 40,697 tax units, and a tax cut for 0 tax units. Am I doing something wrong?

The "All" row also shows 0 for "Percent with Tax Increase", despite the 40k in "Tax Units with Tax Increase". The percent is calculated correctly for each income bin.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I tried a basic reform in the TaxBrain GUI in which the only change is entering $2,000 in the "UBI benefit for those under 18" box: http://www.ospc.org/taxbrain/25246/
>
> This produced a tax liability increase for 40,697 tax units, and a tax cut for 0 tax units. Am I doing something wrong?

If you are surprised by these results, maybe you were thinking the UBI benefit would be non-taxable.
But as the following screen shot shows, you (perhaps inadvertently) assumed that **none** of the UBI benefit is excluded from AGI.

![screen shot 2017-12-08 at 9 11 01 pm](https://user-images.githubusercontent.com/12170745/33791664-587869a2-dc5d-11e7-9168-6e279d615557.png)

Do the UBI results correspond more to what you were expecting if you exclude all of the UBI benefits from AGI?

@MaxGhenis also said:
> The "All" row also shows 0 for "Percent with Tax Increase", despite the 40k in "Tax Units with Tax Increase". The percent is calculated correctly for each income bin.

Yes, this is a known bug that we are working on.  In fact, three columns in the difference table have `All` row values that are incorrect: "Percent with Tax Cut", "Percent with Tax Increase", and "Average Tax Change".
Hopefully, these three incorrect `All` row values will be correct in the next version of Tax-Calculator and TaxBrain.

Thanks for your valuable feedback on using Tax-Calculator and TaxBrain.

**Comment by MaxGhenis** [comment]
I see, I thought tax liability would be net tax liability, with UBI being a negative liability. For example, is this not how TaxBrain communicates EITC refunds?

**Comment by MaxGhenis** [comment]
This could be a reason to consider showing distributions of after-tax income (inclusive of UBI and refunds) in TaxBrain, as William Gale recommends: http://www.taxpolicycenter.org/taxvox/right-way-and-wrong-way-measure-benefits-tax-changes

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I see, I thought tax liability would be net tax liability, with UBI being a negative liability. For example, is this not how TaxBrain communicates EITC refunds?

Good question.  I'm not at all involved in the UBI work.  But as far as I can see (at a distance), UBI benefits are added to expanded income but they are not in Tax-Calculator being considered negative income taxes (as they called UBI in the 1960s).  

Part of the problem in the TaxBrain difference table is that even though Tax-Calculator is computing a "Percentage Increase in After-Tax Expanded Income" statistic, TaxBrain is not yet displaying it.  Again, this is a known problem with TaxBrain that we hope to fix soon.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> This could be a reason to consider showing distributions of after-tax income (inclusive of UBI and refunds) in TaxBrain, as William Gale recommends: http://www.taxpolicycenter.org/taxvox/right-way-and-wrong-way-measure-benefits-tax-changes

I am in complete agreement.  As I said before, Tax-Calculator **is** computing this statistic now but TaxBrain has not yet been revised to show it.

**Comment by hdoupe** [comment]
@MaxGhenis thanks for your feedback.  The incorrect "ALL" values are a long standing issue.  See OpenSourcePolicyCenter/PolicyBrain#73

**Comment by MattHJensen** [comment]
@maxghenis, do you think it would also be valuable to have a UBI variable in the distribution table? If so, we could add `ubi` to `DIST_TABLE_COLUMNS` after `combined.`

**Comment by MaxGhenis** [comment]
UBI in the distribution table would be nice, but given it's pretty straightforward to calculate directly and would probably only apply to a small share of analyzed reforms, I wouldn't consider it high priority from my end.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for the helpful feedback on the problems in TaxBrain when analyzing a UBI reform.

As noted in issue #1737, the TaxBrain developers have on their to-do list adding statistics related to aftertax expanded income to both the TaxBrain distribution and difference tables.  And you can analyze UBI reforms and get UBI benefits as an output variable along with pretax and aftertax expanded income statistics right now by using the command-line `tc` tool (as described in the [user documentation](http://open-source-economics.github.io/Tax-Calculator/)) or by writing your own Python script that uses the taxcalc package (as described in the [Tax-Calculator Cookbook](http://open-source-economics.github.io/Tax-Calculator/cookbook.html)).

So, I'm going to close this issue now.  If you have further suggestions for enhancements or bug reports, please raise a new issue.

@hdoupe
