### ISSUE TITLE
Why 2026 and 2027 _STD warnings when using TCJA_Senate_120117.json?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1738]
Why do I get 2026 and 2027 `_STD` warnings when I do the following?
```
$ conda install -ospc taxcalc
$ tc cps.csv 2018 --reform Tax-Calculator/taxcalc/reforms/TCJA_Senate_120117.json
```
Here are the `_STD` warnings:
```
WARNING: 2026 _STD_0 value 7655.0 < min value 7725.68
WARNING: 2026 _STD_1 value 15311.0 < min value 15551.32
WARNING: 2026 _STD_2 value 7655.0 < min value 7725.68
WARNING: 2026 _STD_3 value 11272.0 < min value 11422.83
WARNING: 2026 _STD_4 value 15311.0 < min value 15551.32
WARNING: 2027 _STD_0 value 7819.58 < min value 7913.5
WARNING: 2027 _STD_1 value 15640.19 < min value 15926.95
WARNING: 2027 _STD_2 value 7819.58 < min value 7913.5
WARNING: 2027 _STD_3 value 11514.35 < min value 11699.38
WARNING: 2027 _STD_4 value 15640.19 < min value 15926.95
```
This reform sets many policy parameters to new values in 2026, but there are warnings only for the `_STD` parameter.

Is the algorithm that generates the warnings buggy?
Or are the `_STD` parameter values for 2026 and 2027 in the reform file not quite right?
(As I remember there was some discussion about what how to set the 2026+ values of the `_AMT_em` and `_AMT_em_ps` parameters before pull request #1725 was merged.)

This question arises from user-posted issue #1736.

@MattHJensen @evtedeschi3 @GoFroggyRun @codykallen

**Comment by codykallen** [comment]
@martinholmer, I encountered this as well, and I've already identified the reason for this issue. One of our warnings is that a user is not supposed to reduce the standard deduction (or the additional standard deduction) because this would cause more people to itemize, but we do not have data on people who do not itemize. 

If you recall, the Senate version of the TCJA undoes all of its reforms to the individual income tax at the end of the budget window. The one exception to this is the indexing to the chained CPI, which remains in effect. Therefore, when we reset the standard deduction to where it would have been in 2026 (when the reforms expire), we set them to the version inflated by the chained CPI. Therefore, the standard deductions in 2026 and 2027 are less than the standard deductions would be if current law were to continue.

**Comment by martinholmer** [comment]
@codykallen said:
> I encountered this as well, and I've already identified the reason for this issue. One of our warnings is that a user is not supposed to reduce the standard deduction (or the additional standard deduction) because this would cause more people to itemize, but we do not have data on people who do not itemize.
>
> If you recall, the Senate version of the TCJA undoes all of its reforms to the individual income tax at the end of the budget window. The one exception to this is the indexing to the chained CPI, which remains in effect. Therefore, when we reset the standard deduction to where it would have been in 2026 (when the reforms expire), we set them to the version inflated by the chained CPI. Therefore, the standard deductions in 2026 and 2027 are less than the standard deductions would be if current law were to continue.

Thanks for the clear explanation.  So, I guess there is nothing to do, right?  The warnings (all of which are generated because we have never imputed itemized expenses for those you do not itemize under current law) are sensible and the reform is correctly specified.  Is that the way you see it?

**Comment by codykallen** [comment]
@martinholmer said:

> The warnings (all of which are generated because we have never imputed itemized expenses for those you do not itemize under current law) are sensible and the reform is correctly specified. Is that the way you see it?

Yes, that's correct. The reform is correctly specified, and those warnings are reasonable. Such tax policies will continue to generate issues like this, unless we can somehow impute data on itemizable expenses for those who do not itemize.

**Comment by martinholmer** [comment]
@MaxGhenis, Tax-Calculator issue #1738 discusses the reasons for the (garbled) TaxBrain warnings you described in issue #1736.   Thanks again for pointing out the need to improve the warnings messages and make it more clear about the ability to procedure with the analysis (because the messages are just data warnings and not errors).

So, it would seem the discussion in #1736 and #1738 has run its course and developers are working on fixing the things you found confusing.  As a results, I'm closing issues #1736 and #1738.  Thanks again for the helpful feedback on your experiences using Tax-Calculator and TaxBrain.  We hope you'll open new issues when you have problems or want to suggest enhancements.
