### ISSUE TITLE
Adding a choice between the SALT Real Estate and Income tax deductions

### ISSUE THREAD

**Issue by evtedeschi3** [open-source-economics/Tax-Calculator#1755]
Based on media reports, there's a possibility that the final TCJA conference tax bill will modify the SALT treatment so that filers will first have to choose between either the real estate or income / sales tax deductions, and then face a cap (e.g. $10K) on their choice.

The way I was mulling over implementing this in Tax-Calculator would be to have the user specify the cap through both `ID_RealEstate_c` and `ID_StateLocalTax_c` (presumably these would be identical under a conference-style SALT compromise), and then add a boolean switch called e.g. `ID_SALT_Limited` or similar to control the calculation of `c18300`. So in the ItemDed function:

```
    c18400 = min((1. - ID_StateLocalTax_hc) * max(e18400_capped, 0.),
                 ID_StateLocalTax_c[MARS - 1])
    c18500 = min((1. - ID_RealEstate_hc) * e18500_capped,
                 ID_RealEstate_c[MARS - 1])
    if ID_SALT_Limited:
    	c18300 = max(c18400, c18500)
    else:
    	c18300 = c18400 + c18500
```

But I wanted to raise this with folks more familiar with Tax-Calculator's structure to see both whether this is conceptually sound and what other changes would need to be made.

**Comment by MattHJensen** [comment]
@evtedeschi3, do you know what the treatment would be if you have $5000 of one and $3000 of another? Would you get to deduct $8000 or $5000?

**Comment by evtedeschi3** [comment]
My impression is that you have to choose one, so you’d get to deduction only $5000 in this case. But I’d emphasize that’s my impression talking with several folks who have only indirect familiarity with what’s being negotiated, and of course it could change.

**Comment by MattHJensen** [comment]
Got it. The reason I ask is that if the taxpayer would get to deduct $8000 in that situation, then I wonder if adding a `ID_SALT_c` parameter (`c18300 = min(ID_SALT_c[MARS - 1], c18400 + c18500)`) would be more clear and would allow the user to change only one parameter rather than three.

**Comment by MattHJensen** [comment]
@evtedeschi3, it seems like one option here would be to prepare a PR that follows the approach that you think is most likely to be accurate, and then we'll review it but wait to merge until we have an answer. Another option would be to prepare two PRs with the alternative approaches, and then we'll merge one and close the other. A third option would be to wait to open a PR. A fourth option would be to advocate that one or both sets of parameters are useful outside of the context of TCJA and should be added regardless of what is in the legislation.

**Comment by evtedeschi3** [comment]
Makes sense. If the broad approach is sound, I think it makes the most sense to just stick with a single PR and refine it as we learn more. Unless someone thinks otherwise, it seems like overkill to include approaches for both possible interpretations.

**Comment by MattHJensen** [comment]
That sounds good to me. Thanks a lot for contributing this @evtedeschi3!

**Comment by evtedeschi3** [comment]
And see, patience is a virtue, because now Brady is saying the bill will allow the $10K cap to be allocated between the two rather than forcing a choice of bucket.

**Comment by siervicul** [comment]
I use the TaxBrain GUI so visibility into the underlying parameters is limited, but it appears that in TaxBrain you can apply this cap under the "Ceiling On The Amount Of Itemized Deductions Allowed" section, by entering the $10k cap and checking only statelocal and realestate as the deductions to which the cap applies.

**Comment by martinholmer** [comment]
@evtedeschi3,  Thanks for pointing out the need for another policy parameter when analyzing the [conference committee's TCJA bill](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Reconciliation.json).   I'm going to close this issue because it has done its job of starting a discussion that lead to the code enhancement in pull request #1756.
