### ISSUE TITLE
About the timing of the alimony haircut in TCJA conference committee bill

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1764]
The `_ALD_Alimony_hc` parameter in the [TCJA_Reconciliation JSON reform file](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Reconciliation.json#L147-L149) takes on it's reform value in 2019 while all the other reform parameters change in 2018.

Is that difference for this one policy parameter correct or is this a typo in the JSON reform file?

@codykallen @MattHJensen @GoFroggyRun

**Comment by codykallen** [comment]
@martinholmer, that is correct. The above the line deduction for alimony payments is suspended, effective in 2019 (not 2018). Like most other provisions in the bill, the suspension of the deduction ends in 2026.

**Comment by martinholmer** [comment]
@codykallen said:
> The above the line deduction for alimony payments is suspended, effective in 2019 (not 2018). Like most other provisions in the bill, the suspension of the deduction ends in 2026.

Thanks for the confirmation.  Again, thanks for all the great work on the TCJA reform bills.
