### ISSUE TITLE
TCJA_Reconciliation error

### ISSUE THREAD

**Issue by reubenfb** [open-source-economics/Tax-Calculator#1767]
The new reform file `TCJA_Reconciliation.json` produces the follow error:

`ERROR: invalid parameter name _ID_AllTaxes_c in 2018`
`ERROR: invalid parameter name _ID_AllTaxes_c in 2026`

@codykallen @MattHJensen

**Comment by martinholmer** [comment]
@reubenfb said:
> The new reform file TCJA_Reconciliation.json produces the follow error:
>
> ERROR: invalid parameter name _ID_AllTaxes_c in 2018
> ERROR: invalid parameter name _ID_AllTaxes_c in 2026

You need to upgrade to the 0.14.1 version of the taxcalc package as described in the *What's New* section of the [user documentation](http://open-source-economics.github.io/Tax-Calculator/).

**Comment by reubenfb** [comment]
@martinholmer Got it! Sorry I missed that.

**Comment by martinholmer** [comment]
@reubenfb said:
> Got it! Sorry I missed that.

No problem!  We're still trying to figure out better ways of communicating with people using Tax-Calculator.
Our methods are far from perfect.  Any suggestions about how we could better communicate something like this would be appreciated.

**Comment by martinholmer** [comment]
@reubenfb,  Your might find [this FAQ](https://github.com/open-source-economics/Tax-Calculator/issues/1762) of some use.
