### ISSUE TITLE
What's New data recorded in RELEASES.md?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1769]
The new `What's New` information in the user docs, contributed recently by @martinholmer, is fantastic. `What's New` is a high level changelog that will be very helpful to our marketing efforts by providing an easy to understand listing of highlights. `What's New` will also make it easier for downstream projects like PolicyBrain to include highlights from upstream models in PolicyBrain's own changelog. 

What do you think about recording this information in a `What's New` section of `RELEASES.md`, rather than directly in `index.htmx`, and then pulling the data into `index.html` from `RELEASES.md` in an automated fashion? This placement of the high-level `What's New` changelog would mean that contributors can track changes in a single location. It would also ensure that other apps could access the `What's New` data in a standardized fashion.

cc @martinholmer @hdoupe @GoFroggyRun

**Comment by martinholmer** [comment]
@MattHJensen, I'm glad you like the *What's New* section of the user documentation.
But I'm not sure how what you seem to be proposing would work because there are
at least two incompatibilities between `RELEASES.md` and `docs/index.html`:

1. One is aimed at a developer audience and the other is aimed at a user audience.

2. One is written in Markdown and the other is written in HTML.

In the `RELEASES.md` entry for 0.14.2 (and subsequent releases), I provide a link to the *What's New* section of the user documentation.

**Comment by MattHJensen** [comment]
@martinholmer, let me describe the capability that would be helpful:

_There should be a machine-readable high-level overview of Tax-Calculator changes and updates, or, in other words, a 'user audience' focussed changelog._ 

This would make it much easier for downstream applications like PolicyBrain or (OSPC marketing tech) to disseminate updates about Tax-Calculator to their audiences. 

I believe that moving the `What's New` content to a standardized section of `RELEASES.md` would be one solution (and then linking from, or better yet machine translating from .md to .html into, `docs/index.html`), but there could very well be other solutions. 

I don't see any downside to keeping the user-audience focussed changelog and developer-audience focussed changelog in the same place, and there are several upsides:
- developers also like to see high-level and easy to read summaries
- users might appreciate a peak at the nuts and bolts effort that goes into their new features
- users will have visibility to the contributor attributions that are included in `RELEASES.md` but not `What's New`

**Comment by MattHJensen** [comment]
The purpose of this issue was to make it easier to use the what's new information in external applications. Given that those external applications aren't designed yet, I am closing this until they are designed and it is easier to specify what their requirements might be.
