### ISSUE TITLE
Specify alternative policy baseline

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1770]
It would be helpful for CLI and python API users to be able to specify alternative policy baselines. One approach would be by reference to a reform file. This would allow users to easily compare, say, the reconciliation bill to the Senate bill. Similarly, it would allow users to directly compare one candidate's tax plan to another's.

**Comment by martinholmer** [comment]
@MattHJensen said:
> It would be helpful for CLI and python API users to be able to specify alternative policy baselines.
> One approach would be by reference to a reform file.

Those engaged in Python programming with the taxcalc package can do this already.  So, we've added in pull request #1784 a new Cookbook recipe that shows how to do this with the existing version of Tax-Calculator.

The remaining part of this issue has to do with those using the command-line tool `tc`.   We'll discuss that issue later in this discussion.

**Comment by martinholmer** [comment]
@MattHJensen said:
> It would be helpful for CLI and python API users to be able to specify alternative policy baselines.

Why exactly would that be helpful for CLI users?
What would such an enhancement allow CLI users to do that they cannot already do?

**Comment by MattHJensen** [comment]
> Why exactly would that be helpful for CLI users?
> What would such an enhancement allow CLI users to do that they cannot already do?

This enhancement would allow users to generate built-in charts and tables that reflect the difference between a reform and alternative baseline (where the alternative baseline is specified by a reform file).

**Comment by martinholmer** [comment]
Pull request #1851, which is part of Tax-Calculator release 0.15.2, resolves issue #1770.
