### ISSUE TITLE
500 Internal Server Error when uploading TCJA_Reconciliation.json to TaxBrain

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1771]
I uploaded [TCJA_Reconciliation.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Reconciliation.json) to https://www.ospc.org/taxbrain/file/, which takes me to https://www.ospc.org/taxbrain/file/?start_year=2017 where it says

> 500 Internal Server Error!

This error arises both when providing and not providing a behavior file, and when choosing *Show me the results!* and *Quick calculation!*.

I don't get the error when uploading the older [TCJA_Senate.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Senate.json), though the difference table is all zeros (https://www.ospc.org/taxbrain/26994/).

**Comment by MaxGhenis** [comment]
I see [here](https://github.com/open-source-economics/Tax-Calculator/issues/1767#issuecomment-352218735) that TCJA_Reconciliation requires Tax-Calculator version 0.14.1, while TaxBrain is on version 0.14.0 per my just-produced Senate result. 

Is there an issue for updating TaxBrain to 0.14.1 I can track?

If possible, a more informative error message would be nice here, e.g. saying the reform includes parameters not available in the current version.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for your reports on problems using TaxBrain to analyze the conference committee's TCJA bill.  I think TaxBrain will soon be using Tax-Calculator release 0.14.1, which should eliminate the problems you're having.  You can follow the progress of TaxBrain at [this GitHub repository](https://github.com/OpenSourcePolicyCenter/PolicyBrain).

@MaxGhenis also said:
> If possible, a more informative error message would be nice here, e.g. saying the reform includes parameters not available in the current version.

Yes, that would be better than the uninformative `500 Internal Server Error!`.
I'll suggest that to the TaxBrain developers.  @hdoupe and/or @GoFroggyRun, can you open an enhancement issue on this topic?

**Comment by martinholmer** [comment]
I'm going to close issue #1771 now that it is on the radar scope of the TaxBrain developers.

**Comment by MaxGhenis** [comment]
Ah, I didn't realize PolicyBrain included TaxBrain. Would it be worth mentioning that front-end issues should be checked/reported there in https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/contributing.md ?

**Comment by hdoupe** [comment]
@MaxGhenis said
> Ah, I didn't realize PolicyBrain included TaxBrain.

Yes, PolicyBrain includes TaxBrain.  The PolicyBrain codebase is a little complicated right now.  So, it's understandable that you didn't find TaxBrain in that mess.  You can follow progress on this issue in OpenSourcePolicyCenter/PolicyBrain#779.
