### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1774]
A user requested:

> Could you update the documentation to finish the documentation for variables like these:

```
Output Variable Name: earned
Description: 
Datatype: float
IRS Form Location:

Output Variable Name: earned_p
Description: 
Datatype: float
IRS Form Location:

Output Variable Name: earned_s
Description: 
Datatype: float
IRS Form Location:
```

> I mean I could probably guess, but I would prefer not to.

He also said:

> Your documentation is otherwise excellent.

**Comment by martinholmer** [comment]
Pending pull request #1775 includes additions to the `records_variables.json` file as requested in #1774.
So, issue #1774 is being closed now.

**Comment by MattHJensen** [comment]
@martinholmer, when I look at #1775 I only see changes to `policy.py`

**Comment by martinholmer** [comment]
@MattHJensen, I just now did a push, so you should be able to see the changes now.

**Comment by MattHJensen** [comment]
Thanks @martinholmer!
