### ISSUE TITLE
Summary of parameters by reform

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1777]
It would be helpful to have a summary table for each parameter, showing its values across reforms (and current policy).

The schema could be `{parameter, reform, value}`, with a summary like `{parameter, first_reform}` (this would require a structured date of introduction for each reform).

This could replace manual documentation of some parameters originating in TCJA, as discussed in #1765.

**Comment by andersonfrailey** [comment]
@MaxGhenis, if my understanding of your issue is correct, we have a way to produce something similar. When working with the Python API, you can use the `reform_documentation(reform)` method in the calculator class and it will return some text containing all of the policy parameters that have been changed along with a short description and the baseline and reform values. The CLI will also automatically produce a text file with this information.

I'm not sure this is exactly what you're looking for, but it is one way to see the changes in a reform file in more context.

**Comment by MaxGhenis** [comment]
Thanks for the info @andersonfrailey, I'm looking for a summary across all reforms though, i.e. those listed in https://github.com/open-source-economics/Tax-Calculator/tree/master/taxcalc/reforms

For example, this table would reveal that `_DependentCredit_Child_c` is in all TCJA reforms, and not in other reforms or the current policy.

It sounds like the `reform_documentation` function could be a helpful tool for generating this, by looping over files in that folder.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Thanks for the info @andersonfrailey, I'm looking for a summary across all reforms though, i.e. those listed in https://github.com/open-source-economics/Tax-Calculator/tree/master/taxcalc/reforms
>
> For example, this table would reveal that _DependentCredit_Child_c is in all TCJA reforms, and not in other reforms or the current policy.
>
> It sounds like the reform_documentation function could be a helpful tool for generating this, by looping over files in that folder.

Sounds like an interesting project, @MaxGhenis.   We look forward to your pull request.

**Comment by MattHJensen** [comment]
> Sounds like an interesting project, @MaxGhenis. We look forward to your pull request.

Agreed!

**Comment by martinholmer** [comment]
@MaxGhenis,  If you are serious about pursuing this topic, consider developing a pull request that contributes an advanced recipe to the [Cookbook of Tested Recipes for Python Programming with Tax-Calculator](http://open-source-economics.github.io/Tax-Calculator/cookbook.html).

**Comment by MaxGhenis** [comment]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1YjyDZxL5z8oJ9zAizjL7H6hbZ590k6F0b6p-JH9_Bjk/edit#gid=1016114673) is the result of [this notebook](https://colab.research.google.com/notebook#fileId=1ebH_7dCX-SY6rOe1t6DYLRRZDdtUFgph), which pulls down parameters for each reform.

@martinholmer since this is more of a reference than an analysis (it doesn't even use `taxcalc`, just normal json operations), would it still fit as a recipe?

**Comment by martinholmer** [comment]
@MaxGhenis said:
> This spreadsheet is the result of this notebook, which pulls down parameters for each reform.
>
> Since this is more of a reference than an analysis (it doesn't even use taxcalc, just normal json operations), would it still fit as a recipe?

Probably not.  Thanks for sharing your notebook with us.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks again for [this notebook](https://colab.research.google.com/notebook#fileId=1ebH_7dCX-SY6rOe1t6DYLRRZDdtUFgph), which generates [these results](https://docs.google.com/spreadsheets/d/1YjyDZxL5z8oJ9zAizjL7H6hbZ590k6F0b6p-JH9_Bjk/edit#gid=1016114673), that you mentioned in issue #1777.
