### ISSUE TITLE
Updating current-law policy for TCJA

### ISSUE THREAD

**Issue by siervicul** [open-source-economics/Tax-Calculator#1787]
Since the TCJA becoming law is imminent, is there a plan for making its provisions the new defaults for Tax-Calculator?

In the meantime, for TaxBrain users I would suggest adding TCJA presets to the list of presets on the TaxBrain main page (after all, it would seem to be more newsworthy at this point than any of the proposals currently listed there).

**Comment by martinholmer** [comment]
@siervicul,  I'm going to move the second part of your question in #1787 to the PolicyBrain repository issue list so that TaxBrain developers can see it.  My understanding is that they are currently working on making a TaxBrain preset for TCJA.

**Comment by martinholmer** [comment]
@siervicul asked in issue #1787:
> Since the TCJA becoming law is imminent, is there a plan for making its provisions the new defaults for Tax-Calculator?

I'm working under the assumption that the `current_law_policy.json` file will be changed in the near future so that it projects forward the policy in the TCJA conference committee bill.

Is that the plan?  Any discussion of alternative approaches?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @codykallen

**Comment by MattHJensen** [comment]
> I'm working under the assumption that the current_law_policy.json file will be changed in the near future so that it projects forward the policy in the TCJA conference committee bill.

This is what I've had in mind, too. current_law_policy.json defaults are updated to reflect the new current_law_policy.json and a reform file is available to take users back to 2017_policy.

**Comment by codykallen** [comment]
@MattHJensen said:

> current_law_policy.json defaults are updated to reflect the new current_law_policy.json and a reform file is available to take users back to 2017_policy.

Before we actually update it, I would appreciate if a few people (myself included) could do a thorough reading of the bill and discussion to ensure that we have accurately modeled every possible provision. There are a lot of changes, and it's certainly possible I missed something while making the JSON.

**Comment by MattHJensen** [comment]
A couple of related notes for the update: 

- [ ] We need to review and update the reform files. Some reforms that are meant to specify new tax systems will no longer be accurate with the new baseline. For example, RyanBrady.json will either need to be updated or we will need to note that the RyanBrady.json file is only accurate in conjunction with a 2017_policy baseline. 

- [ ] Until TaxData adopts a post-TCJA CBO Budget Outlook (likely published in February), we should note to users that the Tax-Calculator+TaxData baseline does not account for behavioral changes that are likely to result from TCJA. (Alternatively, we could do a stage 3 adjustment to account for anticipated behavioral changes, but that would be a significant amount of work and would require the TaxData project to take a stance on behavioral elasticities....I think it is better to wait for the new CBO baseline.)

**Comment by martinholmer** [comment]
The merge of pull request #1803 resolves issue #1787.
