### ISSUE TITLE
Suggest including TaxData version in citation? 

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#1788]
Currently, in tax-calculator's [`README.md`](https://github.com/open-source-economics/Tax-Calculator/blob/d331becb9bef11fc833563b00549f4d13ddbd04c/README.md), the "Citing Tax-Calculator" section provides some advice to cite source of user's analysis as "Tax-Calculator v. #.#.#, author's calculations." Such citation, however, fails to include a key component in order to replicate the analysis: the data source used. 

Sometimes users decide to use the data source prepared by us in its entirety, while occasionally users alter the data a little bit (for example using the CPS data distributed by us, along with the alternative weight factor provided by @evtedeschi3). In light of such ambiguity in data source, it can be difficult to reproduce the whole analysis.

Per discussion in [#137](https://github.com/open-source-economics/taxdata/issues/137), after TaxData were fully versioned, we will have access to better citations. Even if users were citing publicly unable data source like PUF, including its version would help us to accurately replicate users' analysis upon requests. That said, the citation guide should still remind users to include the data source used, even if the data were not versioned. 

cc @MattHJensen @martinholmer

**Comment by martinholmer** [comment]
Issue #1788 has been resolved by the merge of pull request #1841.
