### ISSUE TITLE
odd distribution of charitable deductions in CPS data

### ISSUE THREAD

**Issue by reubenfb** [open-source-economics/Tax-Calculator#1793]
Looking at the `cps.csv` data, there are very few taxpayers with an income (e00200) over $10k that took a charitable deduction (e19800 + e20100) of more than zero dollars but less than $4,000 or so.

![screenshot 2017-12-22 14 17 48](https://user-images.githubusercontent.com/6992836/34310075-687523d8-e723-11e7-8362-684ed6f0e9c8.png)

This doesn't seem like a particularly rare tax situation to me, where a moderate charitable deduction in combination with other deductions makes it worthwhile to itemize.

I don't have access to the PUF dataset, but @codykallen was kind enough to run some numbers. 
For each income group and dataset, the figures below represent the share of itemizers with a charitable deduction > $0 whose total charitable deduction was less than $4,000.

**AGI > 10000**
- CPS: 0.15%
- PUF: 68.83%

**AGI > 20000**
- CPS: 0.13%
- PUF: 68.50%

**AGI > 50000**
- CPS: 0.11%
- PUF: 66.98%

**AGI > 100000**
- CPS: 0.10%
- PUF: 63.44%

This is a pretty dramatic difference. Is there something I'm missing about the methodology behind the CPS file that could lead to this gap?

**Comment by MattHJensen** [comment]
@reubenfb, I'm not immediately aware of the solution to this. Would you mind closing this issue and reopening in the TaxData repo -- it would be helpful to alert the TaxData developers of this issue. It would also be helpful to provide the code snippet (in any language) that you and Cody are using to make the calculations you present. As a word of warning, though, the TaxData project contributors have a lot on their hands right now -- they might have a quick solution, or they might not. 

Depending on your project, we may also be able to arrange for someone at OSPC to run your code on the public use file and return the results to you if you already have your code working with cps.csv. Just shoot me an email. (We haven't yet arranged a formal process for this, yet, but we should)

**Comment by reubenfb** [comment]
Will do @MattHJensen
