### ISSUE TITLE
Specify output directory for CLI

### ISSUE THREAD

**Issue by reubenfb** [open-source-economics/Tax-Calculator#1794]
Minor enhancement, but for running large batches of input files it would be useful to be able to specify an output directory with a flag instead of having all output files automatically generated in the current directory.

Thanks for the great tool!

**Comment by MattHJensen** [comment]
Thanks for the suggestion @reubenfb. I agree that this would be helpful. +1

**Comment by martinholmer** [comment]
Merge of pull request #1801 resolves issue #1794.
