### ISSUE TITLE
Function to modify a reform

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1802]
I'm working on analyses that involve modifying reforms, for example [removing deductions](http://nbviewer.jupyter.org/github/maxghenis/taxcalc-notebooks/blob/master/charitable_repeal/Effect%20of%20repealing%20charitable%20deduction.ipynb), and adding UBI to existing reforms. The UBI amount will be calculated in my script (to be revenue-neutral), so I'd like to be able to modify the reform on-the-fly. The ideal would be something like:

    pol.modify_param(param='_UBI1', value=1000, year=2018)

Where `pol` is an existing reform, e.g. TCJA.

Looking through [policy.py](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/policy.py) and [parameters.py](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters.py) I don't a way to do this.

While the current motivation of seeing how things change under TCJA will soon be irrelevant, I think this would be a broadly useful tool for sensitivity analysis among proposed reforms.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I'm working on analyses that involve modifying reforms, for example removing deductions, and adding UBI to existing reforms. The UBI amount will be calculated in my script (to be revenue-neutral), so I'd like to be able to modify the reform on-the-fly. The ideal would be something like:
>```
> pol.modify_param(param='_UBI1', value=1000, year=2018)
>```
> Where pol is an existing reform, e.g. TCJA.
>
> Looking through policy.py and parameters.py I don't a way to do this.
>
> While the current motivation of seeing how things change under TCJA will soon be irrelevant, I think this would be a broadly useful tool for sensitivity analysis among proposed reforms.

I agree with you, @MaxGhenis, that the ability to implement a "compound reform" (consisting of two simple reforms) will be "broadly useful."  However, I don't think Tax-Calculator needs any enhancements to do what you want to do.  My understanding is that there are no problems calling `implement_reform` twice for the same Policy object.  If you have problems with the approach I outline below (which has been used extensively in pull request #1803), please raise another issue.  Meanwhile, I'm closing this issue.

The (untested) example below assumes use of Tax-Calculator release 0.14.3, the last in which pre-TCJA policy is current-law policy.  It also assumes that the "policy" dictionary derived from the `reforms/TCJA_Reconciliation.json` file is called `tcja_reform'.
```
pol = Policy()
pol.implement_reform(tcja_reform)
ubi_reform = {2018: {'UBI1': [2500], 'UBI2': [10000], 'UBI3': [10000]}}
pol.implement_reform(ubi_reform)
```

**Comment by MaxGhenis** [comment]
Terrific, thank you @martinholmer! I used this to considerably simplify a [charitable deduction analysis](http://nbviewer.jupyter.org/github/maxghenis/taxcalc-notebooks/blob/master/charitable_repeal/Effect%20of%20repealing%20charitable%20deduction.ipynb) ([commit](https://github.com/MaxGhenis/taxcalc-notebooks/commit/d37bbd9648bed7589d4111bbb73a516cccf52cad)) and verified it produces identical results to creating my own separate reforms.

**Comment by martinholmer** [comment]
@MaxGhenis, thanks for the feedback on your experience implementing compound reforms by calling the Policy `implement_reform` method twice.  It's good to hear you were able to check the validity of this approach.  I hope to add soon a [Cookbook](http://open-source-economics.github.io/Tax-Calculator/cookbook.html) recipe that features this technique.

**Comment by MaxGhenis** [comment]
For posterity, the reform parameters require underscores, so could look like:

```
ubi_reform = {2018: {'_UBI1': [ubi_amount], 
                     '_UBI2': [ubi_amount], 
                     '_UBI3': [ubi_amount],
                     '_UBI_ecrt': [1.0]}}
```

I've found `copy.deepcopy` useful in conjunction with this approach, to create an edited version of an existing reform (e.g. to compare to it). For example here was a doubly-compounded reform after modifying to both repeal the charitable deduction and add a UBI (also in the notebook):

```
tcja_ubi_no_charitable_policy = copy.deepcopy(tcja_no_charitable_policy)
tcja_ubi_no_charitable_policy.implement_reform(ubi_reform)
```

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for the correction on my original example in issue #1802 and for you deepcopy usage tip [here](https://github.com/open-source-economics/Tax-Calculator/issues/1802#issuecomment-354933561).
