### ISSUE TITLE
Negative after-tax income for lowest earners create misleading %change charts

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1806]
The bottom decile has negative aggregate after-tax income, according to both CPS and PUF (per TaxBrain UI e.g. [this](http://www.ospc.org/taxbrain/29588/); I don't have the data). This means that any reform that changes after-tax income for this group will be reported as the opposite sign as intended.

For example, [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/Basic%20UBI%20reform.ipynb) considers a simple $100 UBI reform. Cells 10 and 11 show that the bottom decile's after-tax income is -$5.3B under the baseline and -$2.7B under the reform, respectively. Change to after-tax income is then technically +$2.6B / -$5.3B = -49%, as seen in the `decile_graph` plot in cell 14.

I'm not sure how best to address this, but it is pretty misleading. Most reforms don't affect this group as significantly as UBI does, so it may have flown under the radar until now. One solution could be to use a separate column which zeros out negative after-tax incomes. I'm not sure how others handle it; TPC seems to mostly use quintiles instead of deciles, which may help them avoid the issue.

**Comment by feenberg** [comment]
Perhaps we should ignore losses when calculating base income? Does base 
income include the value of medicaid and other benefits?

dan

**Comment by martinholmer** [comment]
@feenberg said:
> Perhaps we should ignore losses when calculating base income? 

Seems like a pretty *ad hoc* approach.
Do any other tax analysis models define expanded income in that way?

@feenberg asked:
> Does [expanded] income include the value of medicaid and other benefits?

No.  But capital losses and business losses that cause the bottom decile to have negative expanded income are so large that the bottom decile would probably still have negative expanded income even if benefits were added to expanded income.

**Comment by feenberg** [comment]
On Wed, 3 Jan 2018, Martin Holmer wrote:

> 
> @feenberg said:
>
>       Perhaps we should ignore losses when calculating base income?
> 
> Seems like a pretty ad hoc approach.
> Do any other tax analysis models define expanded income in that way?

I don't know.

> 
> @feenberg asked:
>
>       Does [expanded] income include the value of medicaid and other benefits?
> 
> No. But capital losses and business losses that cause the bottom decile to have
> negative expanded income are so large that the bottom decile would probably still have
> negative expanded income even if benefits were added to expanded income.
>


Sometimes negative incomes are excluded from the lowest income category, 
but included in the the total. I recall seeing that in several places.

Notice that if you tab by AGI capital losses are capped at $3000 and 
presumably that solves the problem.

These losses don't come from the CPS, do they? We are imputing them from 
the SOI file. I wonder if the imputation is going wrong and imputing an 
unreasonable share of losses to poor taxpayers.

dan

**Comment by martinholmer** [comment]
@MaxGhenis and @feenberg,
I think we should wait for some facts before continuing the conversation in issue #1806.
I have asked the taxdata developers to provide us some facts in [taxdata issue 143](https://github.com/open-source-economics/taxdata/issues/143).

**Comment by martinholmer** [comment]
Merge of pull request #1880 resolves issue #1806.
For a more complete discussion of this matter, see [this comment in taxdata issue 143](https://github.com/open-source-economics/taxdata/issues/143#issuecomment-366129675).
