### ISSUE TITLE
Can we model HSA limit increases?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1811]
A user asked

> Can I model changes in government tax revenue due to increases in annual limits of HSAs (and understanding how the revenue change is distributed across states). For example, what if the 2018 annual HSA contribution limits for individuals ($3,450) and families ($6,900) doubled? Also, would it be possible to simulate an increased use of HSAs (i.e., more people contribute to them)?

The user also said, 

> Since you have a way to place a haircut on the HSAs, I think we just need to allow for a -1 to be entered into the tax brain model (if we assume a that people respond similarly to tax increases and decreases on health savings). While a behavioral parameter estimate would be best, this seems like a quick back of the envelope.

I don't think we can model this because taxpayers don't report HSA contributions exceeding the limit to the IRS. Posting this in case I'm wrong or in case someone wants to work on the necessary imputations over in TaxData. I am waiting to hear if the user is interested in doing the imputations themselves.

**Comment by feenberg** [comment]
On Thu, 4 Jan 2018, Matt Jensen wrote:

> 
> A user asked
...
>
>       Since you have a way to place a haircut on the HSAs, I think we just need
>       to allow for a -1 to be entered into the tax brain model (if we assume a
>       that people respond similarly to tax increases and decreases on health
>       savings). While a behavioral parameter estimate would be best, this seems
>       like a quick back of the envelope.
> 
> I don't think we can model this because taxpayers don't report HSA contributions
> exceeding the limit to the IRS. Posting this in case I'm wrong or in case someone
> wants to work on the necessary imputations over in TaxData. I am waiting to hear if
> the user is interested in doing the imputations themselves.
>

Even if we had the contribution amount, don't we think it would change if 
the limit were increased? Wouldn't many taxpayers want to contribute only 
up to the limit, but at least to that limit? Nevertheless, please 
encourage the user if they are at all competent. I'd be glad to talk to 
them.

Do we know what the user means the -1 to signify?

dan

**Comment by martinholmer** [comment]
No conversation for the past two weeks regarding issue #1811, so it seems to be stale.
