### ISSUE TITLE
Add TCJA treatment of alimony received

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1815]
In #1803 @codykallen said:
> The ALD for alimony paid is repealed (you already got that), but the TCJA also makes alimony received no longer count toward AGI.  So we need a new ALD for alimony received.  I missed this in the construction of the `TCJA_Reconciliation.json` reform file.

**Comment by martinholmer** [comment]
@codykallen,  I'm in the process of adding a new policy parameter called `_ALD_AlimonyReceived_hc`.
Let me double-check with you that I understand what the values of this new parameter should be.

Under pre-TCJA law, `_ALD_AlimonyReceived_hc` is always zero, right?

Under TCJA, the value of `_ALD_AlimonyReceived_hc` switches from zero to one beginning in 2018, right?

Does `_ALD_AlimonyReceived_hc` revert back to zero in 2026?

**Comment by codykallen** [comment]
@martinholmer, it better to think of TCJA as allowing a full ALD for alimony received, and pre-TCJA law as imposing full haircut on the alimony-received above-the-line deduction.

Thus, a haircut on an above-the-line deduction for alimony received would have a value of 1 under pre-TCJA law (b/c there was no deduction), and a value of zero beginning in 2018 under the TCJA. As with the other provisions, it reverts to 1 in 2026.

**Comment by martinholmer** [comment]
@codykallen said:
> Thus, a haircut on an above-the-line deduction for alimony received would have a value of 1 under pre-TCJA law (b/c there was no deduction), and a value of zero beginning in 2018 under the TCJA. As with the other provisions, it reverts to 1 in 2026.

Yes, this is how it is in pull request #1818 **except** for the timing.  See #1818 for the details of my questions about this.

**Comment by martinholmer** [comment]
Issue #1815 has been resolved by merging pull request #1818.
