### ISSUE TITLE
Modify TCJA logic with respect to PT_exclusion_wage_limit

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1816]
In #1803 @codykallen said:
> We need to modify the wage limit in functions.py:TaxInc. The wage limitation, `PT_exclusion_wage_limit`, should actually be phased in.  The following code would replace the TaxInc function with a corrected specification of the wage limitation:
>
> PT_excl_rt: TCJA sets to 0.2
> PT_excl_wagelim_rt: TCJA sets to 0.5
> PT_excl_wagelim_thd: TCJA sets to [157500, 315000, 157500, 157500, 315000]
> PT_excl_wagelim_prt: TCJA sets to [0.00002, 0.00001, 0.00002, 0.00002, 0.00001]
>```
> def TaxInc(c00100, standard, c04470, c04600, c04800,
>            PT_excl_rt, PT_excl_wagelim_rt, PT_excl_wagelim_thd,
>            PT_excl_wagelim_prt, e00900, e26270, e00200):
>    """
>    TaxInc function: ...
>    """
>
>    pt_excl_pre = max(0., PT_excl_rt * (e00900 + e26270))
>    wagelim_pre = e00200 * PT_excl_wagelim_rt
>    taxinc_pre = max(0., c00100 - max(c04470, standard) - c04600)
>    # calculate business income exclusion
>    excess = max(taxinc_pre - PT_excl_wagelim_thd[MARS - 1], 0.)
>    wagelim_rt = min(excess * PT_excl_wagelim_prt[MARS - 1], 1.)
>    limit = wagelim_rt * max(pt_excl_pre - wage_limit_pre, 0.)
>    pt_excl = pt_excl_pre - limit
>    c04800 = max(0., taxinc_pre - pt_excl)
>    return c04800
>```
>
> Note that this implementation of the wage limitation is only based on the data we have and can model. I have not included the option for a tax filer to use an alternative to PT_excl_wagelim_rt, which the TCJA sets to 50% of wages, to instead use 25% of wages plus 2.5% of tangible depreciable property.

**Comment by codykallen** [comment]
There is actually another related piece that needs to be modified, although it would apply separately (I believe in the CapGains function or the AGI function). The TCJA also limits pass-through losses (`e00900 + e26270`) to $500,000 for married filers and $250,000 for other filers, although I doubt this provision will affect many filers.

**Comment by martinholmer** [comment]
@codykallen, what you say at the beginning of issue #1817 is not very clear.  You suggest that all that is needed is a change in the statements in the TaxInc function, but on closer inspection you seem to be implying a need for several more policy parameters that are not now part of Tax-Calculator.   Can you clarify?

**Comment by codykallen** [comment]
@martinholmer, when I said the only change would be in the TaxInc function, I meant that the only changes to the logic in functions.py would be in the TaxInc function. 

But yes, it would require three more policy parameters, and replacing `PT_exclusion_rt` with `PT_excl_rt`.

**Comment by martinholmer** [comment]
@codykallen said:
> when I said the only change would be in the TaxInc function, I meant that the only changes to the logic in `functions.py` would be in the TaxInc function.

But yes, it would require three more policy parameters, and replacing `PT_exclusion_rt` with `PT_excl_rt`.

OK, thanks for the clarification.
Why don't you prepare a pull request that makes all those changes?

**Comment by codykallen** [comment]
> Why don't you prepare a pull request that makes all those changes?

Can do. Do you want the default values set to conform with pre-TCJA law?

**Comment by martinholmer** [comment]
@codykallen asked:
> Do you want the default values set to conform with pre-TCJA law?

Yes, please develop you pull request off the latest version of the master branch, which is still pre-TCJA law.
Thanks.  I'll be happy to review as soon as you post the pull request.

**Comment by martinholmer** [comment]
The issues discussed in #1816 have been resolved by the merge of pull request #1819, the need for which was identified by @codykallen and the development of which was done by @codykallen.

Thanks for all the help, @codykallen!
