### ISSUE TITLE
0% rate capital gain tax base

### ISSUE THREAD

**Issue by Amy-Xu** [open-source-economics/Tax-Calculator#182]
`
if FLPDYR ge 2004 then do;
   if FLPDYR ge 2008 then do;
      _amt5pc  = 0;
      _amt15pc = min(_alminc,c62720)-_amt5pc-min(max(0,_brk2(FLPDYR,MARS)
               -c24520),min(_alminc,c62720));
      if c04800 eq 0 then 
         _amt15pc = max(0,min(_alminc,c62720)-_brk2(FLPDYR,MARS));
      _amt25pc = min(_alminc,c62740) - min(_alminc,c62720);
   end;

`

In the AMT income section, this snippet seems to deal with capital gains and dividends excluding 25% gain and 28% gain. Dan @feenberg , I need to confirm my understanding of this snippet. The tax base of capital gain below bracket 2, which is taxed at 0% currently and 5% before 2004, is set to zero for 2013. Then we subtract the actual capital gain below bracket 2, represented by `min(max(0,_brk2(FLPDYR,MARS)-c24520),min(_alminc,c62720))`,  to get the 15% capital gain tax base. Is that correct?

If so, can we use c24520 from capital gain for regular tax to calculate cap gain for AMT? I thought the accounting of cap gain/loss for AMT is different from the accounting for regular tax. In addition, should we use this `min(max(0,_brk2(FLPDYR,MARS)-c24520),min(_alminc,c62720))` as the value of _amt5pc?

Note: Currently two variables (c24520, c24517) are used in both cap gain tax for regular tax and AMT and therefore linked the two cap gain tax sections together. If we move regular tax, AMT would change as a result of different c24520 and c24517 values.

**Comment by martinholmer** [comment]
Tax-Calculator issue #182 seems to have been resolved by the revisions and bug fixes in pull requests #1000 and #1001, so #182 is being closed.
