### ISSUE TITLE
Treatment of floor for medical expense deduction

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1835]
The new version of Tax-Calculator that accounts for the TCJA rules does not correctly handle the parameter `_ID_Medical_frt_add4aged`. 

Under pre-TCJA law, the floor was 10% of AGI in general but 7.5% of AGI for the elderly, so `_ID_Medical_frt_add4aged` had a value of -0.025. The TCJA reduced the floor to 7.5% for 2017 and 2018, but raised it back to 10% for non-elderly filers effective in 2019. The new values in `current_law_policy.json` are correct for `_ID_Medical_frt`, but the value for `_ID_Medical_frt_add4aged` should be zero for 2017 and 2018 but return to -0.025 beginning in 2019.

@martinholmer

**Comment by martinholmer** [comment]
@codykallen,  Can you provide some documentation for your comment in issue #1835?

**Comment by codykallen** [comment]
@martinholmer, I was wrong. The floor reverts to 10% for all taxpayers in 2019. My mistake. Closing this issue.
