### ISSUE TITLE
test_compatible_data requires more explanation

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1846]
A fairly complex test was added in pull request #1614 and updated in pull request #1839 so that the test passed using the new current-law policy.

If we want this test to be able to be maintained going forward (by developers who were not the original authors of the test), I think the complexities of the test need more documentation in the `test_compatable_data.py` file.  

The test's complexity is in at least two areas:

1. The`fixture_reform_xx` returns a dictionary that is described this way: `Set baseline to activate parameters that are inactive under current law.`  But in #1839 it took several commits to get the "right" values to "activate [the] parameters" in the correct way.  What were the considerations that came into play as those commits were made.  That fixture's docstring needs to include some discussion that answers these questions and provides advice for those faced with updating the test in the future.

2. The concept of a `BATCH` is central to the test, but there appears to be no explanation of what a BATCH is, and no motivation for why it has been introduced into the logic of the test, other that what the `fixture allparams_batch` docstring says: `Fixture for grouping Tax-Calculator parameters`.  This really isn't enough explanation for a future maintainer of the test.

@MattHJensen @hdoupe

**Comment by hdoupe** [comment]
@martinholmer I'll take care of 2. Thanks for bringing this to my attention.

**Comment by MattHJensen** [comment]
And I'll take 1.

**Comment by martinholmer** [comment]
@hdoupe added documentation on item 1 in pull request #1876.  Thanks, @hdoupe!
