### ISSUE TITLE
"could not read cps_benefits.csv.gz data from egg"

### ISSUE THREAD

**Issue by evtedeschi3** [open-source-economics/Tax-Calculator#1862]
I'm getting a new error message when running the tc CLI. Here's the command I ran:

```
python '/Users/ernietedeschi/tc/tax-calculator/taxcalc/cli/tc.py' cps.csv 2025 --dump --baseline '/Users/ernietedeschi/tc/tax-calculator/taxcalc/reforms/2017_law.json'
```

And here's the error output:

```
Traceback (most recent call last):
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.15.2_50_g555e8b2-py3.6.egg/taxcalc/utils.py", line 1240, in read_egg_csv
    path_in_egg),
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1227, in resource_stream
    self, resource_name
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1592, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.15.2_50_g555e8b2-py3.6.egg/taxcalc/cps_benefits.csv.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ernietedeschi/tc/tax-calculator/taxcalc/cli/tc.py", line 249, in <module>
    sys.exit(cli_tc_main())
  File "/Users/ernietedeschi/tc/tax-calculator/taxcalc/cli/tc.py", line 167, in cli_tc_main
    exact_calculations=args.exact)
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.15.2_50_g555e8b2-py3.6.egg/taxcalc/taxcalcio.py", line 322, in init
    exact_calculations=exact_calculations
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.15.2_50_g555e8b2-py3.6.egg/taxcalc/records.py", line 204, in cps_constructor
    start_year=Records.CPSCSV_YEAR)
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.15.2_50_g555e8b2-py3.6.egg/taxcalc/records.py", line 153, in __init__
    self._read_benefits(benefits)
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.15.2_50_g555e8b2-py3.6.egg/taxcalc/records.py", line 568, in _read_benefits
    BEN_partial = read_egg_csv(b_path)  # pragma: no cover
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.15.2_50_g555e8b2-py3.6.egg/taxcalc/utils.py", line 1244, in read_egg_csv
    raise ValueError('could not read {} data from egg'.format(fname))
ValueError: could not read cps_benefits.csv.gz data from egg
```

Somehow the `cps_benefits.csv.gz` file downloaded to my local directory but didn't end up in my latest egg directory. I copied it over manually and the command works fine now. But in thinking about future updates: did I do something wrong here? I updated my local version with the master this morning; I didn't change anything about my normal fetch / merge routine.

**Comment by martinholmer** [comment]
Thanks for the bug report. Will fix it on Friday. You didn’t do anything wrong.

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> I'm getting a new error message when running the tc CLI. Here's the command I ran:
>```
>$ python '/Users/ernietedeschi/tc/tax-calculator/taxcalc/cli/tc.py' cps.csv 2025 --dump --baseline '/Users/ernietedeschi/tc/tax-calculator/taxcalc/reforms/2017_law.json'
>```
> Somehow the `cps_benefits.csv.gz` file downloaded to my local directory but didn't end up in my latest egg directory.   I copied it over manually and the command works fine now.  But in thinking about future updates: did I do something wrong here? I updated my local version with the master this morning; I didn't change anything about my normal fetch / merge routine.

Actually, you did do something that we've never planned for.  The `tc` tool was never designed to execute as a Python script (as you did above: `$ python tc.py cps.csv 2025 ...`) but rather as a command-line tool provided by the installed taxcalc package (like this: `$ tc cps.csv 2025 ...`).

When you updated your source code (on or after February 6th) your **code** included the changes in pull request #1719, which adds the `cps_benefits.csv.gz` file.  So, when you did `$ python tc.py cps.csv 2025 ...` the **new code** was expecting `cps_benefits.csv.gz` to be in the egg.  But it will not be in the egg until we release 0.16.0.

You can either make the *ad hoc* fixes that you will need to make occasionally when executing `$ python tc.py cps.csv 2025 ...` or you can avoid those problems by always using the `tc` tool the way is was designed to be used: `$ tc cps.csv 2025 ...`.  It's up to you.

**Comment by evtedeschi3** [comment]
@martinholmer said:
> Actually, you did do something that we've never planned for. The tc tool was never designed to execute as a Python script (as you did above: $ python tc.py cps.csv 2025 ...) but rather as a command-line tool provided by the installed taxcalc package (like this: $ tc cps.csv 2025 ...).

Ah, I thought I needed to use `python tc.py` in my workflow rather than `tc` if I wanted to always use the latest master version.

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> I thought I needed to use `python tc.py` in my workflow rather than `tc` if I wanted to always use the latest master version.

If your goal is to be using the `tc` tool but with the latest source code enhancements (that is, using the code at the tip of the master branch), then I suggest you make a taxcalc package on your computer using the `conda.recipe/install_local_taxcalc_package.sh` script.  Here are the first few lines of that script:
```
#!/bin/bash
# USAGE: ./install_local_taxcalc_package.sh
# ACTION: (1) uninstalls any installed taxcalc package (conda uninstall)
#         (2) executes "conda install conda-build" (if necessary)
#         (3) builds local taxcalc=0.0.0 package (conda build)
#         (4) installs local taxcalc=0.0.0 package (conda install)
# NOTE: for those with experience working with compiled languages,
#       building a local conda package is analogous to compiling an executable
```

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> Ah, I thought I needed to use `python tc.py` in my workflow rather than tc if I wanted to always use the latest master version.

After further reflection on this: Yes, it is fine to invoke the command-line tool `tc` by executing `python tc.py` on the tip of the master branch.  As you say, the point of doing that is to always have the newest version of the source code (rather than the newest release).  But with that benefit comes a cost.  We do extra pre-release tests that try to reduce the chance that the `tc` tool has problems and those pre-release tests are not done for every merge of a pull request.  So, as they say in the software community: you are welcome to be on the leading edge, but it may turn out sometimes that you are on the bleeding edge.
