### ISSUE TITLE
Why do we have a special formatting requirement for CPI parameters?

### ISSUE THREAD

**Issue by hdoupe** [open-source-economics/Tax-Calculator#1883]
I'm trying to implement string parsing logic that converts raw input strings from PolicyBrain's GUI into the type expected by Tax-Calculator. In doing so, I've had to think of the Tax-Calculator parameters in a systematic way. I noticed that the cpi parameters have a different formatting requirement than other parameters, and I'm not really sure why. I'm interested in hearing the rationale behind this decision. Consider the following example:

```
Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 18:10:31) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import taxcalc

In [2]: taxcalc.__version__
Out[2]: '0.15.1'

In [3]: reform1 = {2017: {"_AMT_em_ps_cpi": True, "_DependentCredit_before_CTC": [True]}}

In [4]: reform2 = {2017: {"_AMT_em_ps_cpi": [True], "_DependentCredit_before_CTC": [True]}}

In [5]: pol1 = taxcalc.Policy()

In [6]: pol2 = taxcalc.Policy()

In [7]: pol1.implement_reform(reform1)

In [8]: pol2.implement_reform(reform2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-2f867fa423e8> in <module>()
----> 1 pol2.implement_reform(reform2)

/anaconda/lib/python3.6/site-packages/taxcalc/policy.py in implement_reform(self, reform)
    198         self._validate_parameter_names_types(reform)
    199         if not self._ignore_errors and self.reform_errors:
--> 200             raise ValueError(self.reform_errors)
    201         # optionally apply cpi_offset to inflation_rates and re-initialize
    202         if Policy._cpi_offset_in_reform(reform):

ValueError: ERROR: 2017 _AMT_em_ps_cpi parameter is not true or false

```

Why does `_AMT_em_ps_cpi` have to be `True` but `_DependentCredit_before_CTC` has to be `[True]`?

**Comment by martinholmer** [comment]
@hdoupe gave an [example](https://github.com/open-source-economics/Tax-Calculator/issues/1883#issue-297565476) of working with different kinds of boolean policy parameters and then asked:
> Why does `_AMT_em_ps_cpi` have to be `True` but `_DependentCredit_before_CTC` has to be `[True]`?

Because that's the way T.J. designed things at the beginning of the project.

**Comment by hdoupe** [comment]
Ok, I see. Thanks for the explanation.

**Comment by hdoupe** [comment]
Closing. This doesn't cause enough problems in PolicyBrain to warrant further discussion.
