### ISSUE TITLE
Flag data availability for output variables in documentation

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1898]
The [user documentation](http://open-source-economics.github.io/Tax-Calculator/) currently lists CPS and PUF availability for all input variables. Would it be possible to do this for the output variables too?

For example, I was looking through `c07230` ("Education tax credits non-refundable amount") and found that it was zero using CPS data. This isn't mentioned in the docs; I discovered it after looking at the data. Looking through the code I found that it's zero because (I think) it derives from the `e87530` input ("Adjusted qualified lifetime learning expenses for all students") which is only in PUF.

Not a big deal but could be be a nice documentation touch. The availability note would need to be more than the bools as the inputs have, since some like after-tax income are just different. But flagging the ones that are null in each dataset would be useful.

**Comment by martinholmer** [comment]
@MaxGhenis said on March 2 (about five months ago):
> The user documentation currently lists CPS and PUF availability for all input variables. Would it be possible to do this for the output variables too?
>
> For example, I was looking through c07230 ("Education tax credits non-refundable amount") and found that it was zero using CPS data. This isn't mentioned in the docs; I discovered it after looking at the data. Looking through the code I found that it's zero because (I think) it derives from the e87530 input ("Adjusted qualified lifetime learning expenses for all students") which is only in PUF.
>
> Not a big deal but could be be a nice documentation touch. The availability note would need to be more than the bools as the inputs have, since some like after-tax income are just different. But flagging the ones that are null in each dataset would be useful.

I agree with the assessment that this enhancement is "[n]ot a big deal but could be be a nice documentation touch."  Given that this enhancement would take quite a bit of work and add only a little to the documentation (being "not a big deal"), the Tax-Calculator developers are currently not in position to make this enhancement given other higher priorities.  But, @MaxGhenis, we would be happy to consider your pull request adding this "nice documentation touch."

@MattHJensen

**Comment by MattHJensen** [comment]
Agree that it would be nice to have this if @MaxGhenis is ever itching to submit a PR. The biggest challenge to me would seem to be adding a test to ensure the documentation's accuracy over time.
