### ISSUE TITLE
EITC doesn't exclude individual filers with high investment income

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1903]
I'm not sure I'm reading this correctly, but my understanding is that the investment income ceiling applies to all EITC filers. [IRS Publication 596 on EIC](https://www.irs.gov/pub/irs-pdf/p596.pdf) lists "Your Investment Income Must Be $3,450 or Less" under the "Rules for Everyone" section. Yet tc's [`EITC` function](https://github.com/open-source-economics/Tax-Calculator/blob/5b20973bbfe4834420a71f892976ec3555c3b52d/taxcalc/functions.py#L1139) only checks filers who don't file individually for the EITC for this condition. 

This is currently in lines 1150-1153, where `invinc` is defined and `c59660` is set to zero for those with `invinc > EITC_InvestIncome_c`. This is inside the statement `if not EITC_indiv:` and the [`else:` section](https://github.com/open-source-economics/Tax-Calculator/blob/5b20973bbfe4834420a71f892976ec3555c3b52d/taxcalc/functions.py#L1185) doesn't have similar logic.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1903:
> I'm not sure I'm reading this correctly, but my understanding is that the investment income ceiling applies to all EITC filers. IRS Publication 596 on EIC lists "Your Investment Income Must Be $3,450 or Less" under the "Rules for Everyone" section. Yet tc's EITC function only checks filers who don't file individually for the EITC for this condition.
>
> This is currently in lines 1150-1153, where `invinc` is defined and `c59660`is set to zero for those with `invinc > EITC_InvestIncome_c`. This is inside the statement `if not EITC_indiv:` and the `else:` section doesn't have similar logic.

We all agree that the EITC investment income ceiling applies to all filing units, and that's how the Tax-Calculator code implements current-law EITC.  Your confusion might be cleared up by reading the documentation of the `_EITC_indiv` policy parameter, which when True simulates a totally different kind of earned income tax credit that does not have an investment income eligibility test.

**Comment by martinholmer** [comment]
The assertion in the title of issue #1903 is not true.  The mistaken assertion is based on a misunderstanding of the `_EITC_indiv` policy parameter, which is False under current-law policy and when True simulates a major reform in which there is no longer an investment income eligibility test.

**Comment by MaxGhenis** [comment]
Thanks @martinholmer, my mistake. I see now that `_EITC_indiv` has this description:

> Current-law value is false implying EITC is filing-unit based; a value of true implies EITC is computed for each individual wage earner. The phase-out of the credit works slightly differently between the two. Individual-based calculation ignore investment income and age eligibilty rules used in filing-unit-based calculations.

The leading underscore should have tipped me off that it's a policy parameter and not an input.

I edited the issue title to avoid the false assertion and make it suitable for a "Working as Intended" label if one exists.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1903:
> The leading underscore should have tipped me off that it's a policy parameter and not an input.

No problem.  The source code is complex, especially bcause some of it is simulating reforms rather than current-law policy.
