### ISSUE TITLE
linkable description of difference between CPS file and PUF file

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1921]
TaxBrain is going to allow users to choose between the CPS and the PUF tax files as the basis for their analyses. I think it would be helpful to link from the user tips section of the TaxBrain input page to a place where the user can read about these two files and their primary differences and usage with Tax-Calculator. 

As a starting point, the Tax-Calculator [user guide](http://open-source-economics.github.io/Tax-Calculator/) has good content on these two files, but not in a chunk that is easily linkable from TaxBrain.

**Comment by andersonfrailey** [comment]
Agreed that this would be helpful. Off the top of my head, I can think of a few pieces of information that should probably be included:
* A list of variables available in one file, but not the other
* A list of policy parameters that are not available for use in each file (the ones greyed out in TaxBrain)
* A comparison of baseline calculations using each file
* A short description of where each file comes from

**Comment by martinholmer** [comment]
Tax-Calculator issue #1921 is resolved by [taxdata pull request 173](https://github.com/open-source-economics/taxdata/pull/173).
