### ISSUE TITLE
Modelling GDP Growth Question

### ISSUE THREAD

**Issue by derrickchoe** [open-source-economics/Tax-Calculator#1924]
Hi all,

Any advice is much appreciated: I’m working on a project that requires estimating the effect of additional GDP growth on filers’ incomes-- using the resulting AGI growth, I’ll be measuring the impact on charitable giving. 
 
I’ve looked into the growdiff parameters, and I’m having trouble figuring out how exactly to model economic growth all around. I was previously increasing AWAGE only, but I’d like to take other forms of income into account. If I want to model an additional 2% real growth in GDP, is the best method to increase growth in all forms of income by 2%: ACGNS, ADIVS, etc.? 
 
Thanks for all of your help,
 
Derrick

**Comment by codykallen** [comment]
The possible growth factors that can be changed are:

- `ABOOK`, foreign tax credit and general business credit
- `ACGNS`, capital gains and losses
- `ACPIM`, medical expenses and contributions
- `ACPIU`, consumer price index
- `ADIVS`, dividends
- `AINTS`, interest income
- `AIPD`, interest paid
- `ASCHCI`, profit from sole proprietorship
- `ASCHCL`, loss from sole proprietorship
- `ASCHEI`, Sch. E profit
- `ASCHEL`, Sch. E loss
- `ASCHF`, farm net income/loss
- `ASOCSEC`, Social Security benefits
- `ATXPY`, all miscellaneous categories
- `AUCOMP`, Unemployment compensation
- `AWAGE`, wage and salary income

Which ones you should change depend on the type of shock to GDP. First, suppose it is an exogenous, homogeneous shock to real GDP (but not to inflation). In that case, you would change all of these except for `ACPIU` and `ASOCSEC`, and perhaps excluding `AUCOMP` as well, or instead changing it by a smaller increment. 

But suppose it instead is driven by an increase in business activity. Then you would want larger changes to `ABOOK`, `ACGNS`, `ADIVS`, `AINTS`, `ASCHCI`, `ASCHCL`, `ASCHEI`, and `ASCHEL`, with smaller, secondary changes to `AWAGE`, `ACPIM`, `ASCHF`, `ATXPY` and `AUCOMP`.

**Comment by codykallen** [comment]
@MattHJensen, @andersonfrailey, @hdoupe

**Comment by derrickchoe** [comment]
@codykallen 
Thanks for the quick response-- I'll check with Alex to see exactly how we'd like the growth distributed. I suspect that we'll just want to expand all growfactors other than the price/government transfers you detail in your first example: 

> First, suppose it is an exogenous, homogeneous shock to real GDP (but not to inflation). In that case, you would change all of these except for ACPIU and ASOCSEC, and perhaps excluding AUCOMP as well, or instead changing it by a smaller increment.

**Comment by feenberg** [comment]
On Thu, 15 Mar 2018, derrickchoe wrote:

> 
> Hi all,
> 
> Any advice is much appreciated: I’m working on a project that requires estimating the
> effect of additional GDP growth on filers’ incomes-- using the resulting AGI growth,
> I’ll be measuring the impact on charitable giving.
> 
> I’ve looked into the growdiff parameters, and I’m having trouble figuring out how
> exactly to model economic growth all around. I was previously increasing AWAGE only,
> but I’d like to take other forms of income into account. If I want to model an
> additional 2% real growth in GDP, is the best method to increase growth in all forms
> of income by 2%: ACGNS, ADIVS, etc.?

I am not aware of any studies showing different tendencies to give to 
charity from different sources of taxable income. You might expect 
unrealized gains to have a higher propensity, but that data is never 
available. So yes, I think the best (least controversial) practice would 
be to increase all incomes.

dan feenberg

**Comment by derrickchoe** [comment]
@feenberg 
Thanks for the input! Applying varying charity responses to different forms of income is currently beyond the scope of our project, so I'll proceed with increasing all incomes as you mentioned. I'll likely be estimating the income effect on charity using after-tax incomes, so equal growth in all forms of income will help ensure that all tax filers benefit from this hypothetical growth.

**Comment by martinholmer** [comment]
@derrickchoe,  Have the questions you posed in issue #1924 been answered?
If not, please ask more questions.
If they have all been answered, please close the issue.

**Comment by derrickchoe** [comment]
Hi @martinholmer,

Thanks for checking in-- my questions have been more than sufficiently addressed. Closing now.

Best,

Derrick
