### ISSUE TITLE
2017 Law JSON: Standard Deduction

### ISSUE THREAD

**Issue by derrickchoe** [open-source-economics/Tax-Calculator#1933]
@MattHJensen @martinholmer @hdoupe @andersonfrailey @codykallen 

Hi all,

I have a question about the [2017_law.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/2017_law.json) file. I noticed that the file doesn't contain any changes to the "_STD" parameter. When I implement the reform, however, it seems taxcalc does the right thing and doesn't raise the standard deduction as per the TCJA in 2018. 

I would assume that without specifying that the standard deduction doesn't change, any calculators advanced past 2018 would assume the TCJA standard deduction amounts. Does this have something to do with the "_cpi_offset" parameter? Thanks for all of your help!

Best,

Derrick

**Comment by martinholmer** [comment]
@derrickchoe asked:
> I have a question about the `2017_law.json` file.  I noticed that the file doesn't contain any changes to the `_STD` parameter. When I implement the reform, however, it seems taxcalc does the right thing and doesn't raise the standard deduction as per the TCJA in 2018.

This same question was asked by @evtedeschi3 on 1/22/2018.  Please read the conversation following his question, which was in [this comment](https://github.com/open-source-economics/Tax-Calculator/pull/1803#issuecomment-359543727).

**Comment by derrickchoe** [comment]
@martinholmer 
Thanks for pointing me to the thread! I believe that I understand how the reform works now.

**Comment by martinholmer** [comment]
@derrickchoe said:
> Thanks for pointing me to the thread! I believe that I understand how the reform works now.

The reform is complicated, so if other questions arise open a new issue.
