### ISSUE TITLE
Move final pieces of parameter processing from TaxBrain to Tax-Calculator

### ISSUE THREAD

**Issue by hdoupe** [open-source-economics/Tax-Calculator#1934]
Over the last few months, almost all of the parameter processing and validation has been moved from TaxBrain to Tax-Calculator (thanks to the hard work of @martinholmer). However, TaxBrain still pins the `AMT_CG_rt` to `CG_rt` under certain conditions (see OpenSourcePolicyCenter/PolicyBrain#607). If this behavior is desired by Tax-Calculator, then I think that Tax-Calculator should implement it. I also think ther requests such as OpenSourcePolicyCenter/PolicyBrain#821 should be directed towards Tax-Calculator.

**Comment by hdoupe** [comment]
Also see more discussion on this in OpenSourcePolicyCenter/PolicyBrain#340.

**Comment by martinholmer** [comment]
@hdoupe said in issue #1934:
> TaxBrain still pins the `AMT_CG_rt` to `CG_rt` under certain conditions (see OpenSourcePolicyCenter/PolicyBrain#607). If this behavior is desired by Tax-Calculator, then I think that Tax-Calculator should implement it.

In Tax-Calculator there is no logical connection between the `_CG_rt?` and `_AMT_CG_rt?` parameter values.  I have no idea why TaxBrain is imposing such a restrictive rule.  So, I think you can see that the notion that "this behavior is desired by Tax-Calculator" is not true.

**Comment by hdoupe** [comment]
Thanks for the response @martinholmer. I'm not sure why it's there either. If there aren't any objections, then I will remove it.

**Comment by martinholmer** [comment]
@hdoupe said:
>  I'm not sure why it's there either. If there aren't any objections, then I will remove it.

Fine with me.

**Comment by martinholmer** [comment]
Issue #1934 has been resolved by [PolicyBrain pull request 868](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/868).
