### ISSUE TITLE
Error using PUF: 'expression "e01500 >= e01700" is not true for every record'

### ISSUE THREAD

**Issue by evtedeschi3** [open-source-economics/Tax-Calculator#1949]
Updated to tc v0.18, and now trying to run a very simple command using the 2011 PUF:

`python '/Users/ernietedeschi/tc/tax-calculator/taxcalc/cli/tc.py' puf.csv 2018 --dump`

Here's the error I'm now getting.

```
Traceback (most recent call last):
  File "/Users/ernietedeschi/tc/tax-calculator/taxcalc/cli/tc.py", line 249, in <module>
    sys.exit(cli_tc_main())
  File "/Users/ernietedeschi/tc/tax-calculator/taxcalc/cli/tc.py", line 167, in cli_tc_main
    exact_calculations=args.exact)
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.18.0_5_g8bc6c8a-py3.6.egg/taxcalc/taxcalcio.py", line 333, in init
    exact_calculations=exact_calculations
  File "/Users/ernietedeschi/anaconda3/lib/python3.6/site-packages/taxcalc-0.18.0_5_g8bc6c8a-py3.6.egg/taxcalc/records.py", line 147, in __init__
    raise ValueError(msg)
ValueError: expression "e01500 >= e01700" is not true for every record
```

**Comment by martinholmer** [comment]
@evtedeschi3, sorry you're having problems using the taxcalc 0.18.0 package, but I cannot reproduce your experience on OSX using the Python 2.7 taxcalc package.   Here is my experience:
```
tax-calculator-data$ conda install -c ospc taxcalc
Solving environment: done
## Package Plan ##
  environment location: /Users/mrh/anaconda
  added / updated specs: 
    - taxcalc
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    taxcalc-0.18.0             |           py27_0        38.1 MB  ospc
The following NEW packages will be INSTALLED:
    taxcalc: 0.18.0-py27_0 ospc
Proceed ([y]/n)? y

tax-calculator-data$ tc --version
Tax-Calculator 0.18.0
tax-calculator-data$ ls -l puf.csv
-rw-r--r--@ 1 mrh  staff  54718219 Mar  1 17:02 puf.csv

tax-calculator-data$ md5 puf.csv
MD5 (puf.csv) = e22429702920a0d927a36ea1103ba067

tax-calculator-data$ tc puf.csv 2018 --dump
You loaded data for 2011.
Tax-Calculator startup automatically extrapolated your data to 2018.
WARNING: Tax-Calculator packages for Python 2.7 will
         no longer be provided beginning in 2019
         because Pandas is stopping development for 2.7.
SOLUTION: upgrade to Python 3.6 now.

tax-calculator-data$ ls -l puf-18-#-#-#.csv 
-rw-r--r--  1 mrh  staff  256658955 Apr  2 09:56 puf-18-#-#-#.csv
```
Are you using the same `puf.csv` file as I'm using?

**Comment by evtedeschi3** [comment]
@martinholmer asked:

> Are you using the same puf.csv file as I'm using?

I'm using a 2011 PUF from Feb 13, generated to correct for the issues in PR 114.

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> I'm using a 2011 `puf.csv` from Feb 13, generated to correct for the issues in PR 114.

There is a newer version with this information:
```
  "puf03092018.csv.gz": {
    "date": "2018-03-09T00:00:00",
    "tax_calculator_pull_request": [1897],
    "tax_data_pull_request": [158]
  }
```
Also, the newest version is documented in the [release notes for 0.16.2](https://github.com/open-source-economics/Tax-Calculator/blob/master/RELEASES.md#2018-03-09-release-0162).

My guess is that you are using an out-of-date version of the `puf.csv` file.  But I'm forced to guess because you haven't supplied any concrete information about the `puf.csv` file you're using (like its byte size and MD5 checksum).  If my guess is correct, then your probably using the `puf.csv` file documented in the [release notes for 0.16.0](https://github.com/open-source-economics/Tax-Calculator/blob/master/RELEASES.md#2018-02-13-release-0160).

**Comment by evtedeschi3** [comment]
The MD5 of the file I'm using is `de4a59c9bce0a7d5e6c3110172237c9b`

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> The MD5 of the file I'm using is de4a59c9bce0a7d5e6c3110172237c9b, which I see from the release notes is different from the latest version. That solves it. Thanks for being patient with users like me who aren't steeped in this every day.

No problem.  But your experience suggests we could do a better job notifying users who have access to the private `taxpuf` repository about the availability of new versions of the `puf.csv` file.  (I'm assuming this is the source of the `puf.csv` files you are using, right?)

@MattHJensen and @andersonfrailey, do you have ideas about how to improve our `taxpuf` notification process?
