### ISSUE TITLE
Add Tax-Calculator behavior parameters validation

### ISSUE THREAD

**Issue by hdoupe** [open-source-economics/Tax-Calculator#1951]
The `taxcalc.tbi.reform_warnings_errors` function only validates the policy parameters and not the behavior parameters. Can this be augmented to validate behavior parameters, too?  I thought that it validated the behavior parameters and, thus, removed the parameter validation for them from PolicyBrain in 1.4.0.

**Comment by hdoupe** [comment]
@martinholmer would you mind if I took a shot at implementing this? I'm interested in getting to know the Tax-Calculator parameter processing/validation logic a little bit better. I think this would be a good way to do this.

**Comment by martinholmer** [comment]
@hdoupe ,  Sure go ahead and give it a try. 
Let me know if you have any questions. 
If I was doing it, I’d try developing the new code along the lines of the policy parameter validation logic.

**Comment by hdoupe** [comment]
@martinholmer Ok, thanks. Good idea. I'll give that a shot.
