### ISSUE TITLE
Option to get all columns in Calculator.dataframe() function

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1957]
Currently the [`dataframe` function](https://github.com/open-source-economics/Tax-Calculator/blob/79b0a8af7a123c565abd2fa33086a65d43918c62/taxcalc/calculate.py#L211) requires a `variable_list` argument specifying the columns to extract. It would be helpful for looking through entire records to have this be optional, in order to get all columns. It wasn't obvious to me looking through the function code how to adapt it to do this.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Currently the  [Calculator class]`dataframe` [method] requires a variable_list argument specifying the columns to extract. It would be helpful for looking through entire records to have this be optional, in order to get all columns. It wasn't obvious to me looking through the [method]  code how to adapt it to do this.

You have two choices:

1.  Use the `--dump` option with the `tc` command-line tool.

2. Read the Tax-Calculator source code if you insist on doing Python programming.

**Comment by MaxGhenis** [comment]
I traced the CLI code to this section of [dump_output](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/taxcalcio.py#

    if dump_varset is None:
        varset = Records.USABLE_READ_VARS | Records.CALCULATED_VARS

Based on this, I could extract all fields using this:

    calc.dataframe(list(tc.Records.USABLE_READ_VARS | tc.Records.CALCULATED_VARS))

WDYT of adding `list(tc.Records.USABLE_READ_VARS | tc.Records.CALCULATED_VARS)` as a default argument to `dataframe`? I can put in a PR if you agree.

**Comment by martinholmer** [comment]
@MaxGhenis asked:
> WDYT of adding `list(tc.Records.USABLE_READ_VARS | tc.Records.CALCULATED_VARS)` as a default argument to `dataframe`? I can put in a PR if you agree.

I strongly disagree.  The default should not be to generate a massive dataframe.  If you want it all you have a one-line way to do that.

**Comment by MaxGhenis** [comment]
OK, yes from CPS data the result is ~700MB, large but not unusable. And using [this function](https://stackoverflow.com/a/30316760/1840471), `Calculator` objects are ~3.7GB. A dump option can also be helpful when passing your own records, and it seems weird to have the CLI support a use case not supported in the Python interface.

Alternatives could be 
1. Another argument (e.g. `dump` as a bool)
2. A keyword like `calc.dataframe('ALL')`

Either could also include a warning about size in the function docstring.

**Comment by MaxGhenis** [comment]
> If the complexity of using the low-level Python API is too much for you

Thanks but it's not. The Python API enables reproducible research in a way the CLI does not (I've yet to see a reproducible taxcalc analysis using the CLI). Given OSPC's ethos of transparency I'd expect this to be a first-class interface, but I understand that most current users use the CLI. 

I have the info I need if you'd like to close without adding the option.
