### ISSUE TITLE
Updating to Latest CBO Projections

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/Tax-Calculator#1966]
I'm working on updating the weights and growth rates using the April 2018 CBO projections. These projections go out to 2028 so it is possible for me to generate growth rates and weights for the PUF. However, I can't generate new weights for the CPS file yet.

Would is be easiest for the Tax-Calculator project if I stick to only generating growth rates and PUF weights to 2027 for now and then I'll update everything again out to 2028 when I can generate weights for the CPS file?

cc @martinholmer

**Comment by martinholmer** [comment]
@andersonfrailey asked:
> Would is be easiest for the Tax-Calculator project if I stick to only generating growth rates and PUF weights to 2027 for now and then I'll update everything again out to 2028 when I can generate weights for the CPS file?

Yes, much easier this way.  Thanks for thinking about this.

**Comment by andersonfrailey** [comment]
Great. I'll open up a PR when I get everything updated.
