### ISSUE TITLE
Confusing warning logic

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#2004]
In [PolicyBrain issue 890](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/890) @andersonfrailey relayed this comment from a TaxBrain user:
> For 2018 with a doubled standard deduction, I'd lower the threshold before a warning is triggered. it's not clear why there's a warning on making changes to decrease the standard deduction more than a fraction of a percent.  If the deduction was just doubled, it seems like a totally fair policy to both estimate if the deduction was scaled back and if was expanded.

**Comment by feenberg** [comment]
On Fri, 18 May 2018, Martin Holmer wrote:

> 
> In PolicyBrain issue 890 @andersonfrailey relayed this comment from a TaxBrain user:
>
>       For 2018 with a doubled standard deduction, I'd lower the threshold before a warning is
>       triggered. it's not clear why there's a warning on making changes to decrease the
>       standard deduction more than a fraction of a percent. If the deduction was just doubled,
>       it seems like a totally fair policy to both estimate if the deduction was scaled back and
>       if was expanded.

Presumably the warning is to remind users that we don't have PUF data for 
itemized deductions that are lower than the standard deduction amount in 
the PUF year, so the revenue estimate is optimistic.

dan

**Comment by martinholmer** [comment]
Pull request #2005, which is included in Tax-Calculator version 0.20.1, eliminates some incorrect standard-deduction warnings.  However, as mentioned in #2005 the most direct way to resolve this issue is to fix the shortcomings of the PUF itemizeable expense variables, and then remove all the warning logic.  There are two different kinds of shortcomings in the PUF data:

1. PUF data include positive itemizeable expense amounts **only** for those who actually itemize.

2. Several positive itemizeable expense variables are capped at some percent of AGI so policy reforms that change those percentage caps may produce unexpected results.
