### ISSUE TITLE
Why are age eligibility rules ignored for an individual-based EITC

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/Tax-Calculator#2012]
One of my colleagues at AEI is doing some research related to the EITC and asked why investment income and age eligibilty rules are ignored in the individual based EITC calculations.

Reading through #1028, I came to the understanding that investment income rules are ignored because we can't distinguish between the primary and secondary earner's income, but I didn't see any mention of why the age rules are ignored. Was this just a provision of the policy proposal discussed in issue #1025?

cc @martinholmer @MattHJensen

**Comment by martinholmer** [comment]
@andersonfrailey asked:
> Was this [the individual-based EITC] just a provision of the policy proposal discussed in issue #1025?

Yes.  And, as you can see from #1025, to get definitive answers to your questions you need a response from @MattHJensen .

**Comment by MattHJensen** [comment]
I don't remember the history of thought on why age rules are ignored, but it appears they could be reintroduced if needed.

**Comment by martinholmer** [comment]
@andersonfrailey, have your questions about the "individual EITC" reform been answered?
If not, can you pose remaining questions?

**Comment by andersonfrailey** [comment]
@martinholmer, my questions have been answered. Closing.
