### ISSUE TITLE
How to manipulate Records after advancing year

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#2025]
I'm doing an analysis that involves manipulating the wages of tax records for tax year 2018, and think I got it working but would love another quick set of eyes to check, given it's a bit complicated. Here were my steps, and full code is in [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/manipulate_records_after_advancing_year.ipynb):

1. Advance a "stock" `Calculator` to 2018, based on the `cps_constructor` `Records`.
2. Extract the columns from the raw CPS file and store this as a dataframe.
3. Manipulate wages as needed.
4. Pass this modified dataframe as the `data` argument in a new `Records` constructor, setting `start_year=2018`.
5. Create a new `Calculator` object based on this new `Records` object.

After doing this, the manipulated column from the Calculator in (5) matched that from (3), as expected. Does this look right? Thanks.

**Comment by martinholmer** [comment]
@MaxGhenis asked in issue #2025:
> I'm doing an analysis that involves manipulating the wages of tax records for tax year 2018, and think I got it working but would love another quick set of eyes to check, given it's a bit complicated. Here were my steps ...
>
> 1. Advance a "stock" Calculator to 2018, based on the cps_constructor Records.
> 2. Extract the columns from the raw CPS file and store this as a dataframe.
> 3. Manipulate wages as needed.
> 4. Pass this modified dataframe as the data argument in a new Records constructor, setting start_year=2018.
> 5. Create a new Calculator object based on this new Records object.
>
> After doing this, the manipulated column from the Calculator in (5) matched that from (3), as expected. Does this look right? 

Yes, this five-step approach seems sensible.  And after the bug-fix in #2027 is merged, step 5 will work.

**Comment by MaxGhenis** [comment]
Thanks @martinholmer!
