### ISSUE TITLE
Is modified AGI calculated separately from AGI?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#2026]
I see that modified AGI is not an output variable in Tax-Calculator. Is it produced separately from AGI? I see references to it from other fields and their documentation (e.g. regarding the CTC), but the only definition I see is [here](https://github.com/open-source-economics/Tax-Calculator/blob/cab40f16d21f6402d4d86b362831d8fc69d4ab06/taxcalc/functions.py#L1222):

`modAGI = c00100  # no foreign earned income deduction to add to AGI
`

Just wanted to check there isn't another field I should be looking for. I tried searching for [magi] and [modified agi] but didn't see anything else. This is not a request for a more comprehensive MAGI calculation.

**Comment by martinholmer** [comment]
@MaxGhenis said in Tax-Calculator issue #2026:
> I see that modified AGI is not an output variable in Tax-Calculator. 

Yes, that is by design.  My understanding (which could be wrong) is that there is not single concept of "modified AGI."   Instead, different provisions in the tax law use different modifications of AGI, which is the standard output variable `c00100`.   So, for example, some provisions ignore negative AGI so that the "modified AGI" variable is sometimes called `posagi`.  What gets added to or subtracted from AGI to produce "modified AGI" can vary depending on what tax or credit is being calculated.

**Comment by MaxGhenis** [comment]
> My understanding (which could be wrong) is that there is not single concept of "modified AGI."

Some further research looks to confirm this. For example, the [H&R Block CTC guide](https://www.hrblock.com/tax-center/filing/credits/child-tax-credit/) says:

> For the purpose of this credit, your modified AGI is your AGI plus foreign earned income, if any.

While this [Turbotax AGI vs MAGI guide](https://turbotax.intuit.com/tax-tips/irs-tax-return/what-is-the-difference-between-agi-and-magi-on-your-taxes/L7kHckNS3) (apparently misleadingly) defines MAGI as a specific formula with several more deductions than AGI.

The CTC `modAGI` comment suggests it aligns with the H&R Block site, and that Tax-Calculator lacks foreign earned income data (which I also didn't see in the documentation), is that right?

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Tax-Calculator lacks foreign earned income data (which I also didn't see in the documentation), is that right?

Yes, that is correct.

**Comment by MaxGhenis** [comment]
OK this clears this up for me then, thank you @martinholmer! If other definitions of MAGI are used differently at some point (doesn't look to be the case now) I wonder if renaming the current one something like `CTCmodAGI` would help clarify, but I think we're all set for now.
