### ISSUE TITLE
2017_law.json lacks standard deduction change

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#2044]
The `2017_law.json` file (https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/2017_law.json) doesn't have a `_STD` change. Is this because we don't know what it would have been, given inflation? It seems like at least having the 2017 values (`[6350.0, 12700.0, 6350.0, 9350.0, 12700.0]`) would be useful.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> The `2017_law.json` file (https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/2017_law.json) doesn't have a `_STD` change.

The reason for its absence was explained on March 20 in #1933, which points back to a conversation that began on January 22, 2018, between @martinholmer and @evtedeschi3.

@MaxGhenis, if these prior conversations (which you seem to have not searched for) don't answer your questions, please open a new issue.

**Comment by MaxGhenis** [comment]
Thanks, interesting discussion. TIL searching GitHub for `2017_law` will not yield results with `2017_law.json`.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> searching GitHub for 2017_law will not yield results with 2017_law.json

Maybe not, but I found this discussion by searching closed issues with `STD` added to the search list.
