### ISSUE TITLE
Appropriate maximum value for _BEN_mcare_value and _BEN_mcaid_value parameters?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#2045]
Currently all the `_BEN_*_value` parameters in the `consumption.json` file have minimum-to-maximum range of [0,1].  This maximum value seems sensible for in-kind benefits that are not insurance.  So, for example, it seems reasonable to think that food stamps (from SNAP) are worth less than one hundred cents per dollar of benefits.  But in-kind insurance benefits are more complex: the in-kind nature of the insurance makes the value less than one hundred cents per dollar of benefits (just like food stamps), but the fact that the benefit is insurance leads beneficaries to value the benefits more than one hundred cents per dollar of benefit.

Below is the abstract of a recent that finds this to be true. 

<img width="1306" alt="screen shot 2018-08-07 at 1 04 09 pm" src="https://user-images.githubusercontent.com/12170745/43791833-f3d9ea1a-9a44-11e8-9a83-64ec183c5e3e.png">

I'm assuming that by "incremental value" the authors mean the value to the insured over and above the actuarial value of the insurance.  But I'm not sure, so I'd appreciate getting a PDF of the full paper from someone who has access.

**Comment by MattHJensen** [comment]
Paper attached for anyone interested. 
[w24851 .pdf](https://github.com/open-source-economics/Tax-Calculator/files/2336424/w24851.pdf)

**Comment by martinholmer** [comment]
I didn't find the NBER working paper as informative (for our CPS benefit work) as I thought it was going to be.
