### ISSUE TITLE
Switching back to unchained CPI changes tax policy parameters to pre-TCJA levels

### ISSUE THREAD

**Issue by erinmelly** [open-source-economics/Tax-Calculator#2066]
@martinholmer @andersonfrailey @MattHJensen @hdoupe @codykallen @derrickchoe 

Hi all- I'm Erin, an Econ Policy RA. I'm working on a project for Alan Viard and have encountered the following issue.

I'm looking to switch back to unchained CPI and run evaluations of tax policy parameters under TCJA law at various projected years. I tried implementing this reform by switching back to unchained CPI and evaluating the reform in 2018, however, this changes any tax policy parameters tied to CPI back to their pre-TCJA levels. This is confirmed by the fact that the difference in the total federal individual income tax liability under current law and that under the unchained CPI reform evaluated in 2018 is such a large magnitude (nearly 30 billion) that it cannot just be the CPI adjustment being altered.

The reform I'm modelling is as follows:
`reform = {
    2017: {
        '_cpi_offset': [0]
    }
}`

**Comment by martinholmer** [comment]
@erinmelly,  Your verbal description of what policy reform you want to implement is a little vague in #2066.

Have you read the FAQ in issue #1830?  Read the whole FAQ, but the first question (**How can I use pre-TCJA policy as the baseline?**) may be particularly helpful.

If you still have problems after reading the FAQ, add a comment here saying **in words** exactly what kind of policy reform you want to specify.

**Comment by codykallen** [comment]
I believe @erinmelly wants to model what the TCJA would be like without the chained CPI indexing. Implementing the indexing change for the TCJA involved setting 
`2017: {"_CPI_offset": -0.0025}`
However, if one now tries to reverse this provision (and only this provision), it requires setting
`2017: {"_CPI_offset": 0}`
I believe @erinmelly is mentioning that making this change (setting the CPI offset to zero) eliminates some of the other changes that the TCJA made to other provisions. For example, it may change the standard deduction from the 2018 values as proscribed in the TCJA to the 2018 values as would have occurred if the 2017 values had increased due to inflation.

**Comment by martinholmer** [comment]
@codykallen said in issue #2066:
> I believe @erinmelly wants to model what the TCJA would be like without the chained CPI indexing. Implementing the indexing change for the TCJA involved setting
>```
>2017: {"_CPI_offset": -0.0025}
>```
>However, if one now tries to reverse this provision (and only this provision), it requires setting
>```
>2017: {"_CPI_offset": 0}
>```

@erinmelly, is @codykallen's interpretation of the reform you want to specify correct?  

If so, you need to read carefully the FAQ in #1830 and the `2017_law.json` file it points to.   Reading that JSON reform file will show you why this statement:
> if one now tries to reverse this [chained CPI indexing] provision (and only this provision), it requires setting
>```
>2017: {"_CPI_offset": 0}
>```
is not correct.

**Comment by erinmelly** [comment]
@martinholmer , yes @codykallen 's interpretation of the reform I am trying to implement is correct. going through the FAQ now, thanks.

**Comment by martinholmer** [comment]
@erinmelly,  After reading the FAQ, also look at reform "58" in the `taxcalc/tests/reforms.json` file.

**Comment by martinholmer** [comment]
@erinmelly,  Its been a couple of days since the last comments were made in issue #2066.
Do you have any other questions about how to "undo" the CPI-offset provision of the TCJA reform?

**Comment by erinmelly** [comment]
@martinholmer yes thank you. @andersonfrailey helped figure out that when you include the CPI offset in a reform, all of the CPI indexed parameter values are recalculated from 2018 on based on their 2017 values. So it effectively cancels out all TCJA reforms made to CPI indexed parameters. In order to actually model the TCJA without chained CPI, you need to do two separate reforms: the first just to repeal chained CPI, and the second containing all provisions of the TCJA except chained CPI.

**Comment by martinholmer** [comment]
@erinmelly said:
>  @andersonfrailey helped figure out that when you include the CPI offset in a reform, all of the CPI indexed parameter values are recalculated from 2018 on based on their 2017 values.  So it effectively cancels out all TCJA reforms made to CPI indexed parameters. In order to actually model the TCJA without chained CPI, you need to do two separate reforms: the first just to repeal chained CPI, and the second containing all provisions of the TCJA except chained CPI.

So, you seem to be saying that the `2017_policy.json` reform file on the Tax-Calculator website is incorrect.
Otherwise, why did you have to implement "two separate reforms"?

**Comment by martinholmer** [comment]
@erinmelly said in issue #2066:
> In order to actually model the TCJA without chained CPI, you need to do two separate reforms: the first just to repeal chained CPI, and the second containing all provisions of the TCJA except chained CPI.

At first I misread your comment.  Yes, given what you want to do, the above procedure makes sense.

If you have other questions, raise them in a new issue.  I'm going to close this issue because it seems to have resolved itself.
