### ISSUE TITLE
Add CI (Travis / Circle CI?)

### ISSUE THREAD

**Issue by Casyfill** [open-source-economics/Tax-Calculator#2074]
shall we add any kind of CI to the project? that will help pushing it forward.
I'd also propose to add `black` for auto-code-formatting. What do you think?

**Comment by hdoupe** [comment]
I think we have some forms of CI in the project. @martinholmer can speak more to that.

I've tried Black out for some smaller projects over the last week. I find it annoying to think about formatting my code while I'm writing it or to go back and do "format fix-up" type commits. So, it's been nice to have Black take care of that for me.

**Comment by martinholmer** [comment]
@Casyfill, Thanks for your interest in the Tax-Calculator project.
Here are my answers to your questions.
> shall we add any kind of CI to the project? 

As you can see from the Tax-Calculator repository, we already use CI tools.

> I'd also propose to add black for auto-code-formatting. What do you think?

After a quick look at black, I'm not interested.

**Comment by MattHJensen** [comment]
@Casyfill, were you thinking of something other than / beyond our use of TravisCI re CI? 

My instinct re `black` is the same as @martinholmer's. We have fairly consistent code style and our developers are used to that style and the tools they use to achieve it. I think there would have to be very strong reasons for Tax-Calculator to make a change as substantial as adopting `black`, and right now I don't see those strong reasons.

**Comment by Casyfill** [comment]
Thanks, got it!
and sorry re CI - didn't find the badge, and for some reason failed to check commits - it looks great as it is now. Closing, thank you for your time!

**Comment by MattHJensen** [comment]
@Casyfill, It would be cool if we reported build status and test coverage badges in the README. I for one would welcome an easy PR on that front.
