### ISSUE TITLE
User-friendly Tax-Calculator changelog

### ISSUE THREAD

**Issue by donboyd5** [open-source-economics/Tax-Calculator#2088]
My first "issue" so if I'm doing it wrong, pls let me know.

On 2018-09-07 @MattHJensen asked me if I: 

> have any interest in contributing a user-friendly Tax-Calculator changelog, starting with 0.20.3, which was released yesterday? Tax-Calculator's RELEASES.md is targeted towards developers rather than users. It might make sense to combine the user-friendly changelog and RELEASES.md in one document...It would be ideal if each entry of the changelog, or some semi-self-contained partition of each entry, could fit in a 280 character tweet.

@MattHJensen suggested that I reach out to @martinholmer and @andersonfrailey on this.

I said sure, then promptly did nothing.

I'll assert an approach and you can tell me if there is a better one:

1. It would be great if you give me any constructive advice you have upfront but I will proceed in any event.

2. In the interest of keeping the ball in motion now that I've started it, I'll plan to proceed as follows unless I hear from you (@martinholmer and @andersonfrailey) otherwise:
a) I'll start, and link to, a Google doc that has both the changelog for 0.20.3 and my "user-friendly" short interpretations.
b) I will both have to understand the changes, and then explain them in lay terms. I may have some questions for you. If so, I'll put them in the Google doc.
c) Once it seems like I've got the substance and tone right, we can fold the Google doc into its own version of Releases.md, or do something else that you think makes more sense.

3. @MattHJensen said I could state my suggestions about how to approach this in my first "PR" but I'm such a github greenhorn that I've never done one. If you need me to do a PR, please tell me so and I'll figure it out; otherwise, I'll go ahead and start that Google doc.

Thanks. I'll be back. Please offer comments/advice if you have them.

**Comment by MattHJensen** [comment]
@donboyd5, starting with a google doc makes sense to me. Let's consider file naming and placement after settling on an approach to the content. Thanks @donboyd5!

**Comment by martinholmer** [comment]
@donboyd5,  as part of getting Tax-Calculator more compliant with Policy Simulation Library criteria, I've made an effort at adding a user-oriented changelog in pull request #2134.   I would appreciate any suggestions for improving my initial effort.  It seemed as if it would make more sense for me to draft the descriptions of changes in the old releases because I'm going to be responsible for updating the user-oriented changelog going forward.

**Comment by martinholmer** [comment]
Initial effort to resolve issue #2088 is in pull request #2134.
Comments and suggestions for improvements to the `CHANGES.md` text are welcome in a new issue.
