### ISSUE TITLE
Possible to do a multiyear diagnostic table in the API with behavioral responses?

### ISSUE THREAD

**Issue by evtedeschi3** [open-source-economics/Tax-Calculator#2125]
I'm playing around with `recipe02.py` and was curious: is there a way to return a multiyear diagnostic table when behavioral responses are active? I tried returning `calc2br.diagnostic_table(5)` but the output is exactly the same as under static assumptions, and `df2br.diagnostic_table(5)` returns a "AttributeError: 'DataFrame' object has no attribute 'diagnostic_table'" error.

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> I'm playing around with `recipe02.py`

Thanks so much for trying out the new Behavioral-Responses package `behresp`.

Your question is an excellent one and has prompted an improvement in Tax-Calculator that will make it easier to do what you want to do.  The new `recipe02.py` recipe and its `recipe02.res` results illustrate how to do what you want to do.  But to use this new approach, you must install the `taxcalc` package for Tax-Calculator 0.23.2, which should be available soon.

**Comment by martinholmer** [comment]
@evtedeschi3,  The newly expanded `recipe02.py` creates three diagnostic tables using the low-level `create_diagnostic_table` utility function like this:
```
dvar_list1 = list()
year_list1 = list()
dvar_list2 = list()
year_list2 = list()
dvar_list3 = list()
year_list3 = list()
for year in range(cyr, cyr + num_years):
    calc1.advance_to_year(year)
    calc2.advance_to_year(year)
    # exclude reform's behavioral responses by passing empty dictionary
    df1, df2sa = behresp.response(calc1, calc2, dict())
    dvar_list1.append(df1)
    year_list1.append(year)
    dvar_list2.append(df2sa)
    year_list2.append(year)
    # include reform's behavioral responses by passing meaningful dictionary
    _, df2br = behresp.response(calc1, calc2, behresp_dict)
    dvar_list3.append(df2br)
    year_list3.append(year)
dtable1 = create_diagnostic_table(dvar_list1, year_list1)
dtable2 = create_diagnostic_table(dvar_list2, year_list2)
dtable3 = create_diagnostic_table(dvar_list3, year_list3)
```
But the Calculator method `diagnostic_table` still works (and will always work) for static analysis.  So, a more succinct recipe fragment would be this:
```
dtable1 = calc1.diagnostic_table(num_years)
dtable2 = calc2.diagnostic_table(num_years)
dvar_list3 = list()
year_list3 = list()
for year in range(cyr, cyr + num_years):
    calc1.advance_to_year(year)
    calc2.advance_to_year(year)
    _, df2br = behresp.response(calc1, calc2, behresp_dict)
    dvar_list3.append(df2br)
    year_list3.append(year)
dtable3 = create_diagnostic_table(dvar_list3, year_list3)
```
Which one do you think would be more helpful in `recipe02.py`?   Now that you see how things work in Tax-Calculator 0.23.2, is there a better way to illustrate doing what you want to do?

**Comment by evtedeschi3** [comment]
Beautiful! Doubly impressive that you did this over the Thanksgiving holiday!

I ran the new `recipe02.py` just as is. The single year comparisons output fine. But then when it gets to the new multiyear tables, I get the following error:

```
TypeError: list indices must be integers or slices, not str
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-63-7aadc664516e> in <module>()
     71     dvar_list3.append(df2br)
     72     year_list3.append(year)
---> 73 dtable1 = create_diagnostic_table(dvar_list1, year_list1)
     74 dtable2 = create_diagnostic_table(dvar_list2, year_list2)
     75 dtable3 = create_diagnostic_table(dvar_list3, year_list3)
~/anaconda3/lib/python3.6/site-packages/taxcalc/utils.py in create_diagnostic_table(vdf, year)
    648         return odict
    649     # tabulate diagnostic table
--> 650     odict = diagnostic_table_odict(vdf)
    651     dframe = pd.DataFrame(data=odict, index=[year], columns=odict.keys())
    652     dframe = dframe.transpose()
~/anaconda3/lib/python3.6/site-packages/taxcalc/utils.py in diagnostic_table_odict(recs)
    579         odict = collections.OrderedDict()
    580         # total number of filing units
--> 581         wghts = vdf['s006']
    582         odict['Returns (#m)'] = round(wghts.sum() * in_millions, 2)
    583         # adjusted gross income
TypeError: list indices must be integers or slices, not str
```

**Comment by martinholmer** [comment]
@evtedeschi3 said in T-C issue #2125:
> Beautiful! Doubly impressive that you did this over the Thanksgiving holiday!

Actually not so impressive because here in Canada Thanksgiving was last month.
This past week has been just a regular work week here.

Sorry to hear that the new `recipe02.py` did not work for you on your computer.
It does work on my computer with the newest taxcalc package for T-C release 0.23.2.

My guess (based on the information you supplied) is that you are inadvertently still using an earlier version of Tax-Calculator.  I'm guessing that because of this traceback information you supplied:
```
create_diagnostic_table(vdf, year)
    648         return odict
    649     # tabulate diagnostic table
--> 650     odict = diagnostic_table_odict(vdf)
    651     dframe = pd.DataFrame(data=odict, index=[year], columns=odict.keys())
    652     dframe = dframe.transpose()
~/anaconda3/lib/python3.6/site-packages/taxcalc/utils.py in 
```
The above code is from an earlier version of Tax-Calculator.  In Tax-Calculator 0.23.2 the signature of the utility function `create_diagnostic_table` is this:
```
create_diagnostic_table(dframe_list, year_list):
```
and the statement the calls the `diagnostic_table_odic` function looks like this:

<img width="1180" alt="screen shot 2018-11-24 at 10 30 02 am" src="https://user-images.githubusercontent.com/12170745/48969951-fdccde80-efd3-11e8-8967-ebb8f7185220.png">

What should you do?  The information you supplied shows you are running the recipe using an older version of the taxcalc package.  You need to upgrade to the newest version by doing this:
```
$ conda update -c PSLmodels taxcalc
```

Notice the use of the `PSLmodels` channel rather than the `ospc` channel.  That is critical because the `ospc` channel is being phased out and has none of the packages for the newest Tax-Calculator releases (see details below).

Let me know if getting the taxcalc package up to date solves your problem.


```
iMac:~ mrh$ conda search -c ospc taxcalc
Loading channels: done
# Name                  Version           Build  Channel             
taxcalc                  0.18.0          py27_0  ospc                
taxcalc                  0.18.0          py36_0  ospc                
taxcalc                  0.19.0          py27_0  ospc                
taxcalc                  0.19.0          py36_0  ospc                
taxcalc                  0.20.0          py27_0  ospc                
taxcalc                  0.20.0          py36_0  ospc                
taxcalc                  0.20.1          py27_0  ospc                
taxcalc                  0.20.1          py36_0  ospc                
taxcalc                  0.20.2          py27_0  ospc                
taxcalc                  0.20.2          py36_0  ospc                
taxcalc                  0.20.3          py27_0  ospc                
taxcalc                  0.20.3          py36_0  ospc                
taxcalc                  0.21.0          py36_0  ospc                
taxcalc                  0.22.0          py36_0  ospc                
taxcalc                  0.22.1          py36_0  ospc                
taxcalc                  0.22.2          py36_0  ospc                
iMac:~ mrh$ conda search -c pslmodels taxcalc
Loading channels: done
# Name                  Version           Build  Channel             
taxcalc                  0.23.0          py36_0  pslmodels           
taxcalc                  0.23.1          py36_0  pslmodels           
taxcalc                  0.23.2          py36_0  pslmodels           
```

**Comment by evtedeschi3** [comment]
Ha, in some ways, the problem was even stupider than that on my part. I had updated `taxcalc`, but forgot to restart my Python session. LOL. All works well now. Thanks for all your hard work in Canada :)

**Comment by evtedeschi3** [comment]
Ah, sorry, and to answer your question above:

@martinholmer asked:
> Which one do you think would be more helpful in recipe02.py? Now that you see how things work in Tax-Calculator 0.23.2, is there a better way to illustrate doing what you want to do?

Unless you think there is pedagogical value to having the longer code, I think succinct is the better way to go.

**Comment by martinholmer** [comment]
@evtedeschi3 said in T-C issue #2125
> Unless you think there is pedagogical value to having the longer code, I think succinct is the better way to go.

OK.  Thanks for the feedback.  
The next Tax-Calculator release will change the code in Cookbook `recipe02.py` to be more succinct.
