### ISSUE TITLE
Produce ASCII output file

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#251]
We should have a function that can produce (at least) an ASCII output table with uniform vertical columns of numbers. Taxpayers (recid) should be in columns and taxpayer characteristics should be in rows. 

We should be able to specify a subset of taxpayers, either by specifying recid or, ideally, also by applying some screen. 

ASCII is useful because it makes for nice pasting into github and it is what Dan works with. 

Example from Dan: 

var            R1          R2          R3          R4          R5          R6

E00100     1854000     1061000      826100      664300      561400      359200
c00100     1286051     1022766      855650      663613      580160      354277
E00200      409900      261500      159900           0       47360           0
E00300      271200      156700      538500      221100      200400       23140
E00400       11270      707900       18910       94110      379500       40120
E00600      135000      777600      236600      214500      340100       32480
E00650      134600      529800      187700      132900      158800       15900
c00650      134600      529800      187700      132900      158800       15900
E00700           0           0         136           0           0           0
E00900           0      145600           0           0           0           0
E01000      161000       -3000       -3000      237700       -3000      307300
c01000      161056       -3000       -3000      237000       -3000      307000
E01200           0           0           0      264200     -108200           0
E01400       60000           0           0           0           0           0
E01500       19800           0           0           0           0           0
E01700        1637           0           0           0           0           0
E02000      233500     -279900      -76140     -282800      103500       -8343
E02400       47370           0           0       11840           0           0
E02500       40270           0           0       10060           0           0
c02500       40265           0           0       10064           0           0
c02650     1312558     1058500      855996      664064      580160      354277
c02900       26507       35734         346         451           0           0
E03240           0           0           0         451           0           0
E03260        7877        8274         346           0           0           0
E03270       18630           0           0           0           0           0
E03300           0       27460           0           0           0           0
c04250        1000        1000        1000        1000        1000        1000
E04470     1313000      802900      768300      397500      653200      365500
c04470     1353119      805154      740577      386260      627725      325871
c04500     -811208     -285181     -250009       66170     -332230     -304211
E04600        4666        4666       11670        4666       11670       11900
c04600        4667        4667       11667        4667       11667       12165
E04800      535900      253700       43850      262100           0           0
c04800           0      212946      103406      272686           0       16241
E05100      115300       28290           0       29550           0           0
c05100           0       22177        5746       31138           0           0
E05200      159200       62450        5779       65220           0           0
c05200           0       49001       18539       68715           0        1634
c05750           0       22177        5746       31138           0           0
E05800      300000      195800      150000      116000       41180       23180
c05800      153592      184762      165775      119049       85468       29719
E06000      246900           0           0           0           0           0
E06200       46610           0           0           0           0           0
E06300       60210           0           0           0           0           0
E06500      300000      181800      145500      104400       41180       22770
c06500      153592      170712      156841      102926       85468       28897
c07100           0       14050           0        7079           0           0
E07150           0       14050        4467       11600           0         411
c07150           0       14050        4467       11601           0         411
E07300           0       14050           0        7079           0           0
c07300           0       14050           0        7079           0           0
c08795      153592      170712      165775      111970       85468       29719
E08800      300000      181800      145500      104400       41180       22770
c08800      153592      170712      161308      107448       85468       29308
c09200      169342      187262      166467      111970       85468       29719
E09400       15750       16550         692           0           0           0
The SAS System                                                                                      11:37 Friday, April 17, 2015   2

 var            R1          R2          R3          R4          R5          R6

E09600      184700      167500      150000       86430       41180       23180
c09600      153592      162585      160029       87911       85468       29719
E10300      322400      198300      148000      104400       41180       22770
c10300      169342      182866      162000      107448       85468       29308
E10605      362400      916300      470100      270100      309300           0
E10700      125400       83900           0          52        4032           0
E10900      237000      828000      470100      270000      305200           0
E11400           0        4396           0           0           0           0
E11550           0           0        4467        4522           0         411
E11900      -36120     -718000     -322100     -165700     -268100       23500
E12000       36120      136300      187200      120000      268100           0
E12200        3853           0           0           0           0         732
c15200        2100           0           0        2100           0           0
c15250        1000        1000        1000        1000        1000        1000
c17750       96454       76707       64174       49771       43512       26571
c18300      670660      504100      195900      186060      146720      227440
E18425      638000      466900      185200      161400      105600      130100
E18500       32660       37200       10700       24660       41120       97340
E19200      107500           0      142400       13840      113100       65380
c19200      107500           0      142400       13840      113100       65380
E19700      586200       59520       16430       11160      154600       10200
c19700      586210       59527       16437       11159      154600       10200
E19800      574700       59220       16420        2772      154600       10200
E20100       11510         307          17        8387           0           0
c20100       11500         300          10        8388           0           0
E20400       15490      270600      409900      193500      229100       31870
c20400       15490      270600      409900      193500      229100       31870
E20550           0           0        6193         230           0           0
E20600        8620       10600           0           0        7500        3950
c20750       25721       20455       17113       13272       11603        7086
E20800           0      249300      393400      180200      217900       24690
c20800           0      250145      392787      180228      217497       24784
E21040       16940        9013        6662        5043        4015        1992
c21040       11251        8618        6947        5027        4192        1933
c21060     1364370      813772      747524      391287      631917      327804
E22250        6656    -3092000    -1039000    -1090000    -1063000    -1737000
E22320      155000      196600       51550      537300       15720     -622800
E22370         169        4103        2068        1516       15120        2520
E23250      154400     -613900      512700     1327000    -1051000     2044000
c23650      161056    -3705900     -526300      237000    -2114000      307000
c24505           0      529800      187700      132900           0       15900
c24510           0           0           0      237000           0      307000
e24510           0           0           0           0           0           0
E24515      117400           0           0           0           0           0
c24515           0           0           0           0           0           0
E24516      289000      529800      187700      370600           0           0
c24516      154400      529800      187700      369900           0      322900
c24517           0      529800      187700      369900           0      322900
e24517           0           0           0           0           0           0
E24518           0           0           0           0           0           0
c24520           0           0           0           0           0           0
e24520           0           0           0           0           0           0
c24530           0       65100       65100       65100           0       16241
e24530           0           0           0           0           0           0
c24532           0           0           0           0           0           0
e24532           0           0           0           0           0           0
The SAS System                                                                                      11:37 Friday, April 17, 2015   3

 var            R1          R2          R3          R4          R5          R6

c24533           0           0           0           0           0           0
e24533           0           0           0           0           0           0
c24534           0       65100       65100       65100           0       16241
e24534           0           0           0           0           0           0
E24535           0           0           0           0           0           0
c24535           0           0           0           0           0           0
c24540           0           0           0           0           0           0
c24550           0           0           0           0           0           0
e24550           0           0           0           0           0           0
E24560       60210           0           0           0           0           0
c24560           0           0           0           0           0           0
c24567           0           0           0           0           0           0
E24570           0           0           0           0           0           0
c24570           0           0           0           0           0           0
c24580           0       22177        5746       31138           0           0
e24580           0           0           0           0           0           0
c24581           0           0           0           0           0           0
e24581           0           0           0           0           0           0
e24583           0           0           0           0           0           0
c24585           0           0           0           0           0           0
e24585           0           0           0           0           0           0
c24587           0           0           0           0           0           0
e24587           0           0           0           0           0           0
c24590           0           0           0           0           0           0
e24590           0           0           0           0           0           0
c24595           0           0           0           0           0           0
e24595           0           0           0           0           0           0
c24597           0      147846       38306      207586           0           0
e24597           0           0           0           0           0           0
E24598       25750       28290           0       29550           0           0
c24598           0       22177        5746       31138           0           0
c24600           0           0           0           0           0           0
e24600           0           0           0           0           0           0
c24605           0           0           0           0           0           0
e24605           0           0           0           0           0           0
c24610           0           0           0           0           0           0
e24610           0           0           0           0           0           0
E24615       29340           0           0           0           0           0
c24615           0           0           0           0           0           0
e25350           0           0       53740        3684           6           0
e25470           0           0        3668           0           0           0
e25700           0           0       38570        3321           6           0
E25820           0           0          22           0           0           0
E25850           0           0       38930        3321           6           0
E25860           0           0          22           0           0           0
E25920           0      192500      182800       21370       15220           0
E25940           0           0        8526       19430      118700           0
E25960      286100       87490           0      285800           0        8343
E25980      312400          30           0        1646           0           0
E26100       11000           0           0           0           0           0
E26160           0           0         822           0           0           0
E26170           0           0       11540           0           0           0
E26180      164100           0           0           0           0           0
E26190      382300           0       51180           0           0           0
E26270      233500     -279900     -112400     -286100      103500       -8343
E26400           0           0        2688           0           0           0
The SAS System                                                                                      11:37 Friday, April 17, 2015   4

 var            R1          R2          R3          R4          R5          R6

E30400        7761      102000           0           0           0           0
E30500        7761           0           0           0           0           0
c32880      204950      203550       79950           0       23680           0
c32890      204950      203550       79950           0       23680           0
E53280           0           0         225          77           0           0
E53410           0           0         452        7315           0           0
E58950       60450       42550      140100      152800      113100       33540
E60000      540600      258400       57850      266800      -91750       -6315
c60000     -811208     -285181     -250009       66170     -332230     -304211
c60130       11251        8618        6947        5027        4192        1933
c60220           0         845        -613          28        -403          94
c60240      670660      504100      195900      186060      146720      227440
c60260           0           0         136           0           0           0
E61850      652600      761900      619000      379500      392200      273500
e62000           0           0           0           0           0           0
E62100     1176000     1011000      670200      641300      296500      265200
c62100      573621      971752      726575      651897      340155      300059
c62600           0           0           0           0       22411       32435
e62600           0           0           0           0           0           0
c62700      573621      971752      726575      651897      317744      267624
E62720      171700      529800      187700      370600      158800      323200
c62720           0      529800      187700      369900           0      322900
E62730      117400           0           0           0           0           0
c62730      117400           0           0           0           0           0
E62740      289000      529800      187700      370600      158800      323200
c62740      117400      529800      187700      369900           0      322900
c62745      124242      120247      147385       75459       85468           0
c62746           0           0           0           0           0           0
e62746           0           0           0           0           0           0
c62747           0           0           0           0           0           0
e62747           0           0           0           0           0           0
c62748           0           0           0           0           0           0
e62748           0           0           0           0           0           0
c62749           0           0           0           0           0           0
c62750           0           0           0           0           0           0
c62755           0       69705       18390       45720           0       30379
c62760           0           0           0           0           0           0
c62770       29350           0           0           0           0           0
c62780      157114      268591      199941      179031       85468       71435
c62800      153592      189952      165775      121179       85468       30379
E62900           0       19240           0        9209           0         660
c62900           0       19240           0        9209           0         660
c63000      153592      170712      165775      111970       85468       29719
c63100           0        8127        5746       24059           0           0
c63200      153592      162585      160029       87911       85468       29719
c64446     1286051     1022766      855650      663613      580160      354277
c64447     1136051      872766      705650      513613      430160      204277
c64448           1           1           1           1           1           1
E65300           0      192500       58990       28640           0           0
E65400           0       82570      939700       33510           0        6636
E68000           0      192500       58990       28640           0           0
e82040           0           0           0           0           0           0
e82041           0           0           0           0           0           0
c82041           .           .           .           .           .           .
e82042           0           0           0           0           0           0
e82043           0           0           0           0           0           0
The SAS System                                                                                      11:37 Friday, April 17, 2015   5

var             R1          R2          R3          R4          R5          R6

E82200       76480           0        8211        4522       13780           0
c82200           .           .           .           .           .           .
c82880           0           0      159900           0       47360           0
e82880           0           0           0           0           0           0
e82882           0           0           0           0           0           0
c82885           0           0      151400           0       38860           0
c82890           0           0       22710           0        5829           0
c82900           0           0           0           0           0           0
e82900           0           0           0           0           0           0
c82905           0           0           0           0           0           0
e82905           0           0           0           0           0           0
c82910           0           0           0           0           0           0
c82915           0           0           0           0           0           0
e82915           0           0           0           0           0           0
c82920           0           0           0           0           0           0
c82925           0           0           0           0           0           0
c82930           0           0           0           0           0           0
c82935           0           0           0           0           0           0
c82937           0           0           0           0           0           0
c82940           0           0           0           0           0           0
e82940           0           0           0           0           0           0
c87570      116000      116000      116000      116000      116000      116000
c87580     1286051     1022766      855650      663613      580160      354277
c87600       20000       20000       20000       20000       20000       20000
AGIR1           32          31          30          30          30          29
EFI              0           1           0           0           0           0
ELECT            2           0           0           1           2           2
F2441            0           0           0           0           0           0
F3800            0           0           1           1           0           0
F6251            1           1           1           1           1           1
F8582            0           1           1           1           0           1
F8606            0           0           2           0           0           0
FDED             1           1           1           1           1           1
FLPDMO          12          12          12          12          12          12
FLPDYR        2008        2008        2008        2008        2008        2008
MARS             2           2           2           2           2           2
N24              0           0           3           0           2           2
P25350           0           0       53740        3684           6           0
P25470           0           0        3668           0           0           0
P25700           0           0       38570        3321           6           0
PREP             1           1           1           1           1           1
RECID       191552      291857      325246      348825      354668      375918
S001         60215      100922      113482      121932      123836      131069
S006           988        1026         988        1014        1044         988
S008          5638        1182        5638       11189        2436        5638
S009         45529        3590       45529       93022       15571       45529
SCHB             1           1           1           1           1           1
SCHCF            0           1           0           0           0           0
SCHE             1           1           1           1           1           1
TXRT           330         150           0         150           0           0
TXST             7           7           0           7           0           0
WSAMP           21         403          21         421           4          21
XFPT             1           1           1           1           1           1
XFST             1           1           1           1           1           1
XOCAH            0           0           3           0           3           3
XTOT             2           2           5           2           5           5
The SAS System                                                                                      11:37 Friday, April 17, 2015   6

var                  R1          R2          R3          R4          R5          R6

_addamt          659409      496327      188340      181061      142125      225601
_agep                50          50          50          50          50          50
_ages                50          50          50          50          50          50
_agierr          567950       38234      -29550         687      -18760        4923
_alminc          573621      971752      726575      651897      317744      267624
_amtded          670660      504945      195287      186088      146317      227534
_avail           153592      170712      165775      111970       85468       29719
_cglong          154400    -3705900     -526300      237000    -2114000      307000
_cmbtp           -18720        8513       29898       13283       27695       21362
_ctc2                 0       14050           0        7079           0           0
_ctcagi         1286051     1022766      855650      663613      580160      354277
_ctctax          153592      170712      165775      111970       85468       29719
_dedmin         1091496      651017      598019      313029      505533      262244
_dedpho           33753       25854       20841       15080       12576        5800
_dispc                0           0           0           0           0           0
_dwks21               .      212946      103406      272686           .       16241
_dwks26               .      529800      187700      369900           .      322900
_dwks28               .      316854       84294       97214           .      306659
_dwks31               .      212946      103406      272686           .       16241
_dwks9                .           0           0      237000           .      307000
_dy              578470     1642200      794010      767410      920000      403040
_earned          409900      407100      159900           0       47360           0
_earnsplit            1           1           1           1           1           1
_fica             15606       15606       15606           0        7246           0
_flpdym          200812      200812      200812      200812      200812      200812
_hasgain              1           1           1           1           1           1
_itemlimit            2           2           2           2           2           2
_lim30            11510           .           .           .           0           .
_lim50           574700           .           .           .      154600           .
_limitratio      160950      160950      160950      160950      160950      160950
_modagi         1297321     1730666      874560      757723      959660      394397
_nbertax         169342      187262      166467      111970       85468       29719
_nctcr                0           0           3           0           2           2
_ngamty          456221      441952      538875      281997      317744           0
_num                  2           2           2           2           2           2
_numextra             2           0           0           2           0           0
_othded          -40119       -2254       27723       11240       25475       39629
_othertax         15750       16550         692           0           0           0
_othtax               0          10           0          20           0           0
_payments             0        4396        4467        4522           0         411
_phase2          160950      160950      160950      160950      160950      160950
_phbuy           150000      150000      150000      150000      150000      150000
_posagi         1286051     1022766      855650      663613      580160      354277
_prexmp            7000        7000       17500        7000       17500       17500
_puf                  1           1           1           1           1           1
_regcrd               0       14050           0        7079           0           0
_sep                  1           1           1           1           1           1
_sey                  0      145600           0           0           0           0
_sit             638000      466900      185200      161400      105600      130100
_statax          638000      466900      185200      161400      105600      130100
_tamt2            29350       69705       18390       45720           0       30379
_taxbc                0       22177        5746       31138           0           0
_taxinc               0      212946      103406      272686           0       16241
_taxspecial           .       22177        5746       31138           .           0
_totald         1849334     1056334      814430      659634           .           .
_txp                  2           2           2           2           2           2
The SAS System                                                                                      11:37 Friday, April 17, 2015   7

var                  R1          R2          R3          R4          R5          R6

_txpyers              2           2           2           2           2           2
_val_rtbase           8           8           8           8           8           8
_val_rtless           8           8           8           8           8           8
_val_ymax         10160       10160       10160       10160       10160       10160
_xtot                 2           2           5           2           5           5
_xyztax               0       49001       18539       68715           0        1634
_ymod           1280741     1730666      874560      754030      959660      394397
_ymod1          1272293     1058500      855996      654000      580160      354277
_ymod2             8448      672166       18564       99579      379500       40120
_ymod3                0           0           0         451           0           0
_ywossbc        1245786     1022766      855650      653549      580160      354277
_ywossbe        1813730     1061000      826100      654240      561400      359200
_amt15pc              0      464700      122600      304800           0      202524
_amt25pc         117400           0           0           0           0           0
_c21060         1364370      813772      747524      391287      631917      327804
i                   170         170         170         170         170         170
p62720                .           .           .           .           .           .
p62900                .           .           .           .           .           .
recno             60215      100922      113482      121932      123836      131069
_sey9235              0      134462           0           0           0           0
soiyr              2008        2008        2008        2008        2008        2008
weight               10          10          10          10          10          10
x02900            26507       35734         346         451           0           0
x04500           744140      502793      365082      211183      284665      332617
x04600               33          33          33          33          33          30
x05750                0       22177        5746       31138           0           0
x07100                0       14050           0        7079           0           0
x20100            11500         300          10        8388           0           0
x60220                0     -249300     -393400     -180200     -217900      -24690
x62100           573621      971752      726575      651897      340155      300059
x62720                0           0           0           0           0           0
x62730                0           0           0           0           0           0
x62740                0           0           0           0           0           0
x62746                0           0           0           0           0           0
x62748                0           0           0           0           0           0
y62745           175000      175000      175000      175000      175000      175000
year               2008        2008        2008        2008        2008        2008

**Comment by MattHJensen** [comment]
Hmm, not so sure about the nice pasting into github now ^^

**Comment by feenberg** [comment]
Notice that whatever program you used to paste into the email, replaced 
all multiple spaces with single spaces. Maybe it would work better as an 
attachment?

dan

**Comment by zrisher** [comment]
Github markdown supports tables if you use pipes `|` as separators:
https://help.github.com/articles/github-flavored-markdown/#tables

**Comment by xiyuw123** [comment]
testing

'''
a     b     c     d     e
f      g     h     i      j
'''

**Comment by MattHJensen** [comment]
Closing this issue as we have had no trouble effectively sharing output lately.
