### ISSUE TITLE
Should we reset zeroed records attributes when we increment year

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#272]
In records.py, we set a number of records attributes to arrays of zeroes when we initialize a records object; in particular, we set to zeroes the non-puf variables and the calculated 'c' variables. 

The question is, should we reset these arrays to zero every time we increment year, or just when we initialize the records object? 

By not resetting them every year, we create a breeding ground for bugs, e.g., #262: 
 
> In the first year, AGI is greater than the NIIT threshold, so NIIT is assigned to a non-zero value. In the second year, AGI is less than the NIIT threshold, so NIIT is neither reassigned nor is it zero-- rather it would be the value that it was assigned in the first year. This is a bug.

I believe Amy ran into a similar situation yesterday, which she caught before committing. 

In the discussion of #262, @feenberg recommended that he finds it useful to zero every year. If we did that, it would raise the follow up question of whether we should get rid of many `else var = 0` statements that would be made nonessential. 

I am unsure of any downsides to zeroing variables every year, rather than just upon initialization. 

cc @Amy-Xu and @talumbau for feedback.

**Comment by feenberg** [comment]
The data available changes from year to year. If an E-value is missing in 
year n, but present in n-1, does the last value in year n-1 get retained 
for each record in year n? That would happen in SAS and would be a serious 
error.

dan

**Comment by MattHJensen** [comment]
> The data available changes from year to year. If an E-value is missing in
year n, but present in n-1, does the last value in year n-1 get retained
for each record in year n? 

@feenberg, I don't believe we have encountered this issue yet as we are only using one data file right now. We should be able to choose the behavior if we do start using more than one data file.

**Comment by martinholmer** [comment]
Merged pull request #837 resolved issue #272 by showing that the current tax-calculating code handles changing CALCULATED_VARS correctly from one call of Calculator.calc_all() to the next.
