### ISSUE TITLE
taxpayers might not optimize their itemization decision

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#282]
From Amy: 

Currently many people choose to itemize their deductions for regular tax because their could deduct more than standard deduction. But they might end up paying AMT, which adds back itemized deduction in the tax base, and get penalized for choosing this higher itemized deduction. In other words, they should have chosen standard deduction even it's smaller than itemized deduction, because standard deduction is not included in AMT base and these taxpayers would therefore have a lower tax liability. This might explain why many taxpayers have lower OSPC tax in the haircut scenario. Because of the haircut, they switched from itemized deduction to standard deduction, reduced their AMT tax base and ended up paying less tax. @MattHJensen is about to do more analysis on this group of tax payers to confirm our hypothesis.

Here're some useful ipython notebook commands for testing:
1) To get the record 100 IDs of taxpayers with lower OSPC tax `calc2.records.RECID[(calc2.records._ospctax-calc1.records._ospctax)<-0.01][:100]`
2) To retrive taxpayer informations from notebook `calc2.records.c00100[calc2.records.RECID==12345]`

**Comment by MattHJensen** [comment]
@Amy-Xu I generated the graph that we discussed, and it looks like what we expected with the first taxpayer I have tried (RECID = 958 -- his _ospctax is 66432 with ID_StateLocalTax_HC == 0 and 66091 with ID_StateLocalTax_HC == 1). I think this supports our hypothesis that the taxpayer would have been better off filing the standard deduction. His tax goes up and up as the haircut is added until the point where his itemized deductions are smaller than standard deduction, then he switches to the standard deduction and his tax falls and then remains steady. 

I will try this with a few more taxpayers, and then think about how we can confirm that this is the *sole* issue contributing to the fact that some taxpayers' tax goes down when we get rid of itemized deductions. 

![image](https://cloud.githubusercontent.com/assets/8301092/8019659/4dbb805c-0c27-11e5-81d6-cde362a3a52e.png)

**Comment by Amy-Xu** [comment]
The diagram looks awesome!

I found something interesting from [JCT's description](https://www.jct.gov/publications.html?func=startdown&id=4776) of their microsimulation model, relevant to this issue.

>The tax calculator chooses those tax options that minimize each tax filing unit’s tax liability. For >example, for each tax filing unit, the calculator determines the level of itemized deductions, as well as >the standard deduction, and generally gives that tax filing unit the higher of the two. Note that, because >of the AMT, in some circumstances, a taxpayer will be better off claiming itemized deductions instead of >the standard deduction, even though the taxpayer’s total itemized deductions are less than the standard >deduction amount. 

This example seems like the opposite case of ours, which we might need to take into consideration when we change our model. Even though it's still unclear how IRS minimize taxpayer tax liabilities though their forms in either case, at lease we should include this step in our micro model as JCT does.

**Comment by feenberg** [comment]
On Mon, 8 Jun 2015, Amy Xu wrote:

> 
> The diagram looks awesome!
> 
> I found something interesting from JCT's description of their microsimulation model, relevant to this issue.
>
>       The tax calculator chooses those tax options that minimize each tax filing unit’s tax liability. For
>       >example, for each tax filing unit, the calculator determines the level of itemized deductions, as
>       well as >the standard deduction, and generally gives that tax filing unit the higher of the two. Note
>       that, because >of the AMT, in some circumstances, a taxpayer will be better off claiming itemized
>       deductions instead of >the standard deduction, even though the taxpayer’s total itemized deductions
>       are less than the standard >deduction amount.
> 
> This example seems like the opposite case of ours, which we might need to take into consideration when we change
> our model. Even though it's still unclear how IRS minimize taxpayer tax liabilities though their forms in either
> case, at lease we should include this step in our micro model as JCT does.

They must have imputations for itemized deductions of non-itemizers, which 
we don't have yet. Otherwise they wouldn't ever see this possibility.

dan

**Comment by mmessick** [comment]
@MattHJensen, it seems like with the proposed changes in PR #302 that the problem here may have been fixed since I changed how we calculated AMTI. I have not fully looked into this, however it might be something to look into later.

**Comment by MattHJensen** [comment]
@GoFroggyRun is this issue resolved?

**Comment by GoFroggyRun** [comment]
@MattHJensen 
Although it seems like PR #490 is somewhat related to the issue here, I don't think the problem in #490 has anything to do with optimization of itemize deduction. Thus this issue itself seems resolved to me.

**Comment by martinholmer** [comment]
@MattHJensen said during April 2016 in issue #282:
> @GoFroggyRun is this issue resolved?

And @GoFroggyRun responded:
> Although it seems like PR #490 is somewhat related to the issue here, I don't think the problem in #490 has anything to do with optimization of itemize deduction. Thus this issue itself seems resolved to me.

So where do we stand on this issue #282?  Is it resolved as @GoFroggyRun suggests in his response?  Or do we need to do something to resolve it?  I'd be willing to work on this but need some guidance.  It seems important to address this issue given that it is labeled as a bug.

@feenberg @Amy-Xu @zrisher

**Comment by MattHJensen** [comment]
It looks like I missed @GoFroggyRun's response that this is resolved. Closing. Thanks @martinholmer and @GoFroggyRun.

**Comment by martinholmer** [comment]
@MattHJensen, Thanks for the quick response.
