### ISSUE TITLE
Add TAXSIM-like input and output capabilities

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#291]
Currently users following the Contributor Guide cannot do much with
the Tax Calculator source code beyond running `py.test`.  The
experience of users just getting started with the Tax Calculator could
be improved considerably if there was a capability of reading in one
or a few simple tax filing units from a text file and getting back
from the Tax Calculator a text file with the results.  I think the
best way to start adding this capability would be to adopt the
Internet TAXSIM file input and output format.  I am imagining that
this model enhancement can be accomplished by leaving the taxcalc code
unchanged and adding two functions.  One would read a TAXSIM-like
input file and write a PUF-like csv file for taxcalc input.  And the
other would write a TAXSIM-like output file by extracting information
from the Tax Calculator results records.  These two functions could
be combined into a single Python script that reads the TAXSIM-like
input file and the specified policy parameters, uses taxcalc to do
the calculations, and then writes the TAXSIM-like output file.

**Comment by MattHJensen** [comment]
For reference, here is internet taxsim: http://users.nber.org/~taxsim/taxsim9/

**Comment by mmessick** [comment]
@martinholmer, I just opened a PR ( #309 ) to facilitate the incorporation of Luca into the code base. I was facing a similar issue with trying to run individual files on our calculator and I thought that refactoring the initialization method for a Records object might help with this. That way, you would not have to write output to a csv file (which might end up making the code run faster). Let me know what you think and if this change would be helpful to you

**Comment by martinholmer** [comment]
The enhancement described in this issue #291 --- addin a capabiltiy like Internet TAXSIM --- was originally implemented in pull reequest #376.
