### ISSUE TITLE
Replace _cmp with puf

### ISSUE THREAD

**Issue by mmessick** [open-source-economics/Tax-Calculator#299]
_cmp = 0 when puf = True
Replace all instances of _cmp in code with the appropriate code for puf.

**Comment by martinholmer** [comment]
Both the `_cmp` and `puf` variables were removed from Tax-Calculator in a series of pull requests merged in late June and July, 2016.  These pull requests are in the range from #803 to #820.  So, this issue has been resolved in a different way than @mmessick envisioned, but her view that there was no need to have two separate variables for the same concept was accurate.
