### ISSUE TITLE
ASCII text generator should accept calculators rather than CSV

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#335]
Our ASCII text generator (#306) takes as input the results csv generated by `test.py`
It would be useful to modify this function to take as input a post-calculation calculator. 

It would also be useful if this function could return both `c` and `e` `records` attributes rather than just `c` columns. 

It might require some thinking to find an elegant way to identify the variables to be included in the ASCII output. 

@xiyuw123, would you mind taking this one?

cc @Amy-Xu

**Comment by xiyuw123** [comment]
Yep, I could start looking into it!

**Comment by MattHJensen** [comment]
Thanks @xiyu123!

**Comment by MattHJensen** [comment]
@xiyuw123, have you had a chance to take a look at this? Any stumbling blocks?

**Comment by xiyuw123** [comment]
Hi Matt, I haven't had much time to look over this but I've been mostly looking into how the calc object works. Is there any documentation that describes this in detail?

**Comment by MattHJensen** [comment]
> Is there any documentation that describes this in detail? 

:laughing:, unfortunately, nothing better than the code and docstrings at this point. Shoot me an email if it would make sense to walk through everything on the phone or a screenshare. 

For the purpose of this task, I think the thing to keep in mind is that after running `calc.calc_all()` all of the records attributes (including e and c variables) can be accessed by, e.g., `calc.records.c00100`. The tricky part is that you can't dump everything from the records object because there are some funny attributes like `BF`, and you also probably don't want to specify every var by hand that should be included in the ascii text file. One thing to try might be dumping everything to ascii text that has the same dimensions of, say, `c00100`.

**Comment by xiyuw123** [comment]
Ok, will do!

So I'm guessing there's no list of codes which are included in records? I see a bunch of codes listed under blowup and read in records.py though I'm not sure if they're comprehensive.

**Comment by martinholmer** [comment]
@MattHJensen, on 03-Aug-2015 you requested an enhancement [ASCII text generator should accept calculators rather than csv files] in Tax-Calculator issue #335.  Where do we stand on this issue?  Given the current (14-Feb-2016) Tax-Calculator capabilities, is this enhancement still a priority?  If so, can you add to this issue a description of the needed capabilities?  If not, does it make sense for you to close the issue?

**Comment by MattHJensen** [comment]
@feenberg, over the last couple of weeks, Sean has sent you a few lists of intermediate variables and final variables l in a vertical format for debugging. Has that format been easy for you to work with? 

@GoFroggyRun, how have you been generating the lists of variables to send to Dan?

**Comment by GoFroggyRun** [comment]
@MattHJensen 
That vertical format was obtained using pivot table/matrix transpose. For single record or few records, it would sometimes be helpful to have the output in this format.

**Comment by MattHJensen** [comment]
Closing this issue. I there is demand again, we can reopen it.
