### ISSUE TITLE
This repository should have code coverage reports

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#346]
Codecov is a common solution here:

https://github.com/codecov/example-python

The task would be to put codecov directives in the repository so that coverage reports are automatically generated with each PR. Sometimes these tools can cause people to spin their wheels writing useless tests because the tool doesn't quite understand a particular code path, but on the whole, I think it's a win to integrate a coverage tool into the repo.

**Comment by martinholmer** [comment]
@talumbau,  Haven't you resolved this issue by adding CodeCov to the Travis-CI tasks?  Or, are there other aspects of this issue that need to be discussed?  If resolved, perhaps you should close this issue.

**Comment by talumbau** [comment]
resolved via https://github.com/open-source-economics/Tax-Calculator/pull/516
