### ISSUE TITLE
Policy Parameters class needs to recognize two parameter indexing rates?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#369]
OK, we need to face up to the fact that at least one of the FICA tax parameters is indexed not by a price inflation rate, but by a wage growth rate.  For details on the two indexes, see this SSA webpage http://www.ssa.gov/OACT/COLA/index.html.  Indexing the maximum taxable earnings level (called _SS_Earnings_c in the params.json file) with price inflation rates (as currently done) leads to a substantial understatement of future year values for this parameter because average wage growth rates are generally higher than price inflation rates.

I'm raising this issue so that the OSPC team can discuss what, if anything, to do about this mistake.  We could just let things be and live with the mistake.  Or we could fix the mistake by doing something like this:

(a) add an indexes.json file containing the two default indexing rates, and

(b) revise the Parameters class to read the indexes.json file by default or a user specified JSON file containing the user's own assumptions about price inflation and wage growth.

Or perhaps there is another approach that would be better.  Any suggestions?

In the "doing something about this mistake" strategy outlined above, the indexes.json file (with comments that would be removed before converting the JSON into an indexes dictionary) would look like this:
```
// indexes.json specifies wage growth rate to be equal to price inflation rate
{
    // rates from CBO --- copied out of taxcalc/parameters.py file.
    "price_inflation_rate": {"2013": 0.015,
                             "2014": 0.020,
                             "2015": 0.022,
                             "2016": 0.020,
                             "2017": 0.021,
                             "2018": 0.022,
                             "2019": 0.023,
                             "2020": 0.024,
                             "2021": 0.024,
                             "2022": 0.024,
                             "2023": 0.024,
                             "2024": 0.024},
    // rates from CBO or SSA probably --- for now just repeat CBO price inflation rates
    "wage_growth_rate": {"2013": 0.015,
                         "2014": 0.020,
                         "2015": 0.022,
                         "2016": 0.020,
                         "2017": 0.021,
                         "2018": 0.022,
                         "2019": 0.023,
                         "2020": 0.024,
                         "2021": 0.024,
                         "2022": 0.024,
                         "2023": 0.024,
                         "2024": 0.024}
}
```

Any and all comments, suggestions, criticisms are welcome.  How should we proceed, if at all?

**Comment by MattHJensen** [comment]
> We could just let things be and live with the mistake. Or we could fix the mistake by doing something like this:

I'd argue for fixing the mistake. 

One complication is that we also use price inflation in the data extrapolation. It makes sense for us to use corresponding values for CPI-u between the data extrapolation and policy indexing. Currently I believe we do -- or at least we are very close (they might be taken from different CBO reports) -- but we store the data separately and we don't check that it is the same.

**Comment by Amy-Xu** [comment]
@martinholmer's solution sounds very feasible. We can allow users to upload their own indexes in future from the webapp. For now probably we can just add the default indexes to correct the mistake?

@MattHJensen How does this relate to data extrapolation?

**Comment by MattHJensen** [comment]
> @MattHJensen How does this relate to data extrapolation?

My point is that a weakness of our current arrangement is that we don't ensure consistency between the price indexes that we use for the policy parameters and the price indexes that we use for the data extrapolation. As we are considering refactoring how we get price indexes for the policy parameters, it might be worthwhile to think about this existing weakness and whether we can address it during the refactor.

**Comment by feenberg** [comment]
On Wed, 30 Sep 2015, Matt Jensen wrote:

>
>       @MattHJensen How does this relate to data extrapolation?
> 
> My point is that a weakness of our current arrangement is that we don't
> ensure consistency between the price indexes that we use for the policy
> parameters and the price indexes that we use for the data extrapolation. As
> we are considering refactoring how we get price indexes for the policy
> parameters, it might be worthwhile to think about this existing weakness and
> whether we can address it during the refactor.

I am not sure I understand the problem. If we default to using the same 
inflation rate, but allow the user to specify a real growth rate above or 
below the CBO forecast, there isn't a significant problem in my view. If 
we use the CBO forecast and targets, then presumably the inflation rates 
are consistent.

It is likely that people will have different views of the likely inflation 
rate, but since almost all of the tax law is indexed, it won't make a 
difference in real outcomes. The biggest exception is the AMT exclusion, 
but no one really believes it won't be increased with inflation, allowing 
it to do otherwise is not helpful.

dan

**Comment by martinholmer** [comment]
@MattHJensen, @feenberg, @Amy-Xu,

I am also confused about Matt's point.  My original statement was simply that over the budget years, in the real world, the OASDI maximum taxable earnings (MTE) level will rise faster than the rate of price inflation (in almost all economic situations).  But in taxcalc MTE is rising only at the rate of price inflation, which means taxcalc is underestimating FICA taxes (and marginal tax rates) for high earners, and the magnitude of the underestimation is growing with each year.

My original statement had nothing to do with the data aging process.  But I'm assuming that earnings (e00200) are being aged from 2009 to subsequent years using an average earnings growth rate that is above the rate of price inflation.  Right?

Another angle to this issue is that, if we are going to make it easy for the user to assume faster economic growth (via Amy's pending changes), then won't that user also want to assume that the MTE rises at a faster rate?  If we don't allow that, then users will be forced into assuming that most of the extra GDP (produced by the faster economic growth) flows into capital income and little flows into labor income.  Recent growth in the US has been moving in that direction, but I think users will want to have the flexibility to make their own assumptions about how the future plays out.

**Comment by feenberg** [comment]
On Wed, 30 Sep 2015, Martin Holmer wrote:

> 
> @MattHJensen, @feenberg, @Amy-Xu,
> 
> I am also confused about Matt's point. My original statement was simply that over the
> budget years, in the real world, the OASDI maximum taxable earnings (MTE) level will
> rise faster than the rate of price inflation (in almost all economic situations). But
> in taxcalc MTE is rising only at the rate of price inflation, which means taxcalc is
> underestimating FICA taxes (and marginal tax rates) for high earners, and the
> magnitude of the underestimation is growing with each year.
> 
> My original statement had nothing to do with the data aging process. But I'm assuming
> that earnings (e00200) are being aged from 2009 to subsequent years using an average
> earnings growth rate that is above the rate of price inflation. Right?
>

It does make sense to grow MTE at the rate assumed for wages in the aging 
process.

dan

**Comment by martinholmer** [comment]
@MattHJensen, @feenberg, @Amy-Xu,

Dan said:
> It does make sense to grow MTE at the rate assumed for wages in the aging process.

This conversation has been very helpful.  I now think we can solve this problem in a way that is simpler than I suggested yesterday __and__ this new solution will also solve the problem of coordinating user changes in economic growth with the indexing the the social security MTE. My new thinking may be somewhat underdeveloped, so please bear with me as I explain it below.

The new approach is based on three observations: (a) the only tax policy parameter that is indexed to the rate of growth in average wages (what social security law calls the "average wage index" or AWI) is the MTE (" _SS_Earnings_c" in the params.json file), (b) Dan's view makes total sense, and (c) as users change growth assumptions (to be different than they were in the default aging process) the rate of nominal average wage growth will change.  Do I have those three things right?  If so, we might consider an approach like this:

(1) Skip the indexing of MTE when all the other tax law parameters are indexed in the Parameters class, but set a flag that indicates MTE has not yet been indexed.

(2) Index MTE as the first step in the Calculator.calc_all() method when the (possibly growth-adjusted) blowup factors are available via the Records object embedded in the Calculator object.  We can make sure this has been done by halting the calculations if the flag indicates the MTE has not yet been indexed.

This approach means we do __not__ have to create a new indexes.json file and all the supporting code.

I did some tabulation of the StageIFactors.csv file, to see how the blowup factors in the Records class could be used to see what the user is assuming about the rate of growth in average wages.  Here is what I found:
```
$ awk -F, 'BEGIN{RS="\r"}NR==1{print $1,$4,$15}' StageIFactors.csv 
YEAR AWAGE APOPN

$ awk -F, 'BEGIN{RS="\r";p=1}NR>1{a=$4/$15;print $1,$4,$15,a,a/p;p=a}' StageIFactors.csv 
2009 1      1      1       1
2010 1.0228 1.0076 1.01509 1.01509
2011 1.061  1.015  1.04532 1.02979
2012 1.1041 1.0224 1.07991 1.03309
2013 1.1348 1.0297 1.10207 1.02052
2014 1.1823 1.0383 1.13869 1.03323
2015 1.2372 1.0468 1.18189 1.03794
2016 1.2988 1.0554 1.23062 1.04124
2017 1.3646 1.064  1.28252 1.04217
2018 1.4303 1.0725 1.33361 1.03984
2019 1.4947 1.0811 1.38257 1.03671
2020 1.5607 1.0896 1.43236 1.03601
2021 1.6289 1.0981 1.48338 1.03562
2022 1.6997 1.1066 1.53597 1.03545
2023 1.7729 1.1149 1.59019 1.0353
2024 1.8488 1.1232 1.64601 1.03511
```
The rate of growth in nominal average wages (plus one) is in the far-right column of AWK output.  These rates could be teased out the Records object (where they might be different than assumed in the aging process, which is what is in StageIFactors.csv) and used in a new Parameters method to index MTE.

__Oops!__  Just now realized this will not work when a reform in the MTE is specified.  Maybe we have to consider waiting to create a Parameters object until we have a Records object from which to get the implied rates of average wage growth.

I guess this approach is based on the assumption that the user-supplied economic growth assumptions will not change the price inflation rates supplied to the Parameters class constructor.  Is that right or wrong?

Well, as you can see, my ideas are not fully thought out.  What's your reaction?  Does it make sense to pursue this kind of approach?

**Comment by MattHJensen** [comment]
> It does make sense to grow MTE at the rate assumed for wages in the aging process.
 
This is true for prices as well.  `ACPIU` from the blowup factors and `irates` from Parameters should be consistent

**Comment by martinholmer** [comment]
@MattHJensen, @feenberg, @Amy-Xu,

>> It does make sense to grow MTE at the rate assumed for wages in the aging process.

> This is true for prices as well. ACPIU from the blowup factors and irates from Parameters should be consistent.

All the above is sensible.  However, we'll have to do some more thinking to develop a plan for achieving these goals.

**Comment by feenberg** [comment]
I am confused as to why so much complexity is required. If we know from 
John what the CBO assumed growth rate of wages is, we can supply default 
MTE values based on that. They would be calculated by hand and entered as 
literals in the program.  Then if users wish to use different values for 
MTE, they would have to be aware of the growth of wages, or they would get 
unexpected results. But that is OK. If the user specifies a differential 
from the CBO growth rate, then it would be added or subtracted from the 
factor growing wages. I expect I am missing something but I can't see 
exactly what.

dan
617-863-0343

**Comment by martinholmer** [comment]
Changes over the past few weeks mean that now the Tax-Calculator code correctly indexes the OASDI (social security) maximum taxable earnings by the rate of growth in wages, while all other indexed tax parameters are increased by the rate of price inflation.  And furthermore, the default prince inflation rates and default wage growth rates --- both of which are hard-coded in the Policy class --- are being checked in the unit tests to ensure that they are consistent with the rates implied by the blowup factors used in aging the input sample to future years.  These recent developments imply that this issue can be closed.
