### ISSUE TITLE
report deadweight loss

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#403]
It would be nice to report estimates of deadweight loss given 
1. user-specified assumptions for the elasticity of taxable income (following [Feldstein 1999](http://www.jstor.org/stable/2646716?seq=1#page_scan_tab_contents)) or
2.  user-specified assumptions for taxable and total income elasticities and the marginal resource cost of sheltering (following [Chetty 2009](https://www.aeaweb.org/articles.php?doi=10.1257/pol.1.2.31)). 

cc @feenberg, @martinholmer, @viard.

**Comment by MattHJensen** [comment]
Would this also give us the implied cost of an additional dollar of government spending, assuming  revenue is raised by the income+payroll taxes on the margin?

**Comment by feenberg** [comment]
I know that Marty has asked me for DWL numbers in the past, but I don't 
think they are legitimate in this context.

The incrmental value of deadweight loss from a change in the income tax 
depends on all the taxes and increasing returns everywhere in the economy, 
not just on the ones in the tax model. The change in DWL from the sales 
tax, when the income tax is changed can easily outstrip the loss we would 
calculate in the model. Add in the changes in all the other taxes and 
increasing returns industries, and the delta DWL we would calculate is not 
dominant at all.

This is something that Kevin and Alan should have a role in deciding.

dan

**Comment by Viard** [comment]
That’s an excellent point.

All taxes need to be included to compute deadweight loss of any tax.

**Comment by MattHJensen** [comment]
@feenberg said:

>The incremental value of deadweight loss from a change in the income tax
depends on all the taxes and increasing returns everywhere in the economy,
not just on the ones in the tax model. The change in DWL from the sales
tax, when the income tax is changed can easily outstrip the loss we would
calculate in the model. Add in the changes in all the other taxes and
increasing returns industries, and the delta DWL we would calculate is not
dominant at all.

@feenberg, my understanding is that these factors mean we can only calculate a lower bound for the delta DWL. Is that right? 

cc @khecon.

**Comment by Viard** [comment]
Of course, you actually need to know all of the other taxes in order to do a correct dynamic revenue estimate – the problem is not unique to deadweight loss.

**Comment by feenberg** [comment]
On Sat, 17 Oct 2015, Viard wrote:

> Of course, you actually need to know all of the other taxes in order to do a correct
> dynamic revenue estimate – the problem is not unique to deadweight loss.
>

Well, I would characterize "other taxes" as second order for revenue 
estimates, but first order for DWL. Consider that the DWL on the income 
tax will be a triangle, but the effect on DWL of other taxes will be a 
rectangle whose long dimension may be income or consumption.


dan

**Comment by MattHJensen** [comment]
@feenberg, the general public thinks the cost of an additional $1 of government spending is $1. If we can show that, no, the *lower bound* (perhaps extreme lower bound) of the cost of an additional $1 of government spending is in fact (1+x) * $1, that seems like a major improvement. Am I making a mistake? If we were to report this, it would be extremely helpful to have something written down for our users explaining why the number is likely a lower bound.

Also, we could make some crude, or not so crude, imputations for many other taxes, and this would provide the community a strong incentive to get to work on those.

**Comment by feenberg** [comment]
On Mon, 19 Oct 2015, Matt Jensen wrote:

> 
> @feenberg, the general public thinks the cost of an additional $1 of government spending is $1. If we can
> show that, no, the lower bound (perhaps extreme lower bound) of the cost of an additional $1 of government
> spending is in fact (1+x) * $1, that seems like a major improvement. Am I making a mistake? If we were to
> report this, it would be extremely helpful to have something written down for our users explaining why the
> number is likely a lower bound.
> 
> Also, we could make some crude, or not so crude, imputations for many other taxes, and this would provide the
> community a strong incentive to get to work on those.

I think this is getting away from "providing a tool" and moving towards 
"doing a research project". But, I recall that Robert Hall has some work 
on price-cost margins that might be usable as a base.

   http://www.nber.org/papers/w1785

Taxes would be in addition to the effect of increasing returns. There 
would be a lot more work. The problem is that providing a lower bound that 
is 1% of the true value may be more misleading than helpful.

dan

**Comment by MattHJensen** [comment]
Closing this based on the argument that it involves a research project and is not essential for the tax-calculator project. It would still be nice to see a researcher undertake it sometime in the future, but it doesn't need an open issue in Tax-Calculator.
