### ISSUE TITLE
Why are the default values of the growth parameters lists of lists?

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#415]
in `growth.json`, the default value for `factor_adjustment` and `factor_target` have values of `[[0.0]]`. Typically, a value that is a scalar for one year will then be presented by a list of scalar values. The list will be of size 1 when the value is only specified for one year. Normally, we have a list of lists when each value for a year is multi-valued. Here, to me it looks like we just have a rate for each year, which would make me think we should just have default values of `[0.0]` for the two parameters. Am I missing something @Amy-Xu @MattHJensen ?

**Comment by MattHJensen** [comment]
>Here, to me it looks like we just have a rate for each year, which would make me think we should just have default values of [0.0] for the two parameters

Seems right to me. @Amy-Xu?

**Comment by Amy-Xu** [comment]
@talumbau I need to double check, but I remember when I used [0.01], I would get a 'dimension doesn't match error', which tells me (1,10) cannot be matched with (,10). I got confused on that but found if I changed the input to [[0.01]], that error disappeared. Still not quite sure why that happened.

**Comment by martinholmer** [comment]
@talumbau,  did you get an answer to the question you posed in Tax-Calculator issue #415?  If so, could you close this issue?  If not, maybe you should ask your question again.

**Comment by talumbau** [comment]
This was resolved by @Amy-Xu with commit 7aa52e507fcc16bbf6ad8db5f7aa4d202104df75. Closing.
