### ISSUE TITLE
Move extrapolation and imputations to taxdata repo? 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#436]
Tax-calculator currently does more than calculate taxes for some given dataset. It also does quite a bit to prepare that dataset, including applying blowup factors, reweighing the data, making some imputations on the fly, and adjusting the data based user-given parameters (`growth.py`). 

I have been wondering whether it would be more sensible to move the extrapolation, imputations, and growth.py functionality to the taxdata repository. Tax-calculator would then purely calculate taxes, and tax-data would purely create tax databases. 

How this would actually be implemented, I'm not so sure.

This relates to #425.

@martinholmer, @talumbau, and @Amy-Xu, what do you think?

**Comment by feenberg** [comment]
On Mon, 2 Nov 2015, Matt Jensen wrote:

> 
> Tax-calculator currently does more than calculate taxes for some given dataset. It
> also does quite a bit to prepare that dataset, including applying blowup factors,
> reweighing the data, making some imputations on the fly, and adjusting the data based
> user-given parameters (growth.py).
> 
> I have been wondering whether it would be more sensible to move the extrapolation,
> imputations, and growth.py functionality to the taxdata repository. Tax-calculator
> would then purely calculate taxes, and tax-data would purely create tax databases.

This is the practice I have mostly observered. I like it. I have a dataset 
for each year and to read all the years I concatenate them:

    cat /home/data/soi/taxsim/asc/x*.asc | a.out

We would need something a little different here.

dan

**Comment by martinholmer** [comment]
After pull request #754 was merged into the master branch, all the data imputation logic is being done in the [taxdata repository final-preparation script](https://github.com/open-source-economics/taxdata/blob/master/final%20prep/puf-cps-processing.py).  The blow-up logic remains in the Tax-Calculator.

Is there any further work that should be done on this issue #436?  If not, should the issue be closed?

@MattHJensen @feenberg @talumbau @Amy-Xu

**Comment by MattHJensen** [comment]
I wonder if, in the future, we will want to pass some sort of generic blowup dictionary to the tax-calculator rather than include blow-up logic that is semi-specific to the taxdata repository. For now, I think what we have is enough and this issue ought to be closed.
