### ISSUE TITLE
Earning Split Issue?

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#469]
I might be terribly wrong, but while working on the validation  against sas calculator , after implementing the earning split into sas calculator, I found that, by printing `e00200p` and `e00200s` outputs/variables in the `EI_FICA` function, the earning split functionality seems to be null in our calculator, in the way that they won't simultaneously take positive values.
I'm using the `puf` file of size 129682845 bytes and executing `test.py` under the tax-calculator directory on current OSPC master.  I was wondering am I the only person experiencing such issue? If so, please advice. Much appreciated. 
@Amy-Xu @martinholmer @MattHJensen

**Comment by martinholmer** [comment]
Sean (@GoFroggyRun),
I'm working on a different project (that involves reading in the puf.csv file) and I'm experiencing some problems as well.  My problem is a python crash.  But it is too early to tell exactly what is the cause of my problem; it may well be my misuse of the basic Tax-Calculator classes.  After I've found out what is causing my problem, I'll report back here.  It may be related or it may be completely unrelated.
cc @Amy-Xu and @MattHJensen

**Comment by GoFroggyRun** [comment]
@martinholmer 
Thanks for the updates. I'll be trying to fix this "issue" myself before it got confirmed.

**Comment by MattHJensen** [comment]
@GoFroggyRun, notice that there are some differences between `calc_all()` and `calc_all_test()` in `calculate.py`. 

`test.py` calls `calc_all_test()`, but every other application of the calculator that I know of uses `call_all()`. For one thing, `calc_all_test()` does not execute the proper itemized filing optimization. It also doesn't allow for the itemized deduction surtax. 

It might be that this difference is causing your issues or it might not be, I haven't had time to check further. But I would suggest that you look at test_calculate.py for more standard uses of the calculator class. 

As an aside, I will be opening an issue suggesting that we remove the `test.py` script and `calc_all_test()` entirely (so we don't need to have a discussion about the usefulness of those scripts here).

**Comment by GoFroggyRun** [comment]
@MattHJensen I see. Thanks for the advice. 
It is quite puzzling, however, that the `_earning_split` variable takes either 0 or 1, where it takes 0 when the conditions got satisfied, for each observation using `test.py` script. And I'm actually pretty confused by why this is happening. Shouldn't its value be constant if this part doesn't get executed at all? The situation right now is that the switch which assigns values to `_earning_split` seems to be valid while `_earning_split` by no means take the right value when the switch is on.
Also, I was wondering whether `test.py` is necessary for the validation work, say if we were abandoning the `test.py`?

**Comment by MattHJensen** [comment]
@GoFroggyRun, have you confirmed using `calc_all()` rather than `calc_all_tests()` resolves this issue?

**Comment by GoFroggyRun** [comment]
@MattHJensen I don't actually think so. By printing out `_earning_split`, `e00200p` and `e00200s` on top of PR #472 . It seems that the same issue persists.

**Comment by GoFroggyRun** [comment]
@martinholmer Yes. It seems that the `_earning_split` variable was of integer type, and that explains everything. By adopting the changes you proposed, the variable was now of type float and yield  desired results. I'll open a PR right away to fix this issue. Thank you so much for the advice!

**Comment by martinholmer** [comment]
@Sean @GoFroggyRun said:
> It seems that the _earning_split variable was of integer type, and that explains everything. By adopting the changes you proposed, the variable was now of type float and yield desired results. I'll open a PR right away to fix this issue. Thank you so much for the advice!

Sure, no problem.

**Comment by GoFroggyRun** [comment]
Closed. Confirmed to be fixed after #474 being merged.
