### ISSUE TITLE
itemized deduction surtax changes IIT revenue but not combined revenue 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#487]
The itemized deduction surtax changes IIT revenue but not combined revenue. Here is an example. 

![image](https://cloud.githubusercontent.com/assets/8301092/11458577/8b181a0c-9690-11e5-8737-0a42eb80ea1e.png)

**Comment by martinholmer** [comment]
@MattHJensen said during November 2015 in issue #487:
> The itemized deduction surtax changes IIT revenue but not combined revenue [in TaxBrain].

This bug has been fixed as shown in [these results](http://www.ospc.org/taxbrain/4725/) generated by TaxBrain version 0.6.5.
