### ISSUE TITLE
Test itemized deduction haircuts and itemized deduction surtax consistency

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#488]
[By definition of the itemized deduction surtax](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/functions.py#L1698-L1732), the following two reforms should produce the same combined revenue change:

1) set the itemized deduction surtax rate at 1 and credit rate at 0 for some subset of itemized deductions.
2) set the haircut rates to 1 for the same subset of itemized deductions. 

We could easily test the internal consistency between these two sets of reforms, and that would prevent problems like #487.

**Comment by martinholmer** [comment]
Issue #488 has been resolved by pull request #842.
