### ISSUE TITLE
use _combined instead of _iitax for calculating income effect 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#489]
Currently we calculate the income effect like this: 

    income_effect = calc_y.behavior.BE_inc * (calc_y.records._iitax -
                                              calc_x.records._iitax)

I believe it should instead be like this: 

    income_effect = calc_y.behavior.BE_inc * (calc_y.records._combined -
                                              calc_x.records._combined)

**Comment by feenberg** [comment]
On Sun, 29 Nov 2015, Matt Jensen wrote:

> 
> Currently we calculate the income effect like this:
> 
> income_effect = calc_y.behavior.BE_inc * (calc_y.records._iitax -
>                                           calc_x.records._iitax)
> 
> I believe it should instead be like this:
> 
> income_effect = calc_y.behavior.BE_inc * (calc_y.records._combined -
>                                           calc_x.records._combined)
>

Yes, the combined it and fica is the correct number to use.

dan

**Comment by MattHJensen** [comment]
Thans Dan. Fixed in #491, so closing.
