### ISSUE TITLE
Enhancement for imputing _othded

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#504]
Previously we are imputing `_othded` by `_othded = e04470 - c04470` in the `functions.py`. But this doesn't make a lot of sense, since we are actually measuring the difference after the extrapolation has been done, and more importantly, the `e04470` was a value in the 09 puf file and thus the difference ought to be measured using calculated values under 09 tax logic. A possible way to catch the difference here would be relocating the calculation to `records.py`.

**Comment by martinholmer** [comment]
The variable ```_othded``` is nowhere to found on the master branch, so it would seem that this issue has been resolved.
