### ISSUE TITLE
What is role of the FLPDYR variable read from puf.csv file?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#517]
The values for the FLPDYR variable in the puf.csv file are as follows: 
```
> awk -F, 'NR==1{for(i=1;i<=NF;i++)if($i~/FLPDYR/)print i,$i}' puf.csv
15 FLPDYR
> awk -F, 'NR>1{t++;n[$15]++}END{print t;for(y in n)print y,n[y]}' puf.csv
219814
2009 212640
2008 5205
2007 1408
2006 561
```
So, about 3.2 percent of the filing units in puf.csv have tax filing years before 2009.

I have two questions about the role of the FLPDYR variable in the Tax-Calculator code given that it seems as if the only uses of the FLPDYR variable are: (a) to compute the _agep and _ages variables when the date of birth variables for the taxpayer (DOBYR) and spouse (SDOBYR) are available, which is not the case with puf.csv input; and (b) to specify Records.current_year when using puf.csv input.

(1)  There is about a three percent chance that (b) will not work because there is no guarantee that the first filing unit in the puf.csv file has a value of 2009.  It turns out that in the current version of the puf.csv file the first record has FLPDYR equal to 2009, but if the records were sorted in a different way that might not be true.  Perhaps we should add a test to test_records.py to ensure that the first record in puf.csv always has the value Records.PUF_YEAR.

(2) In the case where the DOBYR and SDOBYR variables are available, I'm confused about why the Records.increment_year() method increments FLPDYR (```self.FLPDYR += 1```).  It seems as if that would create an unrealistic age distribution that would become more unrealistic with each call to increment_year().  After 10 or more years, there would be no filing units in their twenties and too many elderly filing units that have unrealistic incomes (that is, no social security because they were in their fifties in the puf.csv file).  Why no remove the ```self.FLPDYR += 1``` statement in increment_years()?

**Comment by martinholmer** [comment]
@MattHJensen, @Amy-Xu, @GoFroggyRun,
Have I missed something in my FLPDYR analysis in issue #517?

If not, I'd be happy to prepare a pull request that implements the test I suggest and drop the incrementing of FLPDYR in the Records increment_year() method.

**Comment by feenberg** [comment]
On Tue, 5 Jan 2016, Martin Holmer wrote:

> 
> The values for the FLPDYR variable in the puf.csv file are as follows:
> 
> > awk -F, 'NR==1{for(i=1;i<=NF;i++)if($i~/FLPDYR/)print i,$i}' puf.csv
> 15 FLPDYR
> > awk -F, 'NR>1{t++;n[$15]++}END{print t;for(y in n)print y,n[y]}' puf.csv
> 219814
> 2009 212640
> 2008 5205
> 2007 1408
> 2006 561
> 
> So, about 3.2 percent of the filing units in puf.csv have tax filing years before
> 2009.
> 
> I have two questions about the role of the FLPDYR variable in the Tax-Calculator code
> given that it seems as if the only uses of the FLPDYR variable are: (a) to compute the
> _agep and _ages variables when the date of birth variables for the taxpayer (DOBYR)
> and spouse (SDOBYR) are available, which is not the case with puf.csv input; and (b)
> to specify Records.current_year when using puf.csv input.

Probably the file year would be a better choice for calculating age. After 
all, the late returns are included as a proxy for current year unavailable 
(late) returns. When those are filed the age will be the same as file 
year.

> 
> (1) There is about a three percent chance that (b) will not work because there is no
> guarantee that the first filing unit in the puf.csv file has a value of 2009. It turns
> out that in the current version of the puf.csv file the first record has FLPDYR equal
> to 2009, but if the records were sorted in a different way that might not be true.
> Perhaps we should add a test to test_records.py to ensure that the first record in
> puf.csv always has the value Records.PUF_YEAR.
>

Use of file year solves this problem.

> (2) In the case where the DOBYR and SDOBYR variables are available, I'm confused about
> why the Records.increment_year() method increments FLPDYR (self.FLPDYR += 1). It seems
> as if that would create an unrealistic age distribution that would become more
> unrealistic with each call to increment_year(). After 10 or more years, there would be
> no filing units in their twenties and too many elderly filing units that have
> unrealistic incomes (that is, no social security because they were in their fifties in
> the puf.csv file). Why no remove the self.FLPDYR += 1 statement in increment_years()?
>

I agree.

dan

**Comment by martinholmer** [comment]
Dan @feenberg,
Thanks for your helpful comments (see above).

I can prepare a pull request along the lines you suggest, but first I need to know about future plans.
When we moved from 2008 to 2009 IRS data, we did not maintain the ability to read in 2008 data.  When we move from 2009 to 2010 IRS data, what is the plan?  Are we going to maintain the ability to read in the old 2009 file or just move on and focus exclusively on the 2010 data?

Seems like being able to use historical (now obsolete) data is a nice idea in principle, but it seems as if the cost of doing this would be high.  Am I missing something, or does the net benefit of maintaining the ability to process historical IRS data seem like it is likely to be negative?

cc @MattHJensen @Amy-Xu @GoFroggyRun

**Comment by feenberg** [comment]
On Wed, 6 Jan 2016, Martin Holmer wrote:

> 
> Dan @feenberg,
> Thanks for your helpful comments (see above).
> 
> I can prepare a pull request along the lines you suggest, but first I need to know about future plans.
> When we moved from 2008 to 2009 IRS data, we did not maintain the ability to read in 2008 data. When we move from 2009 to

That is a disappointment. I am concerned that making the calculator too 
dependent on a particular set of variables will limit us in the future.
I have been suggesting that we plan to make the calculator work with the 
CEX and SCF at some future date.

As far as I can tell, the calculator can function without every variable
being available. taxsim requires only year and marital status, any and 
oll other variables are taken to be zero if not available. This is very 
useful when multiple datasets are available. Is that not true of this 
calculator any more?

I am concerned that this is a serious regression - this was a problem for
the government calculators for many years - they could only use the base
year and it interfered with a lot of possible projects.

> 2010 IRS data, what is the plan? Are we going to maintain the ability to read in the old 2009 file or just move on and
> focus exclusively on the 2010 data?
>
> Seems like being able to use historical (now obsolete) data is a nice idea in principle, but it seems as if the cost of
> doing this would be high. Am I missing something, or does the net benefit of maintaining the ability to process historical
> IRS data seem like it is likely to be negative?
>

Why is the cost high? Is the problem ignoring irrelevant variables or 
missing variables? A problem with numpy or pandas?

dan

**Comment by martinholmer** [comment]
Dan @feenberg wrote:
> On Wed, 6 Jan 2016, Martin Holmer wrote:
>
> > Dan @feenberg,
> > Thanks for your helpful comments (see above).
> >
> > I can prepare a pull request along the lines you suggest, but first I need to know about future plans.  When we moved from 2008 to 2009 IRS data, we did not maintain the ability to read in 2008 data.
>
> That is a disappointment. I am concerned that making the calculator too dependent on a particular set of variables will limit us in the future.  I have been suggesting that we plan to make the calculator work with the CEX and SCF at some future date.
>
> As far as I can tell, the calculator can function without every variable being available.  TAXSIM requires only year and marital status, any and all other variables are taken to be zero if not available.  This is very
useful when multiple datasets are available. Is that not true of this calculator any more?
>
> I am concerned that this is a serious regression - this was a problem for the government calculators for many years - they could only use the base year and it interfered with a lot of possible projects.

Dan,  Things are not as bad as you imagine; let me correct and clarify my earlier comments.

I was wrong to say that the Python Tax-Calculator cannot read the old 2008 IRS-PUF file.  It can, and any code variables not in the file will be set to zero.  I spent quite a bit of time during November and December making the Tax-Calculator work in a way that is similar to how you describe TAXSIM working.  In the Python Tax-Calculator (after this pull request is merged) the minimum required variables in an input file are RECID and MARS.  Users specify the year of the data in the input file by setting the Records class constructor argument start_year to the appropriate value.

And the new Records class logic I added last month can handle input from any CSV file that uses the Tax-Calculator variable names in the first row of the file (as long as there are at least two: RECID and MARS).

My misleading statement about the 2008 IRS puf.csv file not being able to be handled refers to the extrapolation and reweighting (the so called "aging") logic that had been applied to the 2008 file.  That is no longer part of the Tax-Calculator code.  So, what I should have said is that the old 2008 puf.csv file can no longer be used by the TaxBrain webapp or by any other application that "ages" the data to future years and expects to get reasonable population-weighted aggregate results.  I believe this is true, but please correct me if I'm wrong about this @MattHJensen and @Amy-Xu.

Dan also wrote:
> Why is the cost high? Is the problem ignoring irrelevant variables or missing variables? A problem with numpy or pandas?

I was referring to the cost of maintaining "aging" data and logic for every year so that any year's data would produce reasonably accurate population-weighted estimates.  Of course, the raw data from any file can be read in, and be specified to be for any year, and those raw data can be used to compute taxes for each filing unit for any year in the 2013+ range.

Dan @feenberg, do these corrections and clarifications of my earlier comments ease your concerns?

**Comment by feenberg** [comment]
So the problem is that if I feed the calculator 2008 data, the aging from 
2008 to 2009 will not take place and the aging routine will be a year 
behind for every subsequent year? Did John provide us with parameters to 
go from 2008 to 2009? Could we use those?

What control does the user have over aging? Can it be turned off if the 
user has current data?

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
> So the problem is that if I feed the calculator 2008 data, the aging from 2008 to 2009 will not take place and the aging routine will be a year behind for every subsequent year?  Did John provide us with parameters to go from 2008 to 2009?  Could we use those?

These are good questions, but they have nothing to do with this issue #515 and the pull request #518 that attempts to resolve this issue.

Your questions are best answered by John O'Hare and @Amy-Xu and @MattHJensen.  But my (perhaps incorrect) impression is that things are much more complicated than simply adding an extra "aging" step from 2008 to 2009.  It would seem to me that there is no logical reason why, for example, the 2009-to-2010 "aging" for the 2009 IRS data would be the correct "aging" from 2009-to-2010 for the 2008 IRS data.  My impression is that we would have to maintain a complete set of "aging" data (for 15+ years of extrapolation) for each IRS PUF data file that we wanted to be able to use to produce reasonably accurate aggregate budget estimates.

But I may be wrong about all this.  So, I would suggest that you open a new issue to discuss this matter with @MattHJensen and @Amy-Xu and John O'Hare.

Dan also wrote:
> What control does the user have over aging? Can it be turned off if the user has current data?

Yes.  I added this capability last fall as part of the SimpleTaxIO class development.  Need this feature in order to calculate taxes on raw data (without any "aging") in order to validate Tax-Calculator results against Internet TAXSIM, which has been done as described on the [Tax-Calculator validation webpage](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/validation/README.md).

**Comment by Amy-Xu** [comment]
>So the problem is that if I feed the calculator 2008 data, the aging from
2008 to 2009 will not take place and the aging routine will be a year
behind for every subsequent year? Did John provide us with parameters to
go from 2008 to 2009? Could we use those?


I feel the main reason why we don't have 08-09 extrapolation is that 08 PUF and 09 PUF are not sharing any weights or factor at all, even for years after 09. Because all the factors are simple rates based on the puf year, at least this is what's implemented right now. So current 09 PUF extrapolation files are not compatible with 08 puf. We were planning to make records.py accommodate both 08 PUF and 09 PUF at one point but I wasn't sure how urgent is that. @MattHJensen Any timeline for this? Plus a underlying assumption is that any user who needs puf on their local machine could always get 09 PUF from us?

**Comment by feenberg** [comment]
On Fri, 8 Jan 2016, Amy Xu wrote:

>
>       So the problem is that if I feed the calculator 2008 data, the aging from
>       2008 to 2009 will not take place and the aging routine will be a year
>       behind for every subsequent year? Did John provide us with parameters to
>       go from 2008 to 2009? Could we use those?
> 
> I feel the main reason why we don't have 08-09 extrapolation is that 08 PUF and 09 PUF
> are not sharing any weights or factor at all, even for years after 09. Because all the
> factors are simple rates based on the puf year, at least this is what's implemented
> right now. So current 09 PUF extrapolation files are not compatible with 08 puf. We
> were planning to make records.py accommodate both 08 PUF and 09 PUF at one point but I
> wasn't sure how urgent is that. @MattHJensen Any timeline for this? Plus a underlying
> assumption is that any user who needs puf on their local machine could always get 09
> PUF from us?

I don't understand this. Is the problem that there was never an 
extrapolation from 2008 to 2009, that the 2008 data was extrapolated to 
2010-2019 and 2009 was never provided by John? I don't see how that 
relates to "not sharing any weights or factor", or indeed what that phrase 
means. Surely 2008 and 2009 share almost all the factor incomes and 
deductions. Can't we update the weights and incomes to 2009 to get a 
dataset that can be processed as if it were the 2009 puf?

dan

**Comment by Amy-Xu** [comment]
@feenberg My bad wording. John provided the original version of code for extrapolation in fortran, and then I translated it into python and used this python version creating all the weights and factors needed in extrapolation (from CBO targets and SOI statistics). We do have a whole set of weights and factors for 08 data, which covers the extrapolation from 08 to 2024. Also we have a separate set for 09 data. These two sets have seemingly different factors because the base years are different, even though the growth from 09 to 24 remains the same. Thus the weights are slightly different as well.

What do you mean by updating the weights and incomes to 2009? Do you mean if the user has 08 puf and wants to use it as 09 puf?

**Comment by feenberg** [comment]
On Fri, 8 Jan 2016, Amy Xu wrote:

> 
> @feenberg My bad wording. John provided the original version of code for extrapolation
> in fortran, and then I translated it into python and used this python version creating
> all the weights and factors needed in extrapolation (from CBO targets and SOI
> statistics). We do have a whole set of weights and factors for 08 data, which covers
> the extrapolation from 08 to 2024. Also we have a separate set for 09 data. These two
> sets have seemingly different factors because the base years are different, even
> though the growth from 09 to 24 remains the same. Thus the weights are slightly
> different as well.
> 
> What do you mean by updating the weights and incomes to 2009? Do you mean if the user
> has 08 puf and wants to use it as 09 puf?

Step 1. Take the 2008 puf and update puf variables to 2009. Call the 
resulting file puf2009f2008

Step 2. Use use puf2009f2008 in place of 2009 puf file. How can the 
computer tell it hasn't been given the 2009 PUF file?

In taxsim I have a routine

   call inflate(in,out,year)

that converts any year of data to any other year of data by an inflation 
factor. In taxsim this just involves multipling each element by a factor 
that depends on the source and target years. I have separate inflation 
factors for weight and all other items so the routine contains just two 
vectors of factors. Since John provides many for factors, the routine 
would be somewhat more complicated - there would have to be a matrix with 
a separate factor for each year and element.

I guess there is something about the present software that prevents 
something like this from being created. I suppose it has to do with 
changing the relative weights of individual records through time to match 
CBO targets. Even so, it should be possible to do my 2 steps above and get 
a rational result, even if 2010+ will not match exactly between 
puf2009f2008 and true puf2009.

dan

**Comment by MattHJensen** [comment]
@feenberg, are you thinking about how to make tax-calculator usable for researchers who might have the 2008 puf but not the 2009 puf? Are there other situations when a user might want to extrapolate the 2008 file using the 2009 extrapolation routine?

**Comment by feenberg** [comment]
On Sat, 9 Jan 2016, Matt Jensen wrote:

> 
> @feenberg, are you thinking about how to make tax-calculator usable for researchers
> who might have the 2008 puf but not the 2009 puf? Are there other situations when a
> user might want to extrapolate the 2008 file using the 2009 extrapolation routine?

Presumably we will update the calculator each year, and I would hope we 
wouldn't require the user to update the data each year - they may have 
reasons (expense, recession, continuity) not to want to follow.

Also, there are none-puf file files that people will want to use - SCF, 
CEX, PSID that may not be available for the year corresponding to the PUF, 
or may have a more recent year available. I would hate to see that ability 
excluded through lack of foresight on our part.

I know I sound like a broken record, but flexibility is the key to 
acquiring users and this is the key to many uses of taxsim. Perhaps I 
should let taxsim keep these users, and let taxbrain restrict itself to 
scoring. That gives each program a separate domain and they don't really 
compete with each other.

dan
