### ISSUE TITLE
How to move a GitHub pull request to a local Git branch?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#534]
T.J. (@talumbau), I imagine there is an easy way to do this, but my searching for an answer has not been successful.  

Consider the following situation: a contributor, who is not a member of the core development team, submits a pull request to the GitHub Tax-Calculator repository and a member of the core development team wants to evaluate this pull request (say, by running the py.test command without skipping the tests marked requires_pufcsv).  

I know that the core developer can go to the contributor's GitHub clone of the Tax-Calculator repository and download a zip file containing all the files in the branch that is the basis of the pull request.  I have done that a few times and have found it clumsy to say the least.  

So, my question is this: can the core developer somehow download the pull-request branch as a branch in the core developer's local Tax-Calculator repository?  Hope I'm asking the question clearly.  If not, please ask for clarification.

**Comment by MattHJensen** [comment]
Is this what you are looking for @martinholmer?

git fetch upstream pull/201/head:pr-201
git checkout pr-201

https://sethvargo.com/checkout-a-github-pull-request/

On Jan 20, 2016, at 8:20 AM, Martin Holmer <notifications@github.com<mailto:notifications@github.com>> wrote:


T.J. (@talumbau<https://github.com/talumbau>), I imagine there is an easy way to do this, but my searching for an answer has not been successful.

Consider the following situation: a contributor, who is not a member of the core development team, submits a pull request to the GitHub Tax-Calculator repository and a member of the core development team wants to evaluate this pull request (say, by running the py.test command without skipping the tests marked requires_pufcsv).

I know that the core developer can go to the contributor's GitHub clone of the Tax-Calculator repository and download a zip file containing all the files in the branch that is the basis of the pull request. I have done that a few times and have found it clumsy to say the least.

So, my question is this: can the core developer somehow download the pull-request branch as a branch in the core developer's local Tax-Calculator repository? Hope I'm asking the question clearly. If not, please ask for clarification.

**Comment by martinholmer** [comment]
Matt said:
> Is this what you are looking for @martinholmer?
>
> ```git fetch upstream pull/201/head:pr-201```
>  ```git checkout pr-201```
>
> https://sethvargo.com/checkout-a-github-pull-request/

Thanks for the tip!  Sounds like this will work just fine.  I'll try it later today.

cc @MattHJensen @talumbau @Amy-Xu @GoFroggyRun

**Comment by talumbau** [comment]
Yes that's actually really nice! Thanks Matt

**Comment by martinholmer** [comment]
Matt said:
> Matt said:
> Is this what you are looking for @martinholmer?
>
> ```git fetch upstream pull/201/head:pr-201```
> ```git checkout pr-201```

@MattHJensen,  I tried this today and it worked just fine.  Thanks for the tip!
