### ISSUE TITLE
Update tax law parameters for 2016

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#538]
IRS has published the new 2016 tax law parameters. We should update current_law_policy.json to include them.

There should be an article by James C Young in Tax Notes that includes all of the changes. This IRS document should also have them. https://www.irs.gov/pub/irs-drop/rp-15-53.pdf

**Comment by talumbau** [comment]
@MattHJensen does this need to be done before we deploy the additional years option on TaxBrain, as suggested in https://github.com/OpenSourcePolicyCenter/webapp-public/issues/135 ?

**Comment by MattHJensen** [comment]
Resolved by #554. Closing.
