### ISSUE TITLE
Distributing Marginal Income

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#549]
While examining how the marginal changes on wage and capital gain would affect unit's state taxes and charitable expenses, it seems that the coefficients for capital gain are significantly diminished, which is due to the high extrapolation factor of capital gain. Please refer to the table for details. ( **bold numbers** are estimates for wage while _Italic_ _numbers_ are estimates for capital gain)

| [numbers shown in cent]   | State Tax, MARS1 | State Tax, MARS2  | State Tax, MARS3 | State Tax, MARS4  | Charity~Wage | Charity~Capital Gain|
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Estimates before extrapolation  | **10.08**,  _2.62_  | **9.70**, _4.84_  | **16.86**, _2.17_  | **17.59**, _1.80_  | **3.39**  | _6.96_  |
| Estimates after extrapolation  | **11.80**, _0.05_  | **11.36**,  _0.09_  | **19.74**,  _0.04_   | **20.59**,  _0.03_   | **3.97**  | _0.13_  |

Not sure if we should still apply extrapolation in this case.

**Comment by MattHJensen** [comment]
@GoFroggyRun, I'm going to close this one until the full write up.
