### ISSUE TITLE
How to prevent mistakes in current_law_policy.json?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#559]
In #554 I identified and corrected the following bug

> _II_brk6, CG_thd2, _and, AMT_CG_thd2 values for married filing separately included a typo in 2015 where 232425 had been mistyped as 223425.

Could we discuss how to prevent bugs like this in the future? 

A couple of ideas from me are:

1) When we update these values every year, have one person do the work and then another person independently replicate. 

2) Perhaps test against internet taxsim for every year that we have hardcoded the IRS's parameter values in `current_law_policy.json`; after #554 is merged that would mean 2013 - 206. The reason not to go farther than this is that we might run into inconsistencies between how we inflate the parameter values into out years between internet taxsim and tax-calculator. 

What do you think of these ideas; any others? 

cc @martinholmer, @feenberg, @GoFroggyRun, @Amy-Xu

**Comment by feenberg** [comment]
I do endorse testing against taxsim - it shouldn't be difficult to create 
a dozen or so test cases that exercise all the important constants.

dan

**Comment by martinholmer** [comment]
Matt said:
> 2) Perhaps test against internet taxsim for every year that we have hardcoded the IRS's parameter values in current_law_policy.json; after #554 is merged that would mean 2013 - 2016. The reason not to go farther than this is that we might run into inconsistencies between how we inflate the parameter values into out years between internet taxsim and tax-calculator.

We already do extensive testing against Internet TAXSIM but only for 2013 and 2014.  You found typos in 2015 tax policy parameters.  Now that the 2015 tax forms are all available, I imagine that Internet TAXSIM policy parameters for 2015 will soon be (or maybe already are) exactly equal to the values on the 2015 forms (rather than being projected with some indexing rate).  Once Internet TAXSIM is in that state, I'd be happy to add 2015 tests to the taxcalc/validation/tests suite.

Dan,  where does Internet TAXSIM stand with regards to this issue?  Does it incorporate actual (rather than projected) tax policy parameters for 2015?

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by feenberg** [comment]
On Wed, 27 Jan 2016, Martin Holmer wrote:

> 
> Matt said:
> 
> Dan, where does Internet TAXSIM stand with regards to this issue? Does it incorporate
> actual (rather than projected) tax policy parameters for 2015?
>

We just finished the update, so please compare.

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
>>  Dan, where does Internet TAXSIM stand with regards to this issue? Does it incorporate  actual (rather than projected) tax policy parameters for 2015?
>
> We just finished the update, so please compare.

I've added a comparison of output from Internet TAXSIM and Tax-Calculator for a random sample of 2015 filing units in pull request #561.

@MattHJensen @GoFroggyRun @Amy-Xu

**Comment by martinholmer** [comment]
Martin said:
> I've added a comparison of output from Internet-TAXSIM and Tax-Calculator for a random sample of 2015 filing units in pull request #561.

Note that the cross-model validation work using this new c15.in sample of filing units revealed EITC differences that have lead to the discovery of incorrect EITC parameters in both models.  Other than having several people (other than the original author) check the contents of the ```current_law_policy.json``` file, I don't see any way to check the entered parameters values except for cross-model validation work.

@MattHJensen @feenberg @GoFroggyRun @Amy-Xu

**Comment by MattHJensen** [comment]
@martinholmer said:

> I don't see any way to check the entered parameter values except for cross-model validation work.

Agreed. 

Given ongoing cross-model validation work against TAXCALC.sas and internet TAXSIM, as well as early-stage testing with Tax Foundation, I am closing this issue.
