### ISSUE TITLE
How to read raw IRS 2008 PUF variables into Tax-Calculator

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#576]
Matt has sent me a list of the 202 variable names in the IRS 2008 PUF and I have compared those variable names with those in Records.VALID_READ_VARS, which is the list of variables the Tax-Calculator knows how to deal with.

I have found nine variable names in the IRS 2008 PUF that are not in Records.VALID_READ_VARS.  Here are those nine with their 2008 definition and my comments about which 2009 variables are related.
Below this list is complete documentation about how I generated this list, including the names Matt sent, the Python script that compares those names to VALID_READ_VARS, and the complete output of that script.

```
number_vars_in_puf2008_but_not_taxcalc=9
----------------------------------------

  e18425 : State and local income taxes

  e18450 : State Sales Taxes

  >>>>>> in IRS 2009 PUF, e18400 is "State and local taxes", which
         is not in IRS 2008 PUF.
  >>>>>> 2008-2009 RELATIONSHIP: e18425 + e18450 = e18400

  e25370 : Rent expenses mortgage interest, Schedule E, line 12

  e25380 : Rent/royalty expenses other interest, Schedule E, line 13

  >>>>>> in IRS 2009 PUF, p25380 is "Rent/Royalty Interest Expenses", which
         is not in IRS 2008 PUF
  >>>>>> 2008-2009 RELATIONSHIP: e25370 + e25380 = p25380

  STATE  : state code with values in 1-52 range (0 for high income units)

  >>>>>> state identifier not included in IRS 2009 PUF
  >>>>>> 2008-2009 RELATIONSHIP: STATE = 0

  e87500 : Hope Qualified Expenses--Limited (Prior Years only)

  e87510 : Hope One-Half Amount (Prior Years only)

  e87520 : Hope Credit

  >>>>>> Hope Credit is not being computed in Tax-Calculator, right?
  >>>>>> 2008-2009 RELATIONSHIP: e87500 = e87510 = e87520 = 0

  e87540 : Lifetime Learning Limited Amount

  >>>>>> don't know enough about education subsidies to know about this
  >>>>>> 2008-2009 RELATIONSHIP: e87540 = 0 ????????????
```

Comments and suggestions would be welcome.

cc @MattHJensen @feenberg @Amy-Xu @GoFroggyRun 

Here is the (slightly edited) file Matt sent me (called irs-2008-puf-vars.txt):
```
F1       =      E00200
F2       =      E00300
F3       =      E00400
F4       =      E00600
F5       =      E00650
F6       =      E00700
F7       =      E00800
F8       =      E00900
F9       =      E01000
F10      =      E01100
F11      =      E01200
F12      =      E01400
F13      =      E01500
F14      =      E01700
F15      =      E02000
F16      =      E02100
F17      =      E02300
F18      =      E02400
F19      =      E02500
F20      =      E03150
F21      =      E03210
F22      =      E03220
F23      =      E03230
F24      =      E03260
F25      =      E03270
F26      =      E03240
F27      =      E03290
F28      =      E03300
F29      =      E03400
F30      =      E03500
F31      =      E00100
F32      =      P04470
F33      =      E04250
F34      =      E04600
F35      =      E04800
F36      =      E05100
F37      =      E05200
F38      =      E05800
F39      =      E06000
F40      =      E06200
F41      =      E06300
F42      =      E09600
F43      =      E07180
F44      =      E07200
F45      =      E07220
F46      =      E07230
F47      =      E07240
F48      =      E07260
F49      =      E07300
F50      =      E07400
F51      =      E07600
F52      =      P08000
F53      =      E07150
F54      =      E06500
F55      =      E08800
F56      =      E09400
F57      =      E09700
F58      =      E09800
F59      =      E09900
F60      =      E10300
F61      =      E10700
F62      =      E10900
F63      =      E59560
F64      =      E59680
F65      =      E59700
F66      =      E59720
F67      =      E11550
F68      =      E11070
F69      =      E11100
F70      =      E11200
F71      =      E11300
F72      =      E11400
F73      =      E11570
F74      =      E11580
F75      =      E11581
F76      =      E11582
F77      =      E11583
F78      =      E10605
F79      =      E11900
F80      =      E12000
F81      =      E12200
F82      =      E17500
F83      =      E18425
F84      =      E18450
F85      =      E18500
F86      =      E19200
F87      =      E19550
F88      =      E19800
F89      =      E20100
F90      =      E19700
F91      =      E20550
F92      =      E20600
F93      =      E20400
F94      =      E20800
F95      =      E20500
F96      =      E21040
F97      =      P22250
F98      =      E22320
F99      =      E22370
F100     =      P23250
F101     =      E24515
F102     =      E24516
F103     =      E24518
F104     =      E24535
F105     =      E24560
F106     =      E24598
F107     =      E24615
F108     =      E24570
F109     =      P25350
F110     =      E25370
F111     =      E25380
F112     =      P25470
F113     =      P25700
F114     =      E25820
F115     =      E25850
F116     =      E25860
F117     =      E25940
F118     =      E25980
F119     =      E25920
F120     =      E25960
F121     =      E26110
F122     =      E26170
F123     =      E26190
F124     =      E26160
F125     =      E26180
F126     =      E26270
F127     =      E26100
F128     =      E26390
F129     =      E26400
F130     =      E27200
F131     =      E30400
F132     =      E30500
F133     =      E32800
F134     =      E33000
F135     =      E53240
F136     =      E53280
F137     =      E53410
F138     =      E53300
F139     =      E53317
F140     =      E53458
F141     =      E58950
F142     =      E58990
F143     =      P60100
F144     =      P61850
F145     =      E60000
F146     =      E62100
F147     =      E62900
F148     =      E62720
F149     =      E62730
F150     =      E62740
F151     =      P65300
F152     =      P65400
F153     =      E68000
F154     =      E82200
F155     =      T27800
F156     =      S27860
F157     =      P27895
F158     =      E87500
F159     =      E87510
F160     =      E87520
F161     =      E87530
F162     =      E87540
F163     =      E87550
F164     =      RECID
F165     =      S006
F166     =      S008
F167     =      S009
F168     =      WSAMP
F169     =      TXRT
C1 = AGIR1
C2 = DSI
C3 = EFI
C4 = EIC
C5 = ELECT
C6 = FDED
C7 = FLPDYR
C8 = FLPDMO
C9 = F2441
C10 = F3800
C11 = F6251
C12 = F8582
C13 = F8606
C14 = IE
C15 = MARS
C16 = MIdR
C17 = N20
C18 = N24
c19 = N25
C20 = PREP
C21 = SCHB
C22 = SCHCF
C23 = SCHE
C24 = STATE
C25 = TFORM
C26 = TXST
C27 = XFPT
C28 = XFST
C29 = XOCAH
C30 = XOCAWH
C31 = XOODEP
C32 = XOPAR
C33 = XTOT 
```

Here is the script that does the variable name comparisons (called vars.py):
```
"""
VARS.PY reads irs-2008-puf-vars.txt and
        compares included variable names with Records.VALID_READ_VARS
USAGE: python vars.py
"""

import sys
import os
import re
CUR_PATH = os.path.abspath(os.path.dirname(__file__))
sys.path.append(os.path.join(CUR_PATH, '..', 'tax-calculator'))
from taxcalc import Records


# create set of IRS 2008 PUF variable names with capitalization corrections
PUF08_VARS = set()
with open('irs-2008-puf-vars.txt', 'r') as ifile:
    for line in ifile:
        cols = line.split()
        var = cols[2]
        if re.match(r'[A-Z][0-9][0-9][0-9][0-9][0-9]', var):
          var = var.lower()
        elif re.match(r'F[0-9][0-9][0-9][0-9]', var):
          var = var.lower()
        elif re.match(r'N[0-9][0-9]', var):
          var = var.lower()
        elif re.match(r'S00[0-9]', var):
          var = var.lower()
        elif re.match(r'MIdR', var):
          var = var.upper()
        PUF08_VARS.add(var)
sys.stdout.write('number_vars_in_puf2008={}\n'.format(len(PUF08_VARS)))

# create copy of Records.VALID_READ_VARS set
TAXCALC_VARS = set(list(Records.VALID_READ_VARS))
sys.stdout.write('number_vars_in_taxcalc={}\n'.format(len(TAXCALC_VARS)))

# list vars in PUF08_VARS but not in TAXCALC_VARS
NOT_IN = PUF08_VARS - TAXCALC_VARS
sys.stdout.write('{}={}\n'.format('number_vars_in_puf2008_but_not_taxcalc',
                                  len(NOT_IN)))
for var in list(NOT_IN):
    sys.stdout.write('  {}\n'.format(var))

# list vars in TAXCALC_VARS but not in PUF08_VARS
NOT_IN = TAXCALC_VARS - PUF08_VARS
sys.stdout.write('{}={}\n'.format('number_vars_in_taxcalc_but_not_puf2008',
                                  len(NOT_IN)))
for var in list(NOT_IN):
    sys.stdout.write('  {}\n'.format(var))
```

And here is the output of that script:
```
number_vars_in_puf2008=202
number_vars_in_taxcalc=228
number_vars_in_puf2008_but_not_taxcalc=9
  e87540
  e25380
  e87520
  e25370
  STATE
  e18450
  e87500
  e87510
  e18425
number_vars_in_taxcalc_but_not_puf2008=35
  e00200p
  e87870
  e00200s
  e87875
  e15210
  p87521
  n30
  p25380
  matched_weight
  e10960
  f8936
  p87482
  e15250
  agedp1
  agedp3
  agedp2
  f8910
  earnsplit
  e02100s
  filer
  e02100p
  e15360
  e10950
  AGERANGE
  e18400
  e87880
  wage_head
  gender
  age
  e18600
  wage_spouse
  e15100
  f8829
  e00900p
  e00900s
```

**Comment by GoFroggyRun** [comment]
@martinholmer:
Thanks for looking into this issue. The transformation 
```
e18425 + e18450 = e18400
e25370 + e25380 = p25380
STATE = 0
e87500 = e87510 = e87520 = 0
e87540 = 0 
```
looks good to me. It seems the best we could do, without excessive modifications in `functions.py`.

My concern is that whether making such transformation would affect the consequential results. This is, however, hard to say before we have compared our 08 puf results against ones from other institutions. 
Also, I was wondering where you think would be appropriate to handle these transformations? Probably in `records.py`?

**Comment by martinholmer** [comment]
Sean asked:
> Also, I was wondering where you think would be appropriate to handle these transformations? Probably in records.py?

Actually, no.  In keeping with Matt's long-run goal of keeping data preparation separate from tax calculations, I think it is best to do the following:

(1) Add a script to the taxdata repository that creates a CSV-formatted 2008 PUF file with the variable names suitable for reading by Tax-Calculator and with the variable transformations we've discussed above.

(2) Put a copy to the file generated by step (1) in some private place close to (but not in) the tax-calculator source code tree.

(3) Write a script in the tax-calculator/taxcalc/altdata directory that reads the file mentioned in step (2), processes it, and writes out some results in a file in that altdata directory.

(4) And finally, compare the output generated in step (3) with an output file generated by another organization's model that used the 2008 input file mentioned in step (1).

This process would keep the 2008 file confidential, but expose to all our preparation of the file and how we processed it in Tax-Calculator to produce the results.

Does this make sense?  Is there a better way to proceed?
I would have already written this up as part of this issue, except that Amy will not be back until the end of the month to do the file preparation work in the taxdata repository.

cc @GoFroggyRun @MattHJensen @feenberg @Amy-Xu

**Comment by feenberg** [comment]
On Fri, 12 Feb 2016, Martin Holmer wrote:

> 
> Sean asked:
>
>       Also, I was wondering where you think would be appropriate to handle these transformations? Probably in
>       records.py?
> 
> Actually, no. In keeping with Matt's long-run goal of keeping data preparation separate from tax calculations, I think
> it is best to do the following:
> 
> (1) Add a script to the taxdata repository that creates a CSV-formatted 2008 PUF file with the variable names suitable
> for reading by Tax-Calculator and with the variable transformations we've discussed above.
>

I agree with this. We should have a input format for the tax calculator 
that is constant through time, and have separate programs to convert 
various other files into that format. Otherwise adding new files will 
become progressively more difficult as they are added.

dan

**Comment by martinholmer** [comment]
Dan said:
> I agree with this [procedure for reading 2008 PUF data]. We should have a input format for the tax calculator that is constant through time, and have separate programs to convert various other files into that format. Otherwise adding new files will become progressively more difficult as they are added.

Dan,  I'm glad to hear you agree.  You've had much more experience than I have with processing tax data from different years (that have slightly different formats and variables).

@feenberg @GoFroggyRun @MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
In light of the changes in pull request #603, all the variables in Records.UNUSED_READ_VARS set should be removed from the 2008 PUF file and only variables in the Records.VALID_READ_VARS set should be included in the 2008 PUF file prepared in the taxdata repository.  This means, I think, that the only remaining variable transformation (from the above discussion) is as follows:
```
e18425 + e18450 ---> e18400
```

**Comment by Amy-Xu** [comment]
@martinholmer The steps transforming 08 PUF data for current Tax-Calculator makes a lot sense to me. Was just wondering where you're planning to incorporate the extrapolation step? I mean the extrapolation that takes in 08 PUF with variable transformations and blows it up to 09 values.

**Comment by martinholmer** [comment]
Amy said:
> The steps transforming 08 PUF data for current Tax-Calculator make a lot sense to me. Was just wondering where you're planning to incorporate the extrapolation step? I mean the extrapolation that takes in 08 PUF with variable transformations and blows it up to 09 values.

Welcome back!  Hope your trip was enjoyable.

No, we do not want to do any extrapolation of the 2008 data.  We simply want the current version of the Tax-Calculator to read in raw 2008 PUF variables (from a .csv file) that are in the Records.VALID_READ_VARS set without any data modification at all.  I know this is not realistic, but that is not the goal.  The goal is to have a cross-model validation capability.  Does that make sense?

@Amy-Xu @MattHJensen @feenberg @GoFroggyRun

**Comment by Amy-Xu** [comment]
Thank you Martin. I see. If we do not care about the accuracy of results, everything looks good to me. Do you already have the script ready? Do you prefer creating a new folder for 08 PUF?

**Comment by martinholmer** [comment]
Amy said:
> Thank you Martin. I see. If we do not care about the accuracy of results, everything looks good to me. Do you already have the script? Do you prefer creating a new folder for 08 PUF?

I don't have a script; thought you could do that in the taxdata repo in a place of your choosing.

I don't believe we can put this new puf2008.csv file anywhere in either the taxdata or the tax-calculator repositories because it is proprietary IRS data.  I think you need to distribute it like you distribute the standard ```puf.csv``` file.

@Amy-Xu @MattHJensen @feenberg @GoFroggyRun

**Comment by martinholmer** [comment]
Tax-Calculator issue #576 has been resolved by taxdata pull request 13.
