### ISSUE TITLE
Wild Imputed Amount for Numextra

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#577]
In `reocrds.py` we imputed `numextra` in this way:
```
        self._numextra = np.where(
            np.logical_or(self.AGERANGE >= 6,
                          np.logical_and(self.FDED != 2,
                                         np.logical_and(
                                             self.AGERANGE <= 0,
                                             self.e02400 > 0))),
            self._txpyers,
            np.where(np.logical_and(self.FDED == 2,
                                    self.p04470 >
                                    std_2009[self.MARS - 1]),
                     np.where(self.MARS != 2,
                              (self.p04470 -
                               std_2009[self.MARS - 1]) /
                              std_aged_2009[0],
                              (self.p04470 -
                               std_2009[self.MARS - 1]) /
                              std_aged_2009[1]), 0))
```
But It seems that there are 84 records in 08 puf will have `numextra` of amount more than 2 after the imputation process under 2014 law, where the largest number should be 2135. 

@feenberg: 
I'm not quite sure why this is happening. If I were not mistaken, `numextra` shall not exceed 2. And I was also wondering whether it's a good idea to cap `numextra` accordingly based on units' MARS during imputation phase.
Please advice, thanks!

cc @martinholmer @MattHJensen

**Comment by martinholmer** [comment]
Sean said:
> In ```records.py``` we imputed ```_numextra``` in this way:
> ```
> COMPLICATED STATEMENT FROM the **impute_variables** function ...
> ```
> But It seems that there are 84 records in 08 puf will have numextra of amount more than 2 after the imputation process under 2014 law, where the largest number should be 2135.

Sean,  The above statement in ```impute_variables``` will **never** be executed because the ```impute_variables``` function will **never** be called for 2008 data.  So, unless I'm missing something, I don't see that there is anything to worry about.  You should never be trying to use the 2009 data "imputation process" on any data except data for 2009.  Can you provide us some background on what you're doing and why this issue came up?

cc @GoFroggyRun @feenberg @Amy-Xu @MattHJensen

**Comment by feenberg** [comment]
Can you supply the amount of the standard deduction for one of the 
offending returns? The code below is difficult to follow, but I think it 
should work unless the file contains records with a standard deduction 
larger than can be achieved with 2 elderly taxpayers. If we had the data, 
we could tell for sure.

dan

**Comment by MattHJensen** [comment]
Thanks @feenberg, but give us time for a little more debugging on our end first. I'll talk to @gofroggyrun about this.

**Comment by MattHJensen** [comment]
@GoFroggyRun, as @martinholmer pointed out, the imputation in the code won't work with 09 data, so it is expected that the imputation process would yield large numextra values. Hold off on this project until we have a chance to talk.

**Comment by martinholmer** [comment]
Sean said: 
> More information on this issue:
> Using [20]09 puf[.csv] and go through the imputation process yields 866 records (out of 219814) with ```_numextra``` more than 2, where the largest number is 45.9.

I have no clue about the logic behind imputing ```_numextra``` in the Records class ```impute_variables``` method.   If you use ```git blame``` you can see that the complex statement that sets the value of ```_numextra``` was written by Amy Xu on December 22, 2015.

cc @GoFroggyRun @MattHJensen @feenberg @Amy-Xu

**Comment by GoFroggyRun** [comment]
@martinholmer 
Thanks for your comments on this issue. Sorry that I'm not quite familiar with the imputation process. I'll switch to other concerns for the moment.

**Comment by MattHJensen** [comment]
@GoFroggyRun, my apologies, I see that you were using the 09 data in the latest comment:
 
> Using 09 puf and go through the imputation process yields 866 records (out of 219814) with numextra more than 2, where the largest number is 45.9.

Please go ahead and proceed with @feenberg's request:

> Can you supply the amount of the standard deduction for one of the
offending returns? The code below is difficult to follow, but I think it
should work unless the file contains records with a standard deduction
larger than can be achieved with 2 elderly taxpayers. If we had the data,
we could tell for sure.

**Comment by GoFroggyRun** [comment]
Dealt with in #588 .

**Comment by martinholmer** [comment]
Sean,
Do you want to close issue #577 now that pull request #588 has been merged into the master branch?

cc @GoFroggyRun

**Comment by GoFroggyRun** [comment]
Sure. Thanks for the reminder @martinholmer .
