### ISSUE TITLE
Allocation of Marginal Income over Itemized Deduction Items

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#583]
We are interested in estimating how state income tax and charitable contribution would change accordingly with extra dollar being added to a person's income, or, more specifically, a person's wage/capital gain. The estimates are obtained from some simple regressions on extrapolated 09 puf data (to 2015), with a few filters applied to the data, and some subgroup regressions according to MARS. More details on the filters will be posted later. 

The tables for wage are displayed as follow: (numbers shown in cents)

| Wage~State Tax   | MARS1 |  MARS2  |  MARS3 |  MARS4  |  
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| Estimates before extrapolation(09)  | **10.08**  | **9.70** | **16.86**  | **17.59**  | 
| Estimates after extrapolation(15)  | **11.80** | **11.36**  | **19.74**   | **20.59**  |

|  Wage~Charity |  |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Estimates before extrapolation(09)  | **3.39** |
| Estimates after extrapolation(15)  | **3.97** |

And the tables for capital gain: (numbers shown in cents)

| Capital Gain~State Tax   | MARS1 |  MARS2  |  MARS3 |  MARS4  |  
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| Estimates before extrapolation(09)  | _2.62_  |  _4.84_  |  _2.17_  | _1.80_  |
| Estimates after extrapolation(15)  |  _0.05_  |   _0.09_  |   _0.04_   |   _0.03_   | 

|  Capital Gain~Charity | |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Estimates before extrapolation(09)  | _6.96_|
| Estimates after extrapolation(15)  | _0.13_  |
(Please note all estimates are before #575 being merged, so there might be some very minor change on the estimates for capital gain, I'd like to, however, acquire as many ideas as possible.)

The issue here is how to deal with the extrapolation process: since the extrapolation factor for capital gain overwhelms extrapolation factors for charitable contribution and state income tax, applying factors respectively will result in significantly diminished estimates that are associated with capital gain. 

I'm not sure what's the best way to deal with this. And, at least as far as I am concerned, I don't think our extrapolation factors seem appropriate in this case. Would ignore the extrapolation process and use the before-extrapolated coefficients be a good approach? 

@martinholmer @feenberg Any comments, concerns or remarks would be appreciated. 

cc @MattHJensen

**Comment by feenberg** [comment]
On Fri, 5 Feb 2016, Sean.Wang wrote:

> 
> We are interested in estimating how state income tax and charitable contribution would
> change accordingly with extra dollar being added to a person's income, or, more
> specifically, a person's wage/capital gain. The estimates are obtained from some
> simple regressions on extrapolated 09 puf data (to 2015), with a few filters applied
> to the data, and some subgroup regressions according to MARS. More details on the
> filters will be posted later.

Is this a regression of extrapolated values on other extrapolated values? 
What is the rationale for that?

What is the dependent variable? What are the independent variables? What 
is the sample? Itemizers? Do you exclude taxpayers that would not itemize 
if they had no charitable giving?

dan

**Comment by GoFroggyRun** [comment]
@feenberg :

Thanks for your comments on this issue. And terribly sorry for the late reply. I have attached some more details on the data and models as attachment. Please take a look and let me what your thoughts are. 

[State_Charity.pdf](https://github.com/open-source-economics/Tax-Calculator/files/126870/State_Charity.pdf)

**Comment by MattHJensen** [comment]
I believe that this issue is resolved via #788, which enables TC users to specify tax-units' marginal propensity to consume deductible expenses. 

Related work, to identify deductible expenses for standard deduction files, is covered by https://github.com/open-source-economics/taxdata/issues/32. 

@GoFroggyRun, if you agree with my assessment, could you close this issue?
