### ISSUE TITLE
New self-employed income info in 09 PUF

### ISSUE THREAD

**Issue by Amy-Xu** [open-source-economics/Tax-Calculator#632]
When I was working on a separated task, I happened to find there were two new variables in 09 PUF that haven't caught anyone's attention. 
- e30400: total self-employment income subject to SS tax from schedule SE
- e30500: self-employment income subject to SS tax, secondary taxpayer 

Thought this two variables might be able to provide a more accurate estimate on earning split, which currently we're using CPS imputations together with the sum of `e00900` and `e02100`. Just curious what you think about this? @feenberg @martinholmer

**Comment by martinholmer** [comment]
Amy,  This is a good find!  Let's put this enhancement on a medium-priority track (rather than on a rush-priority track).

I see in the source code, that self-employment income included in the OASDI and HI tax base is the sum of e00900 (combined taxpayer and spouse Schedule C income) and e02100 (combined farm income).

I'm not very knowledgeable:  what's the relationship between Schedule SE, on the one hand, and Schedule C and farm income, on the other hand?

cc @Amy-Xu @feenberg @MattHJensen

**Comment by feenberg** [comment]
On Tue, 8 Mar 2016, Martin Holmer wrote:

> 
> Amy, This is a good find! Let's put this enhancement on a medium-priority
> track (rather than on a rush-priority track).
> 
> I see in the source code, that self-employment income included in the OASDI
> and HI tax base is the sum of e00900 (combined taxpayer and spouse Schedule C
> income) and e02100 (combined farm income).
> 
> I'm not very knowledgeable: what's the relationship between Schedule SE, on
> the one hand, and Schedule C and farm income, on the other hand?

Some Schedule C and F income is reportable as wages, and some as property 
income. In taxcalc.sas we back out self-employment income from E09400, 
which is available every year:


if e09400 gt .153*_ssmax{flpdyr} then
    _sey = (e09400 - .124*_ssmax{flpdyr})/(.029*.9235);
else
    _sey = e09400/(.153*.9235);

_sey9235 = max(0,.9235*_sey);

Note that there are 2 places on the tax form for self-employment tax, one 
is the adjustment for one-half of self-employment tax (E3260) and the 
other is the amount owed (E09400). They are not always consistent, I don't 
know why that is.

dan

**Comment by martinholmer** [comment]
@Amy-Xu said on March 4, 2016, in Tax-Calculator issue #632:
> When I was working on a separated task, I happened to find there were two new variables in 2009 IRS-SOI PUF that haven't caught anyone's attention.
>
> e30400: total self-employment income subject to SS tax from schedule SE
> e30500: self-employment income subject to SS tax, secondary taxpayer
>
> Thought this two variables might be able to provide a more accurate estimate on earning split, which currently we're using CPS imputations together with the sum of e00900 and e02100. Just curious what you think about this?

As I said at the time, this is a good find.  And now, over a year later, these two variables are being used to construct two new variables in the `puf.csv` file and those variables are being used to compute more accurately the self-employment (payroll) tax.  And we are also following your suggestion to use `e30400` and `e30500` to split other self-employment income.  All these changes are in [taxdata pull request 107](https://github.com/open-source-economics/taxdata/pull/107) and [taxcalc pull request 1438](https://github.com/open-source-economics/Tax-Calculator/pull/1438).

Thanks for pointing out the existence of these two PUF variables.  Now that your suggestions have been implemented, I'm going to close this issue.

@MattHJensen @feenberg @andersonfrailey @hdoupe @codykallen
