### ISSUE TITLE
E-variable information spreadsheet clean up

### ISSUE THREAD

**Issue by Amy-Xu** [open-source-economics/Tax-Calculator#633]
After moving [this spreadsheet](https://github.com/Amy-Xu/Tax-Calculator/blob/sum-stats/taxcalc/e_variable_info.csv) to Tax-Calculator, I think we might need to clean this file up, and integrate several files with similar functionality.
- Different versions of PUF has different variable sets, and they're quite different. Probably we should keep the union here, and label clearly which version one variable's from.
- If one p-variable or t-variable or s-variable previously labeled as e-variable, we should also point that out.
- In terms of description, it seems the first column of this file overlaps a lot with [var_labels.txt](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/var_labels.txt). In addition, [the newly-generated file](https://github.com/Amy-Xu/Tax-Calculator/blob/sum-stats/taxcalc/comparison/variable_stats_summary.csv) also contains a description column. We need to find a way to keep all three sources consistent. In short run, I might create a script to check the consistency. But in long run, we should probably integrate the three sources in some way.

**Comment by martinholmer** [comment]
Amy said:
> In terms of description, it seems the first column of this file overlaps a lot with var_labels.txt. In addition, the newly-generated file also contains a description column. We need to find a way to keep all three sources consistent. In short run, I might create a script to check the consistency. But in long run, we should probably integrate the three sources in some way.

Why not just delete ```var_labels.txt``` and the test that ensures it is consistent with the Records.VALID_READ_VARS set?

@Amy-Xu @MattHJensen

**Comment by martinholmer** [comment]
@Amy-Xu said on March 4, 2016, in issue #633:
> After moving this spreadsheet to Tax-Calculator, I think we might need to clean this file up.

@zrisher has "cleaned this [`e_variable_info.csv`] file up" to some extent in pull request #853, but there is still much more to do with respect to issue #633.  For example, there are many variable in the `e_variable_info.csv` file that are no longer in the Tax-Calculator `VALID_READ_VARS` set.  For a listing of those variable, see the `var_labels.txt` file, which is keep in sync with `Records.VALID_READ_VARS` by a test in the `test_records.py` file.

@MattHJensen @zrisher @Amy-Xu @feenberg @GoFroggyRun

**Comment by zrisher** [comment]
The columns that tell us which Tax Form / Line / Section each variable relates to are also missing some data, which will be included in my Luca PR. Because some of the mappings are not 1-1, documenting them in the TaxForm classes I propose may be a better option than in this file. That will be easier to discuss once my PR is actually opened, though. :smile:

**Comment by martinholmer** [comment]
@zrisher said:
> The columns that tell us which Tax Form / Line / Section each variable relates to are also missing some data, which will be included in my Luca PR. Because some of the mappings are not 1-1, documenting them in the TaxForm classes I propose may be a better option than in this file. That will be easier to discuss once my PR is actually opened, though.

Sounds good.  We're all looking forward to your Luca contributions.

**Comment by martinholmer** [comment]
What is the status of issue #633 with respect to cleaning up the `e_variable_info.csv` file?
Is that file still considered important?  If so, how to we ensure that it does not become out-of-date? 

@MattHJensen @Amy-Xu @zrisher @feenberg

**Comment by Amy-Xu** [comment]
@martinholmer Somehow I missed your initial comment on this issue -- I have very mixed feeling on var_labels.txt in that last time when I tried to see what e01500 and e01700 were and got really confused, which can only be more confusing for other users not familiar with puf variables. Should we keep it in the repo? I'm not quite sure what additional information is provided in var_lables.txt but not `e_variable_info.csv`.

Regarding how to ensure this CSV file doesn't become out-of-date, I think we could do it once or twice a year when a new puf or 1040 coming out -- manually go through the variables currently used by TC and whether line numbers/definition have changed or not. It might sound like a bit of work, but I think it worth the time.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> Somehow I missed your initial comment on this issue -- I have very mixed feeling on `var_labels.txt` in that last time when I tried to see what e01500 and e01700 were and got really confused, which can only be more confusing for other users not familiar with puf variables. Should we keep it in the repo? I'm not quite sure what additional information is provided in `var_lables.txt` but not `e_variable_info.csv`.

Maybe there is no additional information, but at least a human can read it.  And the unit tests ensure that the variable list is correct, which is something that is not true for `e_variable_info.csv`.  Don't you think "users not familiar with puf variables" would be confused by that?

@Amy-Xu continued:
> Regarding how to ensure [the `e_variable_info.csv`] file doesn't become out-of-date, I think we could do it once or twice a year when a new puf or 1040 coming out -- manually go through the variables currently used by TC and whether line numbers/definition have changed or not. It might sound like a bit of work, but I think it worth the time.

Are you volunteering to do this?  The experience of the past few months shows that if being up-to-date is not tested as part  of the unit tests, the `e_variable_info.csv` file will become out-of-date fairly quickly.

@MattHJensen

**Comment by Amy-Xu** [comment]
>Maybe there is no additional information, but at least a human can read it. And the unit tests ensure that the variable list is correct, which is something that is not true for e_variable_info.csv. Don't you think "users not familiar with puf variables" would be confused by that?

Hmmmmm didn't realize e_variable_info.csv is that bad. You meant a human being with a normal range of intelligence score couldn't read it? If that's the case, we should find what exactly is difficult and modify the current version to make it more straightforward.

>Are you volunteering to do this? The experience of the past few months shows that if being up-to-date is not tested as part of the unit tests, the e_variable_info.csv file will become out-of-date fairly quickly.

I can do it if I have time. It also seems to be a very good task for a new intern or RA as a warming-up exercise.

**Comment by martinholmer** [comment]
With respect to issue #633 and @Amy-Xu most recent comments, I think we should remove the `var_label.txt` file and associated test, which is what I suggested on 15-Mar-2016.
I'll be happy to do that this afternoon.

@MattHJensen

**Comment by zrisher** [comment]
This issue asks that we integrate and update three files that contain information about Records variables:
* `var_labels.txt` - per the above this was removed in PR #1082. ✔️ 
* `variable_stats_summary.csv` - the descriptions in here are pulled from `e_variable_info.csv`. ✔️ 
* `e_variable_info.csv` - Has various data quality issues as mentioned above. This is the remaining to-do.

Additional sources of Records variable info:
* `Records.py` - tells us if they're read, required, calculated, and floats or ints
* US Tax Form classes - tell us how they map to form fields


The data included in `e_variable_info.csv` is:

* label/definition/description - Definitely useful
* Form field mappings, Confidence in match, Version of form (if not 2014) - As discussed, this is not always 1-1 so can't be completely described in this format, and it's now available in the Tax Form classes
* Input in PUF & Relevant to Other Users (has tax form and in puf) - These could be derived programatically, but is it useful to anyone?
* read-to-calculated var mappings & Equivalent Codes - Difficult to derive programatically, but useful to anyone?

Given that this file has been out of date for quite some time and no one has complained, I'm guessing that the latter two groups aren't useful. @Amy-Xu @feenberg @MattHJensen might be able to speak to that. If that's the case, then the only remaining useful info provided by this file is the variable descriptions. 

**Thus I propose that we remove everything besides the variable descriptions in  `e_variable_info.csv`, update them to the current Record variable set, and call it a day.** We might also consider refactoring this file to JSON for easier consumption by programs using TaxCalc (i.e. TaxBrain), or even simply move the list of descriptions to a dict in `Records.py`.

@martinholmer

**Comment by martinholmer** [comment]
Merged pull request #1294 integrates into Records class logic the `records_variables.json` file, which was originally developed by @zrisher in pull request #1179.  This `records_variables.json` file is intended to replace several older variable documentation files, including the `e_variable_info.csv` file.  Given this line of development, further improvements in the `e_variable_info.csv` file are no longer required.  As a result, issue #633 ---  E-variable information spreadsheet clean up --- is being closed.
