### ISSUE TITLE
Numba should not be a dependency of `taxcalc`

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#659]
With the merge of #621, it would be helpful if the conda package for taxcalc did not have in its set of dependencies the numba package. Most users don't install taxcalc via a conda package, so it likely makes little difference to users. Typically, they would create a conda environment based on the environment.yaml in this repo and then work directly with the source repository, locally installing via the `setup.py` if necessary. This workflow would not change. This change would be very helpful in automated deployments, especially on Heroku, where the size of the deployed code is limited. Without requiring numba, the `taxcalc` package is much smaller. This should be done in such a way that if taxcalc is run without numba, it will succeed, but give warnings that the run time will be long because numba is not installed. If it runs and numba is present, it will behave as it does today.

**Comment by martinholmer** [comment]
T.J. said among other things:
> It would be helpful if the conda package for taxcalc did not have in its set of dependencies the numba package. [... explanation for why this would be very helpful ...]

So what would have to be done to the Tax-Calculator code in order to reach this desirable goal?

@talumbau

**Comment by talumbau** [comment]
#713 is the PR that will resolve this issue. Needs at least another commit which I hope to do this week.

**Comment by martinholmer** [comment]
T.J. said:
> #713 is the PR that will resolve this [#659] issue. Needs at least another commit which I hope to do this week.

But this seems to be a waste of your valuable time because all of the code that you're changing in #713 is soon moving out of `records.py` to the taxdata repository.  See discussion in issue #688.

@talumbau @MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
Merged pull request #754 seems to have resolved this issue #659.
@talumbau and @MattHJensen, are there other aspects to this issue, or should issue #659 be closed?

**Comment by martinholmer** [comment]
Martin Holmer said on May 27:
> Merged pull request #754 seems to have resolved this issue #659.
> @talumbau and @MattHJensen, are there other aspects to this issue, or should issue #659 be closed?

T.J.'s work in merged pull request #799 --- plus no comments on this issue over the past two months --- suggests that this issue #659 has been resolved.
