### ISSUE TITLE
conda.recipe\run_test fails when running the standard test suite

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#660]
Following the [getting started guide](http://taxcalc.readthedocs.org/en/latest/contributor_guide.html), upon running `py.test -m "not requires_pufcsv"` a user is presented with 111 successes and 1 error:

```
conda.recipe\run_test.py:1: in (module)
    import taxcalc
E   ImportError: No module named `taxcalc`
```

I'm not super familiar with pytest and standard setups, but I have to imagine that this test is only meant to be run after Conda follows the recipe to build the package (especially since the above line is the entire test). 

When run from the taxcalc repo itself and not building, it makes sense that this would fail, correct? 

If so, should a contributor use one of pytest's [skipping methods](https://pytest.org/latest/skipping.html) to avoid this test?

**Comment by talumbau** [comment]
welcome back @zrisher! This should be solved via an entry in a top level setup.cfg, but right now it basically isn't. As I'm sure you see, `pytest` has a fairly zealous test discovery mechanism. If it finds a Python module starting the `test`, it runs it! We don't want to run the test for the conda recipe when running the tests, so the typical usage looks like this (stolen from the .travis.yml):

```
py.test -v -m "not requires_pufcsv" --pep8 taxcalc/tests/
```

so we point it a taxcalc/tests to start off. That would be a quick fix for your case, but we could also give it better directives in a setup.cfg so it wouldn't confuse people.

**Comment by zrisher** [comment]
Thanks @talumbau! 

Looking at https://pytest.org/latest/customize.html, it seems like the best way to do this is including a line into setup.cfg with `testpaths = taxcalc`. 

My only concern with this approach would be that Conda would also make note of it and skip the Conda-specific test. I couldn't find much info online on how Conda discovers and runs tests besides this page: http://conda.pydata.org/docs/building/recipe.html. My interpretation is that it only runs the tests in the recipe folder, so we should be ok. But I imagine you know more than I do on this.

**Comment by talumbau** [comment]
There are two things going on here:

 - we have a [conda recipe](http://conda.pydata.org/docs/building/recipe.html) directory at the top of this directory. A conda recipe directory is just some directory that contains certain files. The files that the directory contains are files that are useful when one wants to create a conda package using the [conda build](http://conda.pydata.org/docs/build_tutorials/pkgs2.html) tool. One of the optional files one can put in a conda recipe is called `run_test.py`. This is used by the build tool to test whether the creation of a package was successful. So, there's no real concept of a "conda-specific test" but this optional test module is sort of like that, in the sense that conda build will execute that module when building a package.

- we use pytest to test our code and have done a few things to our test suite that are pytest-specific. By default, pytest looks for any .py file that has the string `test` in it, starting in the current directory and then working its way down when it is looking for tests. This default behavior will find the `run_test.py` file in the conda recipe directory.

So, now you see how the two worlds have collided. It seems like your PR #670 is reasonable, but I'm surprised that your change did not require a change to the .travis.yml. Does #670 allow one to run `py.test` from the top of the repo and miss the test script in the recipe directory? If so, perhaps we should modify what happens in the .travis.yml as well.

**Comment by zrisher** [comment]
>  Does #670 allow one to run py.test from the top of the repo and miss the test script in the recipe directory?

Yes!

> If so, perhaps we should modify what happens in the .travis.yml as well.

The test command in .travis.yml is:

```
py.test -v -m "not requires_pufcsv" --pep8 taxcalc/tests/
```

Which provides a path directly to the tests at `taxcalc/tests/`. With #670 added this is equivalent to running:

```
py.test -v -m "not requires_pufcsv" --pep8
```

However, the latter would pick up any tests added later to other directories as well. Would you like me to switch it from the first to the second in #670?

**Comment by talumbau** [comment]
I think that would be good. Any unintended consequence would be that Travis CI runs additional tests that perhaps we weren't expecting, but that is surely better than assuming Travis CI is running something but it is not. If it's the first case and it fails, we will see it and can either fix it or mark the test appropriately (if it should not be run by Travis CI).

**Comment by zrisher** [comment]
Updated #670 accordingly!
