### ISSUE TITLE
Thoughts on comparisons of taxcalc.sas and Tax-Calculator results?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#698]
I would be interested in your reactions to the results described in the [taxcalc/taxcalcsas/README.md](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/taxcalcsas/README.md) file.

@feenberg @GoFroggyRun @MattHJensen @Amy-Xu

**Comment by MattHJensen** [comment]
> I would be interested in your reactions to the results described in the taxcalc/taxcalcsas/README.md file.

My reaction is that this is better than where we were a couple of weeks ago! Is the strategy/technique for ferreting out the other differences documented somewhere?

**Comment by martinholmer** [comment]
Matt asked:
> Is the strategy/technique for ferreting out the other differences documented somewhere?

We have decided to delay the investigation of the taxcalc.sas-vs-Tax-Calculator differences described in [the README.md file](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/taxcalcsas/README.md) until NBER finishes its own comparison of taxcalc.sas results and Internet-TAXSIM results.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by martinholmer** [comment]
In the near future, we are going to embark on a comparison of Tax-Calculator and taxcalc.sas output generated from `puf.csv` input.

**Comment by feenberg** [comment]
On Tue, 10 May 2016, Martin Holmer wrote:

> 
> In the near future, we are going to embark on a comparison of Tax-Calculator and
> taxcalc.sas output generated from puf.csv input.

We have been making changes to taxcalc.sas based on a comparison with the 
full (200 variable) fortran calculator. We have nearly completed the 
comparison with 2009 law and can send the update any time. However we are 
continuing to work on this, and it might be best for you to tell us when 
you need the updated version, and I can send it then.

dan

**Comment by martinholmer** [comment]
Dan said:
> We have been making changes to taxcalc.sas based on a comparison with the full (200 variable) fortran calculator. We have nearly completed the comparison with 2009 law and can send the update any time. However we are continuing to work on this, and it might be best for you to tell us when you need the updated version, and I can send it then.

Dan @feenberg,  Thanks for the helpful information. Could you send me via email the updated taxcalc.sas file as soon as you finish the "nearly completed" work with the 2009 law?  We can begin our work with that version and switch to even-more-tested versions of taxcalc.sas in the future.  When do you think you will finish with the 2009 work?  No rush; just want some kind of idea to plan my own work schedule.

@MattHJensen @GoFroggyRun

**Comment by martinholmer** [comment]
Reopening issue #698 in light of new discussion.

**Comment by martinholmer** [comment]
Martin asked Dan @feenberg:
> Could you send me via email the updated taxcalc.sas file as soon as you finish the "nearly completed" work with the 2009 law? 

Just wanted to tell you that there is no rush because I will be out-of-town from May 14th thru May 23rd.
