### ISSUE TITLE
Possible Issues When Implementing Reform 

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#710]
I happened to notice that, when implementing reforms, different expressions could lead to different results. 

As an example, if we specify two reform as follow:

```
reform1 = {2014: {'_EITC_rt':[[0, 0, 0, 0]]
                 ,'_EITC_prt':[[0, 0, 0, 0]]}
          }
policy1.implement_reform(reform1)

reform2 = {2014: {'_EITC_rt':[[0, 0, 0, 0]]},
           2014: {'_EITC_prt':[[0, 0, 0, 0]]
                 }
          }
policy2.implement_reform(reform2)
```
, which are essentially identical. 

The results, however, will be different:

Reform 1:
![screen shot 2016-04-26 at 3 43 12 pm](https://cloud.githubusercontent.com/assets/13324931/14831906/9edf799a-0bc5-11e6-917b-dc68e1abe9a5.png)

Reform 2:
![screen shot 2016-04-26 at 3 43 18 pm](https://cloud.githubusercontent.com/assets/13324931/14831911/a614bd6a-0bc5-11e6-85c0-90e35184d16f.png)

The issue is that, while trying to implement some reforms, each year entry can only be modified once, and thus all reforms for that specific year shall be included. I thought it would be helpful to have a warning message when users are trying to specify duplicated entries of the same year.

**Comment by martinholmer** [comment]
Sean said:
> I happened to notice that, when implementing reforms, different expressions could lead to different results.

Thanks for reporting this issue, but your presentation of the results from the two reforms (`reform1` and `reform2`) is incomprehensible.  You need to show us the **difference** between the two diagnostic tables, line by line.  If you don't know how to produce the differences in the two tables, then look at the code in the `test_agg()` function in the `taxcalc/tests/test_pufcsv.py` file for one way.  Perhaps you can develop an even better way.  In any case, your current approach is not helpful to others on the development team because it imposes too high a time cost in understanding what you have discovered.

@GoFroggyRun

**Comment by MattHJensen** [comment]
@GoFroggyRun, what is the status of this issue?

**Comment by GoFroggyRun** [comment]
@martinholmer @MattHJensen:

Although in #711, the  `test_same_reform_expressed_two_ways` function detects no discrepancy, in this [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/Diff_Policy.ipynb) I just uploaded, the two calculators that use essentially the same reform, specified in different ways however, yield different results. I thus think this problem has not yet been resolved, unless I'm missing something significant in the [notebook](https://github.com/GoFroggyRun/Notebook/blob/master/Diff_Policy.ipynb).

**Comment by martinholmer** [comment]
Sean,  Make a new unit test that demonstrates the bug.  The notebook business is useless for the testing of Tax-Calculator.

@GoFroggyRun @MattHJensen

**Comment by GoFroggyRun** [comment]
@martinholmer:

Sure. I was working on the test unit that relies on the make-up data.

**Comment by martinholmer** [comment]
This issue #710 has been resolved as well as possible by adding a warning to the Policy.implement_reform method docstring in commit 0d2887e on June 20, 2016.
