### ISSUE TITLE
Release 0.6.3 change log

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#723]
Today we will release 0.6.3. (note that 0.6.3 was already released for testing, but we will update and finalize it today).

Could you please reply to this issue with important changes that you have introduced since [version 0.6.2](https://github.com/open-source-economics/Tax-Calculator/releases/tag/0.6.2) so that we can construct a change log? 

Examples of change logs include those of the [Policy Simulation Group](http://www.polsim.com/earlier-versions.html), [SQLite](http://www.sqlite.org/changes.html), [Bokeh](https://github.com/bokeh/bokeh/blob/master/CHANGELOG), and [Python](https://docs.python.org/3/whatsnew/changelog.html).

I would recommend looking through the [commit history](https://github.com/open-source-economics/Tax-Calculator/compare/0.6.2...master) and [closed PRs](https://github.com/open-source-economics/Tax-Calculator/pulls?q=is%3Apr+is%3Aclosed) to jog your memory of work completed. 

This may not be the best way to construct change logs in the future, so I am opening a separate issue shortly for that discussion. 

cc @martinholmer, @GoFroggyRun, @Amy-Xu, @talumbau

**Comment by martinholmer** [comment]
Since 0.6.2 version:
```
Add --records option to simtax.py
Add --csvdump option to inctax.py
Add three d samples to Tax-Calculator versus Internet-TAXSIM comparisons
Add first set of Tax-Calculator versus TaxBrain comparisons
Document first set of Tax-Calculator versus taxcalc.sas comparisons
Add data and logic to implement EITC age-eligibility rules
```

**Comment by GoFroggyRun** [comment]
Since 0.6.2 version:
```
Fix Child Care Expense logic 
Add logic to implement EITC age-eligibility rules
Add logic to exclude dependencies from EITC
```

**Comment by MattHJensen** [comment]
Since 0.6.2 version:

`Update and fix 10_minutes_to_Tax-Calculator.ipynb`

**Comment by Amy-Xu** [comment]
Since 0.6.2 version:

`fix and update files in taxcalc/comparison`

#725

**Comment by MattHJensen** [comment]
Release notes published https://github.com/open-source-economics/Tax-Calculator/releases/tag/0.6.3. Closing this issue, but please let me know if you have any corrections or suggestions.
