### ISSUE TITLE
Drop e15360 (motor vehicle tax) variable from Tax-Calculator?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#741]
The `e15360` (motor vehicle tax) variable is read from the 2009 `puf.csv` file, but is not "aged" in the blowup calculations, and then it is added to the standard deduction amount in the `StdDed` function.  This is appropriate tax logic for 2009 and 2010 when this temporary stimulus feature of the tax law was in effect.  But as far as I can see, this feature of the tax law is no longer in effect.  Is that true?

If no longer part of the tax law, it seems appropriate (given Tax-Calculator is not simulating years before 2013) to drop the `e15360` variable from the `puf.csv` file and from the Tax-Calculator.

Have I missed something?

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by feenberg** [comment]
On Thu, 12 May 2016, Martin Holmer wrote:

> 
> The e15360 (motor vehicle tax) variable is read from 2009 puf.csv file, but is not
> "aged" in the blowup calculations, and then it is added to the standard deduction
> amount in the StdDed function. This is appropriate tax logic for 2009 and 2010 when
> this temporary stimulus feature of the tax law was in effect. But as far as I can see,
> this feature of the tax law is no longer in effect. Is that true?
> 
> If no longer part of the tax law, it seems appropriate (given Tax-Calculator is not
> simulating years before 2013) to drop the e15360 variable from the puf.csv file and
> from the Tax-Calculator.
> 
> Have I missed something?

Unless the tax calculator wants to offer users the option of implementing 
that feature (which I don't think is desirable) you are correct.

dan

**Comment by martinholmer** [comment]
Dan @feenberg,  Thanks for the feedback.

**Comment by martinholmer** [comment]
Issue #741 has been resolved by pull request #746.
