### ISSUE TITLE
BenefitSurtax NOT Working Properly

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#748]
I have been working on #490 for a few days, where #490 added a test to verify the consistency of implementing the same itemized deduction reform in two ways. 

And at least one issue has been identified, which is that the `BenefitSurtax` function is not working in the desired way: itemized deduction parameters are not set to `True` (i.e. value 1) in some of the functions so that we are have discrepant results.

Another potential issue is that we might not be performing the optimization of whether to itemize or not in the right way (We are currently using `c05800`, while the ideal parameter to use might be `_iitax`). But this issue won't be confirmed until the first one has been resolved. 

@MattHJensen @martinholmer

**Comment by martinholmer** [comment]
Closing issue #748 because Sean successfully fixed this bug in pull request #749.
