### ISSUE TITLE
Move Earning Split Calculation out of Imputation?

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#750]
The `_impute_variables` function in `recorsd.py` includes not only the imputation of `_cmbtp_itemizer` and `_cmbtp_standard`, but also a few earning-splits that are extensively used in the `functions.py`. 

If we were, however, to switch off the imputation by using `consider_imputations=False`, the earning-split parts will be skipped as well, since they are inside the `_impute_variables` function. But this is not what we want, as skipping the earning split process will lead to malfunction of the calculator: 
If the process were being skipped, all earning split variables like `e00200p`, `e00200s`, `e00900p` will be zero. And functions like `EI_FICA` and `F2441` won't work in the desired way. 

I'd thus suggest move the earning split calculation out of the `_impute_variables` function.

**Comment by feenberg** [comment]
On Tue, 17 May 2016, Sean.Wang wrote:

> 
> The _impute_variables function in recorsd.py includes not only the imputation of
> _cmbtp_itemizer and _cmbtp_standard, but also a few earning-splits that are
> extensively used in the functions.py.
> 
> If we were, however, to switch off the imputation by using consider_imputations=False,
> the earning-split parts will be skipped as well, since they are inside the
> _impute_variables function. But this is not what we want, as skipping the earning
> split process will lead to malfunction of the calculator:
> If the process were being skipped, all earning split variables like e00200p, e00200s,
> e00900p will be zero. And functions like EI_FICA and F2441 won't work in the desired
> way.
> 
> I'd thus suggest move the earning split calculation out of the _impute_variables
> function.
> 
Remember that the imputation of earning split must be done on the raw 
data, not after any aging or growth parameters are applied. That is why I 
did it with the other imputations in the SAS program. Also, we may be 
getting a better earnsplit variable after 2010.

dan

**Comment by GoFroggyRun** [comment]
Thanks for the minder @martinholmer.
