### ISSUE TITLE
'Corner' Unit Got Better-Off When Choose to Have Zero Deduction

### ISSUE THREAD

**Issue by GoFroggyRun** [open-source-economics/Tax-Calculator#752]
An inconsistency issue has been found in PR #490 and #749, where a test has been added to check deduction reform consistency. And when itemized deductions were suppressed, there's one odd unit, among all `puf` records, should have lower individual income tax liability when he/she choose to have **zero** deduction amount (i.e. zero standard deduction and zero itemized deduction). 

The unit was picked out, simplified and modified:
```
FLPDYR,MARS,e00300,e00900,e02000,e03270,e18400,e18500,e19200,e19700,p23250,e24515
2009,2,14300,175000,-1795000,20000,40000,2700,15700,3200,4580000,2090000
```
Feeding this unit through 2013 tax logic, without any extrapolation/blowup, yields an individual income tax of amount 709,037.64, with `_taxbc` being 600,133.67 and `c63200` being 6,497.5. When itemized deduction being completely suppressed, this unit ended up with an individual income tax of amount 705,990.78, with `_taxbc` being 603,584.30 and `c63200` being 0. Note that this unit will be an itemizer in either scenario, the only difference is that, in the second case, the itemized deduction amount is zero. 

After going through the tax forms, my finding is that:
Although this unit will pay higher `_taxbc` (line 44 on 1040), which substantially comes from higher taxable income when choosing no deduction amount, this higher taxable income will come into play in the AMT calculation, or more specifically in the Schedule D Tax Worksheet for 1040, as an offsetting force. The higher taxable income will completely wipe out the AMT 15% and 20% amount for that unit, so that he/she will end up with a much lower AMT tax. The difference for AMT part is larger than the difference resulting from `_taxbc` difference, in terms of absolute value, and thus this unit has lower `iitax` liability. 

As far as I am concerned, I see nothing wrong in the tax logic, as well as our Itemize VS standard optimization. And this is likely to be a legit case in the tax logic, rather than a bug. 

Anyone interested in such 'counter intuitive' example could checkout the record above. Comments, concerns or remarks are also more than welcomed.

**Comment by martinholmer** [comment]
For a more up-to-date discussion of the `puf.csv` filing unit discussed during May 2016 in issue #752, see the discussion surrounding pull request #842.
