### ISSUE TITLE
The "with pytest.raises" idiom is misused in the tests

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#767]
I noticed a few examples of tests with code like this:

```
   with pytest.raises(ValueError):
         behv = Behavior(behavior_dict=list())
         behv = Behavior(num_years=0)
         behv = Behavior(inflation_rates=list())
```

Note that only the first line, in this case ` behv = Behavior(behavior_dict=list())` will be executed. If that line properly raises a ValueError, all is well according to the test. The context manager will catch the exception and move on, it will not run the other lines of code. I think the best way to proceed would be to replace the above with:

```
   with pytest.raises(ValueError):
         behv = Behavior(behavior_dict=list())
```

```
   with pytest.raises(ValueError):
        behv = Behavior(num_years=0)
```

```
   with pytest.raises(ValueError):
          behv = Behavior(inflation_rates=list())
```

**Comment by martinholmer** [comment]
T.J.,  Thanks for the useful information about how to use the `with pytest.raises()` capability.  I had not been able to find any examples on the web of using it more than once.  I had already tried what you confirm here as the correct syntax in pull request #765 [commit 3cf930f](https://github.com/open-source-economics/Tax-Calculator/pull/765/commits/3cf930f42055301ef5cee990537c4184b5033ba1).

**Comment by martinholmer** [comment]
T.J.,  Do you see any other misuse of `pytest.raises()` in the `taxcalc/tests` directory?  I have tried to fix all of them.  Now there are quite a few examples in the `tests` code that show the correct usage.

@talumbau @MattHJensen

**Comment by talumbau** [comment]
I think this is resolved. closing
