### ISSUE TITLE
PR #783 should be reverted

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#784]
#783 made two significant changes to master.

1. [This line](https://github.com/open-source-economics/Tax-Calculator/pull/783/files#diff-f3e927fe495a7de6cb3ce457911c67fdR5) introduced a dependency on `pytest` into Tax-Calculator, which is bad for situations where one is just using Tax-Calculator and not developing it. Also, the import of the `pytest` module is not used in `utils.py`

2. The [results function](https://github.com/open-source-economics/Tax-Calculator/pull/783/files#diff-f3e927fe495a7de6cb3ce457911c67fdR5) was changed w/o discussion. See my line note for details, but the main point is that the function previously accepted more than just a Calculator instance, and now it will only accept Calculator instances.

Perhaps there is merit in these changes, but there was only about an hour of time between the time the PR was posted and when it was merged. I don't think that's a good way to proceed with the project.

**Comment by martinholmer** [comment]
@talumbau said:
> #783 made two significant changes to master.
>
> This line introduced a dependency on pytest into Tax-Calculator, which is bad for situations where one is just using Tax-Calculator and not developing it. Also, the import of the pytest module is not used in utils.py

This oversight has been fixed in merged pull request #785.

> The results function was changed w/o discussion. See my line note for details, but the main point is that the function previously accepted more than just a Calculator instance, and now it will only accept Calculator instances.

Well then I don't understand why the old documentation said this:
```
Parameters
----------
c : Calculator object
```
There was nothing there saying the results function "accepted raw DataFrames as well as Calculator objects".  In fact. the old documentation was quite explicit about the results argument being a Calculator object.

TJ., if you want the results utility function to work in the undocumented manner that you describe above, then I suggest you change it to be the way you want. You can do that as you add more tests to test_utils.py so that the utils code coverage is complete.

There is no need to revert pull request #783 because your first objection has been fixed and your second objection can be fixed by you as described above.

**Comment by talumbau** [comment]
I think the explanation is that the documentation was wrong/incomplete. We likely currently have other places where the documentation is wrong or incomplete. It's also likely that current correct documentation will become wrong or incomplete as code changes are made, despite our best efforts to avoid such things.

A bigger issue is that it is unusual (and typically not good) to change package code (pretty much any of the`taxcalc/*py` files) with a pull request that is opened and then merged within such a short amount of time as was done with #783.

Different projects have different ground rules here. In some cases, it would not be acceptable to change even test assets unilaterally, but certainly for code in the package itself, I think there are numerous good reasons to let posted PRs stay open for at least a day. Some of those reasons would be:

 - People make mistakes, and more eyeballs on the code help catch mistakes.
 - The pull request mechanism is flexible enough that it's rare to find a case where leaving a PR up for a day is blocking to someone's work. Once a task is completed, a PR can be posted, and then the individual can move on to the next task. This could be another branch off current master, or a branch that is a follow on to the branch for the posted PR.
 - Others might have suggestions on how to make the code better. Leaving the PR open allows time for others to review the code and offer suggestions. Sometimes, such discussions result in a very fruitful paths to take for further development.

There are always exceptions, but in general, I think that most code changes should go through such a process prior to commit to master. Sometimes a PR will not elicit much in the way of comments. That is fine. Sometimes, I give a 'last call' in the form of a "will merge in XX hours" comment.

Anyway, I will follow-up here with a revert of the `results` function, updated doc string, and updated tests.

**Comment by martinholmer** [comment]
@talumbau,  Thanks for your views on what the check-in process should be like.

I'm in general agreement with what you're saying, but in the case of pull request #783, the pre-existing documentation and test suite made it quite clear that the `results` utility function argument was supposed to be a Calculator object.  So, the changes to that function did not alter any basic logic.  In cases where a pull request does alter logic, I have been following your suggested check-in process.  A recent example of that is pull request #765, which has been pending for twelve days at this writing.

**Comment by martinholmer** [comment]
Issue #783 is being closed for the reasons discussed in the closed and unmerged pull request #786.
