### ISSUE TITLE
Release 0.6.4 changes

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#787]
Version 0.6.3 of tax-calculator was released in late April and a new release is due. 

Does this Wednesday (June 15) work for everyone? 

Could you also please reply to this issue with important changes that you have introduced since version 0.6.3 so that we can construct a change log?

This is the same exercise that we completed for 0.6.3 in #723. To see the outcome of that exercise, see the [change log for 0.6.3](https://github.com/open-source-economics/Tax-Calculator/releases). 

Examples of change logs include those of the [Policy Simulation Group](http://www.polsim.com/earlier-versions.html), [SQLite](http://www.sqlite.org/changes.html), [Bokeh](https://github.com/bokeh/bokeh/blob/master/CHANGELOG), and [Python](https://docs.python.org/3/whatsnew/changelog.html).

I would recommend looking through the [commit history](https://github.com/open-source-economics/Tax-Calculator/compare/0.6.3...master) and [closed PRs](https://github.com/open-source-economics/Tax-Calculator/pulls?q=is%3Apr+is%3Aclosed) to jog your memory of work completed. 

This may not be the best way to construct change logs in the future, so feel free to comment on issue #724 with other suggestions. 

cc @martinholmer, @GoFroggyRun, @Amy-Xu, @talumbau

**Comment by martinholmer** [comment]
@MattHJensen said:
> Could you also please reply to this issue with important changes that you have introduced since version 0.6.3 so that we can construct a change log?

Expand scope of taxcalc/validation tests by adding three randomly-generated d samples.
Expand scope of taxcalc/taxcalcsas comparions tests to use more complete input data files.
Enhance taxcalc/taxbrain test scripts to handle delayed reforms.
Make several minor corrections to tax-calculation code and remove unused variables.
Enhance taxcalc/taxbrain test scripts to handle dynamic partial-equilibrium analysis.
Correct dynamic partial-equilibrium analysis logic with respect to payroll taxes.
Move input variable imputation logic out of Tax-Calculator into puf.csv file preparation.
Add many unit tests to increase fraction of code that is tested from 87 to 98 percent.

**Comment by MattHJensen** [comment]
@zrisher, is this the best description of https://github.com/open-source-economics/Tax-Calculator/commit/26fdb8571500a5968c0705d7978d98587a9f9844 for the changelog: 

> Fix Numpy dependency to version 1.10.4 and Pandas dependency to version 0.18.0 

@talumbau, is this the best description of https://github.com/open-source-economics/Tax-Calculator/commit/c5735b3d8330591778145a95df8ebd808df5d143:

> Add scripts to version and release.

**Comment by talumbau** [comment]
yes correct!

**Comment by talumbau** [comment]
I suggest merging https://github.com/open-source-economics/Tax-Calculator/pull/790/files to complete the version update work that @zrisher did.

**Comment by MattHJensen** [comment]
Thanks @TJ, we may need to push off the new release until later today or tomorrow. @martinholmer is going to open a PR that would neutralize https://github.com/open-source-economics/Tax-Calculator/issues/789#issuecomment-226238617 while we have time to think about it more. I'd like that PR to be merged before we release.

**Comment by MattHJensen** [comment]
I said: 

> Thanks @TJ, we may need to push off the new release until later today or tomorrow. @martinholmer is going to open a PR that would neutralize #789 (comment) while we have time to think about it more. I'd like that PR to be merged before we release.

@talumbau, I merged #791 to address this issue and we are good to go as soon as you are satisfied with #790.

**Comment by zrisher** [comment]
> Matt: @zrisher, is this the best description of 26fdb85 for the changelog

How about "Update Numpy and Pandas dependencies to latest versions to avoid a Conda bug with Pandas 0.16.2".

> TJ: I suggest merging https://github.com/open-source-economics/Tax-Calculator/pull/790/files to complete the version update work that @zrisher did.

Agreed!

**Comment by talumbau** [comment]
this is now ready prior to the release:

https://github.com/open-source-economics/Tax-Calculator/pull/790

I would say that this note:

How about "Update Numpy and Pandas dependencies to latest versions to avoid a Conda bug with Pandas 0.16.2".

is potentially confusing unless you want to link [the github issue](https://github.com/ContinuumIO/anaconda-issues/issues/760). I would also suggest "... avoid a bug in the Windows conda package for Pandas 0.16.2"

**Comment by zrisher** [comment]
> is potentially confusing unless you want to link the github issue. I would also suggest "... avoid a bug in the Windows conda package for Pandas 0.16.2"

I was trying to keep it pithy :smile:, but you're absolutely right more description is better in this case. How about:

"Update Numpy and Pandas dependencies to latest versions to avoid a bug in the Windows conda package for Pandas 0.16.2, see [this issue](https://github.com/ContinuumIO/anaconda-issues/issues/760)."

**Comment by martinholmer** [comment]
Sorry for the delay, but here are my major enhancements between release 0.6.3 and release 0.6.4:
```
Test TaxBrain handling of delayed reforms
Move cmbtp calculation and earnings splitting logic from Records class to puf.csv file preparation
Revise Behavior class logic
Add unit tests to increase code coverage to 98 percent.
Create Consumption class used to compute "effective" marginal tax rates
```

**Comment by MattHJensen** [comment]
@martinholmer, I was two slow closing this issue and you posted the list twice. 

Recent:

https://github.com/open-source-economics/Tax-Calculator/issues/787#issuecomment-235059040

```
Test TaxBrain handling of delayed reforms
Move cmbtp calculation and earnings splitting logic from Records class to puf.csv file preparation
Revise Behavior class logic
Add unit tests to increase code coverage to 98 percent.
Create Consumption class used to compute "effective" marginal tax rates
```

Earlier:

https://github.com/open-source-economics/Tax-Calculator/issues/787#issuecomment-225878544

```
Expand scope of taxcalc/validation tests by adding three randomly-generated d samples.
Expand scope of taxcalc/taxcalcsas comparions tests to use more complete input data files.
Enhance taxcalc/taxbrain test scripts to handle delayed reforms.
Make several minor corrections to tax-calculation code and remove unused variables.
Enhance taxcalc/taxbrain test scripts to handle dynamic partial-equilibrium analysis.
Correct dynamic partial-equilibrium analysis logic with respect to payroll taxes.
Move input variable imputation logic out of Tax-Calculator into puf.csv file preparation.
Add many unit tests to increase fraction of code that is tested from 87 to 98 percent.
```

I will use the most recent list. Please let me know if you would like me to add any information from the earlier list.

**Comment by MattHJensen** [comment]
Release published https://github.com/open-source-economics/Tax-Calculator/releases/tag/0.6.4. Closing this issue.
