### ISSUE TITLE
A Calculator should take user-defined functions that are called at calculation time

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#84]
This would be a means to provide a friendly developer/user of the package with a way to add something to the model (credit, deduction, etc.). The idea is that a user may write a function and then register it with the calculator. The calculator will call it at the proper time. It could look like this:

```
def give_everyone_ten_grand(p):
    p.e00100 += 10000

calc = Calculator(tax_dta, default_year=91)

#Register callback here
calc.register_income_callback(give_everyone_ten_grand)

results = calc.run_all()

```

There are two things happening here. One is that `run_all` is now a method on a calculator that will call all of the functions in the designated sequence. Second is that this designated sequence would have a few spots to run any registered UDFs (user-defined functions). So, it would look like:

```
self.CapGains()
self.SSBenefits()
self.all_income_udfs()
self.AGI()
```

`all_income_udfs` would execute any registered income functions. We could have such a mechanism for income, deductions, credits, etc. 

This capability would not be available through the web application, since it would involve execution of arbitrary code. Anyone using the package on their local machine would be able to do this though.

**Comment by martinholmer** [comment]
Issue #84, which was raised almost two years ago on 18-Dec-2014, would seem to have been superseded by the general method contained in pull request #1081.
Is there any reason why issue #84 should not be closed?

@talumbau @MattHJensen @feenberg

**Comment by MattHJensen** [comment]
Agree that this issue has been superseded by #429. Closing
