### ISSUE TITLE
Release 0.6.5 changes

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#840]
Major changes I have contributed between release 0.6.4 (#794) and release 0.6.5 (#820):
```
Add --exact option to simtax.py and inctax.py scripts
Fix itemized deduction logic for charity
Remove puf variable from functions.py code
Add calculation of Schedule R credit
Remove _cmp variable from functions.py code
```

**Comment by MattHJensen** [comment]
It looks like the only other major change between 0.6.4 and 0.6.5 was @talumbau's 

`Remove Numba dependency` from #799. 

Closing this issue and adding changes to the change log.
