### ISSUE TITLE
Tax-Calculator should accept common formats of individual tax data

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#851]
This issue is created to track a portion of the functionality discussed in #319:

> Allow for individuals to enter their own detailed tax information and see how their taxes would change under various reform proposals.

The motivation here is that the dependency on the PUF data may prevent many potential users or contributors from getting involved with the project, and this would make taxcalc interesting to anyone who cares about his own finances but not necessarily about the national implications of tax policy.

All US taxpayers must submit IRS tax forms, so they are the most well-known source for tax data and most users will have previous years' forms readily available. These forms contain all the data required to accurately calculate taxes. **Thus, tax forms seem an excellent target for inclusion as a `Record` data source.**

We have discussed including two formats for tax forms:
- Luca tax form JSON - [Luca](https://github.com/brandon-rhodes/luca) is a personal finance tool written in Python that assists users in organizing bank statements into ledgers using that data to fill out tax forms. Luca stores tax form data in JSON with its own key set.
- Tax forms scanned into PDF - Users could also provide scanned or electronically completed PDFs with their tax info.

While the latter is clearly applicable to a larger user base (any US taxpayer), it requires a significant amount of work to accurately parse PDFs from many different templates, and the rest of the logic required to parse the data and send it through `taxcalc` is exactly the same as the Luca input case. The Luca JSON format is also pretty accessible. **So our plan is to start with the Luca format.**

@mmessick started this work with #309, which aimed to make general accessibility improvements to `Records` that were eventually incorporated by @martinholmer in #352.

@talumbau also expanded the `taxcalc` input set to include the TAXSIM format in #376.

I picked up this project several months ago. 

Initially the bulk of my code was contained in an IO class similar to `SimpleTaxIO` introduced by #376 and I relied on the data in `e_variable_info.csv` to map between tax form fields and `taxcalc` input/output vars.  

However, I found that the relationships between the fields and vars was not always a simple 1-1 mapping, and it could change depending on form year. To support more complex variable mapping as well as all the PDF and general utility functionality that I see us eventually wanting, I've moved towards using classes for the tax forms, with a general base class supporting the shared functionality. I believe this will lead to more legible, usable, and powerful code. 

**I expect to submit a WIP PR with the general logical format for Luca input parsing within the next few weeks.** After fixing it according to the group's commentary, I'll submit a new PR with full tests and polishing.

After that, we can move on to PDF parsing, with the generalized tax form logic already complete.

**Comment by feenberg** [comment]
I don't think we should be parsing PDF files..

A much more important, and also work-intensive task is to allow more 
general tax reforms - specified by formulas rather than check boxes. I 
already have run in to people with reforms they would like to score, but 
couldn't fit into the existing boxes on our web form. As far as I know we 
haven't talked to the programmers about this yet.

dan

**Comment by zrisher** [comment]
> A much more important, and also work-intensive task is to allow more
general tax reforms - specified by formulas rather than check boxes. 

@feenberg It seems that is covered by #429, correct?

**Comment by MattHJensen** [comment]
Thanks @zrisher, looking forward to your WIP PR.

**Comment by zrisher** [comment]
@MattHJensen regarding your two addendum:

1. Yep, and I think we can aggregate all that data into a single custom form for now.
2. I would definitely like to have a naming convention with a basis in what people are using. At the same time, if the existing schemes are used by a small number of people and are difficult to follow (as I expect may be the case), I would recommend taking the opportunity to come up with a new variable naming convention that is easy to follow and can simplify data sharing and analysis.

**Comment by feenberg** [comment]
On Sat, 27 Aug 2016, zrisher wrote:

> 
> @MattHJensen regarding your two addendum:
>
>  1. Yep, and I think we can aggregate all that data into a single custom form for now.
>  2. I would definitely like to have a naming convention with a basis in what people
>     are using. At the same time, if the existing schemes are used by a small number of
>     people and are difficult to follow (as I expect may be the case), I would
>     recommend taking the opportunity to come up with a new variable naming convention
>     that is easy to follow and can simplify data sharing and analysis.

I continue to feel that there are advantages in adopting the names 
(E-codes) used by SOI for taxpayer data. They are not going to adopt our 
names, and any names we make up will (1) require explanation (2) cause 
users to wonder if they are equivalent to similarly defined E-codes and 
(3) will put off users that are already used to the SOI names, or are 
hoping to use SOI files in the future, and would like their human capital 
acquired from TB to be useful when they get access to real data (4) will 
hasten the use of our calculator in government. That last is important - 
if government agencies start using our calculator in place of their own, 
then SOI will be much more cooperative with us with respect to data 
supply.

dan feenberg

**Comment by martinholmer** [comment]
Dan @feenberg said:
> I continue to feel that there are advantages in adopting the names (E-codes) used by SOI for taxpayer data.

But what about the fact that all the E-codes that are not used in the IRS-SOI PUF are not public.  At least this is my understanding of the situation after discussions with @MattHJensen.  Matt even said that IRS-SOI had refused to make all of the E-codes public.  I'm not talking about the data, I'm talking about the definitions of the E-codes.

So, if this is an accurate view of the situation, how can your proposal be taken seriously?

Or, am I wrong and there is a publicly-available list of ALL the E-codes?  Where is that on the Internet?

@MattHJensen @feenberg @zrisher @Amy-Xu @GoFroggyRun

**Comment by feenberg** [comment]
On Sun, 28 Aug 2016, Martin Holmer wrote:

> 
> Dan @feenberg said:
>
>       I continue to feel that there are advantages in adopting the
>       names (E-codes) used by SOI for taxpayer data.
> 
> But what about the fact that all the E-codes that are not used in the
> IRS-SOI PUF are not public. At least this is my understanding of the
> situation after discussions with @MattHJensen. Matt even said that IRS-SOI
> had refused to make all of the E-codes public. I'm not talking about the
> data, I'm talking about the definitions of the E-codes.

My understanding with Michael Weber has always been that I may distribute 
taxcalc.sas with the ecodes mentioned in it. If that isn't the case, we 
have a problem. I think Mike Jensen should confirm this with him.

dan feenberg

**Comment by martinholmer** [comment]
Dan @feenberg said:
> My understanding with Michael Weber has always been that I may distribute taxcalc.sas with the E-codes mentioned in it. If that isn't the case, we have a problem. I think Mike Jensen should confirm this with him.

But that is not anywhere close to being the same as IRS making them public and documenting them as they do for the E-code in the IRS-SOI PUF.

I'm still not convinced about the merit of your idea to use undocumented E-codes for variable names that do not appear in the IRS-SOI PUF documentation.

@MattHJensen @feenberg @zrisher @Amy-Xu @GoFroggyRun

**Comment by MattHJensen** [comment]
@martinholmer said:

> Matt even said that IRS-SOI had refused to make all of the E-codes public.

I made another request this summer, and Barry Johnson indicated that SOI might provide the naming convention that is used to generate E-codes, but probably not the tax forms with the E-codes filled in. We would have to generate that documentation ourselves. That said, I have been waiting several weeks for a followup after an initial round of emails.

**Comment by feenberg** [comment]
On Mon, 29 Aug 2016, Matt Jensen wrote:

> 
> @martinholmer said:
>
>       Matt even said that IRS-SOI had refused to make all of the E-codes public.
> 
> I made another request this summer, and Barry Johnson indicated that SOI might provide
> the naming convention that is used to generate E-codes, but probably not the tax forms
> with the E-codes filled in. We would have to generate that documentation ourselves.
> That said, I have been waiting several weeks for a followup after an initial round of
> emails.
>

I have a spreadsheet with e-code definitions.  However, anyone inside the 
government will have the same document, so we could simply depend upon the 
user to provide their own dictionary file.

dan

**Comment by zrisher** [comment]
An update on this issue:

We just merged PR #893 which introduces the `TaxForm` base class and a child class for each form to help convert raw tax form field data into evars.

The next steps I see towards the objective of this issue "Allow for individuals to enter their own detailed tax information and see how their taxes would change under various reform proposals" are:

* #942 - improving the `TaxForm` class
* Introduce the `TaxFiling` class that holds all the `TaxForms` for a particular filer and year. This would help with grouping newly added forms and generating evars that require an understanding of multiple forms within a filing.
* Introduce the `FilingCollection` class that holds all `TaxFilings` for a particular input session / taxcalc run. This would help with grouping newly added forms and converting them to a `Records` object. 
* Introduce a `LucaIO` class that helps read form data in Luca's JSON format and converts it to a `FilingCollection`. 
* Introduce a `lucatax.py` command line program that helps a local user import Luca tax form data as records and export calculated tax liabilities, optionally using a reform file. Relies on all the above classes to do the heavy lifting.

Then, to improve usability, we could:

* Adjust `webapp-public` to allow a user to upload Luca format tax forms to use as record data
* Introduce a PDF IO class to convert PDFs into a `FilingCollection` (large amount of work)
* Introduce `pdftax.py` command line tool to mirror `lucatax.py`'s functionality for PDFs
* Adjust `webapp-public` to allow a user to upload PDF tax forms to use as record data

Let me know if you see any changes or improvements to these steps.
@MattHJensen @feenberg @martinholmer @Amy-Xu @GoFroggyRun @talumbau

**Comment by martinholmer** [comment]
@MattHJensen said on August 29, **2016** in the discussion of issue #851:
> I made another request this summer, and Barry Johnson [of IRS] indicated that SOI might provide the naming convention that is used to generate E-codes, but probably not the tax forms with the E-codes filled in. We would have to generate that documentation ourselves. That said, I have been waiting several weeks for a followup after an initial round of emails.

So, @MattHJensen, did you ever head from IRS-SOI whether or not they would make publicly available the definitions of E-codes not used in the PUF?

If we have not heard anything in over a year, perhaps issue #851 should be closed.
What do you think?

**Comment by MattHJensen** [comment]
SOI would not share anything with me, and neither would Dan at their request. But, the attached file should help with variable names that are not in the puf. 
[Variable_Names.txt](https://github.com/open-source-economics/Tax-Calculator/files/1381175/Variable_Names.txt)




cc @martinholmer

**Comment by martinholmer** [comment]
The effort discussed in Tax-Calculator issue #851 was focused on developing the ability to input Records variables not only from CSV-formatted text files, but also from two other sources:
- Luca JSON tax forms --- [Luca](https://github.com/brandon-rhodes/luca) is a personal finance tool written in Python that assists users in organizing bank statements into ledgers using that data to fill out tax forms; Luca stores tax form data in JSON with its own key set.
- Tax forms scanned into PDF --- Users could also provide scanned or electronically completed PDFs with their tax info.

The effort to do this yielded many useful insights on how to handle the input of tax record information, and many of these insights have been incorporated into Tax-Calculator, making it a much better piece of software.

But given that the Luca and PDF input turned out to be much more difficult than originally anticipated and given that there has been no work on achieving the issue #851 goals over at least the past year, it seems appropriate to close issue #851, and remove the `taxcalc/filings/forms` code and associated tests from the Tax-Calculator master branch.  That code and associated tests will always remain in the Tax-Calculator repository for future reference, but they will not be part of the master branch, and therefore, will not require maintenance in the future as Tax-Calculator evolves.
