### ISSUE TITLE
Combine CG/DIV rates from AMT and Reg Tax into one set of params?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#861]
Many TC and TB users have been extremely confused when they reduce the LT capital gains/dividends rates and end up losing very little revenue since almost everything is captured back by the AMT. 

I wonder if we should link the AMT LT CG/DIV rates to the regular tax CG/DIV rates. Alternatively, we might want to provide some warning message if a user changes the Regular Tax CG/DIV rates but not the AMT CG/DIV rates. 

There could be some other solution as well. Right now this is a major stumbling block for our users. 

cc @feenberg, @Amy-Xu, @martinholmer, @GoFroggyRun 

This is related to https://github.com/OpenSourcePolicyCenter/webapp-public/issues/295#issuecomment-239535802 and potentially to https://github.com/open-source-economics/Tax-Calculator/issues/182.

**Comment by feenberg** [comment]
On Fri, 12 Aug 2016, Matt Jensen wrote:

> 
> Many TC and TB users have been extremely confused when they reduce the LT capital
> gains/dividends rates and end up losing very little revenue since almost everything is
> captured back by the AMT.
> 
> I wonder if we should link the AMT LT CG/DIV rates to the regular tax CG/DIV rates.
> Alternatively, we might want to provide some warning message if a user changes the
> Regular Tax CG/DIV rates but not the AMT CG/DIV rates.

They have been linked in the law for some years now, people might be 
expecting this. How about a checkbox for "AMT rates same as regular rates" 
that would be on by default.

> 
> There could be some other solution as well. Right now this is a major stumbling block
> for our users.

I can understand that.

dan

**Comment by MattHJensen** [comment]
> How about a checkbox for "AMT rates same as regular rates"
that would be on by default.

Thanks @feenberg. This could be a solution on the webapp, but it wouldn't help users of the Tax-Calculator package.

**Comment by MattHJensen** [comment]
The forthcoming discussion in #868 of how to deal with an optional pass thru rate schedule that is separate from the ordinary income rate schedule may be relevant to this issue (#861).

**Comment by MattHJensen** [comment]
Now that #913 is merged, separating the rate structures applied to pass through income and other taxable income, this discussion is even more important. Now there are two opportunities for users to make mistakes: 

1. Modify _CG_rt and _CG_thd parameters without knowing about _AMT_CG_rt and _AMT_CG_thd parameters. 
2. Modify _II_rt and _II_brk parameters without knowing about _PT_rt and _PT_brk parameters. 

cc @feenberg, @martinholmer, @zrisher, @GoFroggyRun, @andersonfrailey, @talumbau

**Comment by martinholmer** [comment]
It has been almost twenty days since the last comment was added to open issue #861. 

Isn't it true that the potential confusion for TaxBrain users has been eliminated in TaxBrain version 0.6.7?  (See the discussion of [TaxBrain issue 340](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/340).)

Can we close issue #861?

@MattHJensen @talumbau @feenberg

**Comment by martinholmer** [comment]
@MattHJensen,  Can we close issue #861?  Or are there still outstanding related issues?  This issue has been open since August 12.

**Comment by MattHJensen** [comment]
Sorry for not seeing the earlier comment. Happy to close this issue and doing so now. Thanks to everyone for helping to resolve it.
