### ISSUE TITLE
Parameterize a "Buffet Rule"

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#862]
Clinton's tax plan includes a Buffet Rule.

All I can find from Clinton's [own documents](https://www.hillaryclinton.com/briefing/factsheets/2016/01/12/investing-in-america-by-restoring-basic-fairness-to-our-tax-code/) is this:

> Hillary will reiterate her call for the “Buffett Rule,” which ensures that those making more than $1 million per year pay at least an effective tax rate of 30 percent. 

TPC implemented something much more complicated in [their analysis](https://www.hillaryclinton.com/briefing/factsheets/2016/01/12/investing-in-america-by-restoring-basic-fairness-to-our-tax-code/) of her proposal: 

 [From TPC:](http://www.taxpolicycenter.org/publications/analysis-hillary-clintons-tax-proposals): 

> Q2. The documentation states that Secretary Clinton would propose the “Buffett Rule” to ensure
> that “millionaires must pay at least a 30 percent effective rate.” Does Secretary Clinton’s
> version of the Buffett Rule differ in any way from the version that was proposed in the
> Administration’s FY2016 budget, described as follows in the Treasury Green Book (available
> at https://www.treasury.gov/resource-center/tax-policy/Documents/GeneralExplanations-FY2016.pdf):
> 
> The proposal would impose a new minimum tax, called the Fair Share Tax (FST), on high income
> taxpayers. The tentative FST would equal 30 percent of AGI less a credit for charitable
> contributions. The charitable credit would equal 28 percent of itemized charitable contributions
> allowed after the overall limitation on itemized deductions (so called Pease limitation). The final
> FST would be the excess, if any, of the tentative FST over the sum of the taxpayer’s (1) regular
> income tax (after certain credits) including the 3.8-percent net investment income tax, (2) the
> alternative minimum tax, and (3) the employee portion of payroll taxes. The set of certain credits
> subtracted from regular income tax would exclude the foreign tax credit, the credit for tax
> withheld on wages, and the credit for certain uses of gasoline and special fuels. The amount of
> FST payable (i.e., the excess of tentative FST over regular tax) would be phased in linearly
> starting at $1 million of AGI ($500,000 in the case of a married individual filing separate
> return). The FST would be fully phased in at $2 million of AGI ($1 million in the case of a married
> individual filing a separate return). 
> 
> 
> A2. We assume the Secretary’s version of the Buffett Rule would be the same as the
> Administration’s proposal with the exceptions that the AGI thresholds would be indexed for
> inflation after 2015 and that the proposal would be effective 01/01/2017.

I don't think we need to go to so much work to implement something Clinton hasn't proposed. 

How about a simpler approach: 

X% of AGI minimum tax for taxpayers with AGI over Y, with the tax phased in linearly at Z% for every dollar of AGI. 

Defaults would be X = 0, Y = $1mm, Z = 1

The final FST would be the excess, if any, of the tentative FST over the sum of the taxpayer’s (1) regular income tax (after certain credits) including the 3.8-percent net investment income tax, (2) the alternative minimum tax, and (3) the _employee portion_ of payroll taxes. 

Note that this will need to be calculated after the benefit surtax, if any.

**Comment by MattHJensen** [comment]
@andersonfrailey, could you take this one?

**Comment by andersonfrailey** [comment]
@MattHJensen I'm a little confused by differences between the example in the Treasury document and the Clinton tax plan.

From what I'm understanding Clinton wants a 30% tax on those making above $1 million (e.g. a person making $1.25 million will pay $375,000).

The Treasury seems the define the FST as a proportion of the difference between 30% of a person's income and their regular taxes where if you make $2 million you pay all of the difference and if you are below $2 million you pay a proportion of the difference. In this case the person making $1.25 million and facing $250,000 in regular taxes pays $31,250. 

Which of these is closest to what we would like to do?

**Comment by MattHJensen** [comment]
@andersonfrailey, the second is closer -- except for the phase in over the 1-2 million range, I also think that also describes what Clinton has proposed. 

The tentative fst (buffet tax) is the 30%. The final fst is the 30% - what they have already paid.

**Comment by martinholmer** [comment]
Merge of pull request #904 resolves issue #862.

Tax-Calculator estimates of the extra revenue added by such a reform are noticeably larger than the estimates generated by other models.  These differences are being investigated and the results of those investigations will be reported in another issue.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey
