### ISSUE TITLE
Calculate MTR w.r.t currently "invalid" income types

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#880]
Over in B-Tax, @jdebacker asked:

> This line yields the following error:
> `[mtr_fica_mtg, mtr_iit_mtg, mtr_combined_mtg] = calc1.mtr('e19200')`
> `ValueError: mtr income_type_str="e19200" is not valid`
> 
> I see this variable in the PUF. Am I not able to calculate the MTR w.r.t. this item with the Tax-Calculator? Something else causing the error?

To which @Amy-Xu replied: 

> It seems from [this line](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/calculate.py#L229) of code in Tax-Calculator that we only allow a certain set of variables to be passed into MTR function. This set currently does not include interest paid. We should be able to add this variable very easily. What do you think? @MattHJensen

To which @jdebacker responded:

> Thanks for finding that @Amy-Xu. I recall something like this, but couldn't find the lines of code to point out. Does this limitation of the valid strings have to do with some TaxCalc logic or for another reason (e.g. to save computational time it does not compute MTRs for every line item on the 1040)?
> 
> Relatedly, there are some variables such as tax exempt interest that is (obviously) zero-taxed under current law. But one could imagine a reform where the tax-exempt status of this income source were to change. How would one handle that? In particular, would the Tax Calc output then put all interest income in e00300? Or would the formerly tax exempt still show up under e00400, but now face the non-zero tax? I'm just trying to think about how I might compute a MTR on interest income as a whole (taking into account that some might be taxable and some not, with the taxable status changing between the baseline and reform).
>

**Comment by martinholmer** [comment]
@jdebacker said:
> Thanks for finding that @Amy-Xu. I recall something like this, but couldn't find the lines of code to point out. Does this limitation of the valid strings have to do with some TaxCalc logic or for another reason (e.g. to save computational time it does not compute MTRs for every line item on the 1040)?

The limitation has everything to do with the fact that different income types have different MTR logic associated with them as the Calculator.mtr() method shows.  We will never be able to allow any income type to be passed to the mtr() method.

So, do you what to request another valid income type for the Calculator.mtr() method?  If so, which one?

@jdebacker @Amy-Xu @MattHJensen @feenberg @GoFroggyRun @zrisher

**Comment by jdebacker** [comment]
@martinholmer thanks for the quick follow up.

The MTR logic looks fairly straightforward.  I do see that some variable use a different named variable from which to calc the finite difference.  Could one set up a dictionary to map the relation between any 1040 variable and the appropriate variable from which to calc a finite difference?  Then this logic would use that dictionary to make the mapping (as opposed to a series of if statements)?

In the short-term, I'd like to see the following variables added to the list of acceptable variables for the mtr function:
1) e19200
2) e18500

In the longer-term, I'd like to know if variables like e00400 would need to be added to the mtr logic.  That is, items not taxed under current law, but that might be taxed under a user's proposal.  I don't have a good understanding regarding how the TC would handle a reform that takes away tax exempt status for certain income sources (see above for more detail).

**Comment by martinholmer** [comment]
@jdebacker said:
> I'd like to see the following variables added to the list of acceptable variables for the mtr function:
> (1) `e19200`
> (2) `e18500`

For those who do not have E-codes fully memorized, here is how `var_labels.txt` defines these:
```
E18500 = Schedule A: Real estate tax
E19200 = Schedule A: Total interest deduction
```
I'm confused about your request, which is the expand the following list:
```
    MTR_VALID_INCOME_TYPES = ['e00200p', 'e00900p',
                              'e00300', 'e00400',
                              'e00600', 'e00650',
                              'e01400', 'e01700',
                              'e02000', 'e02400',
                              'p22250', 'p23250']
```
But the list contains types of INCOME, not types of itemized deduction expenses.
What sense does it make to compute a marginal tax rate on an itemized expense?

@jdebacker @Amy-Xu @MattHJensen @feenberg @GoFroggyRun @zrisher

**Comment by jdebacker** [comment]
@martinholmer, there is a MTR associated with any income and deduction item.  Just as $1 more in wages increase AGI and tax burden, $1 more in mtg interest affects AGI (potentially) and therefore tax burden.

**Comment by martinholmer** [comment]
Are there more aspects of Calculator.mtr() that people would like to discuss in issue #880?
If not, should issue #880 be closed?

**Comment by martinholmer** [comment]
Martin Holmer said:
> Are there more aspects of Calculator.mtr() that people would like to discuss in issue #880?
> If not, should issue #880 be closed?

Sorry.  Forgot to list any addressees.

@MattHJensen @Amy-Xu @jdebacker

**Comment by martinholmer** [comment]
@jdebacker said:
> @martinholmer solved the short-term problem by adding those two variables I needed for some calculations with B-Tax. But one might leave this issue open until every income/deduction/credit item in the TC is is accounted for in Calculator.mtr(). Or we could just reopen the issue if those do come up. I don't have a strong preference - except in that I'm not volunteering to make those changes right now!

OK, let's close #880 and we'll look forward (sometime in the future) for your pull request that generalizes the logic of the Calculator.mtr() method.
