### ISSUE TITLE
Taxcalc mailing list needs more usage

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#892]
In #724 @feenberg said:

> We also need a mailing list about users questions and taxes, not patches.

**Comment by feenberg** [comment]
We have a mailing list for users

  users@list.ospc.org

and Matt and I moderate it. But it receives almost no use. I have hoped that OSPC insiders would steer users to the list so that it would have more content.  The link to it is buried in the text on the taxbrain web page.

dan

**Comment by zrisher** [comment]
@feenberg Ok, since this isn't a technical issue of the `taxcalc` repo, I'm going to close this issue. I imagine you guys have another tracking tool for issues such as these.
