### ISSUE TITLE
cleanup from separate PT params

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#927]
#913 breaks tax-calculator's backwards compatibility.

@GoFroggyRun, could you please open a PR if possible or if not post an issue to www.github.com/opensourcepolicycenter/webapp-public that makes it so that TaxBrain's regular tax rate and bracket parameters modify both II and PT rt and brk parameters? This must be done before a new version of TC is deployed to TB.

Alternatively, we would need to solve #861 in some way that restores backwards compatibility.

cc @martinholmer, @talumbau, @andersonfrailey, @Amy-Xu, @rickecon, @jdebacker

**Comment by GoFroggyRun** [comment]
@MattHJensen 
Got you. I'll start with an issue to www.github.com/opensourcepolicycenter/webapp-public first to describe our strategy.

**Comment by martinholmer** [comment]
Issue #927 has been resolved in the new version of TaxBrain, which assumes that the PT and II tax brackets and tax rates are the same.
