### ISSUE TITLE
Should the BenefitSurtax() rate be set at 0 or 1 under current law?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#943]
Over at #867, @feenberg asked:

> Also, I do not understand why the default surtax rate is shown as 1.0 (and
the credit also as 1.0) in the "Surtax on Itemized Deduction Beefit"
section. Surely the surtax rate should be .0. 

The reason why I set the surtax rate to 1 is that many (all) reforms in the news that use this feature have a surtax rate of 1. I'm talking about reforms along the lines of Feldstein, Feenberg, and Macguineas where the value of itemized deductions is limited to X% of AGI. If the surtax rate were set at 0, then the user would have to change both the surtax rate and the credit rate. With the surtax rate at 1, then the user will likely only have to change one parameter. 

The advantage of setting the surtax rate at 0 is that the user would have to think through exactly what the rate and credit parameters mean in order to specify their intended reform . Perhaps that would be better. What do you think @feenberg? 

cc @martinholmer, @andersonfrailey, @GoFroggyRun

**Comment by feenberg** [comment]
On Sat, 24 Sep 2016, Matt Jensen wrote:

> 
> Over at #867, @feenberg asked:
>
>       Also, I do not understand why the default surtax rate is shown as 1.0 (and
>       the credit also as 1.0) in the "Surtax on Itemized Deduction Beefit"
>       section. Surely the surtax rate should be .0.
> 
> The reason why I set the surtax rate to 1 is that many (all) reforms in the news that use
> this feature have a surtax rate of 1. I'm talking about reforms along the lines of
> Feldstein, Feenberg, and Macguineas where the value of itemized deductions is limited to
> X% of AGI. If the surtax rate were set at 0, then the user would have to change both the
> surtax rate and the credit rate. With the surtax rate at 1, then the user will likely
> only have to change one parameter.

But doesn't the default raise a little revenue? Aren't there taxpayers 
with negative AGI and itemized deductions? (They would be using the 
itemized deductions on the AMT). I just checked - and it doesn't raise any 
revenue, so perhaps it is ok. But still it is misleading - it suggests 
there is a current surtax, when there isn't. Having a zero rate might be 
the best approach as there is no similar correct default for the AGI 
threshold.

> 
> The advantage of setting the surtax rate at 0 is that the user would have to think
> through exactly what the rate and credit parameters mean in order to specify their
> intended reform . Perhaps that would be better. What do you think @feenberg?
>

I agree with this logic.

dan

**Comment by MattHJensen** [comment]
I said:

> The advantage of setting the surtax rate at 0 is that the user would have to think
 through exactly what the rate and credit parameters mean in order to specify their
 intended reform . Perhaps that would be better. What do you think @feenberg?

To which @feenberg replied: 

> I agree with this logic.

Ok. I just opened a PR to make this change. I'll merge it tomorrow if no one objects. The update will appear on TaxBrain once we have our next release of TC to TB.
