### ISSUE TITLE
odd results from multiyear_diagnostic_table with behavioral calculators

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#985]
I want to get this warning up asap and will post a full report tomorrow.

The `multiyear_diganostic_table()` does not generate accurate results when passed calculators to which behavior has already been applied. Please be cautious when using this table. There appears to be no problem with the `diagnostic_table()`

cc @codykallen @Amy-Xu @martinholmer @GoFroggyRun @andersonfrailey

**Comment by codykallen** [comment]
In the code for multiyear_diagnostic_table(), the behavior.response(calc_clp, cal) function is called for each year. This implies that the behavioral response increases over time, which is possibly causing the odd results. Try only calling behavior.response(calc_clp, cal) only for the first year, and then using calc.increment_year() and calc.calc_all() for future years.

**Comment by GoFroggyRun** [comment]
Thanks to Cody's (@codykallen) comment, I looked at the code line again and found that
```
cal = copy.deepcopy(calc)
dtlist = list()
for iyr in range(1, num_years + 1):
     if cal.behavior.has_response():
     cal_clp = cal.current_law_version()
     cal_br = cal.behavior.response(cal_clp, cal)
```
If `calc` (or `cal`) has already gone through ` cal.behavior.response`, then `cal_br = cal.behavior.response(cal_clp, cal)` is not right. 
The response should be between a base line calculator and a calculator with calculated reform results but has not respond to any behaviors yet.  

In particular,  let `calcbase` be baseline and `calc_feform_wiz_Be` be some calculator with reforms and behaviors (namely `reform_behave`), then 
```
calcbase.calc_all()
calc_feform_wiz_Be.calc_all()
behave.update_behavior(reform_behave)
calc_respond = Behavior.response(calcbase, calc_feform_wiz_Be)
calc_respond_respond = Behavior.response(calcbase, calc_respond)
```
the correct responded calculator should be `calc_respond`, while `multiyear_diganostic_table` generates `calc_respond_respond`.

**Comment by MattHJensen** [comment]
Thanks @codykallen and @GoFroggyRun. I am currently working on a PR to remove the built in behavioral response from `multiyear_diagnostic_table()`. That way the table will not modify the calculator, beyond incrementing year, as advertised. 

First I am trying to add a commit with a failing test to demonstrate the problem. 

However, in my efforts to write a failing test that isolates the problem we've been discussing, I've also realized that `multiyear_diagnostic_table()` is unexpectedly advancing to 2017 without instruction, even when the passed calculator's `current_year` is 2013. Therefore, I'm also trying to find the code that is causing the diagnostic table to advance (which is proving to be elusive). Once I find it, I'll probably open a PR first that makes that stop happening. 


# Testing multiyear diagnostic table

### Import taxcalc package and other useful packages


```python
import sys
sys.path.append("../../")
from taxcalc import *
```


```python
puf = pd.read_csv("../../puf.csv")
policy2 = Policy()
records2 = Records(puf)
bhv = Behavior()
calc2 = Calculator(policy = policy2, records = records2, behavior = bhv)
calc1 = calc2.current_law_version()
```

    You loaded data for 2009.
    Your data have been extrapolated to 2013.



```python
reform = {
2013: {
'_II_rt7': [0.33],
'_PT_rt7': [0.33],
}}

reform_be = {2013: {'_BE_sub': [0.4],
                    '_BE_cg': [-3.67]}}


```


```python
policy2.implement_reform(reform)
bhv.update_behavior(reform_be)
```


```python
calc_behv = Behavior.response(calc1, calc2)
```


```python
calc_behv.calc_all()
```


```python
(calc_behv.records._combined * calc_behav.records.s006).sum()
```




    2210049566073.7783




```python
mydt = multiyear_diagnostic_table(calc_behav, num_years=1)
```


```python
mydt
```




<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>2017</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Returns (#m)</th>
      <td>172.4</td>
    </tr>
    <tr>
      <th>AGI ($b)</th>
      <td>11,039.5</td>
    </tr>
    <tr>
      <th>Itemizers (#m)</th>
      <td>45.4</td>
    </tr>
    <tr>
      <th>Itemized Deduction ($b)</th>
      <td>1,354.1</td>
    </tr>
    <tr>
      <th>Standard Deduction Filers (#m)</th>
      <td>113.6</td>
    </tr>
    <tr>
      <th>Standard Deduction ($b)</th>
      <td>1,023.3</td>
    </tr>
    <tr>
      <th>Personal Exemption ($b)</th>
      <td>1,218.1</td>
    </tr>
    <tr>
      <th>Taxable Income ($b)</th>
      <td>7,922.4</td>
    </tr>
    <tr>
      <th>Regular Tax ($b)</th>
      <td>1,666.6</td>
    </tr>
    <tr>
      <th>AMT Income ($b)</th>
      <td>10,304.3</td>
    </tr>
    <tr>
      <th>AMT Liability ($b)</th>
      <td>41.4</td>
    </tr>
    <tr>
      <th>AMT Filers (#m)</th>
      <td>5.2</td>
    </tr>
    <tr>
      <th>Tax before Credits ($b)</th>
      <td>1,615.0</td>
    </tr>
    <tr>
      <th>Refundable Credits ($b)</th>
      <td>100.9</td>
    </tr>
    <tr>
      <th>Nonrefundable Credits ($b)</th>
      <td>73.7</td>
    </tr>
    <tr>
      <th>Reform Surtaxes ($b)</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Ind Income Tax ($b)</th>
      <td>1,527.0</td>
    </tr>
    <tr>
      <th>Payroll Taxes ($b)</th>
      <td>1,096.1</td>
    </tr>
    <tr>
      <th>Combined Liability ($b)</th>
      <td>2,623.1</td>
    </tr>
  </tbody>
</table>
</div>




```python
create_diagnostic_table(calc_behv)
```




<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>2013</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Returns (#m)</th>
      <td>162.9</td>
    </tr>
    <tr>
      <th>AGI ($b)</th>
      <td>9,226.3</td>
    </tr>
    <tr>
      <th>Itemizers (#m)</th>
      <td>42.4</td>
    </tr>
    <tr>
      <th>Itemized Deduction ($b)</th>
      <td>1,112.9</td>
    </tr>
    <tr>
      <th>Standard Deduction Filers (#m)</th>
      <td>108.1</td>
    </tr>
    <tr>
      <th>Standard Deduction ($b)</th>
      <td>926.9</td>
    </tr>
    <tr>
      <th>Personal Exemption ($b)</th>
      <td>1,117.6</td>
    </tr>
    <tr>
      <th>Taxable Income ($b)</th>
      <td>6,508.6</td>
    </tr>
    <tr>
      <th>Regular Tax ($b)</th>
      <td>1,351.2</td>
    </tr>
    <tr>
      <th>AMT Income ($b)</th>
      <td>8,631.1</td>
    </tr>
    <tr>
      <th>AMT Liability ($b)</th>
      <td>33.4</td>
    </tr>
    <tr>
      <th>AMT Filers (#m)</th>
      <td>4.3</td>
    </tr>
    <tr>
      <th>Tax before Credits ($b)</th>
      <td>1,315.8</td>
    </tr>
    <tr>
      <th>Refundable Credits ($b)</th>
      <td>100.3</td>
    </tr>
    <tr>
      <th>Nonrefundable Credits ($b)</th>
      <td>70.9</td>
    </tr>
    <tr>
      <th>Reform Surtaxes ($b)</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Ind Income Tax ($b)</th>
      <td>1,216.8</td>
    </tr>
    <tr>
      <th>Payroll Taxes ($b)</th>
      <td>921.3</td>
    </tr>
    <tr>
      <th>Combined Liability ($b)</th>
      <td>2,138.0</td>
    </tr>
  </tbody>
</table>
</div>




```python
calc2.current_year
```




    2013




```python

```

**Comment by MattHJensen** [comment]
Please disregard the above. There is no unintended advancing of years. I made a silly mistake:

As you see in the notebook, I was intending to work with calc_behv. However, I accidentally switched to working with calc_behav, which was a zombie variable that I had erased from the script but not the interpreter session. Oops.
